//! Actual native flow exercises the shared Local producer and stored witness replay.
#[path="typed_driver/mod.rs"] mod typed_driver;
use lctx_model::domain::{*,local_semantics::*,normalized::entity_normalization,analysis::{self,local,native::*},resources::ResourceBudget,assertion::*,source::*,flow::*,value::*,stages::*,obligation::ObligationKind};
inspector!(Facts,calls::CallTarget);
async fn fixture()->(LocalData,local::AnalysisInvocation,analysis::AnalysisDefinition,ResourceBudget){
 let tables=typed_driver::Tables::default();typed_driver::run_behavioral(&typed_driver::files("local_semantics"),Facts(tables.clone())).await.unwrap();let budget=ResourceBudget::fixed(512<<20).unwrap();let mut data=LocalData::new(&budget);let mut entities=entity_normalization::EntityData::new(&budget);
 macro_rules! facts {($($field:ident:$ty:ty=>$family:ident,)*)=>{$(for row in typed_driver::rows::<$ty>(&tables){entities.$field.insert(row).unwrap();})*};}lctx_model::normalized_entity_inputs!(facts);
 let normalized=entity_normalization::normalize(entities.inputs(),&budget).unwrap();
 macro_rules! input {($($field:ident:$ty:ty,)*)=>{$(data.visit(<$ty>::NAME,&<$ty as Record>::encode(&typed_driver::rows::<$ty>(&tables)).unwrap()).unwrap();)*};}lctx_model::entry_value_inputs!(input);lctx_model::local_semantic_inputs!(input);
 macro_rules! output {($($field:ident:$ty:ty,)*)=>{$(data.visit(<$ty>::NAME,&<$ty as Record>::encode(&normalized.$field.iter().cloned().collect::<Vec<_>>()).unwrap()).unwrap();)*};}lctx_model::normalized_entity_outputs!(output);
 let mut inventory=NativeInventory::new(&budget);for input in NativeInventory::inputs(){let name=input.name();let frames=tables.lock().unwrap();if let Some(batches)=frames.get(name){inventory.visit(name,batches).unwrap();}}let inventory=inventory.collect().unwrap();for row in inventory.qualifications.iter(){data.native.insert(row.clone()).unwrap();}
 let parameters=analysis::MethodParameters{depth:None,proof_steps:None,work:None,members:None,seed:None,iterations:None,threshold:None,resolution:None,damping:None,model_catalog:None};let definition=analysis::AnalysisDefinition{method:analysis::AnalysisMethod::LocalTransfers,semantic_version:ContentHash::of(b"Local direct v1"),parameters:parameters.id(),interpretation:analysis::Interpretation::ExactUnderContext};let run=data.entry.runs.iter().find(|r|data.entry.providers.get(r.provider).is_some_and(|p|p.tool=="ty")).unwrap();let(invocation,_)=local::AnalysisInvocation::new(run.input,run.context,definition.id(),None,[]);(data,invocation,definition,budget)
}
fn owner_name(data:&LocalData,key:&transfer::local::TransferKey)->String{let normalized::entities::EntityRef::Callable{callable}=data.entry.refs.get(key.owner).unwrap() else{panic!()};let normalized::entities::CallableEntity::Source{declaration,..}=data.entry.callables.get(*callable).unwrap() else{panic!()};let occurrence=data.entry.occurrences.get(*declaration).unwrap();let artifact=data.entry.artifacts.get(occurrence.source).unwrap();let files=typed_driver::files("local_semantics");String::from_utf8(files[&artifact.path][occurrence.start as usize..occurrence.end as usize].to_vec()).unwrap()}
#[tokio::test]
async fn native_local_parameter_receiver_and_class_receiver_return_transfers_are_witnessed(){let(data,invocation,definition,budget)=fixture().await;let rows=produce(&data,&invocation,&definition,&budget).unwrap();for name in ["parameter","method","class_method"]{assert!(rows.keys.iter().any(|key|owner_name(&data,key).contains(&format!("def {name}("))),"missing {name}: {:?}",rows.assessments.iter().map(|a|a.reason).collect::<Vec<_>>());}for name in ["assigned","unbound","loop","nested","nonlocal_write"]{assert!(!rows.keys.iter().any(|key|owner_name(&data,key).contains(&format!("def {name}("))),"admitted {name}");}assert!(rows.assessments.iter().any(|a|a.reason==Some(ObligationKind::CallTransfer)));assert!(rows.assessments.iter().any(|a|a.reason.is_some()));assert_eq!(rows.contributions.len(),rows.supports.len());assert!(rows.entry_sources.iter().any(|source|matches!(source,conditions::entry::EntryAccessSource::Use{..})),"Local publishes separate Use read inventory");for key in rows.keys.iter(){assert!(rows.roots.iter().any(|r|matches!(r,PlaceRoot::Entry{..})&&rows.places.iter().any(|p|p.root==r.id()&&p.id()==key.input)));} }
fn replay(data:&LocalData,invocation:&local::AnalysisInvocation,rows:&LocalRecords,mutation:u8,budget:&ResourceBudget)->Result<(),ModelError>{
 let invariant=LocalAssessment::invariants().remove(0);let mut check=(invariant.create)(budget);
 macro_rules! input {($($field:ident:$ty:ty,)*)=>{$({let input=ValidationInput::of::<$ty>(&["id"]);let input=if is_vocabulary(input.name()){input.at_epoch(PublicationBoundary::Facts)}else{input};check.visit_input(&input,&<$ty as Record>::encode(&data.entry.$field.iter().cloned().collect::<Vec<_>>())?)?;})*};}lctx_model::entry_value_inputs!(input);
 macro_rules! input {($($field:ident:$ty:ty,)*)=>{$({let input=ValidationInput::of::<$ty>(&["id"]);let input=if is_vocabulary(input.name()){input.at_epoch(PublicationBoundary::Facts)}else{input};check.visit_input(&input,&<$ty as Record>::encode(&data.$field.iter().cloned().collect::<Vec<_>>())?)?;})*};}lctx_model::local_semantic_inputs!(input);
 check.visit(local::AnalysisInvocation::NAME,&local::AnalysisInvocation::encode(&[invocation.clone()])?)?;
 let mut contributions=rows.contributions.iter().cloned().collect::<Vec<_>>();let mut guards=rows.guards.iter().cloned().collect::<Vec<_>>();let mut influences=rows.influences.iter().cloned().collect::<Vec<_>>();
 if mutation==1{contributions[0].transfer=rows.keys.iter().find(|row|row.id()!=contributions[0].transfer).unwrap().id();}if mutation==2{guards[0].entry=rows.entries.iter().find(|row|row.id()!=guards[0].entry).unwrap().id();}if mutation==3{influences.clear();}if mutation==4{contributions[0].qualification=data.entry.qualifications.iter().find(|row|row.id()!=contributions[0].qualification).unwrap().id();}
 macro_rules! visit {($ty:ty,$rows:expr)=>{check.visit(<$ty>::NAME,&<$ty as Record>::encode(&$rows)?)?;};}
 visit!(LocalContribution,contributions);visit!(LocalGuardContribution,guards);visit!(transfer::local::ControlInfluence,influences);visit!(LocalAssessment,rows.assessments.iter().cloned().collect::<Vec<_>>());visit!(LocalGuardAssessment,rows.guard_assessments.iter().cloned().collect::<Vec<_>>());visit!(conditions::entry::EntryAccessSource,rows.entry_sources.iter().cloned().collect::<Vec<_>>());visit!(conditions::entry::EntryValueWitness,rows.entries.iter().cloned().collect::<Vec<_>>());visit!(conditions::stability::StabilityWitness,rows.stability.iter().cloned().collect::<Vec<_>>());visit!(transfer::local::TransferKey,rows.keys.iter().cloned().collect::<Vec<_>>());check.finish()
}
#[tokio::test]
async fn local_shared_replay_refuses_forged_transfer_guard_entry_influence_and_qualification(){let(data,invocation,definition,budget)=fixture().await;let rows=produce(&data,&invocation,&definition,&budget).unwrap();assert!(!rows.guards.is_empty());replay(&data,&invocation,&rows,0,&budget).unwrap();for mutation in 1..=4{assert!(replay(&data,&invocation,&rows,mutation,&budget).is_err(),"mutation {mutation}");}}
#[tokio::test]
async fn local_cross_context_and_budget_refuse_without_producing_proofs(){let(data,invocation,definition,budget)=fixture().await;let rows=produce(&data,&invocation,&definition,&budget).unwrap();let contribution=rows.contributions.iter().next().unwrap();let mut foreign=invocation.clone();foreign.context=serde_json::from_value(serde_json::to_value([119u8;16]).unwrap()).unwrap();assert!(LocalContribution::derive(&data,&foreign,contribution.value,contribution.support,&budget).unwrap().is_err());let tiny=ResourceBudget::fixed(16).unwrap();assert!(produce(&data,&invocation,&definition,&tiny).is_err());assert_eq!(tiny.reserved(),0);}

fn entry_replay(data:&LocalData,source:&conditions::entry::EntryAccessSource,witness:&conditions::entry::EntryValueWitness,budget:&ResourceBudget)->Result<(),ModelError>{
 let mut check=(conditions::entry::entry_invariants().remove(0).create)(budget);
 macro_rules! input {($($field:ident:$ty:ty,)*)=>{$(check.visit(<$ty>::NAME,&<$ty as Record>::encode(&data.entry.$field.iter().cloned().collect::<Vec<_>>())?)?;)*};}lctx_model::entry_value_inputs!(input);
 check.visit(conditions::entry::EntryAccessSource::NAME,&<conditions::entry::EntryAccessSource as Record>::encode(&[source.clone()])?)?;
 check.visit(conditions::entry::EntryValueWitness::NAME,&conditions::entry::EntryValueWitness::encode(&[witness.clone()])?)?;check.finish()
}
#[tokio::test]
async fn native_entry_sources_refuse_other_values_regions_supports_and_guard_phases(){
 use conditions::entry::*;use conditions::stability::StabilityWitness;
 let(mut data,invocation,definition,budget)=fixture().await;let rows=produce(&data,&invocation,&definition,&budget).unwrap();
 let contribution=rows.contributions.iter().find(|c|owner_name(&data,rows.keys.get(c.transfer).unwrap()).contains("def parameter(")).unwrap();let proof=LocalContribution::derive(&data,&invocation,contribution.value,contribution.support,&budget).unwrap().unwrap();let entry=proof.entry();let request=entry.witness().request();
 entry_replay(&data,entry.source(),entry.witness(),&budget).unwrap();assert_eq!(entry.evidence_status(),analysis::policy::EvidenceStatus::StructurallyObserved);assert_ne!(entry.qualification().condition,conditions::Diagram::always().id(),"guarded return retains region condition");
 let EntryAccessSource::Value{observation,support,region,region_support}=entry.source() else{panic!("value source")};
 let other_value=data.entry.values.iter().find(|v|v.use_!=data.entry.values.get(*observation).unwrap().use_).unwrap();let other_support=data.entry.value_supports.iter().find(|s|s.assertion==other_value.id()).unwrap();
 let wrong_value=EntryAccessSource::Value{observation:other_value.id(),support:other_support.id(),region:*region,region_support:*region_support};
 let raw_region=data.entry.regions.get(*region).unwrap();let access=data.entry.occurrences.get(request.access).unwrap();
 let sibling=data.entry.regions.iter().find(|r|r.scope==raw_region.scope&&data.entry.occurrences.get(r.statement).is_some_and(|s|!access.structural_path.starts_with(&s.structural_path))).unwrap();let sibling_support=data.entry.region_supports.iter().find(|s|s.assertion==sibling.id()).unwrap();
 let wrong_region=EntryAccessSource::Value{observation:*observation,support:*support,region:sibling.id(),region_support:sibling_support.id()};
 let nested=data.entry.regions.iter().find(|r|data.entry.lexical_scopes.get(r.scope).and_then(|s|data.entry.occurrences.get(s.owner)).is_some_and(|o|o.structural_path.len()>data.entry.occurrences.get(data.entry.lexical_scopes.get(raw_region.scope).unwrap().owner).unwrap().structural_path.len())).unwrap();let nested_support=data.entry.region_supports.iter().find(|s|s.assertion==nested.id()).unwrap();
 let wrong_nested=EntryAccessSource::Value{observation:*observation,support:*support,region:nested.id(),region_support:nested_support.id()};
 let mut foreign_support=data.entry.region_supports.get(*region_support).unwrap().clone();foreign_support.run=data.entry.runs.iter().find(|r|r.id()!=request.run).unwrap().id();let wrong_support=EntryAccessSource::Value{observation:*observation,support:*support,region:*region,region_support:foreign_support.id()};data.entry.region_supports.insert(foreign_support).unwrap();
 for source in [wrong_value,wrong_region,wrong_nested,wrong_support]{assert!(EntryValueWitness::derive_for(&data.entry,request,&source,&budget).unwrap().is_err());let mut forged=entry.witness().clone();forged.access_source=source.id();assert!(entry_replay(&data,&source,&forged,&budget).is_err(),"coupled source/witness forgery");}
 let guard=rows.guards.iter().next().unwrap();let guard_proof=LocalGuardContribution::derive(&data,&invocation,guard.leaf,guard.support,&budget).unwrap().unwrap();let guard_entry=guard_proof.entry();assert!(EntryValueWitness::derive_for(&data.entry,guard_entry.witness().request(),entry.source(),&budget).unwrap().is_err(),"return source cannot certify guard access");
 assert!(StabilityWitness::derive(&data.entry,data.entry.leaves.get(guard.leaf).unwrap().atom,entry).is_err());
}
