#[path="fixtures/transfer_composition.rs"] mod fixture;
#[path="fixtures/source_execution.rs"] mod source_fixture;
use lctx_model::domain::{*,execution,analysis,normalized::Rows};
#[tokio::test]
async fn model_inventory_replays_actual_calls_transfers_and_coupled_erasure(){
 let f=fixture::native_from("source_body_shapes").await;let mut source=source_fixture::data(&f);let input=f.rows::<input::InputRevision>()[0].id();let context=f.data.event_events.iter().next().unwrap().context;
 let mut entries=normalized::Rows::new(&f.budget);let mut entry_sources=normalized::Rows::new(&f.budget);
 for observation in source.flow.use_observations.iter(){let use_=source.flow.uses.get(observation.use_).unwrap();let Some(owner)=source.flow.owners.iter().find(|owner|owner.occurrence==use_.occurrence)else{continue};let Some(support)=source.flow.use_supports.iter().find(|support|support.assertion==observation.id())else{continue};
  for formal in source.flow.formals.iter(){let request=conditions::entry::EntryRequest{owner:owner.entity,formal:formal.id(),access:use_.occurrence,context,run:support.run};if let Ok(proof)=conditions::entry::EntryValueWitness::derive(&source.flow,request,&f.budget).unwrap(){entries.insert(proof.witness().clone()).unwrap();entry_sources.insert(proof.source().clone()).unwrap();}}
 }
 let(base,base_rows)=source_fixture::base_rows_with_entries(&mut source,input,context,&f.budget,&entries,&entry_sources);let(_,source_definition)=execution::configuration::source_calls();source.definitions.insert(source_definition.clone()).unwrap();let parent=analysis::source_call::InvocationSource::BaseCompletion{invocation:base.id()};let(source_invocation,_)=analysis::source_call::AnalysisInvocation::new(input,context,source_definition.id(),None,[parent.id()]);
 let predecessor=execution::source_call_records::prepare_all(&source,&source_invocation,&source_definition,stages::Profile::Behavioral,&f.budget).unwrap();
 let mut data=execution::enriched_production::EnrichedData::new(&f.budget);
 for(name,batch)in f.tables.lock().unwrap().iter(){data.application.visit(name,batch).unwrap();}
 macro_rules! binding_facts{($($field:ident:$ty:ty,)*)=>{$(data.application.visit(<$ty>::NAME,&<$ty as Record>::encode(&f.data.$field.iter().cloned().collect::<Vec<_>>()).unwrap()).unwrap();)*};}lctx_model::normalized_binding_inputs!(binding_facts);
 data.application.premises.decode(&<analysis::native::NativeAssertionPremise as Record>::encode(&source.evaluation.premises.iter().cloned().collect::<Vec<_>>()).unwrap()).unwrap();data.application.native.decode(&analysis::native::NativeQualification::encode(&source.evaluation.native.iter().cloned().collect::<Vec<_>>()).unwrap()).unwrap();data.source=source;
 data.source_invocations.insert(source_invocation).unwrap();data.source_runs.insert(predecessor.run.clone()).unwrap();data.source_results.insert(predecessor.outcome.clone()).unwrap();
 macro_rules! predecessor{($($field:ident:$source:ident,)*)=>{$(for row in predecessor.$source.iter(){data.$field.insert(row.clone()).unwrap();})*};}predecessor!{source_headers:headers,source_members:members,source_boundaries:boundaries,source_calls:invocations,source_releases:releases,source_arguments:arguments,source_outcomes:call_outcomes,source_invocation_boundaries:invocation_boundaries,}
 let catalog=models::Catalog::committed().unwrap();let(parameters,definition)=execution::configuration::enriched_execution(catalog.declaration().id());data.parameters.insert(parameters).unwrap();data.catalogs.insert(catalog.declaration().clone()).unwrap();let parent=analysis::enriched_execution::InvocationSource::SourceCallAnalysis{invocation:data.source_invocations.iter().next().unwrap().id()};let(invocation,_)=analysis::enriched_execution::AnalysisInvocation::new(input,context,definition.id(),None,[parent.id()]);
 let enriched=execution::enriched_production::enrich_all(&data,&invocation,&definition,stages::Profile::Behavioral,&f.budget).unwrap();

 let mut batches=f.tables.lock().unwrap().iter().map(|(name,batch)|(*name,batch.clone())).collect::<Vec<_>>();
 macro_rules! put{($ty:ty,$rows:expr)=>{batches.push((<$ty>::NAME,<$ty as Record>::encode(&$rows).unwrap()));};}
 macro_rules! raw{($($field:ident:$ty:ty,)*)=>{$(put!($ty,f.data.$field.iter().cloned().collect::<Vec<_>>());)*};}lctx_model::normalized_binding_inputs!(raw);
 macro_rules! bound{($($field:ident:$ty:ty,)*)=>{$(put!($ty,f.output.$field.iter().cloned().collect::<Vec<_>>());)*};}lctx_model::normalized_binding_outputs!(bound);
 macro_rules! raw_evaluation{($($field:ident:$ty:ty,)*)=>{$(put!($ty,data.source.evaluation.$field.iter().cloned().collect::<Vec<_>>());)*};}lctx_model::execution_evaluation_inputs!(raw_evaluation);
 macro_rules! raw_entry{($($field:ident:$ty:ty,)*)=>{$(put!($ty,data.source.flow.$field.iter().cloned().collect::<Vec<_>>());)*};}lctx_model::entry_value_inputs!(raw_entry);
 batches.extend(base_rows);
 macro_rules! earlier{($($field:ident:$ty:ty,)*)=>{$(put!($ty,data.$field.iter().cloned().collect::<Vec<_>>());)*};}earlier!{source_invocations:analysis::source_call::AnalysisInvocation,source_runs:execution::source_call_records::SourceCallRun,source_headers:execution::source_call_records::SourceCallHeader,source_members:execution::source_call_records::HeaderMember,source_boundaries:execution::source_call_records::SourceCallBoundary,source_results:analysis::source_call::AnalysisOutcome,source_calls:execution::source_call_records::SourceInvocation,source_releases:execution::source_call_records::SourceFrameRelease,source_arguments:execution::source_call_records::SourceFrameArgument,source_outcomes:execution::source_call_records::SourceCallOutcome,source_invocation_boundaries:execution::source_call_records::InvocationBoundary,}
 put!(analysis::enriched_execution::AnalysisInvocation,vec![invocation.clone()]);put!(execution::modeled_call::ModeledCallEvaluation,enriched.modeled_calls.iter().cloned().collect::<Vec<_>>());put!(execution::modeled_call::ModeledCallArgument,enriched.modeled_arguments.iter().cloned().collect::<Vec<_>>());put!(execution::modeled_call::ModeledCallNative,enriched.modeled_native.iter().cloned().collect::<Vec<_>>());
 let(model_parameters,model_definition)=execution::configuration::models(catalog.declaration().id());
 put!(analysis::AnalysisDefinition,data.source.definitions.iter().cloned().chain([definition.clone(),model_definition.clone()]).collect::<Vec<_>>());put!(analysis::MethodParameters,data.parameters.iter().cloned().chain([model_parameters]).collect::<Vec<_>>());put!(models::ModelCatalog,data.catalogs.iter().cloned().collect::<Vec<_>>());
 let parent=analysis::model::InvocationSource::EnrichedExecution{invocation:invocation.id()};let(model_invocation,_)=analysis::model::AnalysisInvocation::new(input,context,model_definition.id(),None,[parent.id(),analysis::model::InvocationSource::SourceCallAnalysis{invocation:data.source_invocations.iter().next().unwrap().id()}.id()]);put!(analysis::model::AnalysisInvocation,vec![model_invocation.clone()]);
 let mut model_data=execution::model_production::ModelData::new(&f.budget);for(name,batch)in &batches{model_data.visit(name,batch).unwrap();}
 let output=execution::model_production::apply_all(&model_data,&model_invocation,&model_definition,stages::Profile::Behavioral,&f.budget).unwrap();assert!(output.applications.len()>0);assert!(output.transfer_witnesses.len()>0,"exact actual entry to callsite proof");assert_eq!(output.outcome.status,analysis::AnalysisStatus::Partial);
 let invariant=Relation::of::<execution::model_production::ModelRun>().invariants()[0].clone();
 for mutation in 0..5 {let mut check=(invariant.create)(&f.budget);let mut shuffled=batches.clone();if mutation==4{shuffled.reverse();}for(name,batch)in &shuffled{let input=invariant.inputs.iter().find(|i|i.name()==*name&&(!stages::is_vocabulary(name)||i.prefix()==Some(stages::PublicationBoundary::Facts))).cloned().unwrap_or_else(||ValidationInput::of::<input::InputRevision>(&["id"]));if input.name()==*name{check.visit_input(&input,batch).unwrap();}}
 macro_rules! emit{($ty:ty,$rows:expr)=>{check.visit_input(&ValidationInput::of::<$ty>(&["id"]),&<$ty as Record>::encode(&$rows).unwrap()).unwrap();};}
 let erase=mutation==2;let mut run=output.run.clone();if erase{run.applied=0;run.refused=0;}emit!(execution::model_production::ModelRun,vec![run]);let mut outcome=output.outcome.clone();if mutation==3{outcome.status=analysis::AnalysisStatus::Completed;outcome.reason=None;}emit!(analysis::model::AnalysisOutcome,vec![outcome]);
 macro_rules! outputs{($($field:ident:$ty:ty,)*)=>{$(emit!($ty,if erase{vec![]}else{let mut rows=output.$field.iter().cloned().collect::<Vec<_>>();if mutation==4{rows.reverse();}rows});)*};}
 outputs!{applications:execution::model_production::ModelApplication,application_premises:execution::model_production::ApplicationPremise,boundaries:execution::model_production::ApplicationBoundary,targets:execution::model_production::TargetAssessment,rules:execution::model_rules::AppliedRule,channels:execution::model_rules::ChannelAssessment,operations:execution::model_rules::ModeledOperation,resources:execution::model_rules::ResourceIdentity,paths:execution::model_rules::ModelValuePath,action_assessments:execution::model_production::ActionAssessment,action_sources:execution::model_production::ActionSource,postconditions:execution::model_production::ActionPostcondition,
 transfer_keys:transfer::model::TransferKey,transfer_alternatives:transfer::model::TransferAlternative,transfer_supports:transfer::model::TransferSupport,
 transfer_roots:value::PlaceRoot,transfer_places:value::Place,qualifications:assertion::AssertionQualification,conditions:conditions::Condition,condition_nodes:conditions::ConditionNode,
 subjects:analysis::model::ObligationSubject,support_sources:analysis::model::SupportSource,derivations:analysis::model::AnalysisDerivation,propositions:analysis::model::AnalysisProposition,derivation_premises:analysis::model::AnalysisDerivationPremise,}
 let mut witnesses=output.transfer_witnesses.iter().cloned().collect::<Vec<_>>();if mutation==1{witnesses[0].status=analysis::policy::EvidenceStatus::Documented;}emit!(execution::model_transfer::ModelTransferWitness,if erase{vec![]}else{witnesses});
 let result=check.finish();assert_eq!(result.is_ok(),mutation==0||mutation==4,"Model replay mutation {mutation}: {result:?}");
 }
 assert!(execution::model_production::apply_all(&model_data,&model_invocation,&model_definition,stages::Profile::Behavioral,&resources::ResourceBudget::fixed(1).unwrap()).is_err());
 let catalog_output=execution::model_production::apply_all(&model_data,&model_invocation,&model_definition,stages::Profile::Catalog,&f.budget).unwrap();assert_eq!(catalog_output.outcome.status,analysis::AnalysisStatus::NotRequested);assert!(catalog_output.applications.is_empty()&&catalog_output.transfer_witnesses.is_empty());
}
