#[path="fixtures/transfer_composition.rs"]mod fixture;
#[path="fixtures/source_execution.rs"]mod source_fixture;
use lctx_model::domain::{*,analysis,execution::{self,read_channels::*},normalized::Rows,source::*};
fn text(f:&fixture::NativeFixture,id:Id<Occurrence>)->String{let row=f.data.occurrences.get(id).unwrap();let bytes=f.source_bytes(row.source);String::from_utf8(bytes[row.start as usize..row.end as usize].to_vec()).unwrap()}
#[tokio::test]
async fn actual_read_inventory_and_complete_negative_are_replayed(){
 let f=fixture::native_from("transfer_alternatives").await;let data=source_fixture::data(&f);let input=data.flow.artifacts.iter().find(|a|a.path=="transferpkg/__init__.py").unwrap().input;let run=data.flow.runs.get(data.flow.coverage.iter().find(|c|c.family==attribution::FactFamily::Flow&&c.run.is_some_and(|r|data.flow.runs.get(r).is_some_and(|r|r.input==input))).unwrap().run.unwrap()).unwrap();
 let(_,definition)=execution::configuration::base_evaluation();let(local,_)=analysis::local::AnalysisInvocation::new(run.input,run.context,definition.id(),None,[]);let parent=analysis::base_evaluation::InvocationSource::Local{invocation:local.id()};let(invocation,_)=analysis::base_evaluation::AnalysisInvocation::new(run.input,run.context,definition.id(),None,[parent.id()]);
 let records=execution::production::evaluate_all(&data.evaluation,&data.flow,&Rows::new(&f.budget),&Rows::new(&f.budget),&invocation,&definition,stages::Profile::Behavioral,&f.budget).unwrap();
 assert!(!records.reads.reads.is_empty());assert!(!records.reads.dependencies.is_empty());assert!(!records.reads.attributes.is_empty());
 let owner_text=|id:Id<normalized::entities::EntityRef>|{let normalized::entities::EntityRef::Callable{callable}=data.flow.refs.get(id).unwrap()else{panic!("noncallable")};let normalized::entities::CallableEntity::Source{declaration,..}=data.flow.callables.get(*callable).unwrap()else{panic!("nonsource")};text(&f,*declaration)};
 let ignored=records.reads.formals.iter().find(|row|matches!(data.flow.formals.get(row.formal),Some(normalized::entities::ParameterEntity::Source{declaration})if text(&f,*declaration)=="ignored")&&owner_text(row.owner).starts_with("def unused(")).unwrap();assert_eq!(ignored.status,ReadAssessment::CompleteNoReadUnderModel,"{ignored:?}");
 let value=records.reads.formals.iter().find(|row|matches!(data.flow.formals.get(row.formal),Some(normalized::entities::ParameterEntity::Source{declaration})if text(&f,*declaration)=="value")&&owner_text(row.owner).starts_with("def unused(")).unwrap();assert_eq!(value.status,ReadAssessment::ObservedRead);
 assert!(records.reads.reads.iter().any(|r|r.location==ReadLocation::DeclaredGlobal));
 assert!(records.reads.reads.iter().any(|r|r.execution_region.is_some()&&r.region_premise.is_some()));
 let stable_class=data.evaluation.classes.iter().find(|c|matches!(c,normalized::entities::ClassEntity::Source{declaration}if text(&f,*declaration).starts_with("class Stable:"))).unwrap().id();
 let choice=data.evaluation.classes.iter().find(|c|matches!(c,normalized::entities::ClassEntity::Source{declaration}if text(&f,*declaration).starts_with("class ChoiceA:"))).unwrap().id();
 let known=records.reads.dynamic.iter().filter(|d|d.declared_class==Some(stable_class)).collect::<Vec<_>>();assert_eq!(known.len(),2);assert!(known.iter().any(|d|d.kind==execution::read_dynamic::DynamicKind::GetAttr));assert!(known.iter().any(|d|d.kind==execution::read_dynamic::DynamicKind::Dictionary));
 assert!(records.reads.dynamic.iter().any(|d|text(&f,d.site)=="getattr(fixed, name)"&&d.declared_class==Some(choice)));
 assert_eq!(records.reads.dynamic.iter().filter(|d|d.declared_class.is_none()).count(),6);
 assert!(records.reads.dynamic.iter().filter(|d|d.declared_class.is_none()).all(|d|d.inspection==execution::read_dynamic::ClassInspection::Unknown&&d.reason==Some(obligation::ObligationKind::DynamicAccess)));
 // Recomputed admission and native input inventory, rather than output counts, own completeness.
 let validate=|shrink:bool,forge:bool,dynamic_forge:bool,dynamic_shrink:bool|{
 let invariant=execution::production::EvaluationRun::invariants().remove(0);let mut check=(invariant.create)(&f.budget);
 for(name,batch)in f.tables.lock().unwrap().iter(){check.visit(name,batch).unwrap();}
 macro_rules! raw{($($field:ident:$ty:ty,)*)=>{$(let batch=<$ty as Record>::encode(&data.flow.$field.iter().cloned().collect::<Vec<_>>()).unwrap();check.visit(<$ty>::NAME,&batch).unwrap();)*};}lctx_model::entry_value_inputs!(raw);
 macro_rules! eval{($($field:ident:$ty:ty,)*)=>{$(let batch=<$ty as Record>::encode(&data.evaluation.$field.iter().cloned().collect::<Vec<_>>()).unwrap();check.visit(<$ty>::NAME,&batch).unwrap();)*};}lctx_model::execution_evaluation_inputs!(eval);
 macro_rules! put{($ty:ty,$rows:expr)=>{check.visit(<$ty>::NAME,&<$ty as Record>::encode(&$rows).unwrap()).unwrap()};}
 put!(analysis::local::AnalysisInvocation,vec![local.clone()]);put!(analysis::base_evaluation::AnalysisInvocation,vec![invocation.clone()]);put!(analysis::AnalysisDefinition,vec![definition.clone()]);put!(execution::production::EvaluationRun,vec![records.run.clone()]);put!(analysis::base_evaluation::AnalysisOutcome,vec![records.outcome.clone()]);
 put!(execution::records::ExpressionEvaluation,records.evaluations.iter().cloned().collect::<Vec<_>>());put!(execution::records::EvaluationSource,records.sources.iter().cloned().collect::<Vec<_>>());put!(execution::records::EvaluationMember,records.members.iter().cloned().collect::<Vec<_>>());put!(execution::records::EvaluationOperand,records.operands.iter().cloned().collect::<Vec<_>>());put!(execution::production::EvaluationBoundary,records.boundaries.iter().cloned().collect::<Vec<_>>());
 put!(execution::read_dynamic::DynamicAccessObservation,records.reads.dynamic.iter().filter(|row|!dynamic_shrink||row.declared_class!=Some(stable_class)).cloned().map(|mut row|{if dynamic_forge&&row.declared_class==Some(stable_class){row.declared_class=Some(choice);row.status=analysis::policy::EvidenceStatus::FixtureChecked;}row}).collect::<Vec<_>>());put!(execution::read_dynamic::DynamicAccessPremise,records.reads.dynamic_premises.iter().filter(|row|!dynamic_shrink||records.reads.dynamic.get(row.access).unwrap().declared_class!=Some(stable_class)).cloned().collect::<Vec<_>>());
 put!(ReadObservation,records.reads.reads.iter().filter(|r|!shrink||r.owner!=value.owner).cloned().collect::<Vec<_>>());put!(ReadDependency,records.reads.dependencies.iter().filter(|r|!shrink||records.reads.reads.get(r.read).unwrap().owner!=value.owner).cloned().collect::<Vec<_>>());put!(AttributeRead,records.reads.attributes.iter().cloned().collect::<Vec<_>>());put!(FormalReadAssessment,records.reads.formals.iter().filter(|r|!shrink||r.owner!=value.owner).cloned().map(|mut row|{if forge&&row.id()==value.id(){row.status=ReadAssessment::CompleteNoReadUnderModel;}row}).collect::<Vec<_>>());
 check.finish()
 };
 validate(false,false,false,false).unwrap();assert!(validate(true,false,false,false).is_err());assert!(validate(false,true,false,false).is_err());assert!(validate(false,false,true,false).is_err());assert!(validate(false,false,false,true).is_err());
 let mut incomplete=conditions::entry::EntryData::new(&f.budget);macro_rules! copy{($($field:ident:$ty:ty,)*)=>{$(for row in data.flow.$field.iter(){incomplete.$field.insert(row.clone()).unwrap();})*};}lctx_model::entry_value_inputs!(copy);incomplete.coverage=Rows::new(&f.budget);
 let roots=data.flow.artifacts.iter().filter(|a|a.input==run.input).map(Record::id).collect();let out=produce(&data.evaluation,&incomplete,&invocation,&roots,&f.budget).unwrap();assert_eq!(out.formals.iter().find(|r|r.formal==ignored.formal).unwrap().status,ReadAssessment::Unknown);drop(out);
 let mut foreign=invocation.clone();let mut context=f.rows::<attribution::AnalysisContext>().into_iter().find(|context|context.id()==run.context).unwrap();context.config_digest=ContentHash::of(b"negative foreign read context");foreign.context=context.id();let foreign_output=produce(&data.evaluation,&data.flow,&foreign,&roots,&f.budget).unwrap();assert!(foreign_output.reads.is_empty());assert!(foreign_output.formals.iter().all(|r|r.status!=ReadAssessment::CompleteNoReadUnderModel));drop(foreign_output);
 let before=f.budget.reserved();let output=produce(&data.evaluation,&data.flow,&invocation,&roots,&f.budget).unwrap();assert!(f.budget.reserved()>before);drop(output);assert_eq!(f.budget.reserved(),before);
 assert!(produce(&data.evaluation,&data.flow,&invocation,&roots,&resources::ResourceBudget::fixed(1).unwrap()).is_err());
}
