#[macro_export]
macro_rules! normalized_event_inputs {
    ($apply:ident) => {
        $apply! {
            classes: $crate::domain::normalized::entities::ClassEntity,
            trait_supports: $crate::domain::symbols::FunctionTraitSupport,
            ancestry: $crate::domain::symbols::ClassAncestryObservation,
            ancestry_supports: $crate::domain::symbols::ClassAncestrySupport,
            sequences: $crate::domain::symbols::SymbolSequence,
            sequence_members: $crate::domain::symbols::SymbolSequenceMember,

        occurrences: $crate::domain::source::Occurrence,
        coverage: $crate::domain::attribution::ProviderCoverage,
        scopes: $crate::domain::source::CoverageScope,
        declarations: $crate::domain::syntax::DeclarationObservation,
        decorators: $crate::domain::syntax::DeclarationDecorator,
        placements: $crate::domain::syntax::SyntaxPlacement,
        traits: $crate::domain::symbols::FunctionTraitObservation,
        bodies: $crate::domain::types::FunctionBodyObservation,
        signatures: $crate::domain::calls::Signature,
        native_signatures: $crate::domain::types::NativeSignatureObservation,
    overload_traces: $crate::domain::types::NativeOverloadObservation,
    overload_candidates: $crate::domain::types::NativeOverloadCandidate,
    overload_supports: $crate::domain::types::NativeOverloadSupport,
    native_signature_supports: $crate::domain::types::NativeSignatureSupport,
    overload_assessments: $crate::domain::normalized::overload_association::OverloadVariantAssessment,
    overload_members: $crate::domain::normalized::overload_association::OverloadVariantCandidate,
    terms: $crate::domain::types::TypeTerm,
        signature_types: $crate::domain::types::SignatureTypeObservation,
        signature_type_subjects: $crate::domain::types::SignatureTypeSubject,
        slot_types: $crate::domain::normalized::callables::SignatureSlotType,
        return_types: $crate::domain::normalized::callables::SignatureReturnType,
        parameters: $crate::domain::calls::SignatureParameter,
        shapes: $crate::domain::calls::ParameterShape,
        references: $crate::domain::lexical::ReferenceObservation,
        lexical_targets: $crate::domain::lexical::LexicalTarget,
        lexical_resolutions: $crate::domain::lexical::LexicalResolution,
        callables: $crate::domain::normalized::entities::CallableEntity,
        parameter_links: $crate::domain::normalized::entities::ParameterEntityLink,
        reference_assessments: $crate::domain::normalized::links::ReferenceEntityAssessment,
        reference_candidates: $crate::domain::normalized::links::ReferenceEntityCandidate,
        reference_targets: $crate::domain::normalized::links::ReferenceEntityTarget,
        callable_assessments: $crate::domain::normalized::callables::EffectiveCallableAssessment,
        callable_decorators: $crate::domain::normalized::callables::EffectiveDecoratorMember,
        callable_premises: $crate::domain::normalized::callables::EffectiveCallablePremise,
        callable_evidence: $crate::domain::normalized::callables::EffectiveCallableEvidence,
        callable_variants: $crate::domain::normalized::callables::SignatureVariant,
        callable_slots: $crate::domain::normalized::callables::SignatureSlot,
        callable_slot_entities: $crate::domain::normalized::callables::SignatureSlotEntity,
        syntax: $crate::domain::calls::CallSyntax,
        syntax_supports: $crate::domain::calls::CallSyntaxSupport,
        placement_supports: $crate::domain::syntax::SyntaxPlacementSupport,
        artifacts: $crate::domain::source::SourceArtifact,
        modules: $crate::domain::source::Module,
        runs: $crate::domain::attribution::ProviderRun,
        surfaces: $crate::domain::assertion::ProviderSurface,
        native_evidence: $crate::domain::assertion::Evidence,
        receiver_assessments: $crate::domain::normalized::receiver::ReceiverAssessment,
        receiver_evidence: $crate::domain::normalized::receiver::ReceiverEvidence,
        receiver_premises: $crate::domain::normalized::receiver::ReceiverPremise,
            qualifications: $crate::domain::assertion::AssertionQualification,
            symbols: $crate::domain::calls::ProviderSymbol,
            provider_callables: $crate::domain::calls::ProviderCallable,
            provider_modules: $crate::domain::calls::ProviderModule,
            call_sites: $crate::domain::calls::ProviderCallSite,
            site_supports: $crate::domain::calls::ProviderCallSiteSupport,
            targets: $crate::domain::calls::CallTarget,
            target_supports: $crate::domain::calls::CallTargetSupport,
            channels: $crate::domain::calls::CallChannel,
            destinations: $crate::domain::calls::CallDestination,
            receivers: $crate::domain::calls::Receiver,
            resolutions: $crate::domain::calls::CallResolution,
            resolution_supports: $crate::domain::calls::CallResolutionSupport,
            members: $crate::domain::calls::CallResolutionMember,
            symbol_resolutions: $crate::domain::normalized::entities::SymbolEntityResolution,
            refs: $crate::domain::normalized::entities::EntityRef,
            owners: $crate::domain::normalized::entities::OccurrenceOwnership,
            paths: $crate::domain::flow::FlowValuePathObservation,
            steps: $crate::domain::flow::FlowCallStep,
        }
    };
}
#[macro_export]
macro_rules! normalized_event_outputs {
    ($apply:ident) => {
        $apply! {
            alternative_sources: $crate::domain::normalized::events::CallAlternativeSource,
            dispatch_assessments: $crate::domain::normalized::dispatch::DispatchAssessment,
            dispatch_members: $crate::domain::normalized::dispatch::DispatchMember,
            dispatch_premises: $crate::domain::normalized::dispatch::DispatchPremise,
            dispatch_evidence: $crate::domain::normalized::dispatch::DispatchEvidence,
            events: $crate::domain::normalized::events::NormalizedCallEvent,
            sources: $crate::domain::normalized::events::CallEventSource,
            source_evidence: $crate::domain::normalized::events::CallEventSourceEvidence,
            resolutions: $crate::domain::normalized::events::CallEventResolution,
            resolution_evidence: $crate::domain::normalized::events::CallEventResolutionEvidence,
            alternatives: $crate::domain::normalized::events::NormalizedCallAlternative,
            alternative_evidence: $crate::domain::normalized::events::CallAlternativeEvidence,
            assessments: $crate::domain::normalized::events::EventAssessment,
            phase_targets: $crate::domain::normalized::events::EventPhaseTarget,
            policy_assessments: $crate::domain::normalized::events::CallPolicyAssessment,
            admissions: $crate::domain::normalized::events::CallPolicyAdmission,
            flow_links: $crate::domain::normalized::events::FlowCallEventLink,
        }
    };
}
