//! Exact pre-event receiver derivation inventory; no event or binding output dependency.
#[macro_export]
macro_rules! normalized_receiver_inputs { ($apply:ident) => { $apply! {

    occurrences: $crate::domain::source::Occurrence,
    qualifications: $crate::domain::assertion::AssertionQualification,
    coverage: $crate::domain::attribution::ProviderCoverage,
    scopes: $crate::domain::source::CoverageScope,
    declarations: $crate::domain::syntax::DeclarationObservation,
    decorators: $crate::domain::syntax::DeclarationDecorator,
    placements: $crate::domain::syntax::SyntaxPlacement,
    traits: $crate::domain::symbols::FunctionTraitObservation,
    bodies: $crate::domain::types::FunctionBodyObservation,
    signatures: $crate::domain::calls::Signature,
    parameters: $crate::domain::calls::SignatureParameter,
    shapes: $crate::domain::calls::ParameterShape,
    references: $crate::domain::lexical::ReferenceObservation,
    lexical_targets: $crate::domain::lexical::LexicalTarget,
    lexical_resolutions: $crate::domain::lexical::LexicalResolution,
    callables: $crate::domain::normalized::entities::CallableEntity,
    refs: $crate::domain::normalized::entities::EntityRef,
    symbol_resolutions: $crate::domain::normalized::entities::SymbolEntityResolution,
    owners: $crate::domain::normalized::entities::OccurrenceOwnership,
    parameter_links: $crate::domain::normalized::entities::ParameterEntityLink,
    reference_assessments: $crate::domain::normalized::links::ReferenceEntityAssessment,
    reference_candidates: $crate::domain::normalized::links::ReferenceEntityCandidate,
    reference_targets: $crate::domain::normalized::links::ReferenceEntityTarget,
    callable_assessments: $crate::domain::normalized::callables::EffectiveCallableAssessment,
    callable_decorators: $crate::domain::normalized::callables::EffectiveDecoratorMember,
    callable_premises: $crate::domain::normalized::callables::EffectiveCallablePremise,
    callable_evidence: $crate::domain::normalized::callables::EffectiveCallableEvidence,
    callable_variants: $crate::domain::normalized::callables::SignatureVariant,
    callable_slots: $crate::domain::normalized::callables::SignatureSlot,
    callable_slot_entities: $crate::domain::normalized::callables::SignatureSlotEntity,
    targets: $crate::domain::calls::CallTarget,
    target_supports: $crate::domain::calls::CallTargetSupport,
    destinations: $crate::domain::calls::CallDestination,
    receivers: $crate::domain::calls::Receiver,
    syntax: $crate::domain::calls::CallSyntax,
    syntax_supports: $crate::domain::calls::CallSyntaxSupport,
    placement_supports: $crate::domain::syntax::SyntaxPlacementSupport,
    artifacts: $crate::domain::source::SourceArtifact,
    modules: $crate::domain::source::Module,
    runs: $crate::domain::attribution::ProviderRun,
    surfaces: $crate::domain::assertion::ProviderSurface,
    native_evidence: $crate::domain::assertion::Evidence,
} }; }
#[macro_export]
macro_rules! normalized_receiver_outputs { ($apply:ident) => { $apply! {
    receiver_assessments: $crate::domain::normalized::receiver::ReceiverAssessment,
    receiver_evidence: $crate::domain::normalized::receiver::ReceiverEvidence,
    receiver_premises: $crate::domain::normalized::receiver::ReceiverPremise,
} }; }
