//! Exact source associations under a deliberately small plain initializer model.
//! None of these records proves allocation, reaching heap state, mutation freedom between
//! methods, normal invocation, or a receiver's runtime value. Callable metadata is the writer.
//! Restart checkpoint: record association admission remains refused until exact decorator
//! target/options, field-default and generated-signature screens are qualified.
use crate::{Domain,DomainCode};
use crate::domain::{*,normalized::{Rows,callable_aspects::{AspectData,AspectOutput,FieldDefault},entities::*},assertion::*,attribution::*,source::*,syntax::*,symbols::*,lexical::*,calls::*,declarations::*,types::*,obligation::ObligationKind,resources::ResourceBudget};
#[derive(Debug,Clone,Copy,PartialEq,Eq,Hash,DomainCode)]#[repr(i16)]pub enum SourceStorageKind{PlainInitializer=0,GeneratedRecord=1}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]#[model(name="source_field_class_assessments",rule="source_plain_record_shape")]
pub struct SourceFieldClass{#[model(key)]pub class:Id<Occurrence>,#[model(key)]pub qualification:Id<AssertionQualification>,#[model(premise)]pub traits:Id<ClassTraitObservation>,#[model(premise)]pub support:Id<ClassTraitSupport>,pub supported_record:bool,pub reason:Option<ObligationKind>,pub inventory:ContentHash}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]#[model(name="source_field_stores",rule="source_receiver_field_store")]
pub struct SourceFieldStore{#[model(key)]pub class:Id<Occurrence>,#[model(key)]pub constructor:Id<Occurrence>,#[model(key)]pub target:Id<Occurrence>,pub name:String,pub value:Id<Occurrence>,#[model(premise)]pub formal:Id<ParameterDeclaration>,#[model(premise)]pub receiver:Id<ParameterSyntaxObservation>,#[model(premise)]pub placement:Id<SyntaxPlacement>,#[model(premise)]pub traits:Id<FunctionTraitObservation>,pub qualification:Id<AssertionQualification>,pub plain_initializer:bool,pub inventory:ContentHash}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]#[model(name="source_field_readers",rule="source_receiver_field_reader")]
pub struct SourceFieldReader{#[model(key)]pub class:Id<Occurrence>,#[model(key)]pub reader:Id<Occurrence>,#[model(key)]pub access:Id<Occurrence>,pub name:String,#[model(premise)]pub receiver:Id<ParameterSyntaxObservation>,#[model(premise)]pub placement:Id<SyntaxPlacement>,#[model(premise)]pub traits:Id<FunctionTraitObservation>,pub qualification:Id<AssertionQualification>,pub inventory:ContentHash}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]#[model(name="source_field_associations",rule="source_field_initialization_association")]
pub struct SourceFieldAssociation{#[model(key,premise)]pub class:Id<SourceFieldClass>,#[model(key,premise)]pub field:Id<RecordFieldObservation>,#[model(key,premise)]pub parameter:Id<SignatureParameter>,#[model(premise)]pub store:Option<Id<SourceFieldStore>>,pub kind:SourceStorageKind,pub qualification:Id<AssertionQualification>,pub inventory:ContentHash}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]#[model(name="source_field_reader_links",rule="source_field_reader_association")]
pub struct SourceFieldReaderLink{#[model(key,premise)]pub association:Id<SourceFieldAssociation>,#[model(key,premise)]pub reader:Id<SourceFieldReader>}
fn exact(d:&AspectData,id:Id<AssertionQualification>,context:Id<AnalysisContext>)->bool{d.qualifications.get(id).is_some_and(|q|q.context==context&&q.modality==Modality::Definite&&q.approximation==Approximation::Exact&&q.condition==conditions::Diagram::always().id())}
fn same(d:&AspectData,a:Id<Occurrence>,b:Id<Occurrence>)->bool{d.occurrences.get(a).zip(d.occurrences.get(b)).is_some_and(|(a,b)|(a.source,a.start,a.end)==(b.source,b.start,b.end))}
fn source<R:Assertion,S:Support<Assertion=R>>(d:&AspectData,row:&R,supports:&Rows<S>,context:Id<AnalysisContext>)->bool{supports.iter().filter(|s|s.assertion()==row.id()).any(|s|s.attribution().is_some_and(|a|a.fidelity==Fidelity::NativeStructural&&d.symbolic_runs.get(a.run).is_some_and(|r|r.context==context)))}
fn symbol_for(d:&AspectData,occurrence:Id<Occurrence>,context:Id<AnalysisContext>)->Option<Id<ProviderSymbol>>{let mut rows=d.symbolic_symbol_declarations.iter().filter(|r|same(d,r.declaration,occurrence)&&exact(d,r.qualification,context)&&source(d,*r,&d.symbolic_symbol_supports,context));let first=rows.next()?;if rows.any(|r|r.symbol!=first.symbol){return None}Some(first.symbol)}
fn method<'a>(d:&'a AspectData,function:Id<Occurrence>,class:Id<ProviderSymbol>,context:Id<AnalysisContext>)->Option<&'a FunctionTraitObservation>{let symbol=symbol_for(d,function,context)?;let mut rows=d.traits.iter().filter(|r|r.symbol==symbol&&r.defining_class==Some(class)&&!r.staticmethod&&!r.classmethod&&!r.property_getter&&!r.property_setter&&!r.stub&&r.origin==FunctionOrigin::DefStatement&&exact(d,r.qualification,context)&&source(d,*r,&d.symbolic_trait_supports,context));let row=rows.next()?;if rows.next().is_some(){return None}Some(row)}
fn receiver(d:&AspectData,function:Id<Occurrence>,context:Id<AnalysisContext>)->Option<&ParameterSyntaxObservation>{let mut rows=d.symbolic_parameter_syntax.iter().filter(|r|same(d,r.function,function)&&r.ordinal==0&&exact(d,r.qualification,context)&&source(d,*r,&d.symbolic_parameter_syntax_supports,context));let first=rows.next()?;if rows.next().is_some(){return None}Some(first)}
fn formal_read(d:&AspectData,read:Id<Occurrence>,parameter:Id<Occurrence>,context:Id<AnalysisContext>)->bool{let mut found=false;for r in d.lexical_resolutions.iter().filter(|r|same(d,r.read,read)&&exact(d,r.qualification,context)){if r.captured||!source(d,r,&d.symbolic_resolution_supports,context){return false}let Some(LexicalTarget::Binding{event})=d.symbolic_lexical_targets.get(r.target)else{return false};let Some(event)=d.binding_events.get(*event)else{return false};if !same(d,event.site,parameter){return false}found=true}found}
fn child<'a>(d:&'a AspectData,parent:Id<Occurrence>,field:SyntaxField,context:Id<AnalysisContext>)->Option<&'a SyntaxPlacement>{let mut rows=d.placements.iter().filter(|p|p.parent.is_some_and(|p|same(d,p,parent))&&p.field==field&&exact(d,p.qualification,context)&&source(d,*p,&d.symbolic_placement_supports,context));let row=rows.next()?;if rows.next().is_some(){return None}Some(row)}
fn attribute(d:&AspectData,site:Id<Occurrence>,receiver:&ParameterSyntaxObservation,context:Id<AnalysisContext>)->Option<String>{if d.occurrences.get(site)?.syntax_kind!=SyntaxKind::ExprAttribute{return None}let base=child(d,site,SyntaxField::Value,context)?;if !formal_read(d,base.occurrence,receiver.parameter,context){return None}let mut name=None;for p in d.placements.iter().filter(|p|p.parent.is_some_and(|p|same(d,p,site))&&d.occurrences.get(p.occurrence).is_some_and(|o|o.syntax_kind==SyntaxKind::Identifier)){if !source(d,p,&d.symbolic_placement_supports,context){return None}for text in d.spellings.iter().filter(|s|same(d,s.occurrence,p.occurrence)&&exact(d,s.qualification,context)){if name.as_ref().is_some_and(|old|old!=text.spelling.as_str()){return None}name=Some(text.spelling.as_str().to_owned());}}name}
fn contains(d:&AspectData,outer:Id<Occurrence>,inner:Id<Occurrence>)->bool{d.occurrences.get(outer).zip(d.occurrences.get(inner)).is_some_and(|(a,b)|a.source==b.source&&a.start<=b.start&&a.end>=b.end&&b.structural_path.starts_with(&a.structural_path))}
fn covered(d:&AspectData,class:Id<Occurrence>,context:Id<AnalysisContext>)->bool{let Some(o)=d.occurrences.get(class)else{return false};let Some(a)=d.artifacts.get(o.source)else{return false};!a.is_stub()&&d.symbolic_coverage.iter().any(|c|c.context==context&&c.family==FactFamily::Syntax&&c.status==CoverageStatus::CompleteUnderStatedModel&&c.run.is_some_and(|r|d.symbolic_runs.get(r).is_some_and(|r|r.input==a.input&&r.context==context))&&match d.symbolic_scopes.get(c.scope){Some(CoverageScope::Artifact{artifact})=>*artifact==a.id(),Some(CoverageScope::Input{input})=>*input==a.input,Some(CoverageScope::Module{module})=>d.modules.get(*module).is_some_and(|m|m.source==a.id()),_=>false})}
fn class_inventory(d:&AspectData,class:Id<Occurrence>,context:Id<AnalysisContext>,symbol:Id<ProviderSymbol>)->ContentHash{let mut k=KeySink::new("source-field-class-full-inventory");class.encode(&mut k);context.encode(&mut k);macro_rules! rows{($f:ident,$pred:expr)=>{for r in d.$f.iter().filter(|r|($pred)(*r)){r.content_digest().encode(&mut k);}};}rows!(placements,|r:&SyntaxPlacement|contains(d,class,r.occurrence)&&exact(d,r.qualification,context));rows!(declarations,|r:&DeclarationObservation|contains(d,class,r.declaration)&&exact(d,r.qualification,context));rows!(decorators,|r:&DeclarationDecorator|contains(d,class,r.declaration)&&exact(d,r.qualification,context));rows!(traits,|r:&FunctionTraitObservation|r.defining_class==Some(symbol)&&exact(d,r.qualification,context));rows!(symbolic_record_fields,|r:&RecordFieldObservation|r.class==symbol&&exact(d,r.qualification,context));rows!(symbolic_ancestry,|r:&ClassAncestryObservation|r.class==symbol&&exact(d,r.qualification,context));rows!(symbolic_parameter_declarations,|r:&ParameterDeclaration|contains(d,class,r.declaration)&&exact(d,r.qualification,context));k.finish()}
fn plain_init(d:&AspectData,function:Id<Occurrence>,symbol:Id<ProviderSymbol>,context:Id<AnalysisContext>,receiver:&ParameterSyntaxObservation)->bool{
 if d.decorators.iter().any(|r|same(d,r.declaration,function)&&exact(d,r.qualification,context)){return false}
 for p in d.placements.iter().filter(|p|p.parent.is_some_and(|p|same(d,p,function))&&p.field==SyntaxField::Body&&exact(d,p.qualification,context)){
  if !source(d,p,&d.symbolic_placement_supports,context){return false}let Some(node)=d.occurrences.get(p.occurrence)else{return false};match node.syntax_kind{
   SyntaxKind::StmtPass=>{},SyntaxKind::StmtExpr=>{let Some(v)=child(d,node.id(),SyntaxField::Value,context)else{return false};if d.occurrences.get(v.occurrence).is_none_or(|n|n.syntax_kind!=SyntaxKind::ExprStringLiteral){return false}},
   SyntaxKind::StmtAssign=>{let Some(t)=child(d,node.id(),SyntaxField::Target,context)else{return false};let Some(name)=attribute(d,t.occurrence,receiver,context)else{return false};if !d.symbolic_record_fields.iter().any(|f|f.class==symbol&&f.name.as_str()==name&&f.record==RecordKind::Dataclass){return false}let Some(v)=child(d,node.id(),SyntaxField::Value,context)else{return false};let Some(vn)=d.occurrences.get(v.occurrence)else{return false};if !matches!(vn.syntax_kind,SyntaxKind::ExprName|SyntaxKind::ExprStringLiteral|SyntaxKind::ExprNumberLiteral|SyntaxKind::ExprBooleanLiteral|SyntaxKind::ExprNoneLiteral){return false}if vn.syntax_kind==SyntaxKind::ExprName&&!d.symbolic_parameter_syntax.iter().any(|p|same(d,p.function,function)&&formal_read(d,v.occurrence,p.parameter,context)){return false}},_=>return false
  }
 }true
}
fn record_gate(d:&AspectData,class:Id<Occurrence>,symbol:Id<ProviderSymbol>,context:Id<AnalysisContext>,out:&AspectOutput)->Option<ObligationKind>{
 if !covered(d,class,context){return Some(ObligationKind::IncompleteCoverage)}
 let decorators=d.decorators.iter().filter(|r|same(d,r.declaration,class)&&exact(d,r.qualification,context)).collect::<Vec<_>>();if decorators.len()!=1||!source(d,decorators[0],&d.symbolic_decorator_supports,context){return Some(ObligationKind::OutsideProviderModel)}
 if d.placements.iter().any(|p|p.parent.is_some_and(|p|same(d,p,class))&&p.field==SyntaxField::Argument&&exact(d,p.qualification,context)){return Some(ObligationKind::IncompleteDomain)}
 let mut mros=d.symbolic_ancestry.iter().filter(|m|m.class==symbol&&m.relation==AncestryRelation::Mro&&exact(d,m.qualification,context));let Some(mro)=mros.next()else{return Some(ObligationKind::MissingEvidence)};if mros.next().is_some()||mro.linearization!=Some(Linearization::Complete)||!source(d,mro,&d.symbolic_ancestry_supports,context)||d.symbolic_sequences.get(mro.ancestors).is_none_or(|s|s.id()!=SymbolSequence::empty()){return Some(ObligationKind::IncompleteDomain)}
 for method in d.declarations.iter().filter(|r|r.parent.is_some_and(|p|same(d,p,class))&&exact(d,r.qualification,context)){let Some(text)=d.spellings.iter().find(|s|same(d,s.occurrence,method.name))else{return Some(ObligationKind::MissingEvidence)};if matches!(text.spelling.as_str(),"__new__"|"__post_init__"|"__setattr__"|"__getattribute__"|"__getattr__")||d.symbolic_record_fields.iter().any(|f|f.class==symbol&&f.name.as_str()==text.spelling.as_str()){return Some(ObligationKind::IncompleteDomain)}}
 for f in d.symbolic_record_fields.iter().filter(|f|f.class==symbol&&exact(d,f.qualification,context)){if f.record!=RecordKind::Dataclass||!source(d,f,&d.symbolic_record_supports,context){return Some(ObligationKind::MissingEvidence)};let decls=d.fields.iter().filter(|l|d.field_syntax.get(l.declaration).is_some_and(|s|same(d,s.class,class)&&d.occurrences.get(s.target).zip(f.declaration.and_then(|id|d.occurrences.get(id))).is_some_and(|(a,b)|a.start==b.start&&a.source==b.source))).collect::<Vec<_>>();for l in decls{let Some(a)=out.fields.iter().find(|a|a.declaration==l.id())else{return Some(ObligationKind::MissingEvidence)};if !matches!(out.defaults.get(a.default),Some(FieldDefault::Absent{}|FieldDefault::Literal{..}|FieldDefault::Factory{..})){return Some(ObligationKind::IncompleteDomain)}}}
 // Exact standard decorator resolution/options and the full field-default inventory are
 // not yet checked here. Missing proof refuses; the partial screen cannot admit a record.
 Some(ObligationKind::MissingEvidence)
}
pub(super) fn normalize(d:&AspectData,out:&mut AspectOutput,b:&ResourceBudget)->Result<(),ModelError>{
 let allowance=d.occurrences.len().saturating_add(d.placements.len()).saturating_add(d.symbolic_record_fields.len()).saturating_mul(2048);let _scratch=b.reserve("source-symbolic-field-check",allowance.saturating_add(1024))?;
 for declaration in d.declarations.iter().filter(|r|r.kind==DeclarationKind::Class){let Some(q)=d.qualifications.get(declaration.qualification)else{continue};if !exact(d,q.id(),q.context)||!source(d,declaration,&d.symbolic_declaration_supports,q.context){continue}let class=declaration.declaration;let Some(symbol)=symbol_for(d,class,q.context)else{continue};let mut traits=d.symbolic_class_traits.iter().filter(|t|t.symbol==symbol&&exact(d,t.qualification,q.context)&&source(d,*t,&d.symbolic_class_supports,q.context));let Some(traits)=traits.next()else{continue};let Some(support)=d.symbolic_class_supports.iter().find(|s|s.assertion==traits.id())else{continue};let inventory=class_inventory(d,class,q.context,symbol);let reason=if traits.dataclass&&!traits.synthesized{record_gate(d,class,symbol,q.context,out)}else{Some(ObligationKind::IncompleteDomain)};let assessment=SourceFieldClass{class,qualification:q.id(),traits:traits.id(),support:support.id(),supported_record:reason.is_none(),reason,inventory};out.symbolic_classes.insert(assessment.clone())?;
  for function in d.declarations.iter().filter(|r|r.parent.is_some_and(|p|same(d,p,class))&&r.kind==DeclarationKind::Function&&exact(d,r.qualification,q.context)){
   let Some(traits)=method(d,function.declaration,symbol,q.context)else{continue};let Some(receiver)=receiver(d,function.declaration,q.context)else{continue};let is_init=d.spellings.iter().any(|s|same(d,s.occurrence,function.name)&&s.spelling.as_str()=="__init__");let plain=is_init&&plain_init(d,function.declaration,symbol,q.context,receiver);
   for p in d.placements.iter().filter(|p|contains(d,function.declaration,p.occurrence)&&exact(d,p.qualification,q.context)){
    let Some(name)=attribute(d,p.occurrence,receiver,q.context)else{continue};if p.field==SyntaxField::Target&&is_init{let Some(statement)=p.parent else{continue};if d.occurrences.get(statement).is_none_or(|s|s.syntax_kind!=SyntaxKind::StmtAssign){continue}let Some(rhs)=child(d,statement,SyntaxField::Value,q.context)else{continue};let Some(formal)=d.symbolic_parameter_declarations.iter().find(|a|contains(d,function.declaration,a.declaration)&&!same(d,a.declaration,receiver.parameter)&&formal_read(d,rhs.occurrence,a.declaration,q.context)&&source(d,*a,&d.symbolic_parameter_supports,q.context))else{continue};out.symbolic_stores.insert(SourceFieldStore{class,constructor:function.declaration,target:p.occurrence,name,value:rhs.occurrence,formal:formal.id(),receiver:receiver.id(),placement:p.id(),traits:traits.id(),qualification:q.id(),plain_initializer:plain,inventory})?;
    }else if p.field!=SyntaxField::Target&&!is_init{out.symbolic_readers.insert(SourceFieldReader{class,reader:function.declaration,access:p.occurrence,name,receiver:receiver.id(),placement:p.id(),traits:traits.id(),qualification:q.id(),inventory})?;}
   }
  }
  if !assessment.supported_record{continue}
  for f in d.symbolic_record_fields.iter().filter(|f|f.class==symbol&&exact(d,f.qualification,q.context)){
   for store in out.symbolic_stores.iter().filter(|s|same(d,s.class,class)&&s.name==f.name.as_str()&&s.plain_initializer){let Some(formal)=d.symbolic_parameter_declarations.get(store.formal)else{continue};out.symbolic_associations.insert(SourceFieldAssociation{class:assessment.id(),field:f.id(),parameter:formal.parameter,store:Some(store.id()),kind:SourceStorageKind::PlainInitializer,qualification:q.id(),inventory})?;}
   // Native generated initializer parameters have no source assignment or source formal.
   if !d.declarations.iter().any(|m|m.parent.is_some_and(|p|same(d,p,class))&&d.spellings.iter().any(|s|same(d,s.occurrence,m.name)&&s.spelling.as_str()=="__init__")){
    for signature in d.symbolic_signatures.iter().filter(|s|s.symbol==symbol&&exact(d,s.qualification,q.context)&&source(d,*s,&d.symbolic_signature_supports,q.context)){for p in d.symbolic_parameters.iter().filter(|p|p.signature==signature.id()){if d.symbolic_parameter_shapes.get(p.shape).is_some_and(|s|s.name.as_ref().is_some_and(|n|n.as_str()==f.name.as_str())){out.symbolic_associations.insert(SourceFieldAssociation{class:assessment.id(),field:f.id(),parameter:p.id(),store:None,kind:SourceStorageKind::GeneratedRecord,qualification:q.id(),inventory})?;}}}
   }
  }
 }
 for association in out.symbolic_associations.iter(){let Some(class)=out.symbolic_classes.get(association.class)else{continue};let Some(field)=d.symbolic_record_fields.get(association.field)else{continue};for reader in out.symbolic_readers.iter().filter(|r|same(d,r.class,class.class)&&r.name==field.name.as_str()&&r.qualification==association.qualification){out.symbolic_links.insert(SourceFieldReaderLink{association:association.id(),reader:reader.id()})?;}}
 Ok(())
}
