//! Native facts and confirmed entity sources publish Local entry/stability through the real store.
#[path="fixtures/local_model.rs"] mod local_model;
use cpg_core::{generation_read::{AttemptSession,ProviderOptions},model_runtime::{AttemptRuntime,RuntimeOptions}};
use cpg_extract::{acquisition::AcquiredInput,bundle::{CapturedInputs,run_stage},capture::CapturedInput};
use futures::TryStreamExt;
use lctx_model::domain::{*,admission::FrontierContract,local_semantics,normalized::{entity_normalization,entities::*},stages::*,source::*,value::*};
use lctx_postgres::{generations::GenerationStore,roles::{Role,RoleConfig},testing::DisposableDatabase};
use std::sync::Arc;
async fn run(profile:Profile) {
 let runtime=AttemptRuntime::new(RuntimeOptions{memory_bytes:1<<30,partitions:2}).unwrap();let budget=runtime.budget();let db=DisposableDatabase::start().await;db.migrate().await;
 let config=RoleConfig{format:1,role:Role::Importer,url:db.url("lctx_importer"),max_connections:6,provider_connections:4,acquire_timeout_seconds:5,statement_timeout_seconds:60,lock_timeout_seconds:10};let model=Arc::new(local_model::model());let store=GenerationStore::install(db.owner.clone(),model.clone()).await.unwrap();
 let root=std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/python/local_semantics");let bytes=std::fs::read(root.join("cases.py")).unwrap();
 let captured=Arc::new(CapturedInputs::new(vec![AcquiredInput::tree(CapturedInput::capture(&root,&["cases.py".into()],budget).unwrap(),"entry")],cpg_extract::native_context::NativeContextConfig::committed(profile,budget).unwrap()));
 let retained=budget.reserved();let mut providers=cpg_core::facts::providers(ContentHash::of(b"native entry publication"));let mut stages:Vec<_>=providers.iter().map(|p|p.declaration(profile)).collect();stages.extend([entity_normalization::stage(),normalized::relation_normalization::stage(profile),normalized::callable_normalization::stage(profile),normalized::callable_aspects::stage(profile),normalized::receiver::stage(profile),normalized::event_normalization::stage(profile),normalized::binding_normalization::stage(profile),projection::normalization::stage(profile),normalized::coverage::stage(profile)]);stages.push(analysis::preparation::native_stage(profile));
 let parameters=analysis::MethodParameters{depth:None,proof_steps:None,work:None,members:None,seed:None,iterations:None,threshold:None,resolution:None,damping:None,model_catalog:None};let definition=analysis::AnalysisDefinition{method:analysis::AnalysisMethod::LocalTransfers,semantic_version:ContentHash::of(b"Local direct v1"),parameters:parameters.id(),interpretation:analysis::Interpretation::ExactUnderContext};let configuration=analysis::preparation::Configuration::new(captured.config().catalog(),[(parameters,definition.clone())],budget).unwrap();stages.push(configuration.declaration());stages.push(local_semantics::stage(profile,&definition,&model));
 let facts_members=stages.iter().filter(|s|s.name!="analyze_local"&&s.outputs.iter().any(|r|is_vocabulary(r.name()))).map(|s|s.name).collect();let schedule=Schedule::build_with_publications(&model,stages,&[],profile,vec![PublicationGroup::new(PublicationBoundary::Facts,facts_members),PublicationGroup::new(PublicationBoundary::Local,vec!["analyze_local"])]).unwrap();let facts=FrontierContract::facts(&model,profile).unwrap();let mut execution=schedule.execute();let attempt=store.begin_conformance(db.writer.clone(),&mut execution,budget.clone()).await.unwrap();let id=attempt.generation();
 for stage in schedule.stages(){
  if stage.name=="normalize_entities" {attempt.checkpoint(&execution,&facts).await.unwrap();cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::normalize::entities(access,&attempt,&config,&runtime,&model).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="normalize_relations" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::normalize::relations(access,&attempt,&config,&runtime,&model).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="normalize_callables" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::normalize::callables(access,&attempt,&config,&runtime,&model).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="normalize_callable_aspects" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::catalog_core::aspects(access,&attempt,&config,&runtime,&model).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="normalize_receivers" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::normalize::receivers(access,&attempt,&config,&runtime,&model).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="normalize_events" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::normalize::events(access,&attempt,&config,&runtime,&model).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="normalize_bindings" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::normalize::bindings(access,&attempt,&config,&runtime,&model).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="normalize_projections" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::normalize::projections(access,&attempt,&config,&runtime,&model).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="normalize_coverage" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::normalize::coverage(access,&attempt,&config,&runtime,&model).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="analysis_native_inventory" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::analysis_prepare::native_inventory(access,&attempt,&config,&runtime,&model).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="analysis_configuration" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::analysis_prepare::configuration(access,&attempt,&model,&runtime,&configuration).await,&mut |_|{}).await.unwrap();}
  else if stage.name=="analyze_local" {cpg_core::stage_runtime::run_declared_stage(&mut execution,stage,async |access|cpg_core::local_semantics::run(access,&attempt,&config,&runtime,&model,&definition).await,&mut |_|{}).await.unwrap();}
  else {let index=providers.iter().position(|p|p.declaration(profile).name==stage.name).unwrap();run_stage(providers.swap_remove(index),execution.begin(stage.name).unwrap(),&attempt,&model,&captured,budget,Default::default()).await.unwrap();}
 }
 drop(configuration);let checked=attempt.seal(execution.finish().unwrap()).await.unwrap().validate().await;let validated=checked.unwrap();let counts:(i64,i64,i64)=sqlx::query_as(sqlx::AssertSqlSafe(format!("SELECT (SELECT count(*) FROM {}.local_flow_contributions),(SELECT count(*) FROM {}.local_transfer_alternatives),(SELECT count(*) FROM {}.local_flow_assessments WHERE reason IS NOT NULL)",id.schema(),id.schema(),id.schema()))).fetch_one(db.owner.pool()).await.unwrap();if profile==Profile::Behavioral{assert!(counts.0>0);assert_eq!(counts.0,counts.1);assert!(counts.2>0);}else{assert_eq!(counts,(0,0,0));let statuses:Vec<i16>=sqlx::query_scalar(sqlx::AssertSqlSafe(format!("SELECT status FROM {}.local_analysis_outcomes",id.schema()))).fetch_all(db.owner.pool()).await.unwrap();assert!(!statuses.is_empty());assert!(statuses.iter().all(|s|*s==3));let availabilities:Vec<i16>=sqlx::query_scalar(sqlx::AssertSqlSafe(format!("SELECT availability FROM {}.local_analysis_coverage",id.schema()))).fetch_all(db.owner.pool()).await.unwrap();assert!(!availabilities.is_empty());assert!(availabilities.iter().all(|s|*s==normalized::coverage::EvidenceAvailability::NotRequested.code() as i16));}let complete:i64=sqlx::query_scalar(sqlx::AssertSqlSafe(format!("SELECT count(*) FROM {}.local_analysis_coverage WHERE availability=0",id.schema()))).fetch_one(db.owner.pool()).await.unwrap();assert_eq!(complete,0);validated.abort().await.unwrap();drop(captured);assert_eq!(budget.reserved(),0);
}
#[tokio::test] async fn actual_local_transfers_publish_from_native_completed_sources(){run(Profile::Behavioral).await;}

#[tokio::test] async fn catalog_local_publishes_not_requested_without_semantic_rows(){run(Profile::Catalog).await;}
