"""Render OUTDIR/report.md from metrics.json and extras.json (local reading; may show command shapes)."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config  # noqa: E402

OUT = config.OUTDIR
lines = []


def w(s=""):
    lines.append(s)


def top(d, n=20):
    return sorted((d or {}).items(), key=lambda x: -x[1] if isinstance(x[1], (int, float)) else 0)[:n]


def table(title, d, keys=("all", "all|P0-3", "all|P4-5"), n=20):
    w("### " + title)
    for k in keys:
        if k in d:
            w("- **%s**: %s" % (k, ", ".join("%s %s" % (a, b) for a, b in top(d[k], n))))
    w()


def main():
    M = json.load(open(os.path.join(OUT, "metrics.json")))
    X = json.load(open(os.path.join(OUT, "extras.json")))
    L = M["lctx"]
    w("# W1 friction-mechanism report (library-context)")
    w()
    w("Generated by miner/report.py. Local only: shapes below are normalized command forms.")
    w()
    table("Shell commands by stratum", M["shell"], keys=sorted(M["shell"]), n=1)
    table("Classes", M["classes"])
    table("Outcomes", M["outcomes"])
    table("Heuristics", M["heuristics"], n=40)
    table("Recipes used", M["recipes"]["used"], n=40)
    w("- used but no longer defined: %s" % ", ".join(M["recipes"]["used_not_current"]))
    w("- defined but never used: %s" % ", ".join(M["recipes"]["never_used_current"]))
    w()
    for k in ("families", "bare_cargo_tests", "uv", "wrappers", "locations", "edit_errors", "codex_fn", "compactions", "timeout_params"):
        table("lctx: " + k, L[k], n=30)
    w("### Family and agent-flock wall time")
    for k, v in sorted(L["family_wall"].get("all", {}).items()):
        w("- %s: n=%s sum_h=%s p50=%s p90=%s max=%s" % (k, v["n"], v["sum_h"], v["p50"], v["p90"], v["max"]))
    w()
    table("Polling", M["polling"]["counts"])
    w("- sleep: %s" % json.dumps(M["polling"]["sleep"].get("all")))
    w("- lock-wait commands (total wall incl. work): %s" % json.dumps(M["polling"]["lockwait"].get("all")))
    w()
    table("Retries without an edit", M["retry"]["no_edit"])
    table("Redirect vs pipe", M["pipes"]["redirect_vs_pipe"])
    w("### Wall time by class (P4-5)")
    for c, v in M["wall_by_class"].get("all|P4-5", {}).items():
        w("- %s: n=%s sum_h=%s p50=%s p90=%s" % (c, v["n"], v["sum_h"], v["p50"], v["p90"]))
    w()
    w("### Extras")
    for k, v in X.items():
        w("- **%s**: `%s`" % (k, json.dumps(v)[:1500]))
    w()
    w("### Longest commands")
    for x in M["longest"][:15]:
        w("- %ss %s-%s %s %s :: %s" % (x["wall_s"], x["rt"], x["ak"], x["per"], x["out"], x["norm"][:110]))
    open(os.path.join(OUT, "report.md"), "w").write("\n".join(lines) + "\n")
    print("wrote", os.path.join(OUT, "report.md"), len(lines), "lines")


if __name__ == "__main__":
    main()
