//! Total invocation domain is derived from actual native runs, including inputs with no roots.
use super::{*,build::{invalid,need}};
use crate::domain::{attribution::ProviderRun,normalized::Rows,resources::ResourceBudget,charged::{ChargedSet,StateCharge}};
use analysis::{catalog_core as core,catalog_evidence as evidence};
pub fn parents(runs:&Rows<ProviderRun>,parents:&Rows<core::Invocation>,budget:&ResourceBudget)->Result<Rows<core::Invocation>,ModelError> {
 let mut charge=StateCharge::new(budget,"catalog-evidence-invocation-frames");let mut frames=ChargedSet::default();for run in runs.iter() {frames.insert(&mut charge,(run.input,run.context))?;}
 let definition=catalog::build::definition().1.id();let mut output=Rows::new(budget);
 for (input,context) in frames.iter() {let mut candidates=parents.iter().filter(|r|r.input==*input && r.context==*context && r.definition==definition && r.subject.is_none());let parent=candidates.next().ok_or_else(||invalid("C1 requires the fixed completed C0 invocation for every native frame"))?;if candidates.next().is_some() {return Err(invalid("C1 native frame has duplicate C0 invocations"));}output.insert(parent.clone())?;}Ok(output)
}
pub fn verify(runs:&Rows<ProviderRun>,core:&Rows<core::Invocation>,invocations:&Rows<evidence::Invocation>,sources:&Rows<evidence::InvocationSource>,inputs:&Rows<evidence::AnalysisInput>,budget:&ResourceBudget)->Result<(),ModelError> {
 let parents=parents(runs,core,budget)?;let definition=super::build::definition().1.id();let mut expected_sources=Rows::new(budget);let mut expected_inputs=Rows::new(budget);let mut count=0;
 for parent in parents.iter() {let mut matches=invocations.iter().filter(|r|r.input==parent.input && r.context==parent.context && r.definition==definition && r.subject.is_none());let invocation=matches.next().ok_or_else(||invalid("catalog evidence invocation domain is incomplete"))?;if matches.next().is_some() {return Err(invalid("catalog evidence frame has duplicate invocations"));}count+=1;let source=expected_sources.insert(evidence::InvocationSource::CatalogCore {invocation:parent.id()})?;expected_inputs.insert(evidence::AnalysisInput {invocation:invocation.id(),parent:source})?;}
 if count!=invocations.len() || !expected_sources.same(sources) || !expected_inputs.same(inputs) {return Err(invalid("catalog evidence invocation frames or exact C0 parent membership differ"));}Ok(())
}
pub(super) fn invariants()->Vec<Invariant> {vec![Invariant {name:"catalog_evidence_invocation_domain",inputs:vec![ValidationInput::of::<ProviderRun>(&["id"]),ValidationInput::of::<core::Invocation>(&["id"]),ValidationInput::of::<evidence::Invocation>(&["id"]),ValidationInput::of::<evidence::InvocationSource>(&["id"]),ValidationInput::of::<evidence::AnalysisInput>(&["id"])],create:std::sync::Arc::new(|b|Box::new(Check {runs:Rows::new(b),core:Rows::new(b),invocations:Rows::new(b),sources:Rows::new(b),inputs:Rows::new(b),budget:b.clone()}))}]}
struct Check {runs:Rows<ProviderRun>,core:Rows<core::Invocation>,invocations:Rows<evidence::Invocation>,sources:Rows<evidence::InvocationSource>,inputs:Rows<evidence::AnalysisInput>,budget:ResourceBudget}
impl InvariantCheck for Check {fn visit(&mut self,name:&str,batch:&arrow_array::RecordBatch)->Result<(),ModelError> {if name==ProviderRun::NAME {self.runs.decode(batch)?;}else if name==core::Invocation::NAME {self.core.decode(batch)?;}else if name==evidence::Invocation::NAME {self.invocations.decode(batch)?;}else if name==evidence::InvocationSource::NAME {self.sources.decode(batch)?;}else if name==evidence::AnalysisInput::NAME {self.inputs.decode(batch)?;}else {return Err(invalid("undeclared evidence frame input"));}Ok(())}fn finish(self:Box<Self>)->Result<(),ModelError> {verify(&self.runs,&self.core,&self.invocations,&self.sources,&self.inputs,&self.budget)} }
