//! Hand-expected scope/membership controls; native graph topology and PG publication are separate.
use lctx_model::domain::{*,analysis::{self,settings::AnalyticsConfiguration,structural as owner},structural::{*,build::{self,Data},frames::Context},normalized::{Rows,entities::*,callables::*},projection::{self,snapshot::hydrate},resources::ResourceBudget,source::*,attribution::*,catalog::*};
fn id<T>(n:u8)->Id<T>{serde::Deserialize::deserialize(serde::de::value::SeqDeserializer::<_,serde::de::value::Error>::new([n;16].into_iter())).unwrap()}
fn fixture()->(ResourceBudget,Data,Context){
 let b=ResourceBudget::fixed(64<<20).unwrap();let mut d=Data::new(&b);let mut c=Context::new(&b);let settings=AnalyticsConfiguration{module_prefixes:vec!["api".into()],public_roots:vec!["api".into()],configured_seeds:vec!["api.run".into(),"api.missing".into()],depth:2,vertices:16,arcs:32,witnesses:2,brief_budget:3,communities:false,pagerank:false,fca:false,rca:false,knn:false,type_layer:false,mention_layer:false,knn_layer:false};
 c.settings.insert(settings.clone()).unwrap();let input=id(1);let context=id(2);let artifact=SourceArtifact::from_bytes(input,"api.py".into(),b"def run(): pass\n").unwrap();d.projection.artifacts.insert(artifact.clone()).unwrap();d.projection.scopes.insert(CoverageScope::Input{input}).unwrap();d.projection.scopes.insert(CoverageScope::Artifact{artifact:artifact.id()}).unwrap();let module=d.projection.modules.insert(Module{source:artifact.id(),qualified_name:"api".into()}).unwrap();d.uses.insert(input::ArtifactUse{input,artifact:artifact.id(),role:input::SourceRole::Release}).unwrap();
 d.projection.runs.insert(ProviderRun{provider:id(3),context,input,configuration:ContentHash::of(b"c"),requested_families:ContentHash::of(b"r")}).unwrap();let declaration=d.projection.occurrences.insert(Occurrence{source:artifact.id(),start:0,end:15,syntax_kind:SyntaxKind::StmtFunctionDef,role:OccurrenceRole::Syntax,structural_path:vec![0]}).unwrap();let callable=d.projection.callables.insert(CallableEntity::Source{declaration,kind:CallableKind::Function}).unwrap();let entity=d.projection.refs.insert(EntityRef::Callable{callable}).unwrap();
 let core=analysis::catalog_core::Invocation::new(input,context,catalog::build::definition().1.id(),None,[]).0;d.core_invocations.insert(core.clone()).unwrap();let local=c.local.insert(analysis::local::Invocation::new(input,context,id(4),None,[]).0).unwrap();let member=d.members.insert(CatalogMember{input,access:module,path:vec!["run".into()],name:"run".into()}).unwrap();d.core_links.insert(CatalogMemberInvocation{member,invocation:core.id()}).unwrap();let assessment=d.assessments.insert(EffectiveCallableAssessment{callable,context,decorators:ContentHash::of(b"d"),policy:ContentHash::of(b"p"),identity:Knowledge::Unknown,identity_reason:CallableReason::UnsupportedDecorator,signatures:Knowledge::Known,signature_reason:CallableReason::EvidenceAgreement,descriptor:Knowledge::Unknown,descriptor_kind:None,descriptor_reason:CallableReason::UnsupportedDecorator,body:Knowledge::Unknown,body_admitted:false,body_reason:CallableReason::MissingBodyEvidence,asynchronous:None,generator:None}).unwrap();d.callables.insert(CatalogCallable{member,candidate:id(5),assessment,basis:CatalogContractBasis::PublicCandidate}).unwrap();
 c.graphs=projection::normalization::normalize(&d.projection,&b).unwrap();
 for method in [analysis::AnalysisMethod::Delegation,analysis::AnalysisMethod::DirectUsage]{let (parameters,definition)=build::definition(&settings,method).unwrap();c.parameters.insert(parameters).unwrap();c.definitions.insert(definition.clone()).unwrap();let parents=[owner::InvocationSource::Local{invocation:local},owner::InvocationSource::CatalogCore{invocation:core.id()}];let (row,links)=owner::Invocation::new(input,context,definition.id(),None,parents.iter().map(Record::id));for parent in parents{c.sources.insert(parent).unwrap();}for link in links{c.inputs.insert(link).unwrap();}c.invocations.insert(row).unwrap();}
 assert_eq!(d.projection.refs.get(entity).unwrap().id(),entity);(b,d,c)
}
fn produce(d:&Data,c:&Context,b:&ResourceBudget)->Output{let core=d.core_invocations.iter().next().unwrap();let f=frames::frame(c,core).unwrap();let graph=|assessment|{let a=c.graphs.assessments.get(assessment).unwrap();let h=c.graphs.snapshots.iter().find(|s|s.assessment==assessment).unwrap();hydrate(h,a,&c.graphs.chunks,b).unwrap()};build::produce(d,&f,c.invocations.get(f.invocation).unwrap(),c.configuration().unwrap(),&graph(f.invocation_graph),&graph(f.definition_graph),b).unwrap()}
#[test]
fn candidate_uncertainty_missing_authored_seed_and_exact_scope_survive_replay(){let (b,d,c)=fixture();let out=produce(&d,&c,&b);frames::verify(&d,&c,&out,&b).unwrap();assert_eq!(out.public.len(),1);let candidate=out.public.iter().next().unwrap();assert_eq!(candidate.path,"api.run");assert!(candidate.in_subsystem);assert_eq!(out.configured.iter().find(|r|r.path=="api.missing").unwrap().candidates,0);assert!(out.usage_scores.is_empty(),"missing observed use is not a stored zero score");assert_eq!(d.assessments.iter().next().unwrap().identity,Knowledge::Unknown);
 let mut omitted=produce(&d,&c,&b);omitted.public=Rows::new(&b);assert!(frames::verify(&d,&c,&omitted,&b).is_err());let mut forged=produce(&d,&c,&b);let mut seed=forged.configured.iter().find(|r|r.path=="api.missing").unwrap().clone();seed.candidates=1;forged.configured=Rows::new(&b);forged.configured.insert(seed).unwrap();assert!(frames::verify(&d,&c,&forged,&b).is_err());
 let tiny=ResourceBudget::fixed(1).unwrap();let core=d.core_invocations.iter().next().unwrap();let f=frames::frame(&c,core).unwrap();let a=c.graphs.assessments.get(f.invocation_graph).unwrap();let h=c.graphs.snapshots.iter().find(|s|s.assessment==a.id()).unwrap();assert!(hydrate(h,a,&c.graphs.chunks,&tiny).is_err());assert_eq!(tiny.reserved(),0);
 drop(out);drop(omitted);drop(forged);drop(d);drop(c);assert_eq!(b.reserved(),0);
}
#[test]
fn coupled_frame_removal_foreign_settings_and_parent_shrink_refuse(){let (b,d,mut c)=fixture();let out=produce(&d,&c,&b);c.invocations=Rows::new(&b);c.inputs=Rows::new(&b);c.sources=Rows::new(&b);assert!(frames::verify(&d,&c,&Output::new(&b),&b).is_err());drop(out);let (b,d,mut c)=fixture();let out=produce(&d,&c,&b);c.inputs=Rows::new(&b);assert!(frames::verify(&d,&c,&out,&b).is_err());let mut changed=c.configuration().unwrap().clone();changed.depth+=1;c.settings=Rows::new(&b);c.settings.insert(changed).unwrap();assert!(frames::verify(&d,&c,&out,&b).is_err());}
#[test]
fn static_conclusions_retain_exact_source_and_refuse_promotion_or_erasure(){
 use analysis::{policy::{FindingKind,EvidenceStatus},support::DerivedEvidence};
 let (b,d,c)=fixture();let mut out=produce(&d,&c,&b);let row=out.conclusions.iter().find(|r|r.kind==FindingKind::PublicAlias).unwrap().clone();
 assert_eq!(row.source_facts().status,EvidenceStatus::StructurallyObserved);
 let q=out.conclusion_qualifications.get(row.qualification()).unwrap();assert_eq!(q.modality,Modality::Candidate);assert_eq!(q.approximation,assertion::Approximation::Over);assert_eq!(q.condition,conditions::Diagram::always().id());assert_eq!(q.scope,CoverageScope::Input{input:d.core_invocations.iter().next().unwrap().input}.id());
 assert!(matches!(out.conclusion_sources.get(row.source),Some(ConclusionSource::Public{candidate}) if out.public.get(*candidate).is_some()));
 let mut forged=row;forged.kind=FindingKind::ConditionalRaise;out.conclusions=Rows::new(&b);out.conclusions.insert(forged).unwrap();assert!(frames::verify(&d,&c,&out,&b).is_err());
 let mut out=produce(&d,&c,&b);out.conclusions=Rows::new(&b);out.conclusion_sources=Rows::new(&b);assert!(frames::verify(&d,&c,&out,&b).is_err());
}
