//! Finite transport contract dispatch.
use super::*;
pub fn schema(name: &str, output: bool) -> Result<serde_json::Value, WireError> {
    match name {
        "Requirement" => Ok(schema_for::<Requirement>(output)),
        "RequirementResult" => Ok(schema_for::<RequirementResult>(output)),
        "EmbeddingSpec" => Ok(schema_for::<crate::embedding_spec::Spec>(output)),
        "ProjectionManifest" => Ok(schema_for::<crate::serving_projection::Manifest>(output)),
        "RelationReceipt" => Ok(schema_for::<crate::serving_projection::RelationReceipt>(
            output,
        )),
        "ArtifactReceipt" => Ok(schema_for::<crate::serving_projection::ArtifactReceipt>(
            output,
        )),
        "Capabilities" => Ok(schema_for::<crate::catalog::Capabilities>(output)),
        "CoverageSummary" => Ok(schema_for::<crate::serving_projection::CoverageSummary>(
            output,
        )),

        "Discharge" => Ok(schema_for::<Discharge>(output)),
        "Fate" => Ok(schema_for::<Fate>(output)),
        "ParameterRecord" => Ok(schema_for::<ParameterRecord>(output)),
        "SettingRead" => Ok(schema_for::<SettingRead>(output)),
        "FieldRecord" => Ok(schema_for::<FieldRecord>(output)),
        "FacetValue" => Ok(schema_for::<FacetValue>(output)),
        "CatalogMember" => Ok(schema_for::<CatalogMember>(output)),
        "CatalogBinding" => Ok(schema_for::<CatalogBinding>(output)),
        "CatalogParameter" => Ok(schema_for::<CatalogParameter>(output)),
        "CatalogSignature" => Ok(schema_for::<CatalogSignature>(output)),
        "CatalogEvidence" => Ok(schema_for::<CatalogEvidence>(output)),
        "CatalogType" => Ok(schema_for::<CatalogType>(output)),
        "CatalogTypeArgument" => Ok(schema_for::<CatalogTypeArgument>(output)),
        "CatalogTypeObservation" => Ok(schema_for::<CatalogTypeObservation>(output)),
        "CatalogConstructor" => Ok(schema_for::<CatalogConstructor>(output)),
        "CatalogRecord" => Ok(schema_for::<CatalogRecord>(output)),
        "AmbiguousOperation" => Ok(schema_for::<AmbiguousOperation>(output)),
        "Operation" => Ok(schema_for::<Operation>(output)),
        "OperationRef" => Ok(schema_for::<OperationRef>(output)),
        "OperationSet" => Ok(schema_for::<OperationSet>(output)),
        "OperationHit" => Ok(schema_for::<OperationHit>(output)),
        "OperationHits" => Ok(schema_for::<OperationHits>(output)),
        "Hit" => Ok(schema_for::<Hit>(output)),
        "CapabilityUnavailable" => Ok(schema_for::<CapabilityUnavailable>(output)),
        "SearchResult" => Ok(schema_for::<SearchResult>(output)),
        "Evidence" => Ok(schema_for::<Evidence>(output)),
        "FindingWitness" => Ok(schema_for::<FindingWitness>(output)),
        "ConceptAttribute" => Ok(schema_for::<ConceptAttribute>(output)),
        "AttributeIncidence" => Ok(schema_for::<AttributeIncidence>(output)),
        "FindingMember" => Ok(schema_for::<FindingMember>(output)),
        "FindingSupport" => Ok(schema_for::<FindingSupport>(output)),
        "Support" => Ok(schema_for::<Support>(output)),
        "Assertion" => Ok(schema_for::<Assertion>(output)),
        "Capability" => Ok(schema_for::<Capability>(output)),
        "RetrievalMetadata" => Ok(schema_for::<RetrievalMetadata>(output)),
        "ProofStep" => Ok(schema_for::<ProofStep>(output)),
        "ValueLinkEvidence" => Ok(schema_for::<ValueLinkEvidence>(output)),
        "TheoryWork" => Ok(schema_for::<TheoryWork>(output)),
        "ValuePath" => Ok(schema_for::<ValuePath>(output)),
        "OpenBoundary" => Ok(schema_for::<OpenBoundary>(output)),
        "ValuePathPage" => Ok(schema_for::<ValuePathPage>(output)),
        "Where" => Ok(schema_for::<Where>(output)),
        "FacetTerm" => Ok(schema_for::<FacetTerm>(output)),
        "ExactPrimitive" => Ok(schema_for::<ExactPrimitive>(output)),
        "SearchCapabilitiesRequest" => Ok(schema_for::<SearchCapabilitiesRequest>(output)),
        "GetCapabilityRequest" => Ok(schema_for::<GetCapabilityRequest>(output)),
        "GetOperationRequest" => Ok(schema_for::<GetOperationRequest>(output)),
        "InspectValuePathsRequest" => Ok(schema_for::<InspectValuePathsRequest>(output)),
        "FindOperationsRequest" => Ok(schema_for::<FindOperationsRequest>(output)),
        "SearchOperationsRequest" => Ok(schema_for::<SearchOperationsRequest>(output)),
        "GetOperationResponse" => Ok(schema_for::<GetOperationResponse>(output)),
        "GetCapabilityResponse" => Ok(schema_for::<GetCapabilityResponse>(output)),
        "SearchCapabilitiesResponse" => Ok(schema_for::<SearchCapabilitiesResponse>(output)),
        "InspectValuePathsResponse" => Ok(schema_for::<InspectValuePathsResponse>(output)),
        "FindOperationsResponse" => Ok(schema_for::<FindOperationsResponse>(output)),
        "SearchOperationsResponse" => Ok(schema_for::<SearchOperationsResponse>(output)),
        _ => Err(WireError("unknown wire contract".into())),
    }
}
pub fn decode(name: &str, raw: &str) -> Result<String, WireError> {
    if raw.len() > RESPONSE_BYTES {
        return Err(WireError("resource_refused: wire byte budget".into()));
    }
    match name {
        "Requirement" => normalize::<Requirement>(raw),
        "RequirementResult" => normalize::<RequirementResult>(raw),
        "EmbeddingSpec" => normalize::<crate::embedding_spec::Spec>(raw),
        "ProjectionManifest" => normalize::<crate::serving_projection::Manifest>(raw),
        "RelationReceipt" => normalize::<crate::serving_projection::RelationReceipt>(raw),
        "ArtifactReceipt" => normalize::<crate::serving_projection::ArtifactReceipt>(raw),
        "Capabilities" => normalize::<crate::catalog::Capabilities>(raw),
        "CoverageSummary" => normalize::<crate::serving_projection::CoverageSummary>(raw),

        "Discharge" => normalize::<Discharge>(raw),
        "Fate" => normalize::<Fate>(raw),
        "ParameterRecord" => normalize::<ParameterRecord>(raw),
        "SettingRead" => normalize::<SettingRead>(raw),
        "FieldRecord" => normalize::<FieldRecord>(raw),
        "FacetValue" => normalize::<FacetValue>(raw),
        "CatalogMember" => normalize::<CatalogMember>(raw),
        "CatalogBinding" => normalize::<CatalogBinding>(raw),
        "CatalogParameter" => normalize::<CatalogParameter>(raw),
        "CatalogSignature" => normalize::<CatalogSignature>(raw),
        "CatalogEvidence" => normalize::<CatalogEvidence>(raw),
        "CatalogType" => normalize::<CatalogType>(raw),
        "CatalogTypeArgument" => normalize::<CatalogTypeArgument>(raw),
        "CatalogTypeObservation" => normalize::<CatalogTypeObservation>(raw),
        "CatalogConstructor" => normalize::<CatalogConstructor>(raw),
        "CatalogRecord" => normalize::<CatalogRecord>(raw),
        "AmbiguousOperation" => normalize::<AmbiguousOperation>(raw),
        "Operation" => normalize::<Operation>(raw),
        "OperationRef" => normalize::<OperationRef>(raw),
        "OperationSet" => normalize::<OperationSet>(raw),
        "OperationHit" => normalize::<OperationHit>(raw),
        "OperationHits" => normalize::<OperationHits>(raw),
        "Hit" => normalize::<Hit>(raw),
        "CapabilityUnavailable" => normalize::<CapabilityUnavailable>(raw),
        "SearchResult" => normalize::<SearchResult>(raw),
        "Evidence" => normalize::<Evidence>(raw),
        "FindingWitness" => normalize::<FindingWitness>(raw),
        "ConceptAttribute" => normalize::<ConceptAttribute>(raw),
        "AttributeIncidence" => normalize::<AttributeIncidence>(raw),
        "FindingMember" => normalize::<FindingMember>(raw),
        "FindingSupport" => normalize::<FindingSupport>(raw),
        "Support" => normalize::<Support>(raw),
        "Assertion" => normalize::<Assertion>(raw),
        "Capability" => normalize::<Capability>(raw),
        "RetrievalMetadata" => normalize::<RetrievalMetadata>(raw),
        "ProofStep" => normalize::<ProofStep>(raw),
        "ValueLinkEvidence" => normalize::<ValueLinkEvidence>(raw),
        "TheoryWork" => normalize::<TheoryWork>(raw),
        "ValuePath" => normalize::<ValuePath>(raw),
        "OpenBoundary" => normalize::<OpenBoundary>(raw),
        "ValuePathPage" => normalize::<ValuePathPage>(raw),
        "Where" => normalize::<Where>(raw),
        "FacetTerm" => normalize::<FacetTerm>(raw),
        "ExactPrimitive" => normalize::<ExactPrimitive>(raw),
        "SearchCapabilitiesRequest" => normalize::<SearchCapabilitiesRequest>(raw),
        "GetCapabilityRequest" => normalize::<GetCapabilityRequest>(raw),
        "GetOperationRequest" => normalize::<GetOperationRequest>(raw),
        "InspectValuePathsRequest" => normalize::<InspectValuePathsRequest>(raw),
        "FindOperationsRequest" => normalize::<FindOperationsRequest>(raw),
        "SearchOperationsRequest" => normalize::<SearchOperationsRequest>(raw),
        "GetOperationResponse" => normalize::<GetOperationResponse>(raw),
        "GetCapabilityResponse" => normalize::<GetCapabilityResponse>(raw),
        "SearchCapabilitiesResponse" => normalize::<SearchCapabilitiesResponse>(raw),
        "InspectValuePathsResponse" => normalize::<InspectValuePathsResponse>(raw),
        "FindOperationsResponse" => normalize::<FindOperationsResponse>(raw),
        "SearchOperationsResponse" => normalize::<SearchOperationsResponse>(raw),
        _ => Err(WireError("unknown wire contract".into())),
    }
}
