//! One finite declaration drives both generated schemas and Rust decoding.
use super::*;
macro_rules! contracts {
    ($($name:literal => $ty:ty),+ $(,)?) => {
        pub fn schema(name: &str, output: bool) -> Result<serde_json::Value, WireError> {
            match name { $($name => Ok(schema_for::<$ty>(output)),)+ _ => Err(WireError("unknown wire contract".into())) }
        }
        pub fn decode(name: &str, raw: &str) -> Result<String, WireError> {
            if raw.len() > RESPONSE_BYTES { return Err(WireError("resource_refused: wire byte budget".into())); }
            match name { $($name => normalize::<$ty>(raw),)+ _ => Err(WireError("unknown wire contract".into())) }
        }
    };
}
contracts! {
    "TaskReceipt" => crate::evidence::TaskReceipt,
    "GetEvidenceRequest" => GetEvidenceRequest,
    "GetEvidenceResponse" => GetEvidenceResponse,
    "EvidenceResult" => EvidenceResult,
    "Selection" => Selection,
    "SelectionResults" => SelectionResults,
    "Requirement" => Requirement,
    "RequirementResult" => RequirementResult,
    "EmbeddingSpec" => lctx_model::domain::embedding::Spec,
    "ProjectionManifest" => crate::serving_projection::Manifest,
    "RelationReceipt" => crate::serving_projection::RelationReceipt,
    "ArtifactReceipt" => crate::serving_projection::ArtifactReceipt,
    "Capabilities" => crate::catalog::Capabilities,
    "CoverageSummary" => crate::serving_projection::CoverageSummary,
    "Discharge" => Discharge,
    "Fate" => Fate,
    "SettingRead" => SettingRead,
    "FieldRecord" => FieldRecord,
    "FacetValue" => FacetValue,
    "CatalogMember" => CatalogMember,
    "CatalogBinding" => CatalogBinding,
    "CatalogParameter" => CatalogParameter,
    "CatalogSignature" => CatalogSignature,
    "CatalogEvidence" => CatalogEvidence,
    "CatalogType" => CatalogType,
    "CatalogTypeArgument" => CatalogTypeArgument,
    "CatalogTypeObservation" => CatalogTypeObservation,
    "CatalogConstructor" => CatalogConstructor,
    "CatalogRecord" => CatalogRecord,
    "AmbiguousOperation" => AmbiguousOperation,
    "Hit" => Hit,
    "CapabilityUnavailable" => CapabilityUnavailable,
    "SearchResult" => SearchResult,
    "Evidence" => Evidence,
    "FindingWitness" => FindingWitness,
    "ConceptAttribute" => ConceptAttribute,
    "AttributeIncidence" => AttributeIncidence,
    "FindingMember" => FindingMember,
    "FindingSupport" => FindingSupport,
    "Support" => Support,
    "Assertion" => Assertion,
    "Capability" => Capability,
    "RetrievalMetadata" => RetrievalMetadata,
    "ProofStep" => ProofStep,
    "ValueLinkEvidence" => ValueLinkEvidence,
    "TheoryWork" => TheoryWork,
    "ValuePath" => ValuePath,
    "OpenBoundary" => OpenBoundary,
    "ValuePathPage" => ValuePathPage,
    "FacetTerm" => FacetTerm,
    "ExactPrimitive" => ExactPrimitive,
    "SearchCapabilitiesRequest" => SearchCapabilitiesRequest,
    "GetCapabilityRequest" => GetCapabilityRequest,
    "GetOperationRequest" => GetOperationRequest,
    "InspectValuePathsRequest" => InspectValuePathsRequest,
    "FindOperationsRequest" => FindOperationsRequest,
    "SearchOperationsRequest" => SearchOperationsRequest,
    "GetOperationResponse" => GetOperationResponse,
    "GetCapabilityResponse" => GetCapabilityResponse,
    "SearchCapabilitiesResponse" => SearchCapabilitiesResponse,
    "InspectValuePathsResponse" => InspectValuePathsResponse,
    "FindOperationsResponse" => FindOperationsResponse,
    "SearchOperationsResponse" => SearchOperationsResponse,
    "OperationPacket" => OperationPacket,
    "OperationSectionPage" => OperationSectionPage,
    "BrowseLibraryRequest" => BrowseLibraryRequest,
    "BrowseLibraryResponse" => BrowseLibraryResponse,
    "SearchEvidenceRequest" => SearchEvidenceRequest,
    "SearchEvidenceResponse" => SearchEvidenceResponse,
    "CompareOperationsRequest" => CompareOperationsRequest,
    "CompareOperationsResponse" => CompareOperationsResponse,
}
