//! JSON adapters consume the same finite vocabulary as canonical validation and PG DDL.
use super::*;
macro_rules! vocabulary {
 ($name:ident,$decode:ident,$nullable:ident,$relation:literal,$field:literal)=>{
  pub struct $name;
  impl JsonSchema for $name {
   fn schema_name()->Cow<'static,str>{stringify!($name).into()}
   fn json_schema(_: &mut SchemaGenerator)->Schema{json_schema!({"type":"string","enum":crate::catalog::vocabulary($relation,$field).expect("declared vocabulary")})}
  }
  pub fn $decode<'de,D:Deserializer<'de>>(d:D)->Result<String,D::Error>{
   let value=String::deserialize(d)?;
   if crate::catalog::vocabulary($relation,$field).expect("declared vocabulary").contains(&value.as_str()){Ok(value)}else{Err(serde::de::Error::custom(concat!("invalid ",$relation,".",$field)))}
  }
  pub fn $nullable<'de,D:Deserializer<'de>>(d:D)->Result<Option<String>,D::Error>{
   let value=Option::<String>::deserialize(d)?;
   if value.as_ref().is_none_or(|value|crate::catalog::vocabulary($relation,$field).expect("declared vocabulary").contains(&value.as_str())){Ok(value)}else{Err(serde::de::Error::custom(concat!("invalid ",$relation,".",$field)))}
  }
 }
}
vocabulary!(
    Profile,
    decode_profile,
    decode_profile_nullable,
    "catalog_compilation",
    "profile"
);
vocabulary!(
    BriefState,
    decode_brief_state,
    decode_brief_state_nullable,
    "catalog_members",
    "brief_status"
);
vocabulary!(
    BindingResolution,
    decode_binding_resolution,
    decode_binding_resolution_nullable,
    "catalog_members",
    "resolution"
);
vocabulary!(
    BindingRole,
    decode_binding_role,
    decode_binding_role_nullable,
    "catalog_bindings",
    "role"
);
vocabulary!(
    SignatureRole,
    decode_signature_role,
    decode_signature_role_nullable,
    "catalog_signatures",
    "role"
);
vocabulary!(
    SignatureForm,
    decode_signature_form,
    decode_signature_form_nullable,
    "catalog_signatures",
    "form"
);
vocabulary!(
    DefaultState,
    decode_default_state,
    decode_default_state_nullable,
    "catalog_parameters",
    "default_state"
);
vocabulary!(
    ParameterKind,
    decode_parameter_kind,
    decode_parameter_kind_nullable,
    "catalog_parameters",
    "kind"
);
vocabulary!(
    ProviderParameterKind,
    decode_provider_parameter_kind,
    decode_provider_parameter_kind_nullable,
    "catalog_parameters",
    "provider_kind"
);
vocabulary!(
    EvidenceRole,
    decode_evidence_role,
    decode_evidence_role_nullable,
    "catalog_evidence",
    "role"
);
vocabulary!(
    TypeKind,
    decode_type_kind,
    decode_type_kind_nullable,
    "catalog_types",
    "kind"
);
vocabulary!(
    TypeArgumentRole,
    decode_type_argument_role,
    decode_type_argument_role_nullable,
    "catalog_type_args",
    "role"
);
vocabulary!(
    TypeParameterKind,
    decode_type_parameter_kind,
    decode_type_parameter_kind_nullable,
    "catalog_type_args",
    "parameter_kind"
);
vocabulary!(
    TypeObservationRole,
    decode_type_observation_role,
    decode_type_observation_role_nullable,
    "catalog_type_observations",
    "role"
);
vocabulary!(
    BindingMode,
    decode_binding_mode,
    decode_binding_mode_nullable,
    "catalog_surfaces",
    "binding_mode"
);
vocabulary!(
    AccessorRole,
    decode_accessor_role,
    decode_accessor_role_nullable,
    "catalog_surfaces",
    "accessor_role"
);
vocabulary!(
    ProtocolForm,
    decode_protocol_form,
    decode_protocol_form_nullable,
    "catalog_surfaces",
    "protocol"
);
vocabulary!(
    RegistrationForm,
    decode_registration_form,
    decode_registration_form_nullable,
    "catalog_surfaces",
    "registration"
);
vocabulary!(
    BodyAdmission,
    decode_body_admission,
    decode_body_admission_nullable,
    "catalog_surfaces",
    "admission"
);
vocabulary!(
    RecordModel,
    decode_record_model,
    decode_record_model_nullable,
    "catalog_configurations",
    "record_kind"
);
vocabulary!(
    FieldDefaultState,
    decode_field_default_state,
    decode_field_default_state_nullable,
    "catalog_configurations",
    "default_state"
);
vocabulary!(
    FieldLinkKind,
    decode_field_link_kind,
    decode_field_link_kind_nullable,
    "catalog_field_links",
    "kind"
);
