//! Four-family deterministic renderer and shared replay, over completed canonical C0/C1 evidence.
use super::*;
use crate::domain::{catalog::evidence::build::{EvidenceData,EvidenceOutput},normalized::Rows,resources::ResourceBudget,stages::*};
pub fn invalid(s:impl Into<String>)->ModelError {ModelError::Invalid(s.into())}
pub fn need<R:Record>(r:&Rows<R>,id:Id<R>)->Result<&R,ModelError> {r.get(id).ok_or_else(||invalid(format!("retrieval premise absent: {}",R::NAME)))}
pub struct Data {pub source:EvidenceData,pub evidence:EvidenceOutput,pub facts:Facts}
impl Data {
 pub fn new(b:&ResourceBudget)->Self {Self {source:EvidenceData::new(b),evidence:EvidenceOutput::new(b),facts:Facts::new(b)}}
 pub fn visit(&mut self,n:&str,b:&arrow_array::RecordBatch)->Result<bool,ModelError> {if self.source.visit(n,b)? || self.evidence.visit(n,b)? {return Ok(true);}self.facts.visit(n,b)}
 pub fn inputs()->Vec<ValidationInput> {let mut r=EvidenceData::inputs();r.extend(EvidenceOutput::inputs());r.extend(Facts::inputs());r.sort_by_key(|r|r.name());r.dedup_by_key(|r|r.name());r}
 pub fn selected(&self)->Result<&Definition,ModelError> {if self.facts.definitions.len()!=1 {return Err(invalid("retrieval needs one completed authored definition"));}let r=self.facts.definitions.iter().next().unwrap();r.validate()?;Ok(r)}
}
macro_rules! facts {($($f:ident:$ty:ty,)*)=>{pub struct Facts {$(pub $f:Rows<$ty>,)*}impl Facts {pub fn new(b:&ResourceBudget)->Self {Self {$($f:Rows::new(b),)*}}pub fn visit(&mut self,n:&str,b:&arrow_array::RecordBatch)->Result<bool,ModelError> {$(if n==<$ty>::NAME {self.$f.decode(b)?;return Ok(true);})*Ok(false)}pub fn inputs()->Vec<ValidationInput> {vec![$(ValidationInput::of::<$ty>(&["id"])),*]}fn uses()->Vec<RelationUse> {vec![$(RelationUse::stored::<$ty>()),*]}}};}
crate::retrieval_inputs!(facts);
macro_rules! outputs {($($f:ident:$ty:ty,)*)=>{pub struct Output {$(pub $f:Rows<$ty>,)*}impl Output {pub fn new(b:&ResourceBudget)->Self {Self {$($f:Rows::new(b),)*}}pub fn visit(&mut self,n:&str,b:&arrow_array::RecordBatch)->Result<bool,ModelError> {$(if n==<$ty>::NAME {self.$f.decode(b)?;return Ok(true);})*Ok(false)}pub fn inputs()->Vec<ValidationInput> {vec![$(ValidationInput::of::<$ty>(&["id"])),*]}pub fn matches(&self,o:&Self)->Result<(),ModelError> {$(if !self.$f.same(&o.$f) {return Err(invalid(format!("canonical retrieval closure differs: {}",<$ty>::NAME)));})*Ok(())}}};}
crate::retrieval_outputs!(outputs);
pub fn fragments(definition:&Definition,corpus:&CorpusText,out:&mut Rows<Fragment>,b:&ResourceBudget)->Result<(),ModelError> {
 definition.validate()?;corpus.validate()?;let text=corpus.text.as_str();let mut start=0;let mut ordinal=0;
 while start<text.len() {let mut end=(start+definition.fragment_bytes as usize).min(text.len());while !text.is_char_boundary(end) {end-=1;}if end==start {return Err(invalid("retrieval window cannot fit Unicode scalar"));}let _copy=b.reserve("retrieval-fragment-copy",(end-start)*2+size_of::<Fragment>())?;let part=&text[start..end];out.insert(Fragment {definition:definition.id(),fragment_bytes:definition.fragment_bytes,corpus:corpus.id(),ordinal,start:start as i64,end:end as i64,digest:ContentHash::of(part.as_bytes()),text:Utf8Text::from(part)})?;start=end;ordinal+=1;}Ok(())
}
struct Render {text:String,anchors:Vec<AnchorSource>,subjects:Vec<Subject>}
fn member_path(d:&Data,m:&catalog::CatalogMember)->Result<String,ModelError> {let module=need(&d.source.core.modules,m.access)?;Ok(format!("{}.{}",module.qualified_name,m.name))}
fn api(d:&Data,m:&catalog::CatalogMember,context:Id<AnalysisContext>)->Result<Render,ModelError> {
 let mut text=member_path(d,m)?;text.push('\n');
 for exposure in d.source.catalog.exposures.iter().filter(|r|r.member==m.id()) {let exposure=need(&d.source.core.exposures,exposure.exposure)?;if exposure.context==context {text.push_str(&format!("Exposure status={:?} reason={:?}\n",exposure.status,exposure.reason));}}

 let mut callables=d.source.catalog.callables.iter().filter(|r|r.member==m.id() && d.source.core.assessments.get(r.assessment).is_some_and(|a|a.context==context)).collect::<Vec<_>>();callables.sort_by_key(|r|r.id());
 for c in callables {let a=need(&d.source.core.assessments,c.assessment)?;text.push_str(&format!("Callable {:?}: identity={:?} signatures={:?} descriptor={:?}/{:?} body={:?} admitted={}\n",c.basis,a.identity,a.signatures,a.descriptor,a.descriptor_kind,a.body,a.body_admitted));
  let mut variants=d.source.catalog.invocations.iter().filter(|r|r.callable==c.id()).collect::<Vec<_>>();variants.sort_by_key(|r|r.variant);
  for i in variants {let v=need(&d.source.core.variants,i.variant)?;let signature=need(&d.facts.signatures,v.signature)?;text.push_str(&format!("Signature {:?} adjustment={:?}\n",signature.form,v.adjustment));let mut slots=d.source.core.slots.iter().filter(|r|r.variant==v.id()).collect::<Vec<_>>();slots.sort_by_key(|r|(r.ordinal,r.id()));for slot in slots {let parameter=need(&d.facts.signature_parameters,slot.parameter)?;let shape=need(&d.facts.shapes,parameter.shape)?;text.push_str(&format!("Parameter {:?} {:?} required={} default-slot={:?}\n",shape.name,shape.kind,shape.required,slot.default));}}
  for aspect in d.source.catalog.aspects.iter().filter(|r|r.callable==c.id()) {let a=need(&d.source.core.aspects,aspect.aspect)?;text.push_str(&format!("Aspect {:?} admission={:?}\n",a.kind,a.admission));}
 }
 let mut options=d.source.catalog.options.iter().filter(|r|r.member==m.id()).collect::<Vec<_>>();options.sort_by_key(|r|r.id());for o in options {let subject=need(&d.source.catalog.subjects,o.subject)?;let default=need(&d.source.catalog.defaults,o.default)?;let label=match subject {catalog::CatalogOptionSubject::Parameter {slot}=>{let slot=need(&d.source.core.slots,*slot)?;let p=need(&d.facts.signature_parameters,slot.parameter)?;let shape=need(&d.facts.shapes,p.shape)?;format!("effective parameter {:?} ({:?})",shape.name,shape.kind)},catalog::CatalogOptionSubject::Field {field}=>format!("configuration field {}",need(&d.source.core.fields,*field)?.name),catalog::CatalogOptionSubject::SourceParameter {..}=>"original source parameter".into()};let value=match default {catalog::CatalogDefault::Absent {}=>"Absent".into(),catalog::CatalogDefault::Unknown {}=>"Unknown".into(),catalog::CatalogDefault::Unavailable {}=>"Unavailable".into(),catalog::CatalogDefault::Literal {literal}=>format!("Literal {:?}",need(&d.facts.literals,*literal)?),catalog::CatalogDefault::Expression {..}=>"Unevaluated expression".into(),catalog::CatalogDefault::Factory {..}=>"Factory (not evaluated)".into()};text.push_str(&format!("Option {label}: default={value}\n"));}
 for class in d.source.catalog.classes.iter().filter(|r|r.member==m.id()) {for c in d.source.catalog.constructors.iter().filter(|r|r.class==class.id()) {text.push_str(&format!("Constructor {:?} {:?} applicability={:?} disposition={:?}\n",c.origin,c.kind,c.applicability,c.disposition));}}
 let module=need(&d.source.core.modules,m.access)?;let original=c1::OriginalSource::Artifact {artifact:module.source};need(&d.evidence.original_sources,original.id())?;
 Ok(Render {text,anchors:vec![AnchorSource::Original {source:original.id()}],subjects:vec![Subject::Member {member:m.id()}]})
}
fn add(d:&Data,out:&mut Output,root:&c1::EvidenceRoot,family:Family,origin:Origin,title:String,render:Render,b:&ResourceBudget)->Result<(),ModelError> {
 for a in &render.anchors {let (artifact,_,_)=super::source::coordinates(d,a)?;if need(&d.source.core.artifacts,artifact)?.input!=root.input {return Err(invalid("retrieval anchor crosses captured input"));}}
 let corpus=out.corpus.insert(CorpusText {family,rendering_version:d.selected()?.rendering_version,digest:ContentHash::of(render.text.as_bytes()),text:Utf8Text::from(render.text)})?;let origin=out.origins.insert(origin)?;let unit=out.units.insert(Unit {input:root.input,context:root.context,family,origin,corpus,title:Utf8Text::from(title)})?;
 out.roots.insert(UnitRoot {unit,root:root.id()})?;
 for subject in render.subjects {let subject=out.subjects.insert(subject)?;out.unit_subjects.insert(UnitSubject {unit,subject})?;}
 for (ordinal,anchor) in render.anchors.into_iter().enumerate() {let original=out.anchor_sources.insert(anchor)?;out.anchors.insert(OriginalAnchor {unit,ordinal:ordinal as i64,original})?;}
 // Each distinct corpus text is fragmented once; membership remains on all original units.
 if !out.fragments.iter().any(|f|f.corpus==corpus) {fragments(d.selected()?,need(&out.corpus,corpus)?,&mut out.fragments,b)?;}Ok(())
}
pub fn build(d:&Data,b:&ResourceBudget)->Result<Output,ModelError> {
 d.selected()?;let mut out=Output::new(b);
 // Bound render buffers before allocating. Input rows and retained output rows have separate charges.
 let mut payload=0usize;let mut count=0usize;
 macro_rules! measure {($rows:expr)=>{for row in $rows.iter() {payload=payload.checked_add(row.heap_bytes()).ok_or_else(||invalid("retrieval render heap overflow"))?;count=count.checked_add(1).ok_or_else(||invalid("retrieval render count overflow"))?;}};}
 macro_rules! core {($($f:ident:$ty:ty,)*)=>{$(measure!(d.source.core.$f);)*};}crate::catalog_inputs!(core);
 macro_rules! catalog {($($f:ident:$ty:ty,)*)=>{$(measure!(d.source.catalog.$f);)*};}crate::catalog_outputs!(catalog);
 macro_rules! facts {($($f:ident:$ty:ty,)*)=>{$(measure!(d.source.facts.$f);)*};}crate::catalog_evidence_inputs!(facts);
 macro_rules! evidence {($($f:ident:$ty:ty,)*)=>{$(measure!(d.evidence.$f);)*};}crate::catalog_evidence_outputs!(evidence);
 macro_rules! extra {($($f:ident:$ty:ty,)*)=>{$(measure!(d.facts.$f);)*};}crate::retrieval_inputs!(extra);
 let bound=payload.checked_mul(16).and_then(|n|count.checked_mul(4096).and_then(|c|n.checked_add(c))).ok_or_else(||invalid("retrieval render allocation overflow"))?;let _render=b.reserve("retrieval-render-buffers",bound)?;
 for root in d.evidence.roots.iter() {match need(&d.evidence.subjects,root.subject)? {
  c1::RootSubject::Member {member}=>{let m=need(&d.source.catalog.members,*member)?;if m.input!=root.input {return Err(invalid("retrieval member root crosses input"));}let title=member_path(d,m)?;add(d,&mut out,root,Family::ApiOptions,Origin::Api {member:*member},title.clone(),api(d,m,root.context)?,b)?;let module=need(&d.source.core.modules,m.access)?;let source=c1::OriginalSource::Artifact {artifact:module.source};let anchor=AnchorSource::Original {source:source.id()};let text=super::source::read(d,&anchor,b)?;add(d,&mut out,root,Family::Source,Origin::Original {source:source.id()},need(&d.source.core.artifacts,module.source)?.path.clone(),Render {text:text.value.clone(),anchors:vec![anchor],subjects:vec![Subject::Member {member:*member}]},b)?;},
  c1::RootSubject::Scenario {scenario}=>{let r=need(&d.evidence.scenarios,*scenario)?;let mut text=format!("Scenario intent={:?} extraction={:?} parse={:?} binding={:?} environment={:?} execution={:?}\n",r.intent,r.extraction,r.parse,r.binding,r.environment,r.execution);let mut anchors=vec![];let mut spans=d.evidence.spans.iter().filter(|r|r.scenario==*scenario).collect::<Vec<_>>();spans.sort_by_key(|r|(r.ordinal,r.id()));for span in spans {let anchor=AnchorSource::Original {source:span.source};let original=super::source::read(d,&anchor,b)?;text.push_str(&format!("Span {:?}\n{}\n",span.role,original.value));anchors.push(anchor);}for dependency in d.evidence.dependencies.iter().filter(|r|r.scenario==*scenario) {text.push_str(&format!("Setup {:?} status={:?}\n",need(&d.evidence.setup,dependency.dependency)?,dependency.status));}let mut subjects=vec![];for a in d.evidence.associations.iter().filter(|r|r.scenario==*scenario && d.source.core.qualifications.get(r.qualification).is_some_and(|q|q.context==root.context)) {text.push_str(&format!("Association basis={:?} phase={:?} intent={:?}\n",a.basis,a.phase,a.intent));subjects.push(Subject::Member {member:a.member});}add(d,&mut out,root,Family::Scenario,Origin::Scenario {scenario:*scenario},"Usage scenario".into(),Render {text,anchors,subjects},b)?;},
  c1::RootSubject::Document {observation}=>{let document=need(&d.source.facts.documents,*observation)?;let artifact=need(&d.source.core.artifacts,document.source)?;let mut any=false;for passage in d.source.facts.passages.iter().filter(|p|d.source.core.qualifications.get(p.qualification).is_some_and(|q|q.context==root.context)) {let node=need(&d.source.facts.nodes,passage.passage.id())?;let anchor=AnchorSource::Span {span:node.span()};if super::source::coordinates(d,&anchor)?.0!=document.source {continue;}any=true;let text=super::source::read(d,&anchor,b)?;let mut subjects=vec![];for a in d.evidence.document_associations.iter() {let candidate=need(&d.source.facts.mention_candidates,a.candidate)?;let assessment=need(&d.source.facts.mention_assessments,candidate.assessment)?;let mention=need(&d.source.facts.mentions,assessment.observation)?;if mention.passage==passage.passage && d.source.core.qualifications.get(mention.qualification).is_some_and(|q|q.context==root.context) {subjects.push(Subject::Member {member:a.member});}}add(d,&mut out,root,Family::DocumentationDeployment,Origin::Passage {observation:passage.id()},passage.heading.clone().unwrap_or_else(||artifact.path.clone()),Render {text:text.value.clone(),anchors:vec![anchor],subjects},b)?;}if !any {let anchor=AnchorSource::Artifact {artifact:document.source};let text=super::source::read(d,&anchor,b)?;add(d,&mut out,root,Family::DocumentationDeployment,Origin::Document {observation:*observation},document.title.clone().unwrap_or_else(||artifact.path.clone()),Render {text:text.value.clone(),anchors:vec![anchor],subjects:vec![]},b)?;}},
  c1::RootSubject::Deployment {deployment}=>{let row=need(&d.evidence.deployments,*deployment)?;let observation=need(&d.source.facts.deployment,row.observation)?;let anchor=AnchorSource::Span {span:observation.span};let text=super::source::read(d,&anchor,b)?;let subjects=d.evidence.release_deployments.iter().filter(|r|r.deployment==*deployment).map(|r|Subject::Release {release:r.release}).collect();add(d,&mut out,root,Family::DocumentationDeployment,Origin::Deployment {deployment:*deployment},observation.field.clone(),Render {text:format!("Declared {} {:?} interpretation={:?}\n{}",observation.field,observation.name,observation.interpretation,text.value),anchors:vec![anchor],subjects},b)?;},
  c1::RootSubject::Option {..}|c1::RootSubject::Release {..}=>{},
 }}Ok(out)
}
pub fn invariants()->Vec<Invariant> {let mut inputs=Data::inputs();inputs.extend(Output::inputs());vec![Invariant {name:"retrieval_canonical_rendering",inputs,create:std::sync::Arc::new(|b|Box::new(Check {data:Data::new(b),out:Output::new(b),budget:b.clone()}))}]}
struct Check {data:Data,out:Output,budget:ResourceBudget}
impl InvariantCheck for Check {fn visit(&mut self,n:&str,b:&arrow_array::RecordBatch)->Result<(),ModelError> {if !self.data.visit(n,b)? && !self.out.visit(n,b)? {return Err(invalid("undeclared retrieval rendering input"));}Ok(())}fn finish(self:Box<Self>)->Result<(),ModelError> {self.out.matches(&build(&self.data,&self.budget)?)} }
pub fn definition()->(analysis::MethodParameters,analysis::AnalysisDefinition) {let (parameters,_)=catalog::build::definition();let definition=analysis::AnalysisDefinition {method:analysis::AnalysisMethod::Retrieval,interpretation:analysis::Interpretation::Heuristic,parameters:parameters.id(),semantic_version:ContentHash::of(b"retrieval-preparation/v1")};(parameters,definition)}

/// Mandatory helper closure, reused within the single final E0 producer stage.
pub fn mandatory_inputs(profile:Profile)->Vec<RelationUse> {let parent=c1::build::stage(profile);let mut inputs=parent.inputs;inputs.extend(parent.outputs.into_iter().map(|r|r.completed_store()));inputs.extend(Facts::uses());inputs.sort_by_key(|r|r.name());inputs.dedup_by_key(|r|r.name());inputs}
