//! Retrieval owns its exact vector uses; both consumers replay one immutable winner recipe.
use super::{*,build::{Data,Output,invalid,need}};
use crate::domain::{analysis::retrieval::{AnalysisInvocation,AnalysisOutcome},embedding::{EmbeddingSpec,configuration::ServiceConfiguration,analytic::{AnalysisEmbeddingUse,VectorAvailability},text::TextWindow,consumption::{Winners,ValueReceipt},value},normalized::Rows,resources::ResourceBudget,obligation::ObligationKind};
use crate::Domain;
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="retrieval_embedding_uses",validate=validate_use,invariants=invariants)]
pub struct RetrievalEmbeddingUse {
 #[model(key)]pub invocation:Id<AnalysisInvocation>,
 #[model(key)]pub fragment:Id<Fragment>,
 pub specification:Id<EmbeddingSpec>,pub input:ContentHash,pub availability:VectorAvailability,
 pub admitted_tokens:Option<i64>,pub codec:Option<i16>,pub value_digest:Option<ContentHash>,pub bytes:Option<EvidenceBytes>,
}
fn validate_use(r:&RetrievalEmbeddingUse)->Result<(),ModelError> {
 let value=r.codec==Some(value::VALUE_CODEC) && r.value_digest.is_some() && r.bytes.is_some();let absent=r.codec.is_none() && r.value_digest.is_none() && r.bytes.is_none();let valid=match r.availability {VectorAvailability::Available=>value && r.admitted_tokens.is_some_and(|n|n>=0),VectorAvailability::ServiceUnavailable=>absent && r.admitted_tokens.is_none(),VectorAvailability::TokenLimit=>absent && r.admitted_tokens.is_some_and(|n|n>=0)};if !valid {return Err(invalid("retrieval vector availability and bytes disagree"));}Ok(())
}
impl RetrievalEmbeddingUse {
 pub fn admit_into(rows:&mut Rows<Self>,invocation:Id<AnalysisInvocation>,fragment:Id<Fragment>,specification:&EmbeddingSpec,value:&value::AdmittedValue,b:&ResourceBudget)->Result<Id<Self>,ModelError> {if value.spec()!=specification.service_hash {return Err(invalid("retrieval value changed selected specification"));}let _copy=b.reserve("retrieval-use-copy",size_of::<Self>()+value.bytes().len())?;rows.insert(Self {invocation,fragment,specification:specification.id(),input:value.input(),availability:VectorAvailability::Available,admitted_tokens:Some(value.tokens().into()),codec:Some(value::VALUE_CODEC),value_digest:Some(value.digest()),bytes:Some(EvidenceBytes(value.bytes().to_vec()))})}
 pub fn receipt(&self)->Result<ValueReceipt<'_>,ModelError> {self.validate()?;if self.availability!=VectorAvailability::Available {return Err(invalid("retrieval vector is unavailable"));}Ok(ValueReceipt {input:self.input,codec:self.codec.unwrap(),digest:self.value_digest.unwrap(),admitted_tokens:u32::try_from(self.admitted_tokens.unwrap()).map_err(ModelError::codec)?,bytes:&self.bytes.as_ref().unwrap().0})}
}
pub struct ConsumptionData {pub render:Data,pub output:Output,pub specifications:Rows<EmbeddingSpec>,pub services:Rows<ServiceConfiguration>,pub analytic_uses:Rows<AnalysisEmbeddingUse>,pub windows:Rows<TextWindow>,pub sources:Rows<crate::domain::analysis::retrieval::InvocationSource>,pub parents:Rows<crate::domain::analysis::retrieval::AnalysisInput>}
impl ConsumptionData {
 pub fn new(b:&ResourceBudget)->Self {Self {render:Data::new(b),output:Output::new(b),specifications:Rows::new(b),services:Rows::new(b),analytic_uses:Rows::new(b),windows:Rows::new(b),sources:Rows::new(b),parents:Rows::new(b)}}
 pub fn inputs()->Vec<ValidationInput> {let mut r=Data::inputs();r.extend(Output::inputs());r.extend([ValidationInput::of::<EmbeddingSpec>(&["id"]),ValidationInput::of::<ServiceConfiguration>(&["id"]),ValidationInput::of::<AnalysisEmbeddingUse>(&["id"]),ValidationInput::of::<TextWindow>(&["id"]),ValidationInput::of::<crate::domain::analysis::retrieval::InvocationSource>(&["id"]),ValidationInput::of::<crate::domain::analysis::retrieval::AnalysisInput>(&["id"])]);r}
 pub fn visit(&mut self,n:&str,b:&arrow_array::RecordBatch)->Result<bool,ModelError> {if self.render.visit(n,b)? || self.output.visit(n,b)? {return Ok(true);}macro_rules! row {($($f:ident:$ty:ty),*)=>{$(if n==<$ty>::NAME {self.$f.decode(b)?;return Ok(true);})*};}row!(specifications:EmbeddingSpec,services:ServiceConfiguration,analytic_uses:AnalysisEmbeddingUse,windows:TextWindow,sources:crate::domain::analysis::retrieval::InvocationSource,parents:crate::domain::analysis::retrieval::AnalysisInput);Ok(false)}
 pub fn selected_spec(&self)->Result<&EmbeddingSpec,ModelError> {if self.specifications.len()!=1 || self.services.len()!=1 {return Err(invalid("requested retrieval needs one selected service and specification"));}let spec=self.specifications.iter().next().unwrap();if self.services.iter().next().unwrap().specification!=spec.id() {return Err(invalid("retrieval service changed selected specification"));}Ok(spec)}
 pub fn owns(&self,i:&AnalysisInvocation,f:&Fragment)->bool {self.output.units.iter().any(|u|u.corpus==f.corpus && u.input==i.input && u.context==i.context)}
 pub fn outcome(&self,i:&AnalysisInvocation,uses:&Rows<RetrievalEmbeddingUse>)->Result<AnalysisOutcome,ModelError> {let reason=if !self.render.selected()?.embedding_requested {None}else {crate::domain::obligation::first(uses.iter().filter(|r|r.invocation==i.id()).filter_map(|r|match r.availability {VectorAvailability::Available=>None,VectorAvailability::ServiceUnavailable=>Some(ObligationKind::EmbeddingServiceUnavailable),VectorAvailability::TokenLimit=>Some(ObligationKind::EmbeddingTokenLimit)}))};Ok(AnalysisOutcome {invocation:i.id(),status:if reason.is_some(){analysis::AnalysisStatus::Partial}else{analysis::AnalysisStatus::Completed},reason})}
 pub fn verify(&self,invocations:&Rows<AnalysisInvocation>,outcomes:&Rows<AnalysisOutcome>,uses:&Rows<RetrievalEmbeddingUse>,b:&ResourceBudget)->Result<(),ModelError> {
  self.output.matches(&build::build(&self.render,b)?)?;let selected=self.render.selected()?.embedding_requested;let mut charge=charged::StateCharge::new(b,"retrieval-consumption-membership");let mut expected=charged::ChargedSet::default();let mut frames=charged::ChargedSet::default();let mut actual=charged::ChargedSet::default();for run in self.render.source.facts.runs.iter() {frames.insert(&mut charge,(run.input,run.context))?;}
  let mut expected_sources=Rows::new(b);let mut expected_parents=Rows::new(b);let mut winners=Winners::new(b);
  // Earlier analytic rows participate in byte equality, not retrieval relevance or requirements.
  for r in self.analytic_uses.iter() {r.validate()?;if r.availability==VectorAvailability::Available {let spec=need(&self.specifications,r.specification)?.configuration()?;let window=need(&self.windows,r.window)?;drop(winners.replay(&spec,window.text.as_str(),r.receipt()?)?);}}
  for i in invocations.iter() {if i.definition!=build::definition().1.id() || i.subject.is_some() || !frames.contains(&(i.input,i.context)) || !actual.insert(&mut charge,(i.input,i.context))? {return Err(invalid("retrieval invocation differs from fixed native frame"));}let mut parent_ids=[None;2];for (ordinal,source) in self.render.parents(i.input,i.context)?.into_iter().enumerate() {let parent=expected_sources.insert(source)?;parent_ids[ordinal]=Some(parent);expected_parents.insert(crate::domain::analysis::retrieval::AnalysisInput {invocation:i.id(),parent})?;}if i.inputs!=AnalysisInvocation::new(i.input,i.context,i.definition,None,parent_ids.into_iter().flatten()).0.inputs {return Err(invalid("retrieval parent digest differs from exact S0/C1 frames"));}let outcome=self.outcome(i,uses)?;if outcomes.get(outcome.id())!=Some(&outcome) {return Err(invalid("retrieval outcome differs from exact availability"));}if !selected {continue;}let specification=self.selected_spec()?;let spec=specification.configuration()?;
   for fragment in self.output.fragments.iter().filter(|f|self.owns(i,f)) {let key=RetrievalEmbeddingUseKey {invocation:i.id(),fragment:fragment.id()};let id=Id::of(&key);expected.insert(&mut charge,id)?;let row=need(uses,id)?;row.validate()?;if row.specification!=specification.id() {return Err(invalid("retrieval use changed selected specification"));}let bound=fragment.text.as_str().len().checked_mul(spec.document_template.matches("{text}").count()).and_then(|n|n.checked_add(spec.document_template.len())).and_then(|n|n.checked_mul(2)).ok_or_else(||invalid("retrieval request overflow"))?;let _request=b.reserve("retrieval-consumption-request",bound)?;if row.input!=value::input_hash(&spec.document_text(fragment.text.as_str())) {return Err(invalid("retrieval input differs from completed fragment"));}match row.availability {VectorAvailability::Available=>{drop(winners.replay(&spec,fragment.text.as_str(),row.receipt()?)?);},VectorAvailability::TokenLimit if row.admitted_tokens.is_none_or(|n|n<=i64::from(spec.max_document_tokens))=>return Err(invalid("retrieval token refusal within selected cap")),_=>{}}
   }
  }
  if !expected_sources.same(&self.sources) || !expected_parents.same(&self.parents) || frames.len()!=actual.len() || expected.len()!=uses.len() || outcomes.len()!=invocations.len() {return Err(invalid("retrieval consumption domain missing or unexpected rows"));}Ok(())
 }
}
pub fn relations()->Vec<Relation> {vec![Relation::of::<RetrievalEmbeddingUse>()]}
pub fn invariants()->Vec<Invariant> {let mut inputs=ConsumptionData::inputs();inputs.extend([ValidationInput::of::<AnalysisInvocation>(&["id"]),ValidationInput::of::<AnalysisOutcome>(&["id"]),ValidationInput::of::<RetrievalEmbeddingUse>(&["id"])]);vec![Invariant {name:"retrieval_embedding_consumption_and_winners",inputs,create:std::sync::Arc::new(|b|Box::new(Check {data:ConsumptionData::new(b),invocations:Rows::new(b),outcomes:Rows::new(b),uses:Rows::new(b),budget:b.clone()}))}]}
struct Check {data:ConsumptionData,invocations:Rows<AnalysisInvocation>,outcomes:Rows<AnalysisOutcome>,uses:Rows<RetrievalEmbeddingUse>,budget:ResourceBudget}
impl InvariantCheck for Check {fn visit(&mut self,n:&str,b:&arrow_array::RecordBatch)->Result<(),ModelError> {if self.data.visit(n,b)? {return Ok(());}if n==AnalysisInvocation::NAME {self.invocations.decode(b)?;}else if n==AnalysisOutcome::NAME {self.outcomes.decode(b)?;}else if n==RetrievalEmbeddingUse::NAME {self.uses.decode(b)?;}else{return Err(invalid("undeclared retrieval consumption input"));}Ok(())}fn finish(self:Box<Self>)->Result<(),ModelError> {self.data.verify(&self.invocations,&self.outcomes,&self.uses,&self.budget)} }
