//! Explicit PostgreSQL physical adapter for the cpg-schema serving contracts.
use arrow_array::RecordBatch;
use arrow_schema::DataType;
use bytes::BytesMut;
use cpg_schema::{
    bundle,
    serving_projection::{self, ProjectionError, corrupt},
};

/// COPY targets a temporary staging table. real[] is checked and cast to vector(1024) on INSERT.
pub fn staging_type(t: &DataType) -> Result<&'static str, ProjectionError> {
    Ok(match t {
        DataType::FixedSizeBinary(16 | 32) => "bytea",
        DataType::Utf8 => "text",
        DataType::Int64 => "bigint",
        DataType::Boolean => "boolean",
        DataType::FixedSizeList(_, 1024) => "real[]",
        _ => return Err(corrupt("unsupported PostgreSQL projection type")),
    })
}
pub fn copy_bytes(
    name: &str,
    dimensions: i32,
    batch: &RecordBatch,
) -> Result<BytesMut, ProjectionError> {
    if !matches!(dimensions, 0 | 1024) {
        return Err(corrupt("unsupported projection dimensions"));
    }
    serving_projection::validate_batch(name, dimensions, batch)?;
    if serving_projection::batch_bytes(batch)? > super::serving::STAGING_BYTES {
        return Err(serving_projection::refused("COPY staging byte budget"));
    }
    let mut encoder = pgpq::ArrowToPostgresBinaryEncoder::try_new(&batch.schema())
        .map_err(|_| corrupt("COPY schema"))?;
    let mut out = BytesMut::new();
    encoder
        .write_header(&mut out)
        .map_err(|_| corrupt("COPY header"))?;
    encoder
        .write_batch(batch, &mut out)
        .map_err(|_| corrupt("COPY batch"))?;
    encoder
        .write_footer(&mut out)
        .map_err(|_| corrupt("COPY footer"))?;
    if out.len() > super::serving::STAGING_BYTES {
        return Err(serving_projection::refused("COPY encoded byte budget"));
    }
    Ok(out)
}
/// Generated once into the immutable SQLx migration. No runtime DDL or schema inference.
pub fn relation_ddl() -> Result<String, ProjectionError> {
    relation_ddl_for(0)
}
/// Additive PR1 relations only; historical migration bodies never change.
pub fn catalog_ddl() -> Result<String, ProjectionError> {
    relation_ddl_for(1)
}
pub fn specificity_ddl() -> Result<String, ProjectionError> {
    relation_ddl_for(2)
}
fn relation_ddl_for(increment: u8) -> Result<String, ProjectionError> {
    let selected = |name: &str| match increment {
        2 => matches!(
            name,
            "catalog_surfaces" | "catalog_configurations" | "catalog_field_links"
        ),
        1 => {
            name.starts_with("catalog_")
                && !matches!(
                    name,
                    "catalog_surfaces" | "catalog_configurations" | "catalog_field_links"
                )
        }
        _ => !name.starts_with("catalog_"),
    };
    let mut sql =
        String::from("-- Generated by lctx-postgres/examples/projection_ddl.rs from cpg-schema.\n");
    let books = cpg_schema::codebook::registry();
    for file in bundle::files(1024) {
        if !selected(file.name) {
            continue;
        }
        let mut columns=vec!["generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest)".to_owned(),"row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0)".to_owned()];
        for f in file.schema.fields() {
            let ty = if matches!(f.data_type(), DataType::FixedSizeList(..)) {
                "lctx_ext.vector(1024)"
            } else {
                staging_type(f.data_type())?
            };
            let n = format!("\"{}\"", f.name());
            let mut column = format!("{n} {ty}{}", if f.is_nullable() { "" } else { " NOT NULL" });
            if let DataType::FixedSizeBinary(width) = f.data_type() {
                column.push_str(&format!(" CHECK (octet_length({n}) = {width})"));
            }
            if matches!(f.data_type(), DataType::FixedSizeList(..)) {
                column.push_str(&format!(
                    " CHECK (abs(lctx_ext.vector_norm({n}) - 1.0) <= 0.001)"
                ));
            }
            if let Some(values) = cpg_schema::catalog::vocabulary(file.name, f.name()) {
                let values =
                    if increment == 1 && file.name == "catalog_evidence" && f.name() == "role" {
                        vec!["declares"]
                    } else {
                        values
                    };
                let values = values
                    .iter()
                    .map(|v| format!("'{}'", v.replace('\'', "''")))
                    .collect::<Vec<_>>()
                    .join(",");
                column.push_str(&format!(" CHECK ({n} IN ({values}))"));
            }
            if let Some(book) = serving_projection::codebook_name(file.name, f.name()) {
                let values = books
                    .iter()
                    .find(|b| b.name == book)
                    .ok_or_else(|| corrupt("unknown declared codebook"))?
                    .values
                    .iter()
                    .map(|(_, v)| format!("'{}'", v.replace('\'', "''")))
                    .collect::<Vec<_>>()
                    .join(",");
                column.push_str(&format!(" CHECK ({n} IN ({values}))"));
            }
            columns.push(column);
        }
        columns.push(
            if file.name == "operation_vectors" {
                "PRIMARY KEY (generation_digest,embedding_view,row_ordinal)"
            } else {
                "PRIMARY KEY (generation_digest,row_ordinal)"
            }
            .into(),
        );
        // Domain keys are explicit. A sort key alone is not evidence of uniqueness.
        if let Some(key) = serving_projection::unique_key(file.name) {
            columns.push(format!("UNIQUE (generation_digest,{key})"));
        }
        sql.push_str(&format!(
            "CREATE TABLE lctx_serving.{} (\n {}\n){};\n",
            file.name,
            columns.join(",\n "),
            if matches!(file.name, "vectors" | "operation_vectors") {
                " PARTITION BY LIST (generation_digest)"
            } else {
                ""
            }
        ));
        sql.push_str(&format!("ALTER TABLE lctx_serving.{0} ENABLE ROW LEVEL SECURITY;\nCREATE POLICY ready_read ON lctx_serving.{0} FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));\nCREATE POLICY import_read ON lctx_serving.{0} FOR SELECT TO lctx_importer USING (true);\nCREATE POLICY import_insert ON lctx_serving.{0} FOR INSERT TO lctx_importer WITH CHECK (true);\nCREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.{0} FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();\nGRANT SELECT ON lctx_serving.{0} TO lctx_serving,lctx_importer;\nGRANT INSERT ON lctx_serving.{0} TO lctx_importer;\n",file.name));
    }
    for (table, fields, parent, targets) in serving_projection::foreign_keys() {
        if !selected(table) {
            continue;
        }
        sql.push_str(&format!("ALTER TABLE lctx_serving.{table} ADD FOREIGN KEY (generation_digest,{fields}) REFERENCES lctx_serving.{parent}(generation_digest,{targets}) DEFERRABLE INITIALLY DEFERRED;\n"));
    }
    Ok(sql)
}
/// Reconstruct declared Arrow types and metadata explicitly. PostgreSQL types do not establish
/// domain identity. Nullable arrays are checked separately from their scalar values.
pub fn decode_rows(
    name: &str,
    dimensions: i32,
    rows: &[sqlx::postgres::PgRow],
) -> Result<RecordBatch, ProjectionError> {
    let file = bundle::files(dimensions)
        .into_iter()
        .find(|f| f.name == name)
        .ok_or_else(|| corrupt("unknown relation"))?;
    let batch = decode_schema(file.schema, rows)?;
    serving_projection::validate_batch(name, dimensions, &batch)?;
    Ok(batch)
}
/// Decode a separately declared, finite reporting schema with the same domain codec.
pub(crate) fn decode_schema(
    schema: arrow_schema::SchemaRef,
    rows: &[sqlx::postgres::PgRow],
) -> Result<RecordBatch, ProjectionError> {
    use arrow_array::{
        ArrayRef, BooleanArray, Int64Array, StringArray,
        builder::{FixedSizeBinaryBuilder, FixedSizeListBuilder, Float32Builder},
    };
    use sqlx::Row;
    use std::sync::Arc;
    if rows.len() > serving_projection::MAX_RELATION_ROWS {
        return Err(serving_projection::refused("row budget"));
    }
    let mut columns = Vec::<ArrayRef>::new();
    for field in schema.fields() {
        let col = field.name().as_str();
        columns.push(match field.data_type() {
            DataType::FixedSizeBinary(width) => {
                let mut b = FixedSizeBinaryBuilder::with_capacity(rows.len(), *width);
                for row in rows {
                    let v: Option<Vec<u8>> =
                        row.try_get(col).map_err(|_| corrupt("binary decode"))?;
                    match v {
                        None => b.append_null(),
                        Some(v) => b.append_value(v).map_err(|_| corrupt("identifier width"))?,
                    }
                }
                Arc::new(b.finish())
            }
            DataType::Utf8 => Arc::new(StringArray::from(
                rows.iter()
                    .map(|row| {
                        row.try_get::<Option<String>, _>(col)
                            .map_err(|_| corrupt("text decode"))
                    })
                    .collect::<Result<Vec<_>, _>>()?,
            )),
            DataType::Int64 => Arc::new(Int64Array::from(
                rows.iter()
                    .map(|row| {
                        row.try_get::<Option<i64>, _>(col)
                            .map_err(|_| corrupt("integer decode"))
                    })
                    .collect::<Result<Vec<_>, _>>()?,
            )),
            DataType::Boolean => Arc::new(BooleanArray::from(
                rows.iter()
                    .map(|row| {
                        row.try_get::<Option<bool>, _>(col)
                            .map_err(|_| corrupt("boolean decode"))
                    })
                    .collect::<Result<Vec<_>, _>>()?,
            )),
            DataType::FixedSizeList(child, width) => {
                let mut b = FixedSizeListBuilder::new(Float32Builder::new(), *width)
                    .with_field(child.clone());
                for row in rows {
                    let v: Option<pgvector::Vector> =
                        row.try_get(col).map_err(|_| corrupt("vector decode"))?;
                    match v {
                        Some(v) => {
                            if v.as_slice().len() != *width as usize {
                                return Err(corrupt("vector width"));
                            }
                            b.values().append_slice(v.as_slice());
                            b.append(true);
                        }
                        None => {
                            for _ in 0..*width {
                                b.values().append_value(0.0);
                            }
                            b.append(false);
                        }
                    }
                }
                Arc::new(b.finish())
            }
            _ => return Err(corrupt("unsupported serving type")),
        });
    }
    let batch = RecordBatch::try_new(schema, columns)
        .map_err(|_| corrupt("reconstructed schema/nullability"))?;
    Ok(batch)
}
