#!/usr/bin/env python3
"""Generate SurrealQL DDL from `lctx model describe --format json` (the model declarations).

Representation (see README): one *identity* table per model relation, keyed by the content id
(lowercase hex, string key), holding the key fields; relations with non-key fields get a
*payload* table `<relation>__p` keyed by [id_hex, payload_hash_hex] with `identity_of` and the non-key
fields. Every record carries `spans` (snapshot-ordinal intervals) and is selectable by record
users only inside the snapshot pinned on their session. Content fields are READONLY.

Usage: gen_schema.py MODEL_JSON OUT_SURQL OUT_MAPPING_JSON
"""
import json
import sys

INT_RANGE = {"int16": (-32768, 32767), "int32": (-(2**31), 2**31 - 1)}


def q(name):
    return f"`{name}`"


def base_type(f):
    t = f["type"]
    if t == "id":
        return f"record<{f['target']}>"
    return {
        "int16": "int",
        "int32": "int",
        "int64": "int",
        "bool": "bool",
        "text": "string",
        "digest": "string",
        "binary": "bytes",
        "finite_f64": "float",
    }[t]


def field_type(f):
    t = base_type(f)
    if f["list"]:
        t = f"array<{t}>"
    if f["nullable"]:
        t = f"option<{t}>"
    return t


def scalar_assert(f, v="$value"):
    """Assertion on one scalar value, or None. Returns (expr, kinds) for the mapping report."""
    parts, kinds = [], []
    t = f["type"]
    if t in INT_RANGE:
        lo, hi = INT_RANGE[t]
        parts.append(f"{v} >= {lo} AND {v} <= {hi}")
        kinds.append("int-range")
    if t == "digest":
        parts.append(f"string::len({v}) = 64 AND string::is_hexadecimal({v})")
        kinds.append("digest-shape")
    if t == "finite_f64":
        parts.append(f"{v} = {v} AND {v} != math::INF AND {v} != math::NEG_INF")
        kinds.append("finite")
    if "codes" in f:
        codes = ", ".join(str(c[0]) for c in f["codes"])
        parts.append(f"{v} IN [{codes}]")
        kinds.append("codebook")
    if not parts:
        return None, kinds
    return " AND ".join(f"({p})" for p in parts), kinds


def field_assert(f):
    expr, kinds = scalar_assert(f, "$v" if f["list"] else "$value")
    if expr is None:
        return None, kinds
    if f["list"]:
        expr = f"$value.all(|$v| {expr})"
    if f["nullable"]:
        expr = f"$value = NONE OR ({expr})"
    return expr, kinds


def sum_assert(rel, key_fields):
    """ASSERT on the tag field: the arm's required fields are present, other arms' fields absent."""
    s = rel["sum"]
    arm_fields = {fl["name"] for arm in s["arms"] for fl in arm["fields"]}
    if not arm_fields <= key_fields:
        return None  # spans identity and payload: left to the validation pass
    # Long AND/OR chains exceed the 3.3 parser's expression depth limit (raw/schema-apply-*.txt),
    # so each arm is a flat array predicate and the arms are one flat array.
    alts = []
    for arm in s["arms"]:
        own = {fl["name"] for fl in arm["fields"]}
        req = [f"$this.{q(fl['name'])}" for fl in arm["fields"] if fl["required"]]
        absent = [f"$this.{q(n)}" for n in sorted(arm_fields - own)]
        cond = f"$value = {arm['code']}"
        if req:
            cond += f" AND [{', '.join(req)}].all(|$x| $x != NONE)"
        if absent:
            cond += f" AND [{', '.join(absent)}].all(|$x| $x = NONE)"
        alts.append(f"({cond})")
    return f"[{', '.join(alts)}].any(|$x| $x)"


def perms():
    return ("PERMISSIONS FOR select WHERE fn::live(spans, $session.data.snap) "
            "FOR create, update, delete NONE")


def main():
    model = json.load(open(sys.argv[1]))
    out, mapping = [], {"model_digest": model["digest"], "relations": {}, "totals": {}}
    out.append("-- generated by gen_schema.py from lctx model describe; model " + model["digest"])
    out.append("DEFINE FUNCTION OVERWRITE fn::live($spans: option<array>, $s: int) -> bool {"
               " RETURN $spans != NONE AND $spans.any(|$p| $p[0] <= $s AND (array::len($p) = 1 OR $p[1] > $s)); }"
               " PERMISSIONS FULL;")
    totals = {}

    def bump(k, n=1):
        totals[k] = totals.get(k, 0) + n

    for rel in model["relations"]:
        name = rel["name"]
        keys = [f for f in rel["fields"] if f["key"]]
        pay = [f for f in rel["fields"] if not f["key"]]
        m = {"identity_fields": len(keys), "payload_fields": len(pay), "references": 0,
             "asserted": {}, "sum": None, "subtype_refs": [], "validation_pass": [],
             "invariants": rel["invariant_refs"], "publication_checks": rel["publication_refs"]}
        tables = [(name, keys, None)]
        if pay:
            tables.append((name + "__p", pay, name))
        for table, fields, owner in tables:
            out.append(f"DEFINE TABLE OVERWRITE {table} TYPE NORMAL SCHEMAFULL {perms()};")
            out.append(f"DEFINE FIELD OVERWRITE spans ON {table} TYPE array<array<int>>;")
            if owner:
                out.append(f"DEFINE FIELD OVERWRITE identity_of ON {table} TYPE record<{owner}> REFERENCE READONLY;")
            for f in fields:
                clause = f"DEFINE FIELD OVERWRITE {q(f['name'])} ON {table} TYPE {field_type(f)}"
                if f["type"] == "id" and not f["list"]:
                    clause += " REFERENCE"
                    m["references"] += 1
                    bump("references")
                    m["validation_pass"].append(f"closure:{table}.{f['name']}->{f['target']}")
                    if "subtype" in f:
                        m["subtype_refs"].append(f"{table}.{f['name']}")
                        m["validation_pass"].append(f"subtype:{table}.{f['name']}={f['subtype']}")
                        bump("subtype_refs")
                expr, kinds = field_assert(f)
                if expr:
                    clause += f" ASSERT {expr}"
                    for k in kinds:
                        m["asserted"][k] = m["asserted"].get(k, 0) + 1
                        bump("assert:" + k)
                clause += " READONLY;"
                out.append(clause)
                bump("fields")
        if "sum" in rel:
            expr = sum_assert(rel, {f["name"] for f in keys})
            tag = rel["sum"]["tag"]
            tagf = next(f for f in rel["fields"] if f["name"] == tag)
            if expr and tagf["key"]:
                # re-define the tag field with the arm assertion (codebook kept)
                base, _ = field_assert(tagf)
                full = f"({base}) AND ({expr})" if base else expr
                out.append(f"DEFINE FIELD OVERWRITE {q(tag)} ON {name} TYPE {field_type(tagf)} ASSERT {full} READONLY;")
                m["sum"] = "assert"
                bump("sum:assert")
            else:
                m["sum"] = "validation-pass"
                m["validation_pass"].append("sum-arms")
                bump("sum:validation-pass")
        if pay:
            m["validation_pass"].append("one-payload-per-identity")
            bump("payload-tables")
        bump("invariants-external", len(rel["invariant_refs"]))
        mapping["relations"][name] = m
    out.append("DEFINE TABLE OVERWRITE snapshot SCHEMAFULL PERMISSIONS FOR select WHERE ordinal = $session.data.snap FOR create, update, delete NONE;")
    out.append("DEFINE FIELD OVERWRITE ordinal ON snapshot TYPE int READONLY;")
    out.append("DEFINE FIELD OVERWRITE state ON snapshot TYPE string ASSERT $value IN ['staging', 'validated', 'published', 'failed', 'retired'];")
    out.append("DEFINE FIELD OVERWRITE source ON snapshot TYPE string READONLY;")
    out.append("DEFINE FIELD OVERWRITE model_digest ON snapshot TYPE string READONLY;")
    out.append("DEFINE FIELD OVERWRITE manifest ON snapshot TYPE option<object> FLEXIBLE;")
    out.append("DEFINE TABLE OVERWRITE selection SCHEMAFULL PERMISSIONS FOR select FULL FOR create, update, delete NONE;")
    out.append("DEFINE FIELD OVERWRITE snap ON selection TYPE int;")
    out.append("DEFINE TABLE OVERWRITE lease SCHEMAFULL PERMISSIONS FOR select WHERE id = $auth.id FOR create, update, delete NONE;")
    out.append("DEFINE FIELD OVERWRITE snap ON lease TYPE int;")
    out.append("DEFINE FIELD OVERWRITE reader ON lease TYPE string;")
    out.append("DEFINE FIELD OVERWRITE expires ON lease TYPE datetime;")
    out.append("DEFINE TABLE OVERWRITE reader SCHEMAFULL PERMISSIONS NONE;")
    out.append("DEFINE FIELD OVERWRITE name ON reader TYPE string;")
    out.append("DEFINE FIELD OVERWRITE pass ON reader TYPE string;")
    out.append("DEFINE INDEX OVERWRITE reader_name ON reader FIELDS name UNIQUE;")
    # Pinning: SIGNIN creates a lease record and returns it as the session identity ($auth), so
    # every later authentication of the token (HTTP re-authenticates per request) reads the same
    # pinned ordinal. Run 1 read selection:current in CONTEXT and was NOT pinned over HTTP
    # (raw/synthetic-run1-context-from-selection.log).
    out.append(
        "DEFINE ACCESS OVERWRITE agent ON DATABASE TYPE RECORD "
        "SIGNIN { LET $u = (SELECT * FROM ONLY reader WHERE name = $name AND crypto::argon2::compare(pass, $pass) LIMIT 1); "
        "IF $u = NONE { THROW 'bad credentials' }; "
        "RETURN (CREATE ONLY lease SET snap = (SELECT VALUE snap FROM ONLY selection:current), reader = $name, expires = time::now() + 1h).id; } "
        "CONTEXT { RETURN { snap: $auth.snap } } "
        "DURATION FOR TOKEN 1h, FOR SESSION 1h;")
    totals["relations"] = len(model["relations"])
    totals["invariants_declared"] = len(model["invariants"])
    totals["publication_checks_declared"] = len(model["publication_checks"])
    mapping["totals"] = totals
    open(sys.argv[2], "w").write("\n".join(out) + "\n")
    json.dump(mapping, open(sys.argv[3], "w"), indent=1, sort_keys=True)
    print(json.dumps(totals, sort_keys=True))


if __name__ == "__main__":
    main()
