[package]
name = "ruffprobe"
version = "0.0.0"
edition = "2024"
[workspace]
[dependencies]
ruff_python_ast = "=0.0.14"
ruff_text_size = "=0.0.14"
ruff_db = "=0.0.14"
ty_python_core = "=0.0.14"
ty_module_resolver = "=0.0.14"
ty_vendored = "=0.0.14"
salsa = { version = "0.28", default-features = false, features = ["compact_str", "macros", "salsa_unstable", "inventory", "ordermap"] }
anyhow = "1"
