//! Relation declarations: the single authority for every canonical relation (DESIGN §15.2).
//!
//! A relation is declared once with [`relation!`](crate::relation). The declaration states its
//! layer, family and producing stage, its typed columns, its generation-qualified key, its identity
//! recipe, its participant roles, its coverage scope and polarity, its fidelity class and its
//! serving exposure. The Rust row type, Arrow schema and batch codec are generated by the macro;
//! PostgreSQL DDL, constraints, codebook references, grants and every relation list are generated
//! at run time from the declaration ([`crate::ddl`]). [`model!`](crate::model) declares the one
//! registry, `RelationId`.

use std::collections::BTreeSet;
use std::sync::Arc;

use arrow_array::{ArrayRef, RecordBatch};
use arrow_schema::{ArrowError, DataType, Field, Schema, SchemaRef};

use crate::id::Recipe;

/// Schema metadata key naming the relation.
pub const RELATION_KEY: &str = "lctx.relation";
/// Schema metadata key naming the relation's layer.
pub const LAYER_KEY: &str = "lctx.layer";

/// The partition-key column every canonical relation is qualified by. It leads every key and is
/// supplied by the store, never by a producer's batch.
pub const GENERATION_COLUMN: &str = "generation_id";

/// Longest relation name: every derived constraint and index name stays within PostgreSQL's
/// 63-byte identifier limit.
pub const MAX_NAME: usize = 48;

/// The model layer a relation belongs to (DESIGN §15.1). L4 serving is generated, never declared.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Layer {
    /// Attributed provider observations.
    L0,
    /// Normalized relations: entities, occurrences, places, calls, bindings.
    L1,
    /// Derived semantic relations: transfers, conditions, obligations, derivations, findings.
    L2,
    /// Product relations: catalog, requirements, associations, retrieval units.
    L3,
}

impl Layer {
    pub fn text(self) -> &'static str {
        match self {
            Self::L0 => "L0",
            Self::L1 => "L1",
            Self::L2 => "L2",
            Self::L3 => "L3",
        }
    }
}

/// What kind of truth a relation's rows carry (CI-02).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FidelityClass {
    /// Read from a provider's structure.
    Extracted,
    /// Resolved by an analyzer or a named policy.
    Resolved,
    /// Derived by a declared rule from other relations.
    Derived,
    /// Heuristic: never reaches a served claim as fact.
    Heuristic,
}

/// Whether an absent row within the coverage scope means "no" (DESIGN §15.8).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Polarity {
    /// The rows are exactly the facts within scope; absence is a negative.
    Exact,
    /// Over-approximation: every true fact is present, some rows may not hold.
    May,
    /// Under-approximation: every row holds, some true facts may be missing.
    Must,
}

/// How a column takes part in the relation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColumnClass {
    /// Semantic content.
    Payload,
    /// Where a row came from (run, depth, witness, rendered text). Never an identity input.
    Provenance,
    /// A participant role: a generation-qualified reference to a key column of another relation.
    Reference {
        relation: &'static str,
        column: &'static str,
    },
}

/// One declared column. `field` is the column type's Arrow field constructor, so type,
/// nullability and codebook metadata have one source.
#[derive(Debug, Clone, Copy)]
pub struct ColumnDecl {
    pub name: &'static str,
    pub field: fn(&str) -> Field,
    pub class: ColumnClass,
}

impl ColumnDecl {
    pub fn arrow(&self) -> Field {
        (self.field)(self.name)
    }
}

/// The identity of a row: its id column is the recipe over exactly `inputs`, in recipe order.
#[derive(Debug, Clone, Copy)]
pub struct IdentityDecl {
    pub column: &'static str,
    pub recipe: Recipe,
    pub inputs: &'static [&'static str],
}

/// How a relation is exposed to serving (DESIGN §15.12).
#[derive(Debug, Clone, Copy)]
pub struct Exposure {
    /// Readable by the serving role.
    pub serve: bool,
    /// Lookup indexes beyond the key, each a column list.
    pub lookups: &'static [&'static [&'static str]],
    /// The row is a wire DTO.
    pub wire: bool,
}

impl Exposure {
    /// Canonical but not served.
    pub const INTERNAL: Self = Self {
        serve: false,
        lookups: &[],
        wire: false,
    };
}

/// A relation's complete declaration.
#[derive(Debug, Clone, Copy)]
pub struct RelationDecl {
    pub name: &'static str,
    pub layer: Layer,
    pub family: &'static str,
    /// The producing stage's id (DESIGN §15.11).
    pub stage: &'static str,
    pub columns: &'static [ColumnDecl],
    /// The key within a generation; the store prefixes [`GENERATION_COLUMN`].
    pub key: &'static [&'static str],
    pub unique: &'static [&'static [&'static str]],
    pub identity: Option<IdentityDecl>,
    pub checks: &'static [(&'static str, &'static str)],
    pub fidelity: FidelityClass,
    pub polarity: Polarity,
    /// The domain within which an absent row is meaningful.
    pub coverage: &'static str,
    pub exposure: Exposure,
}

impl RelationDecl {
    /// The Arrow schema of a producer's batch: the declared columns, without the generation.
    pub fn schema(&self) -> SchemaRef {
        Arc::new(
            Schema::new(self.columns.iter().map(ColumnDecl::arrow).collect::<Vec<_>>())
                .with_metadata(
                    [
                        (RELATION_KEY.to_owned(), self.name.to_owned()),
                        (LAYER_KEY.to_owned(), self.layer.text().to_owned()),
                    ]
                    .into(),
                ),
        )
    }

    pub fn column(&self, name: &str) -> Option<&ColumnDecl> {
        self.columns.iter().find(|c| c.name == name)
    }

    /// The participant roles, in column order.
    pub fn references(&self) -> impl Iterator<Item = (&'static str, &'static str, &'static str)> {
        self.columns.iter().filter_map(|c| match c.class {
            ColumnClass::Reference { relation, column } => Some((c.name, relation, column)),
            _ => None,
        })
    }
}

/// A declared relation's generated row codec.
pub trait Relation {
    const DECL: RelationDecl;
    type Row;
    /// Build a batch; `RecordBatch::try_new` checks types, nullability and metadata.
    fn to_batch(rows: &[Self::Row]) -> Result<RecordBatch, ArrowError>;
    /// Read every row of a batch whose fields equal the declaration's by name and type.
    fn from_batch(batch: &RecordBatch) -> Result<Vec<Self::Row>, ArrowError>;
}

/// A declaration defect, found by [`validate`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeclError {
    pub relation: String,
    pub message: String,
}

impl std::fmt::Display for DeclError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.relation, self.message)
    }
}

/// Check a model's declarations against each other: names, keys, identities, roles, lookups.
/// Every generator relies on these holding; the registry test runs it over the whole model.
pub fn validate(model: &[&RelationDecl]) -> Result<(), Vec<DeclError>> {
    let mut errors = Vec::new();
    let mut names = BTreeSet::new();
    for decl in model {
        let mut err = |message: String| {
            errors.push(DeclError {
                relation: decl.name.to_owned(),
                message,
            })
        };
        if !names.insert(decl.name) {
            err("declared twice".into());
        }
        if decl.name.is_empty() || decl.name.len() > MAX_NAME {
            err(format!("name must be 1..={MAX_NAME} bytes"));
        }
        if !decl
            .name
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_')
        {
            err("name must be lowercase ASCII, digits and underscores".into());
        }
        let mut columns = BTreeSet::new();
        for c in decl.columns {
            if !columns.insert(c.name) {
                err(format!("column {} declared twice", c.name));
            }
            if c.name == GENERATION_COLUMN {
                err(format!("{GENERATION_COLUMN} is supplied by the store"));
            }
            if c.name.len() > 63 {
                err(format!("column {} exceeds 63 bytes", c.name));
            }
        }
        let known = |name: &str| decl.column(name).is_some();
        if decl.key.is_empty() {
            err("key is empty".into());
        }
        for k in decl.key {
            match decl.column(k) {
                None => err(format!("key column {k} is not declared")),
                Some(c) if c.arrow().is_nullable() => {
                    err(format!("key column {k} is nullable; declare a unique key instead"))
                }
                Some(_) => {}
            }
        }
        for u in decl.unique {
            for c in *u {
                if !known(c) {
                    err(format!("unique column {c} is not declared"));
                }
            }
        }
        for lookup in decl.exposure.lookups {
            for c in *lookup {
                if !known(c) {
                    err(format!("lookup column {c} is not declared"));
                }
            }
        }
        if let Some(identity) = decl.identity {
            match decl.column(identity.column) {
                None => err(format!("identity column {} is not declared", identity.column)),
                Some(c) if c.arrow().data_type() != &DataType::FixedSizeBinary(16) => {
                    err(format!("identity column {} is not an Id", identity.column))
                }
                Some(_) => {}
            }
            if identity.inputs.len() != identity.recipe.fields.len() {
                err(format!(
                    "identity {} takes {} inputs, recipe {} has {} fields",
                    identity.column,
                    identity.inputs.len(),
                    identity.recipe.name,
                    identity.recipe.fields.len()
                ));
            }
            for input in identity.inputs {
                match decl.column(input) {
                    None => err(format!("identity input {input} is not declared")),
                    Some(c) if c.class == ColumnClass::Provenance => {
                        err(format!("identity input {input} is provenance"))
                    }
                    Some(_) if *input == identity.column => {
                        err(format!("identity input {input} is the id itself"))
                    }
                    Some(_) => {}
                }
            }
        }
        for (column, relation, target) in decl.references() {
            match model.iter().find(|d| d.name == relation) {
                None => err(format!("{column} refers to undeclared relation {relation}")),
                Some(t) => {
                    let keyed = t.key == [target]
                        || t.unique.iter().any(|u| *u == [target]);
                    if !keyed {
                        err(format!(
                            "{column} refers to {relation}.{target}, which is not a single-column key"
                        ));
                    }
                    let (Some(from), Some(to)) = (decl.column(column), t.column(target)) else {
                        err(format!("{column} refers to missing column {relation}.{target}"));
                        continue;
                    };
                    if from.arrow().data_type() != to.arrow().data_type() {
                        err(format!(
                            "{column} and {relation}.{target} have different types"
                        ));
                    }
                }
            }
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors)
    }
}

/// Read row `i` of one declared column, naming the relation and column on failure.
#[doc(hidden)]
pub fn read_field<T: crate::decl::column::ArrowColumn>(
    relation: &str,
    column: &str,
    array: &ArrayRef,
    i: usize,
) -> Result<T, ArrowError> {
    T::read(array.as_ref(), i)
        .map_err(|e| ArrowError::InvalidArgumentError(format!("{relation}.{column}: {e}")))
}

/// Check a batch against a declaration by field name and type (metadata is ignored, since a
/// reader may not carry it).
#[doc(hidden)]
pub fn check_batch(decl: &RelationDecl, batch: &RecordBatch) -> Result<(), ArrowError> {
    let declared = decl.schema();
    let got = batch.schema();
    let same = declared.fields().len() == got.fields().len()
        && declared
            .fields()
            .iter()
            .zip(got.fields())
            .all(|(a, b)| a.name() == b.name() && a.data_type() == b.data_type());
    if same {
        Ok(())
    } else {
        Err(ArrowError::SchemaError(format!(
            "{}: batch schema differs from the declaration",
            decl.name
        )))
    }
}

/// The class of a column from its optional `[...]` marker.
#[doc(hidden)]
#[macro_export]
macro_rules! __column_class {
    () => {
        $crate::decl::relation::ColumnClass::Payload
    };
    (provenance) => {
        $crate::decl::relation::ColumnClass::Provenance
    };
    (ref $relation:ident . $column:ident) => {
        $crate::decl::relation::ColumnClass::Reference {
            relation: stringify!($relation),
            column: stringify!($column),
        }
    };
}

/// Declare a relation once (DESIGN §15.2). Columns may carry `[provenance]` or
/// `[ref relation.column]`; everything else is payload.
///
/// ```ignore
/// relation! {
///     /// Source occurrences.
///     Occurrences, OccurrencesRow = "occurrences" {
///         layer: L0, family: "syntax", stage: "extract",
///         fidelity: Extracted, polarity: Exact, coverage: "module",
///         key: [occurrence_id],
///         identity: occurrence_id = recipes::OCCURRENCE [module_id, start_byte, end_byte, syntax_kind],
///     }
///     row {
///         occurrence_id: Id,
///         module_id: Id [ref entities.entity_id],
///         start_byte: i64,
///         end_byte: i64,
///         syntax_kind: String,
///         run_id: Id [provenance],
///     }
/// }
/// ```
#[macro_export]
macro_rules! relation {
    (
        $(#[$meta:meta])*
        $rel:ident, $row:ident = $name:literal {
            layer: $layer:ident,
            family: $family:literal,
            stage: $stage:literal,
            fidelity: $fidelity:ident,
            polarity: $polarity:ident,
            coverage: $coverage:literal,
            key: [$($key:ident),+ $(,)?],
            $(unique: [$([$($unique:ident),+ $(,)?]),* $(,)?],)?
            $(identity: $idcol:ident = $recipe:path [$($input:ident),+ $(,)?],)?
            $(checks: [$(($cname:literal, $cexpr:literal)),* $(,)?],)?
            $(serve: { lookups: [$([$($lookup:ident),+ $(,)?]),* $(,)?], wire: $wire:literal $(,)? },)?
        }
        $(derives = [$($derive:path),* $(,)?])?
        row { $($(#[$fmeta:meta])* $field:ident : $ty:ty $([$($class:tt)*])?),+ $(,)? }
    ) => {
        #[doc = concat!("A row of `", $name, "`.")]
        #[derive(Debug, Clone, PartialEq)]
        $(#[derive($($derive),*)])?
        pub struct $row { $($(#[$fmeta])* pub $field: $ty),+ }

        $(#[$meta])*
        pub struct $rel;

        impl $crate::decl::relation::Relation for $rel {
            const DECL: $crate::decl::relation::RelationDecl = $crate::decl::relation::RelationDecl {
                name: $name,
                layer: $crate::decl::relation::Layer::$layer,
                family: $family,
                stage: $stage,
                columns: &[$(
                    $crate::decl::relation::ColumnDecl {
                        name: stringify!($field),
                        field: <$ty as $crate::decl::column::ArrowColumn>::field,
                        class: $crate::__column_class!($($($class)*)?),
                    }
                ),+],
                key: &[$(stringify!($key)),+],
                unique: &[$($(&[$(stringify!($unique)),+]),*)?],
                identity: $crate::__identity!($($idcol = $recipe [$($input),+])?),
                checks: &[$($(($cname, $cexpr)),*)?],
                fidelity: $crate::decl::relation::FidelityClass::$fidelity,
                polarity: $crate::decl::relation::Polarity::$polarity,
                coverage: $coverage,
                exposure: $crate::__exposure!($([$([$($lookup),+]),*] $wire)?),
            };
            type Row = $row;

            fn to_batch(
                rows: &[$row],
            ) -> Result<$crate::__private::arrow_array::RecordBatch, $crate::__private::arrow_schema::ArrowError> {
                let columns: Vec<$crate::__private::arrow_array::ArrayRef> = vec![
                    $(<$ty as $crate::decl::column::ArrowColumn>::array(rows.iter().map(|r| &r.$field))),+
                ];
                $crate::__private::arrow_array::RecordBatch::try_new(
                    <Self as $crate::decl::relation::Relation>::DECL.schema(),
                    columns,
                )
            }

            fn from_batch(
                batch: &$crate::__private::arrow_array::RecordBatch,
            ) -> Result<Vec<$row>, $crate::__private::arrow_schema::ArrowError> {
                $crate::decl::relation::check_batch(&<Self as $crate::decl::relation::Relation>::DECL, batch)?;
                let columns = batch.columns();
                (0..batch.num_rows())
                    .map(|i| {
                        let mut column = columns.iter();
                        Ok($row {
                            $($field: $crate::decl::relation::read_field::<$ty>(
                                $name,
                                stringify!($field),
                                column.next().expect("a column per field"),
                                i,
                            )?),+
                        })
                    })
                    .collect()
            }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __identity {
    () => {
        None
    };
    ($idcol:ident = $recipe:path [$($input:ident),+]) => {
        Some($crate::decl::relation::IdentityDecl {
            column: stringify!($idcol),
            recipe: $recipe,
            inputs: &[$(stringify!($input)),+],
        })
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __exposure {
    () => {
        $crate::decl::relation::Exposure::INTERNAL
    };
    ([$([$($lookup:ident),+]),*] $wire:literal) => {
        $crate::decl::relation::Exposure {
            serve: true,
            lookups: &[$(&[$(stringify!($lookup)),+]),*],
            wire: $wire,
        }
    };
}

/// Declare the model's one registry: [`RelationId`] and the declarations in registry order.
/// Every relation list in the system is derived from it.
#[macro_export]
macro_rules! model {
    ($($rel:ident),* $(,)?) => {
        /// Every declared relation. The single registry (DESIGN §15.2).
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
        pub enum RelationId { $($rel),* }

        impl RelationId {
            pub const ALL: &'static [RelationId] = &[$(RelationId::$rel),*];

            pub fn decl(self) -> &'static $crate::decl::relation::RelationDecl {
                match self {
                    $(RelationId::$rel => &<$rel as $crate::decl::relation::Relation>::DECL,)*
                }
            }
        }

        /// The declarations, in registry order.
        pub const DECLS: &[&$crate::decl::relation::RelationDecl] =
            &[$(&<$rel as $crate::decl::relation::Relation>::DECL),*];
    };
}
