#[macro_export]
macro_rules! catalog_inputs {($m:ident)=>{$m! {
    aspects: $crate::domain::normalized::callable_aspects::CallableAspect,
    field_defaults: $crate::domain::normalized::callable_aspects::FieldDefault,
    field_default_assessments: $crate::domain::normalized::callable_aspects::FieldDefaultAssessment,
    export_origins: $crate::domain::symbols::ExportOrigin,
    provider_modules: $crate::domain::calls::ProviderModule,
    ownership: $crate::domain::normalized::entities::OccurrenceOwnership,
    references: $crate::domain::lexical::ReferenceObservation,
    reference_assessments: $crate::domain::normalized::links::ReferenceEntityAssessment,
    reference_candidates: $crate::domain::normalized::links::ReferenceEntityCandidate,
    reference_targets: $crate::domain::normalized::links::ReferenceEntityTarget,
    lexical_resolutions: $crate::domain::lexical::LexicalResolution,
    class_members: $crate::domain::class_metadata::ClassMemberObservation,
    class_metadata: $crate::domain::class_metadata::ClassMetadataObservation,
    class_traits: $crate::domain::symbols::ClassTraitObservation,
    source_callables: $crate::domain::normalized::entities::CallableEntity,
    source_classes: $crate::domain::normalized::entities::ClassEntity,
    declarations: $crate::domain::syntax::DeclarationObservation,
    bindings: $crate::domain::lexical::BindingObservation,
    binding_events: $crate::domain::lexical::BindingEvent,
    lexical_scopes: $crate::domain::lexical::LexicalScope,
    placements: $crate::domain::syntax::SyntaxPlacement,
    occurrences: $crate::domain::source::Occurrence,
    artifacts: $crate::domain::source::SourceArtifact,
    modules: $crate::domain::source::Module,
    names: $crate::domain::symbols::PublicNameObservation,
    exposures: $crate::domain::normalized::entities::PublicExposure,
    exposure_candidates: $crate::domain::normalized::entities::PublicExposureCandidate,
    resolutions: $crate::domain::normalized::entities::SymbolEntityResolution,
    entity_candidates: $crate::domain::normalized::entities::SymbolEntityCandidate,
    refs: $crate::domain::normalized::entities::EntityRef,
    assessments: $crate::domain::normalized::callables::EffectiveCallableAssessment,
    variants: $crate::domain::normalized::callables::SignatureVariant,
    slots: $crate::domain::normalized::callables::SignatureSlot,
    slot_entities: $crate::domain::normalized::callables::SignatureSlotEntity,
    parameter_links: $crate::domain::normalized::entities::ParameterEntityLink,
    parameters: $crate::domain::normalized::entities::ParameterEntity,
    parameter_syntax: $crate::domain::syntax::ParameterSyntaxObservation,
    qualifications: $crate::domain::assertion::AssertionQualification,
    traits: $crate::domain::symbols::FunctionTraitObservation,
    symbols: $crate::domain::calls::ProviderSymbol,
    ancestry: $crate::domain::normalized::links::AncestryEntityAssessment,
    sequence_members: $crate::domain::symbols::SymbolSequenceMember,
    native_coverage: $crate::domain::attribution::ProviderCoverage,
    ancestors: $crate::domain::normalized::links::AncestryEntityMember,
    ancestry_observations: $crate::domain::symbols::ClassAncestryObservation,
    fields: $crate::domain::normalized::entities::FieldEntity,
    field_links: $crate::domain::normalized::entities::FieldEntityLink,
    field_declarations: $crate::domain::normalized::entities::FieldDeclarationLink,
    field_syntax: $crate::domain::syntax::ClassFieldSyntaxObservation,
    field_observations: $crate::domain::types::RecordFieldObservation,
}};}
#[macro_export]
macro_rules! catalog_outputs {
    ($m:ident) => {
        $m! {
            members:$crate::domain::catalog::CatalogMember,
            exposures:$crate::domain::catalog::CatalogExposure,
            candidates:$crate::domain::catalog::CatalogCandidate,
            callables:$crate::domain::catalog::CatalogCallable,
            aspects:$crate::domain::catalog::CatalogCallableAspect,
            invocations:$crate::domain::catalog::CatalogInvocation,
            aliases:$crate::domain::catalog::CatalogAlias,
            paths:$crate::domain::catalog::CatalogPath,
            boundaries:$crate::domain::catalog::CatalogPathBoundary,
            class_members: $crate::domain::catalog::CatalogClassMember,
            class_metadata:$crate::domain::catalog::CatalogClassMetadata,
            classes:$crate::domain::catalog::CatalogClass,
            constructors:$crate::domain::catalog::CatalogConstructor,
            subjects:$crate::domain::catalog::CatalogOptionSubject,
            defaults:$crate::domain::catalog::CatalogDefault,
            evidence:$crate::domain::catalog::CatalogOptionEvidence,
            options:$crate::domain::catalog::CatalogOption,
        }
    };
}
