-- ADR-0076: independently rooted original evidence. Existing migrations remain immutable.
DO $$ DECLARE c record; BEGIN
 FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='lctx_serving.generations'::regclass
 AND contype='c' AND (pg_get_constraintdef(oid) LIKE '%bundle_format%' OR pg_get_constraintdef(oid) LIKE '%''format''%')
 LOOP EXECUTE format('ALTER TABLE lctx_serving.generations DROP CONSTRAINT %I',c.conname); END LOOP;
END $$;
ALTER TABLE lctx_serving.generations ADD CHECK
 (((manifest->>'format')::int,(manifest->>'bundle_format')::int) IN ((1,11),(2,12),(3,13),(4,14),(5,15)));
-- Generated by lctx-postgres/examples/projection_ddl.rs from cpg-schema.
CREATE TABLE lctx_serving.catalog_artifacts (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "artifact_id" bytea NOT NULL CHECK (octet_length("artifact_id") = 16),
 "release_id" bytea NOT NULL CHECK (octet_length("release_id") = 16),
 "path" text NOT NULL,
 "source_kind" text NOT NULL,
 "source_digest" bytea NOT NULL CHECK (octet_length("source_digest") = 32),
 "byte_len" bigint NOT NULL,
 "body" bytea NOT NULL,
 "alignment" text NOT NULL CHECK ("alignment" IN ('exact','mapped_with_evidence','other','unknown')),
 "provenance" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,artifact_id)
);
ALTER TABLE lctx_serving.catalog_artifacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_artifacts FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_artifacts FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_artifacts FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_artifacts FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_artifacts TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_artifacts TO lctx_importer;
CREATE TABLE lctx_serving.catalog_spans (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "span_id" bytea NOT NULL CHECK (octet_length("span_id") = 16),
 "artifact_id" bytea NOT NULL CHECK (octet_length("artifact_id") = 16),
 "start_byte" bigint NOT NULL,
 "end_byte" bigint NOT NULL,
 "extraction" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,span_id)
);
ALTER TABLE lctx_serving.catalog_spans ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_spans FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_spans FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_spans FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_spans FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_spans TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_spans TO lctx_importer;
CREATE TABLE lctx_serving.catalog_scenarios (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "scenario_id" bytea NOT NULL CHECK (octet_length("scenario_id") = 16),
 "primary_span_id" bytea NOT NULL CHECK (octet_length("primary_span_id") = 16),
 "detail" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,scenario_id)
);
ALTER TABLE lctx_serving.catalog_scenarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_scenarios FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_scenarios FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_scenarios FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_scenarios FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_scenarios TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_scenarios TO lctx_importer;
CREATE TABLE lctx_serving.catalog_deployments (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "deployment_id" bytea NOT NULL CHECK (octet_length("deployment_id") = 16),
 "span_id" bytea NOT NULL CHECK (octet_length("span_id") = 16),
 "ordinal" bigint NOT NULL,
 "derivation" text NOT NULL,
 "detail" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,deployment_id)
);
ALTER TABLE lctx_serving.catalog_deployments ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_deployments FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_deployments FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_deployments FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_deployments FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_deployments TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_deployments TO lctx_importer;
CREATE TABLE lctx_serving.catalog_associations (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "association_id" bytea NOT NULL CHECK (octet_length("association_id") = 16),
 "member_id" bytea CHECK (octet_length("member_id") = 16),
 "release_id" bytea CHECK (octet_length("release_id") = 16),
 CHECK ((member_id IS NULL) <> (release_id IS NULL)),
 "evidence_id" bytea NOT NULL CHECK (octet_length("evidence_id") = 16),
 "evidence_kind" text NOT NULL CHECK ("evidence_kind" IN ('span','scenario','deployment')),
 "role" text NOT NULL CHECK ("role" IN ('declares','surface','configuration','reader','documents','demonstrates','invokes','tests_failure','suggests','observes')),
 "basis" text NOT NULL CHECK ("basis" IN ('source_fact','resolved_target','candidate_targets','exact_textual_reference','ambiguous_textual_mention','same_document_passage','owning_distribution','task_observation','release_distribution','explicit_config_reference')),
 "site_id" bytea CHECK (octet_length("site_id") = 16),
 "intent" text NOT NULL CHECK ("intent" IN ('demonstration','assertion_test','expected_failure','skip_xfail','unknown')),
 "support" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,association_id)
);
ALTER TABLE lctx_serving.catalog_associations ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_associations FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_associations FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_associations FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_associations FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_associations TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_associations TO lctx_importer;
ALTER TABLE lctx_serving.catalog_spans ADD FOREIGN KEY (generation_digest,artifact_id) REFERENCES lctx_serving.catalog_artifacts(generation_digest,artifact_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.catalog_scenarios ADD FOREIGN KEY (generation_digest,primary_span_id) REFERENCES lctx_serving.catalog_spans(generation_digest,span_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.catalog_deployments ADD FOREIGN KEY (generation_digest,span_id) REFERENCES lctx_serving.catalog_spans(generation_digest,span_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.catalog_associations ADD FOREIGN KEY (generation_digest,member_id) REFERENCES lctx_serving.catalog_members(generation_digest,member_id) DEFERRABLE INITIALLY DEFERRED;

CREATE OR REPLACE FUNCTION lctx_serving.prepare_generation(doc text, transport bytea) RETURNS bigint
 LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE id bytea:=sha256(convert_to(doc,'UTF8')); prior text; a bigint; n text; child text; v text;
BEGIN
 IF (doc::jsonb->>'format')::int IS DISTINCT FROM 5 OR (doc::jsonb->>'bundle_format')::int IS DISTINCT FROM 15
 OR doc::jsonb#>'{capabilities,catalog}' IS DISTINCT FROM 'true'::jsonb
 OR coalesce(doc::jsonb#>>'{context,library}','')='' THEN RAISE EXCEPTION 'unsupported projection context'; END IF;
 PERFORM pg_advisory_xact_lock(lctx_serving.lock_key(id));
 INSERT INTO lctx_serving.generations(generation_digest,canonical_manifest) VALUES(id,doc) ON CONFLICT DO NOTHING;
 SELECT canonical_manifest INTO prior FROM lctx_serving.generations WHERE generation_digest=id;
 IF prior<>doc THEN RAISE EXCEPTION 'projection identity conflict'; END IF;
 IF EXISTS(SELECT FROM lctx_serving.generations WHERE generation_digest=id AND state='failed') THEN RAISE EXCEPTION 'terminal projection failure'; END IF;
 INSERT INTO lctx_serving.import_recipes VALUES(id,1,transport) ON CONFLICT DO NOTHING;
 IF EXISTS(SELECT FROM lctx_serving.import_recipes WHERE generation_digest=id AND transport_digest<>transport)
 AND NOT lctx_serving.is_ready(id) THEN RAISE EXCEPTION 'frozen transport conflict'; END IF;
 UPDATE lctx_serving.import_attempts SET outcome='interrupted',finished_at=clock_timestamp(),failure_code='owner_disconnected'
 WHERE generation_digest=id AND outcome='running';
 INSERT INTO lctx_serving.import_attempts(generation_digest) VALUES(id) RETURNING attempt_id INTO a;
 IF NOT lctx_serving.is_ready(id) THEN
  FOREACH n IN ARRAY ARRAY['vectors','operation_vectors'] LOOP
   child:=CASE n WHEN 'vectors' THEN 'v_' ELSE 'o_' END || substr(encode(id,'hex'),1,48);
   IF to_regclass('lctx_serving.'||child) IS NULL THEN
    EXECUTE format('CREATE TABLE lctx_serving.%I PARTITION OF lctx_serving.%I FOR VALUES IN (%L)%s',child,n,id,
     CASE n WHEN 'operation_vectors' THEN ' PARTITION BY LIST (embedding_view)' ELSE '' END);
    IF n='operation_vectors' THEN
     FOREACH v IN ARRAY ARRAY['signature_doc','source_body'] LOOP
      EXECUTE format('CREATE TABLE lctx_serving.%I PARTITION OF lctx_serving.%I FOR VALUES IN (%L)',child||CASE v WHEN 'signature_doc' THEN '_d' ELSE '_s' END,child,v);
     END LOOP;
    END IF;
   ELSIF NOT EXISTS(SELECT FROM pg_class WHERE oid=to_regclass('lctx_serving.'||child)
      AND pg_get_expr(relpartbound,oid) LIKE '%'||encode(id,'hex')||'%') THEN
    RAISE EXCEPTION 'partition identity conflict';
   END IF;
  END LOOP;
 END IF;
 PERFORM lctx_serving.check_partitions(id);
 RETURN a;
END $$;
CREATE OR REPLACE FUNCTION lctx_serving.cleanup_generation(id bytea) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE n text; phase text; BEGIN
 IF NOT pg_try_advisory_xact_lock(lctx_serving.lock_key(id)) THEN RAISE EXCEPTION 'generation import is active'; END IF;
 SELECT state INTO phase FROM lctx_serving.generations WHERE generation_digest=id FOR UPDATE;
 IF phase IS NULL OR phase='ready' OR EXISTS(SELECT FROM lctx_serving.selections WHERE generation_digest=id) THEN RAISE EXCEPTION 'generation cannot be cleaned'; END IF;
 SET CONSTRAINTS ALL DEFERRED;
 FOREACH n IN ARRAY ARRAY['catalog_associations','catalog_scenarios','catalog_deployments','catalog_spans','catalog_artifacts','catalog_surfaces','catalog_field_links','catalog_configurations','catalog_constructors','catalog_type_observations','catalog_type_args','catalog_types','catalog_parameters','catalog_signatures','catalog_evidence','catalog_bindings','catalog_members','briefs','assertions','supports','support_findings','support_witnesses','support_members','support_attributes','support_attribute_incidences','evidence','brief_members','symbol_map','public_paths','lexical_text','embedding_spec','vectors','operations','operation_facets','operation_facet_status','behaviors','conditions','condition_nodes','analysis_conditions','analysis_condition_nodes','callable_parameters','summary_flows','source_context_value_identities','source_body_completions','source_body_steps','source_body_release_inputs','source_call_bindings','source_call_normals','source_call_header_steps','model_frame_exits','model_frame_exit_arguments','model_frame_exit_steps','source_modeled_identities','source_parameter_identities','return_completion_certificates','model_context_protocols','source_context_sites','source_context_arguments','summary_flow_steps','summary_boundaries','behavior_discharges','flow_test_leaves','flow_test_value_links','singletons','ambient_reads','place_claims','operation_text','operation_vectors'] LOOP
  EXECUTE format('DELETE FROM lctx_serving.%I WHERE generation_digest=$1',n) USING id;
 END LOOP;
 DELETE FROM lctx_serving.artifact_locations WHERE generation_digest=id;
 DELETE FROM lctx_serving.artifacts WHERE generation_digest=id;
 IF phase<>'failed' THEN UPDATE lctx_serving.generations SET state='failed' WHERE generation_digest=id; END IF;
 UPDATE lctx_serving.import_attempts SET outcome='interrupted',finished_at=clock_timestamp(),failure_code='owned_cleanup' WHERE generation_digest=id AND outcome='running';
 -- Keep the manifest, transport, attempts and batch receipts as terminal diagnostic history.
 -- Content-addressed files remain retained, including files shared with other generations.
END $$;
CREATE OR REPLACE FUNCTION lctx_serving.analyze_generation(id bytea) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE n text; BEGIN
 IF NOT EXISTS(SELECT FROM lctx_serving.generations WHERE generation_digest=id AND state='validating') THEN RAISE EXCEPTION 'not validating'; END IF;
 FOREACH n IN ARRAY ARRAY['catalog_associations','catalog_scenarios','catalog_deployments','catalog_spans','catalog_artifacts','catalog_surfaces','catalog_field_links','catalog_configurations','catalog_constructors','catalog_members','catalog_bindings','catalog_signatures','catalog_parameters','catalog_evidence','catalog_types','catalog_type_args','catalog_type_observations','vectors','operation_vectors','operations','operation_facets','operation_facet_status','behaviors','assertions','supports'] LOOP
  EXECUTE format('ANALYZE lctx_serving.%I',n);
 END LOOP;
END $$;

CREATE INDEX catalog_association_member ON lctx_serving.catalog_associations(generation_digest,member_id,association_id);
CREATE INDEX catalog_span_artifact ON lctx_serving.catalog_spans(generation_digest,artifact_id);
ALTER TABLE lctx_serving.catalog_artifacts ADD CHECK (byte_len = octet_length(body));
ALTER TABLE lctx_serving.catalog_spans ADD CHECK (start_byte >= 0 AND end_byte >= start_byte);

CREATE INDEX evidence_release ON lctx_serving.catalog_associations(generation_digest,release_id,association_id) WHERE release_id IS NOT NULL;
