-- ADR-0077: typed domain closure and addressable immutable retrieval artifacts.
DO $$ DECLARE c record; BEGIN
 FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='lctx_serving.generations'::regclass
 AND contype='c' AND pg_get_constraintdef(oid) LIKE '%format%' LOOP
  EXECUTE format('ALTER TABLE lctx_serving.generations DROP CONSTRAINT %I',c.conname);
 END LOOP;
END $$;
ALTER TABLE lctx_serving.generations ADD CONSTRAINT generation_formats CHECK (((manifest->>'format')::int,(manifest->>'bundle_format')::int) = (6,16));
-- Generated by lctx-postgres/examples/projection_ddl.rs from cpg-schema.
CREATE TABLE lctx_serving.catalog_selection_domains (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "member_id" bytea NOT NULL CHECK (octet_length("member_id") = 16),
 "domain_id" bytea NOT NULL CHECK (octet_length("domain_id") = 16),
 "detail" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,member_id)
);
ALTER TABLE lctx_serving.catalog_selection_domains ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_selection_domains FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_selection_domains FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_selection_domains FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_selection_domains FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_selection_domains TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_selection_domains TO lctx_importer;
CREATE TABLE lctx_serving.retrieval_units (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "unit_id" bytea NOT NULL CHECK (octet_length("unit_id") = 16),
 "family" text NOT NULL,
 "detail" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,unit_id)
);
ALTER TABLE lctx_serving.retrieval_units ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.retrieval_units FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.retrieval_units FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.retrieval_units FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.retrieval_units FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.retrieval_units TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.retrieval_units TO lctx_importer;
CREATE TABLE lctx_serving.retrieval_subjects (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "unit_id" bytea NOT NULL CHECK (octet_length("unit_id") = 16),
 "member_id" bytea CHECK (octet_length("member_id") = 16),
 "release_id" bytea CHECK (octet_length("release_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.retrieval_subjects ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.retrieval_subjects FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.retrieval_subjects FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.retrieval_subjects FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.retrieval_subjects FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.retrieval_subjects TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.retrieval_subjects TO lctx_importer;
CREATE TABLE lctx_serving.retrieval_fragments (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "fragment_id" bytea NOT NULL CHECK (octet_length("fragment_id") = 16),
 "unit_id" bytea NOT NULL CHECK (octet_length("unit_id") = 16),
 "family" text NOT NULL,
 "text" text NOT NULL,
 "content_digest" bytea NOT NULL CHECK (octet_length("content_digest") = 32),
 "embedding_status" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,fragment_id)
);
ALTER TABLE lctx_serving.retrieval_fragments ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.retrieval_fragments FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.retrieval_fragments FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.retrieval_fragments FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.retrieval_fragments FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.retrieval_fragments TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.retrieval_fragments TO lctx_importer;
CREATE TABLE lctx_serving.retrieval_vectors (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "fragment_id" bytea NOT NULL CHECK (octet_length("fragment_id") = 16),
 "input_hash" bytea NOT NULL CHECK (octet_length("input_hash") = 32),
 "vector" lctx_ext.vector(1024) NOT NULL CHECK (abs(lctx_ext.vector_norm("vector") - 1.0) <= 0.001),
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,fragment_id)
);
ALTER TABLE lctx_serving.retrieval_vectors ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.retrieval_vectors FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.retrieval_vectors FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.retrieval_vectors FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.retrieval_vectors FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.retrieval_vectors TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.retrieval_vectors TO lctx_importer;
CREATE TABLE lctx_serving.retrieval_receipt (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "detail" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.retrieval_receipt ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.retrieval_receipt FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.retrieval_receipt FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.retrieval_receipt FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.retrieval_receipt FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.retrieval_receipt TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.retrieval_receipt TO lctx_importer;
ALTER TABLE lctx_serving.catalog_selection_domains ADD FOREIGN KEY (generation_digest,member_id) REFERENCES lctx_serving.catalog_members(generation_digest,member_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.retrieval_fragments ADD FOREIGN KEY (generation_digest,unit_id) REFERENCES lctx_serving.retrieval_units(generation_digest,unit_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.retrieval_subjects ADD FOREIGN KEY (generation_digest,unit_id) REFERENCES lctx_serving.retrieval_units(generation_digest,unit_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.retrieval_subjects ADD FOREIGN KEY (generation_digest,member_id) REFERENCES lctx_serving.catalog_members(generation_digest,member_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.retrieval_vectors ADD FOREIGN KEY (generation_digest,fragment_id) REFERENCES lctx_serving.retrieval_fragments(generation_digest,fragment_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE lctx_serving.catalog_types ADD COLUMN literal_json text;

CREATE OR REPLACE FUNCTION lctx_serving.mark_ready(id bytea, policy_text text, receipts jsonb) RETURNS void
 LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE phase text; expected bigint; actual bigint; declared jsonb; r record;
BEGIN
 PERFORM pg_advisory_xact_lock(lctx_serving.lock_key(id));
 SELECT state INTO phase FROM lctx_serving.generations WHERE generation_digest=id FOR UPDATE;
 IF phase='ready' THEN RETURN; END IF;
 IF phase IS DISTINCT FROM 'validating' OR policy_text IS DISTINCT FROM '{"format":3,"route":"exact","metric":"pgvector-cosine-f32-v1","ties":"member-unit-fragment-ascending;family-rrf-v1;promotion-primary","rrf_k":60}'  THEN RAISE EXCEPTION 'not validated exact publication'; END IF;
 SELECT count(*) INTO expected FROM lctx_serving.generations g,jsonb_object_keys(g.manifest->'artifacts') WHERE g.generation_digest=id;
 SELECT count(*) INTO actual FROM lctx_serving.artifacts WHERE generation_digest=id;
 IF expected<>actual OR EXISTS(SELECT FROM lctx_serving.artifacts a WHERE a.generation_digest=id AND NOT EXISTS
  (SELECT FROM lctx_serving.artifact_locations l WHERE l.generation_digest=id AND l.name=a.name)) THEN RAISE EXCEPTION 'missing artifacts'; END IF;
 SELECT manifest->'relations' INTO declared FROM lctx_serving.generations WHERE generation_digest=id;
 IF receipts IS DISTINCT FROM declared THEN RAISE EXCEPTION 'shared validation receipt mismatch'; END IF;
 FOR r IN SELECT key,value FROM jsonb_each(declared) LOOP
  IF NOT EXISTS(SELECT FROM information_schema.columns WHERE table_schema='lctx_serving' AND table_name=r.key AND column_name='row_ordinal')
  THEN RAISE EXCEPTION 'undeclared relation'; END IF;
  EXECUTE format('SELECT count(*) FROM lctx_serving.%I WHERE generation_digest=$1',r.key) INTO actual USING id;
  IF actual IS DISTINCT FROM (r.value->>'rows')::bigint THEN RAISE EXCEPTION 'stored relation count mismatch'; END IF;
 END LOOP;
 PERFORM lctx_serving.check_partitions(id);
 INSERT INTO lctx_serving.validation_receipts VALUES(id,1,id,clock_timestamp(),receipts) ON CONFLICT DO NOTHING;
 INSERT INTO lctx_serving.retrieval_profiles(generation_digest,profile_digest,policy,qualification,canonical_policy)
 VALUES(id,sha256(convert_to(policy_text,'UTF8')),policy_text::jsonb,'{"route":"exact","validator":1}',policy_text);
 UPDATE lctx_serving.generations SET state='ready' WHERE generation_digest=id;
END $$;

CREATE INDEX retrieval_subject_member ON lctx_serving.retrieval_subjects(generation_digest,member_id,unit_id) WHERE member_id IS NOT NULL;
CREATE INDEX retrieval_fragment_unit ON lctx_serving.retrieval_fragments(generation_digest,unit_id);

CREATE OR REPLACE FUNCTION lctx_serving.prepare_generation(doc text, transport bytea) RETURNS bigint
 LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE id bytea:=sha256(convert_to(doc,'UTF8')); prior text; a bigint; child text;
BEGIN
 IF (doc::jsonb->>'format')::int IS DISTINCT FROM 6 OR (doc::jsonb->>'bundle_format')::int IS DISTINCT FROM 16
 OR doc::jsonb#>'{capabilities,catalog}' IS DISTINCT FROM 'true'::jsonb
 OR coalesce(doc::jsonb#>>'{context,library}','')='' THEN RAISE EXCEPTION 'unsupported projection context'; END IF;
 PERFORM pg_advisory_xact_lock(lctx_serving.lock_key(id));
 INSERT INTO lctx_serving.generations(generation_digest,canonical_manifest) VALUES(id,doc) ON CONFLICT DO NOTHING;
 SELECT canonical_manifest INTO prior FROM lctx_serving.generations WHERE generation_digest=id;
 IF prior<>doc THEN RAISE EXCEPTION 'projection identity conflict'; END IF;
 IF EXISTS(SELECT FROM lctx_serving.generations WHERE generation_digest=id AND state='failed') THEN RAISE EXCEPTION 'terminal projection failure'; END IF;
 INSERT INTO lctx_serving.import_recipes VALUES(id,1,transport) ON CONFLICT DO NOTHING;
 IF EXISTS(SELECT FROM lctx_serving.import_recipes WHERE generation_digest=id AND transport_digest<>transport)
 AND NOT lctx_serving.is_ready(id) THEN RAISE EXCEPTION 'frozen transport conflict'; END IF;
 UPDATE lctx_serving.import_attempts SET outcome='interrupted',finished_at=clock_timestamp(),failure_code='owner_disconnected'
 WHERE generation_digest=id AND outcome='running';
 INSERT INTO lctx_serving.import_attempts(generation_digest) VALUES(id) RETURNING attempt_id INTO a;
 IF NOT lctx_serving.is_ready(id) THEN
  child:='v_'||substr(encode(id,'hex'),1,48);
  IF to_regclass('lctx_serving.'||child) IS NULL THEN
   EXECUTE format('CREATE TABLE lctx_serving.%I PARTITION OF lctx_serving.vectors FOR VALUES IN (%L)',child,id);
  ELSIF NOT EXISTS(SELECT FROM pg_class WHERE oid=to_regclass('lctx_serving.'||child)
     AND pg_get_expr(relpartbound,oid) LIKE '%'||encode(id,'hex')||'%') THEN
   RAISE EXCEPTION 'partition identity conflict';
  END IF;
 END IF;
 PERFORM lctx_serving.check_partitions(id);
 RETURN a;
END $$;
CREATE OR REPLACE FUNCTION lctx_serving.cleanup_generation(id bytea) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE n text; phase text; BEGIN
 IF NOT pg_try_advisory_xact_lock(lctx_serving.lock_key(id)) THEN RAISE EXCEPTION 'generation import is active'; END IF;
 SELECT state INTO phase FROM lctx_serving.generations WHERE generation_digest=id FOR UPDATE;
 IF phase IS NULL OR phase='ready' OR EXISTS(SELECT FROM lctx_serving.selections WHERE generation_digest=id) THEN RAISE EXCEPTION 'generation cannot be cleaned'; END IF;
 SET CONSTRAINTS ALL DEFERRED;
 FOREACH n IN ARRAY ARRAY['retrieval_vectors','retrieval_fragments','retrieval_subjects','retrieval_units','retrieval_receipt','catalog_selection_domains','catalog_associations','catalog_scenarios','catalog_deployments','catalog_spans','catalog_artifacts','catalog_surfaces','catalog_field_links','catalog_configurations','catalog_constructors','catalog_type_observations','catalog_type_args','catalog_types','catalog_parameters','catalog_signatures','catalog_evidence','catalog_bindings','catalog_members','briefs','assertions','supports','support_findings','support_witnesses','support_members','support_attributes','support_attribute_incidences','evidence','brief_members','symbol_map','public_paths','lexical_text','embedding_spec','vectors','operations','operation_facets','operation_facet_status','behaviors','conditions','condition_nodes','analysis_conditions','analysis_condition_nodes','callable_parameters','summary_flows','source_context_value_identities','source_body_completions','source_body_steps','source_body_release_inputs','source_call_bindings','source_call_normals','source_call_header_steps','model_frame_exits','model_frame_exit_arguments','model_frame_exit_steps','source_modeled_identities','source_parameter_identities','return_completion_certificates','model_context_protocols','source_context_sites','source_context_arguments','summary_flow_steps','summary_boundaries','behavior_discharges','flow_test_leaves','flow_test_value_links','singletons','ambient_reads','place_claims'] LOOP
  EXECUTE format('DELETE FROM lctx_serving.%I WHERE generation_digest=$1',n) USING id;
 END LOOP;
 DELETE FROM lctx_serving.artifact_locations WHERE generation_digest=id;
 DELETE FROM lctx_serving.artifacts WHERE generation_digest=id;
 IF phase<>'failed' THEN UPDATE lctx_serving.generations SET state='failed' WHERE generation_digest=id; END IF;
 UPDATE lctx_serving.import_attempts SET outcome='interrupted',finished_at=clock_timestamp(),failure_code='owned_cleanup' WHERE generation_digest=id AND outcome='running';
 -- Keep the manifest, transport, attempts and batch receipts as terminal diagnostic history.
 -- Content-addressed files remain retained, including files shared with other generations.
END $$;
CREATE OR REPLACE FUNCTION lctx_serving.analyze_generation(id bytea) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE n text; BEGIN
 IF NOT EXISTS(SELECT FROM lctx_serving.generations WHERE generation_digest=id AND state='validating') THEN RAISE EXCEPTION 'not validating'; END IF;
 FOREACH n IN ARRAY ARRAY['retrieval_vectors','retrieval_fragments','retrieval_subjects','retrieval_units','retrieval_receipt','catalog_selection_domains','catalog_associations','catalog_scenarios','catalog_deployments','catalog_spans','catalog_artifacts','catalog_surfaces','catalog_field_links','catalog_configurations','catalog_constructors','catalog_members','catalog_bindings','catalog_signatures','catalog_parameters','catalog_evidence','catalog_types','catalog_type_args','catalog_type_observations','vectors','operations','operation_facets','operation_facet_status','behaviors','assertions','supports'] LOOP
  EXECUTE format('ANALYZE lctx_serving.%I',n);
 END LOOP;
END $$;


CREATE OR REPLACE FUNCTION lctx_serving.check_partitions(id bytea) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE child text; bound text;
BEGIN
 child:='v_'||substr(encode(id,'hex'),1,48);
 SELECT pg_get_expr(c.relpartbound,c.oid) INTO bound FROM pg_class c JOIN pg_inherits i ON i.inhrelid=c.oid
 WHERE c.oid=to_regclass('lctx_serving.'||child) AND i.inhparent='lctx_serving.vectors'::regclass;
 IF bound IS DISTINCT FROM ('FOR VALUES IN ('''||chr(92)||'x'||encode(id,'hex')||''')') THEN RAISE EXCEPTION 'generation partition definition mismatch'; END IF;
END $$;

-- The design-phase reset starts from an empty database. No old-generation adapter survives.
DROP TABLE lctx_serving.operation_text;
DROP TABLE lctx_serving.operation_vectors CASCADE;

-- No callable implementation of the retired fixed-view ANN policy survives this schema.
CREATE OR REPLACE FUNCTION lctx_serving.select_generation(lib text, id bytea, profile bytea) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 PERFORM pg_advisory_xact_lock_shared(lctx_serving.lock_key(id));
 IF NOT EXISTS(SELECT FROM lctx_serving.generations g JOIN lctx_serving.retrieval_profiles p USING(generation_digest)
 WHERE g.generation_digest=id AND g.state='ready' AND g.manifest#>>'{context,library}'=lib AND p.profile_digest=profile
 AND p.policy->>'route'='exact' AND p.policy->>'format'='3') THEN RAISE EXCEPTION 'incompatible ready exact selection'; END IF;
 INSERT INTO lctx_serving.selections VALUES(lib,id,profile) ON CONFLICT(library)
 DO UPDATE SET generation_digest=EXCLUDED.generation_digest,profile_digest=EXCLUDED.profile_digest;
END $$;
DROP FUNCTION lctx_serving.build_hnsw(bytea);
DROP FUNCTION lctx_serving.record_profile(bytea,text,jsonb);
DROP FUNCTION lctx_serving.record_mixed_profile(bytea,text,jsonb);
DROP FUNCTION lctx_serving.index_realization(bytea);
DROP TABLE lctx_serving.profile_admissions;
DROP TABLE lctx_serving.profile_attempts;
ALTER TABLE lctx_serving.retrieval_profiles DROP CONSTRAINT retrieval_profiles_policy_check;
ALTER TABLE lctx_serving.retrieval_profiles ADD CHECK(policy->>'route'='exact' AND policy->>'format'='3');
