-- Generated by lctx-postgres/examples/projection_ddl.rs from cpg-schema.
CREATE TABLE lctx_serving.briefs (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "brief_id" bytea NOT NULL CHECK (octet_length("brief_id") = 16),
 "seed_node_id" bytea NOT NULL CHECK (octet_length("seed_node_id") = 16),
 "access_path" text NOT NULL,
 "title" text NOT NULL,
 "applicable_case" text,
 "documentation_only" boolean NOT NULL,
 "review_state" text NOT NULL CHECK ("review_state" IN ('unreviewed','accepted','rejected','needs_changes')),
 "outcome" text,
 "outcome_status" text NOT NULL CHECK ("outcome_status" IN ('structurally_observed','documented','statistically_derived','fixture_checked','unresolved')),
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,brief_id)
);
ALTER TABLE lctx_serving.briefs ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.briefs FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.briefs FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.briefs FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.briefs FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.briefs TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.briefs TO lctx_importer;
CREATE TABLE lctx_serving.assertions (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "brief_id" bytea NOT NULL CHECK (octet_length("brief_id") = 16),
 "ordinal" bigint NOT NULL,
 "assertion_id" bytea NOT NULL CHECK (octet_length("assertion_id") = 16),
 "kind" text NOT NULL CHECK ("kind" IN ('outcome','public_access','coordinates','parameter','analysis_boundary','related','control','transformed_control','restriction','usage_pattern','handoff','unfollowed_control','applicable_case','implication','doc_link','shared_signature','documented_warning')),
 "section" text NOT NULL,
 "status" text NOT NULL CHECK ("status" IN ('structurally_observed','documented','statistically_derived','fixture_checked','unresolved')),
 "text" text,
 "applicable_case" text,
 "conditions" text,
 "limitations" text,
 "template_version" bigint NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,brief_id,ordinal)
);
ALTER TABLE lctx_serving.assertions ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.assertions FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.assertions FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.assertions FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.assertions FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.assertions TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.assertions TO lctx_importer;
CREATE TABLE lctx_serving.supports (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "assertion_id" bytea NOT NULL CHECK (octet_length("assertion_id") = 16),
 "role" text NOT NULL CHECK ("role" IN ('support','scope')),
 "ordinal" bigint NOT NULL,
 "finding_id" bytea CHECK (octet_length("finding_id") = 16),
 "finding_kind" text CHECK ("finding_kind" IN ('public_alias','direct_delegation','bounded_delegation_path','implementation_boundary','incomplete_resolution','traversal_stop','forwarding','transformed_argument','conditional_raise','handoff','unfollowed_argument','community','centrality','applicable_case','implication','doc_link','community_label','direct_usage')),
 "evidence_id" bytea CHECK (octet_length("evidence_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.supports ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.supports FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.supports FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.supports FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.supports FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.supports TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.supports TO lctx_importer;
CREATE TABLE lctx_serving.support_findings (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "finding_id" bytea NOT NULL CHECK (octet_length("finding_id") = 16),
 "finding_kind" text NOT NULL CHECK ("finding_kind" IN ('public_alias','direct_delegation','bounded_delegation_path','implementation_boundary','incomplete_resolution','traversal_stop','forwarding','transformed_argument','conditional_raise','handoff','unfollowed_argument','community','centrality','applicable_case','implication','doc_link','community_label','direct_usage')),
 "evidence_status" text NOT NULL CHECK ("evidence_status" IN ('structurally_observed','documented','statistically_derived','fixture_checked','unresolved')),
 "subject_node_id" bytea NOT NULL CHECK (octet_length("subject_node_id") = 16),
 "related_node_id" bytea CHECK (octet_length("related_node_id") = 16),
 "invocation_id" bytea NOT NULL CHECK (octet_length("invocation_id") = 16),
 "model_id" text NOT NULL,
 "method" text NOT NULL CHECK ("method" IN ('pass_a_bfs','pass_b_flows','pass_c_handoffs','leiden','community_consensus','pagerank','fca_next_closure','seed_selection','knn','usage_count','pass_b_surface')),
 "parameters" text NOT NULL,
 "completion" text NOT NULL CHECK ("completion" IN ('complete_under_stated_model','partial','not_requested','unavailable','failed')),
 "stop_reason" text CHECK ("stop_reason" IN ('depth_limit','vertex_budget','edge_budget','witness_limit','subsystem_boundary','external_boundary','synthetic_boundary','unresolved_site','concept_budget')),
 "witnesses_omitted" boolean NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,finding_id)
);
ALTER TABLE lctx_serving.support_findings ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.support_findings FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.support_findings FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.support_findings FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.support_findings FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.support_findings TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.support_findings TO lctx_importer;
CREATE TABLE lctx_serving.support_witnesses (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "finding_id" bytea NOT NULL CHECK (octet_length("finding_id") = 16),
 "path" bigint NOT NULL,
 "step" bigint NOT NULL,
 "caller_node_id" bytea NOT NULL CHECK (octet_length("caller_node_id") = 16),
 "call_site_node_id" bytea NOT NULL CHECK (octet_length("call_site_node_id") = 16),
 "callee_node_id" bytea NOT NULL CHECK (octet_length("callee_node_id") = 16),
 "arc_kind" text NOT NULL CHECK ("arc_kind" IN ('call','definition')),
 "modality" text NOT NULL CHECK ("modality" IN ('definite','candidate','potential')),
 "phase" text CHECK ("phase" IN ('call','new','init','decorator','property_get','property_set')),
 "source_fact_id" bytea CHECK (octet_length("source_fact_id") = 16),
 "source_path" text,
 "start_byte" bigint,
 "end_byte" bigint,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,finding_id,path,step)
);
ALTER TABLE lctx_serving.support_witnesses ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.support_witnesses FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.support_witnesses FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.support_witnesses FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.support_witnesses FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.support_witnesses TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.support_witnesses TO lctx_importer;
CREATE TABLE lctx_serving.support_members (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "finding_id" bytea NOT NULL CHECK (octet_length("finding_id") = 16),
 "role" text NOT NULL CHECK ("role" IN ('access_path','source_parameter','value','alias','formal','producer_site','consumer_site','conditional_call','reason','community_member','supporting_site','extent_member','intent_attribute','premise','conclusion','label','handoff_attribute')),
 "ordinal" bigint NOT NULL,
 "node_id" bytea CHECK (octet_length("node_id") = 16),
 "cited_fact_id" bytea CHECK (octet_length("cited_fact_id") = 16),
 "attribute_id" bytea CHECK (octet_length("attribute_id") = 16),
 "fact_table" text,
 "fact_model_id" text,
 "label" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,finding_id,role,ordinal)
);
ALTER TABLE lctx_serving.support_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.support_members FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.support_members FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.support_members FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.support_members FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.support_members TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.support_members TO lctx_importer;
CREATE TABLE lctx_serving.support_attributes (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "attribute_id" bytea NOT NULL CHECK (octet_length("attribute_id") = 16),
 "kind" text NOT NULL CHECK ("kind" IN ('parameter','parameter_type','returns','raises','decorator','calls','hands_off','takes_from')),
 "symbol" text,
 "parameter_kind" text CHECK ("parameter_kind" IN ('positional_only','positional_or_keyword','var_positional','keyword_only','var_keyword')),
 "type_term_id" bytea CHECK (octet_length("type_term_id") = 16),
 "class_module" text,
 "class_key" text,
 "target_node_id" bytea CHECK (octet_length("target_node_id") = 16),
 "modality" text CHECK ("modality" IN ('definite','candidate','potential')),
 "phase" text CHECK ("phase" IN ('call','new','init','decorator','property_get','property_set')),
 "producer_modality" text CHECK ("producer_modality" IN ('definite','candidate','potential')),
 "producer_phase" text CHECK ("producer_phase" IN ('call','new','init','decorator','property_get','property_set')),
 "display" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,attribute_id)
);
ALTER TABLE lctx_serving.support_attributes ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.support_attributes FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.support_attributes FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.support_attributes FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.support_attributes FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.support_attributes TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.support_attributes TO lctx_importer;
CREATE TABLE lctx_serving.support_attribute_incidences (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "finding_id" bytea NOT NULL CHECK (octet_length("finding_id") = 16),
 "incidence_id" bytea NOT NULL CHECK (octet_length("incidence_id") = 16),
 "attribute_id" bytea NOT NULL CHECK (octet_length("attribute_id") = 16),
 "object_node_id" bytea NOT NULL CHECK (octet_length("object_node_id") = 16),
 "source_fact_id" bytea NOT NULL CHECK (octet_length("source_fact_id") = 16),
 "fact_table" text NOT NULL,
 "fact_model_id" text NOT NULL,
 "site_node_id" bytea CHECK (octet_length("site_node_id") = 16),
 "edge_id" bytea CHECK (octet_length("edge_id") = 16),
 "other_site_node_id" bytea CHECK (octet_length("other_site_node_id") = 16),
 "other_edge_id" bytea CHECK (octet_length("other_edge_id") = 16),
 "consumer_formal_id" bytea CHECK (octet_length("consumer_formal_id") = 16),
 "other_fact_id" bytea CHECK (octet_length("other_fact_id") = 16),
 "other_fact_table" text,
 "other_fact_model_id" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,finding_id,incidence_id)
);
ALTER TABLE lctx_serving.support_attribute_incidences ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.support_attribute_incidences FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.support_attribute_incidences FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.support_attribute_incidences FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.support_attribute_incidences FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.support_attribute_incidences TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.support_attribute_incidences TO lctx_importer;
CREATE TABLE lctx_serving.evidence (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "evidence_id" bytea NOT NULL CHECK (octet_length("evidence_id") = 16),
 "kind" text NOT NULL CHECK ("kind" IN ('fact','span','passage','example','fixture_run')),
 "node_id" bytea CHECK (octet_length("node_id") = 16),
 "path" text,
 "start_byte" bigint,
 "end_byte" bigint,
 "text" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,evidence_id)
);
ALTER TABLE lctx_serving.evidence ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.evidence FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.evidence FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.evidence FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.evidence FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.evidence TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.evidence TO lctx_importer;
CREATE TABLE lctx_serving.brief_members (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "brief_id" bytea NOT NULL CHECK (octet_length("brief_id") = 16),
 "access_path" text NOT NULL,
 "export_node_id" bytea NOT NULL CHECK (octet_length("export_node_id") = 16),
 "declaration_node_id" bytea NOT NULL CHECK (octet_length("declaration_node_id") = 16),
 "own" boolean NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.brief_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.brief_members FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.brief_members FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.brief_members FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.brief_members FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.brief_members TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.brief_members TO lctx_importer;
CREATE TABLE lctx_serving.symbol_map (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "symbol" text NOT NULL,
 "brief_id" bytea NOT NULL CHECK (octet_length("brief_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.symbol_map ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.symbol_map FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.symbol_map FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.symbol_map FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.symbol_map FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.symbol_map TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.symbol_map TO lctx_importer;
CREATE TABLE lctx_serving.public_paths (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "node_id" bytea NOT NULL CHECK (octet_length("node_id") = 16),
 "access_path" text NOT NULL,
 "kind" text NOT NULL CHECK ("kind" IN ('function','async_function','class')),
 "own" boolean NOT NULL,
 "preferred" boolean NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,access_path)
);
ALTER TABLE lctx_serving.public_paths ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.public_paths FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.public_paths FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.public_paths FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.public_paths FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.public_paths TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.public_paths TO lctx_importer;
CREATE TABLE lctx_serving.lexical_text (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "brief_id" bytea NOT NULL CHECK (octet_length("brief_id") = 16),
 "text" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,brief_id)
);
ALTER TABLE lctx_serving.lexical_text ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.lexical_text FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.lexical_text FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.lexical_text FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.lexical_text FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.lexical_text TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.lexical_text TO lctx_importer;
CREATE TABLE lctx_serving.embedding_spec (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "spec_hash" bytea NOT NULL CHECK (octet_length("spec_hash") = 32),
 "spec" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,spec_hash)
);
ALTER TABLE lctx_serving.embedding_spec ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.embedding_spec FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.embedding_spec FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.embedding_spec FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.embedding_spec FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.embedding_spec TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.embedding_spec TO lctx_importer;
CREATE TABLE lctx_serving.vectors (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "brief_id" bytea NOT NULL CHECK (octet_length("brief_id") = 16),
 "chunk" bigint NOT NULL,
 "input_hash" bytea NOT NULL CHECK (octet_length("input_hash") = 32),
 "vector" lctx_ext.vector(1024) NOT NULL CHECK (abs(lctx_ext.vector_norm("vector") - 1.0) <= 0.001),
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,brief_id,chunk)
) PARTITION BY LIST (generation_digest);
ALTER TABLE lctx_serving.vectors ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.vectors FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.vectors FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.vectors FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.vectors FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.vectors TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.vectors TO lctx_importer;
CREATE TABLE lctx_serving.operations (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "node_id" bytea NOT NULL CHECK (octet_length("node_id") = 16),
 "access_path" text NOT NULL,
 "kind" text NOT NULL CHECK ("kind" IN ('function','async_function','class')),
 "is_method" boolean NOT NULL,
 "qualified_name" text NOT NULL,
 "module" text NOT NULL,
 "docstring_summary" text,
 "behavior_status" text NOT NULL CHECK ("behavior_status" IN ('established','conditional','refuted_under_model','unknown','not_analyzed')),
 "boundary_reason" text CHECK ("boundary_reason" IN ('native_unavailable','unresolved_target','unsupported_unpacking','ambiguous_binding','unsupported_control_flow','scope_boundary','budget_reached','missing_evidence','not_requested','provider_disagreement','outside_provider_model','syntax_error','undecodable_source','no_source_declaration','unreachable_in_context','variable_origin','dynamic_access','override_dispatch','runtime_unreachable','call_transfer','abstract_body','summary_depth_limit','condition_work_limit','condition_node_limit','condition_atom_limit','summary_pair_work_limit','expression_depth_limit','expression_work_limit','completion_depth_limit','completion_work_limit','summary_proof_limit','default_unavailable','default_stability_unknown','handler_name_cleanup','invocation_argument_limit','action_trigger_unavailable','resource_identity_unavailable','frame_exit_cleanup')),
 "status_reason" text,
 "brief_id" bytea CHECK (octet_length("brief_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,node_id)
);
ALTER TABLE lctx_serving.operations ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.operations FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.operations FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.operations FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.operations FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.operations TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.operations TO lctx_importer;
CREATE TABLE lctx_serving.operation_facets (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "node_id" bytea NOT NULL CHECK (octet_length("node_id") = 16),
 "facet" text NOT NULL CHECK ("facet" IN ('parameter','parameter_type','returns','raises','decorator','async','delegates_to','forwards_to','hands_off_to','takes_from','module','kind','reads_setting')),
 "value" text NOT NULL,
 "verdict" text NOT NULL CHECK ("verdict" IN ('established','conditional','refuted_under_model','unknown','not_analyzed')),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.operation_facets ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.operation_facets FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.operation_facets FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.operation_facets FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.operation_facets FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.operation_facets TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.operation_facets TO lctx_importer;
CREATE TABLE lctx_serving.operation_facet_status (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "node_id" bytea NOT NULL CHECK (octet_length("node_id") = 16),
 "facet" text NOT NULL CHECK ("facet" IN ('parameter','parameter_type','returns','raises','decorator','async','delegates_to','forwards_to','hands_off_to','takes_from','module','kind','reads_setting')),
 "verdict" text NOT NULL CHECK ("verdict" IN ('established','conditional','refuted_under_model','unknown','not_analyzed')),
 "reason" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,node_id,facet)
);
ALTER TABLE lctx_serving.operation_facet_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.operation_facet_status FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.operation_facet_status FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.operation_facet_status FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.operation_facet_status FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.operation_facet_status TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.operation_facet_status TO lctx_importer;
CREATE TABLE lctx_serving.behaviors (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "behavior_id" bytea NOT NULL CHECK (octet_length("behavior_id") = 16),
 "operation_node_id" bytea NOT NULL CHECK (octet_length("operation_node_id") = 16),
 "kind" text NOT NULL CHECK ("kind" IN ('forwards','supplies_literal','raises_when','unfollowed','delegates','hands_off_to','takes_from','derives','stores','reads_setting','is_read','returns','tests')),
 "transfer" text CHECK ("transfer" IN ('identity','derived','call')),
 "condition_scope_node_id" bytea NOT NULL CHECK (octet_length("condition_scope_node_id") = 16),
 "parameter_name" text,
 "callee_node_id" bytea CHECK (octet_length("callee_node_id") = 16),
 "callee" text,
 "target_name" text,
 "value" text,
 "depth" bigint NOT NULL,
 "conditional" boolean NOT NULL,
 "verdict" text NOT NULL CHECK ("verdict" IN ('established','conditional','refuted_under_model','unknown','not_analyzed')),
 "boundary_reason" text CHECK ("boundary_reason" IN ('native_unavailable','unresolved_target','unsupported_unpacking','ambiguous_binding','unsupported_control_flow','scope_boundary','budget_reached','missing_evidence','not_requested','provider_disagreement','outside_provider_model','syntax_error','undecodable_source','no_source_declaration','unreachable_in_context','variable_origin','dynamic_access','override_dispatch','runtime_unreachable','call_transfer','abstract_body','summary_depth_limit','condition_work_limit','condition_node_limit','condition_atom_limit','summary_pair_work_limit','expression_depth_limit','expression_work_limit','completion_depth_limit','completion_work_limit','summary_proof_limit','default_unavailable','default_stability_unknown','handler_name_cleanup','invocation_argument_limit','action_trigger_unavailable','resource_identity_unavailable','frame_exit_cleanup')),
 "condition" text,
 "callee_text" text,
 "phase" text CHECK ("phase" IN ('import','construction','snapshot','per_call')),
 "premise_key" text,
 "occurrences" bigint NOT NULL,
 "path" text,
 "line" bigint,
 "site_text" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,behavior_id)
);
ALTER TABLE lctx_serving.behaviors ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.behaviors FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.behaviors FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.behaviors FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.behaviors FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.behaviors TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.behaviors TO lctx_importer;
CREATE TABLE lctx_serving.conditions (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "condition_id" bytea NOT NULL CHECK (octet_length("condition_id") = 16),
 "root_id" bytea CHECK (octet_length("root_id") = 16),
 "boundary_reason" text,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.conditions ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.conditions FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.conditions FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.conditions FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.conditions FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.conditions TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.conditions TO lctx_importer;
CREATE TABLE lctx_serving.condition_nodes (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "node_id" bytea NOT NULL CHECK (octet_length("node_id") = 16),
 "atom" text NOT NULL,
 "low_id" bytea NOT NULL CHECK (octet_length("low_id") = 16),
 "high_id" bytea NOT NULL CHECK (octet_length("high_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.condition_nodes ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.condition_nodes FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.condition_nodes FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.condition_nodes FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.condition_nodes FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.condition_nodes TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.condition_nodes TO lctx_importer;
CREATE TABLE lctx_serving.analysis_conditions (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "condition_id" bytea NOT NULL CHECK (octet_length("condition_id") = 16),
 "root_id" bytea CHECK (octet_length("root_id") = 16),
 "boundary_reason" text,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.analysis_conditions ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.analysis_conditions FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.analysis_conditions FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.analysis_conditions FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.analysis_conditions FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.analysis_conditions TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.analysis_conditions TO lctx_importer;
CREATE TABLE lctx_serving.analysis_condition_nodes (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "node_id" bytea NOT NULL CHECK (octet_length("node_id") = 16),
 "atom" text NOT NULL,
 "low_id" bytea NOT NULL CHECK (octet_length("low_id") = 16),
 "high_id" bytea NOT NULL CHECK (octet_length("high_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.analysis_condition_nodes ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.analysis_condition_nodes FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.analysis_condition_nodes FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.analysis_condition_nodes FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.analysis_condition_nodes FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.analysis_condition_nodes TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.analysis_condition_nodes TO lctx_importer;
CREATE TABLE lctx_serving.callable_parameters (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "formal_node_id" bytea NOT NULL CHECK (octet_length("formal_node_id") = 16),
 "name" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.callable_parameters ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.callable_parameters FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.callable_parameters FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.callable_parameters FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.callable_parameters FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.callable_parameters TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.callable_parameters TO lctx_importer;
CREATE TABLE lctx_serving.summary_flows (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "summary_id" bytea NOT NULL CHECK (octet_length("summary_id") = 16),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "parameter_node_id" bytea NOT NULL CHECK (octet_length("parameter_node_id") = 16),
 "input_path" text NOT NULL,
 "output_path" text NOT NULL,
 "kind" text NOT NULL CHECK ("kind" IN ('value','transform','constant')),
 "condition_id" bytea NOT NULL CHECK (octet_length("condition_id") = 16),
 "verdict" text NOT NULL CHECK ("verdict" IN ('established','conditional','refuted_under_model','unknown','not_analyzed')),
 "boundary_reason" text CHECK ("boundary_reason" IN ('native_unavailable','unresolved_target','unsupported_unpacking','ambiguous_binding','unsupported_control_flow','scope_boundary','budget_reached','missing_evidence','not_requested','provider_disagreement','outside_provider_model','syntax_error','undecodable_source','no_source_declaration','unreachable_in_context','variable_origin','dynamic_access','override_dispatch','runtime_unreachable','call_transfer','abstract_body','summary_depth_limit','condition_work_limit','condition_node_limit','condition_atom_limit','summary_pair_work_limit','expression_depth_limit','expression_work_limit','completion_depth_limit','completion_work_limit','summary_proof_limit','default_unavailable','default_stability_unknown','handler_name_cleanup','invocation_argument_limit','action_trigger_unavailable','resource_identity_unavailable','frame_exit_cleanup')),
 "source_flow_fact_id" bytea NOT NULL CHECK (octet_length("source_flow_fact_id") = 16),
 "source_origin_id" bytea NOT NULL CHECK (octet_length("source_origin_id") = 16),
 "return_site_fact_id" bytea NOT NULL CHECK (octet_length("return_site_fact_id") = 16),
 "return_region_fact_id" bytea NOT NULL CHECK (octet_length("return_region_fact_id") = 16),
 "approximated" boolean NOT NULL,
 "path_depth" bigint NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.summary_flows ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.summary_flows FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.summary_flows FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.summary_flows FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.summary_flows FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.summary_flows TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.summary_flows TO lctx_importer;
CREATE TABLE lctx_serving.source_context_value_identities (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "identity_id" bytea NOT NULL CHECK (octet_length("identity_id") = 16),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "parameter_node_id" bytea NOT NULL CHECK (octet_length("parameter_node_id") = 16),
 "parameter_name" text NOT NULL,
 "source_flow_fact_id" bytea NOT NULL CHECK (octet_length("source_flow_fact_id") = 16),
 "source_origin_id" bytea NOT NULL CHECK (octet_length("source_origin_id") = 16),
 "condition_id" bytea NOT NULL CHECK (octet_length("condition_id") = 16),
 "return_site_fact_id" bytea NOT NULL CHECK (octet_length("return_site_fact_id") = 16),
 "return_region_fact_id" bytea NOT NULL CHECK (octet_length("return_region_fact_id") = 16),
 "return_condition_id" bytea NOT NULL CHECK (octet_length("return_condition_id") = 16),
 "return_start_byte" bigint NOT NULL,
 "context_site_id" bytea NOT NULL CHECK (octet_length("context_site_id") = 16),
 "argument_fact_id" bytea NOT NULL CHECK (octet_length("argument_fact_id") = 16),
 "argument_expression_fact_id" bytea NOT NULL CHECK (octet_length("argument_expression_fact_id") = 16),
 "argument_reference_fact_id" bytea NOT NULL CHECK (octet_length("argument_reference_fact_id") = 16),
 "argument_resolution_fact_id" bytea NOT NULL CHECK (octet_length("argument_resolution_fact_id") = 16),
 "parameter_binding_fact_id" bytea NOT NULL CHECK (octet_length("parameter_binding_fact_id") = 16),
 "parameter_fact_id" bytea NOT NULL CHECK (octet_length("parameter_fact_id") = 16),
 "target_binding_fact_id" bytea NOT NULL CHECK (octet_length("target_binding_fact_id") = 16),
 "expression_fact_id" bytea NOT NULL CHECK (octet_length("expression_fact_id") = 16),
 "reference_fact_id" bytea NOT NULL CHECK (octet_length("reference_fact_id") = 16),
 "resolution_fact_id" bytea NOT NULL CHECK (octet_length("resolution_fact_id") = 16),
 "scope_fact_id" bytea NOT NULL CHECK (octet_length("scope_fact_id") = 16),
 "module_node_id" bytea NOT NULL CHECK (octet_length("module_node_id") = 16),
 "start_byte" bigint NOT NULL,
 "end_byte" bigint NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_context_value_identities ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_context_value_identities FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_context_value_identities FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_context_value_identities FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_context_value_identities FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_context_value_identities TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_context_value_identities TO lctx_importer;
CREATE TABLE lctx_serving.source_body_completions (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "body_id" bytea NOT NULL CHECK (octet_length("body_id") = 16),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "declaration_fact_id" bytea NOT NULL CHECK (octet_length("declaration_fact_id") = 16),
 "syntax_fact_id" bytea NOT NULL CHECK (octet_length("syntax_fact_id") = 16),
 "kind" text NOT NULL,
 "terminal_fact_id" bytea CHECK (octet_length("terminal_fact_id") = 16),
 "exception" text,
 "reason" text,
 "release_reason" text,
 "function_retainer_required" boolean NOT NULL,
 "runtime_statement_count" bigint NOT NULL,
 "step_count" bigint NOT NULL,
 "steps_digest" bytea NOT NULL CHECK (octet_length("steps_digest") = 32),
 "release_count" bigint NOT NULL,
 "releases_digest" bytea NOT NULL CHECK (octet_length("releases_digest") = 32),
 "work" bigint NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_body_completions ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_body_completions FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_body_completions FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_body_completions FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_body_completions FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_body_completions TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_body_completions TO lctx_importer;
CREATE TABLE lctx_serving.source_body_steps (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "body_id" bytea NOT NULL CHECK (octet_length("body_id") = 16),
 "ordinal" bigint NOT NULL,
 "kind" text NOT NULL,
 "evidence_id" bytea NOT NULL CHECK (octet_length("evidence_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_body_steps ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_body_steps FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_body_steps FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_body_steps FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_body_steps FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_body_steps TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_body_steps TO lctx_importer;
CREATE TABLE lctx_serving.source_body_release_inputs (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "body_id" bytea NOT NULL CHECK (octet_length("body_id") = 16),
 "ordinal" bigint NOT NULL,
 "syntax_fact_id" bytea NOT NULL CHECK (octet_length("syntax_fact_id") = 16),
 "safety" text NOT NULL,
 "proof_offset" bigint NOT NULL,
 "proof_count" bigint NOT NULL,
 "proof_digest" bytea NOT NULL CHECK (octet_length("proof_digest") = 32),
 "evaluation_evidence_id" bytea NOT NULL CHECK (octet_length("evaluation_evidence_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_body_release_inputs ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_body_release_inputs FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_body_release_inputs FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_body_release_inputs FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_body_release_inputs FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_body_release_inputs TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_body_release_inputs TO lctx_importer;
CREATE TABLE lctx_serving.source_call_bindings (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "binding_id" bytea NOT NULL CHECK (octet_length("binding_id") = 16),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "call_node_id" bytea NOT NULL CHECK (octet_length("call_node_id") = 16),
 "call_fact_id" bytea NOT NULL CHECK (octet_length("call_fact_id") = 16),
 "syntax_fact_id" bytea NOT NULL CHECK (octet_length("syntax_fact_id") = 16),
 "callee_node_id" bytea NOT NULL CHECK (octet_length("callee_node_id") = 16),
 "pysa_fact_id" bytea NOT NULL CHECK (octet_length("pysa_fact_id") = 16),
 "signature_fact_id" bytea NOT NULL CHECK (octet_length("signature_fact_id") = 16),
 "declaration_fact_id" bytea NOT NULL CHECK (octet_length("declaration_fact_id") = 16),
 "header_fact_id" bytea NOT NULL CHECK (octet_length("header_fact_id") = 16),
 "statement_fact_id" bytea NOT NULL CHECK (octet_length("statement_fact_id") = 16),
 "binding_fact_id" bytea NOT NULL CHECK (octet_length("binding_fact_id") = 16),
 "reference_fact_id" bytea NOT NULL CHECK (octet_length("reference_fact_id") = 16),
 "resolution_fact_id" bytea NOT NULL CHECK (octet_length("resolution_fact_id") = 16),
 "header_count" bigint NOT NULL,
 "header_digest" bytea NOT NULL CHECK (octet_length("header_digest") = 32),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_call_bindings ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_call_bindings FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_call_bindings FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_call_bindings FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_call_bindings FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_call_bindings TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_call_bindings TO lctx_importer;
CREATE TABLE lctx_serving.source_call_normals (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "certificate_id" bytea NOT NULL CHECK (octet_length("certificate_id") = 16),
 "binding_id" bytea NOT NULL CHECK (octet_length("binding_id") = 16),
 "body_id" bytea NOT NULL CHECK (octet_length("body_id") = 16),
 "body_count" bigint NOT NULL,
 "body_kind" text NOT NULL CHECK ("body_kind" IN ('normal','return','raise','break','continue','unknown')),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_call_normals ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_call_normals FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_call_normals FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_call_normals FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_call_normals FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_call_normals TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_call_normals TO lctx_importer;
CREATE TABLE lctx_serving.source_call_header_steps (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "binding_id" bytea NOT NULL CHECK (octet_length("binding_id") = 16),
 "ordinal" bigint NOT NULL,
 "kind" text NOT NULL CHECK ("kind" IN ('raw_identity','callee_resolution','argument_evaluation','call_target','model_rule','return_exit','call_site','definition_reaching','return_source','callee_summary','finalizer_pass','preceding_call_normal','module_import_binding','module_import_region','callee_condition_link','caller_condition_link','expression_syntax','parameter_binding','completion_statement','local_assignment_binding','statement_condition','handler_class_evidence','definition_header_evidence','default_availability_evidence','default_value_evidence','default_stability_evidence','source_parameter_identity','context_construction','context_entry','context_exit','context_exception_evidence','context_entry_value_identity','model_invocation','source_modeled_identity','model_defaults_available','model_default_formal','model_frame_exit','source_call_normal','source_invocation')),
 "evidence_id" bytea NOT NULL CHECK (octet_length("evidence_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_call_header_steps ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_call_header_steps FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_call_header_steps FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_call_header_steps FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_call_header_steps FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_call_header_steps TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_call_header_steps TO lctx_importer;
CREATE TABLE lctx_serving.model_frame_exits (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "frame_exit_id" bytea NOT NULL CHECK (octet_length("frame_exit_id") = 16),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "call_node_id" bytea NOT NULL CHECK (octet_length("call_node_id") = 16),
 "call_fact_id" bytea NOT NULL CHECK (octet_length("call_fact_id") = 16),
 "syntax_fact_id" bytea NOT NULL CHECK (octet_length("syntax_fact_id") = 16),
 "target_node_id" bytea NOT NULL CHECK (octet_length("target_node_id") = 16),
 "pysa_fact_id" bytea NOT NULL CHECK (octet_length("pysa_fact_id") = 16),
 "model_id" bytea NOT NULL CHECK (octet_length("model_id") = 16),
 "return_parameter" text NOT NULL,
 "return_argument_fact_id" bytea NOT NULL CHECK (octet_length("return_argument_fact_id") = 16),
 "argument_count" bigint NOT NULL,
 "signature_count" bigint NOT NULL,
 "arguments_digest" bytea NOT NULL CHECK (octet_length("arguments_digest") = 32),
 "invocation_count" bigint NOT NULL,
 "invocation_digest" bytea NOT NULL CHECK (octet_length("invocation_digest") = 32),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.model_frame_exits ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.model_frame_exits FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.model_frame_exits FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.model_frame_exits FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.model_frame_exits FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.model_frame_exits TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.model_frame_exits TO lctx_importer;
CREATE TABLE lctx_serving.model_frame_exit_arguments (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "frame_exit_id" bytea NOT NULL CHECK (octet_length("frame_exit_id") = 16),
 "ordinal" bigint NOT NULL,
 "argument_fact_id" bytea NOT NULL CHECK (octet_length("argument_fact_id") = 16),
 "expression_fact_id" bytea NOT NULL CHECK (octet_length("expression_fact_id") = 16),
 "safety" text NOT NULL CHECK ("safety" IN ('closed','caller_retained','unknown')),
 "parameter_name" text NOT NULL,
 "expression_offset" bigint NOT NULL,
 "expression_count" bigint NOT NULL,
 "expression_digest" bytea NOT NULL CHECK (octet_length("expression_digest") = 32),
 "parameters_digest" bytea NOT NULL CHECK (octet_length("parameters_digest") = 32),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.model_frame_exit_arguments ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.model_frame_exit_arguments FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.model_frame_exit_arguments FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.model_frame_exit_arguments FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.model_frame_exit_arguments FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.model_frame_exit_arguments TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.model_frame_exit_arguments TO lctx_importer;
CREATE TABLE lctx_serving.model_frame_exit_steps (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "frame_exit_id" bytea NOT NULL CHECK (octet_length("frame_exit_id") = 16),
 "ordinal" bigint NOT NULL,
 "operand_fact_id" bytea NOT NULL CHECK (octet_length("operand_fact_id") = 16),
 "evidence_id" bytea NOT NULL CHECK (octet_length("evidence_id") = 16),
 "status" text NOT NULL CHECK ("status" IN ('source_operand','literal_normal','unknown','builtin_name_normal','parameter_name_normal','assignment_name_normal','lexical_parameter_normal','closed_expression_normal','composed_expression_normal','pinned_call_normal','callee_entry_normal','source_call_normal')),
 "kind" text NOT NULL CHECK ("kind" IN ('raw_identity','callee_resolution','argument_evaluation','call_target','model_rule','return_exit','call_site','definition_reaching','return_source','callee_summary','finalizer_pass','preceding_call_normal','module_import_binding','module_import_region','callee_condition_link','caller_condition_link','expression_syntax','parameter_binding','completion_statement','local_assignment_binding','statement_condition','handler_class_evidence','definition_header_evidence','default_availability_evidence','default_value_evidence','default_stability_evidence','source_parameter_identity','context_construction','context_entry','context_exit','context_exception_evidence','context_entry_value_identity','model_invocation','source_modeled_identity','model_defaults_available','model_default_formal','model_frame_exit','source_call_normal','source_invocation')),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.model_frame_exit_steps ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.model_frame_exit_steps FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.model_frame_exit_steps FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.model_frame_exit_steps FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.model_frame_exit_steps FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.model_frame_exit_steps TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.model_frame_exit_steps TO lctx_importer;
CREATE TABLE lctx_serving.source_modeled_identities (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "identity_id" bytea NOT NULL CHECK (octet_length("identity_id") = 16),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "parameter_node_id" bytea NOT NULL CHECK (octet_length("parameter_node_id") = 16),
 "source_flow_fact_id" bytea NOT NULL CHECK (octet_length("source_flow_fact_id") = 16),
 "source_origin_id" bytea NOT NULL CHECK (octet_length("source_origin_id") = 16),
 "condition_id" bytea NOT NULL CHECK (octet_length("condition_id") = 16),
 "return_site_fact_id" bytea NOT NULL CHECK (octet_length("return_site_fact_id") = 16),
 "call_fact_id" bytea NOT NULL CHECK (octet_length("call_fact_id") = 16),
 "call_expression_fact_id" bytea NOT NULL CHECK (octet_length("call_expression_fact_id") = 16),
 "source_argument_fact_id" bytea NOT NULL CHECK (octet_length("source_argument_fact_id") = 16),
 "pysa_fact_id" bytea NOT NULL CHECK (octet_length("pysa_fact_id") = 16),
 "model_id" bytea NOT NULL CHECK (octet_length("model_id") = 16),
 "rule_id" bytea NOT NULL CHECK (octet_length("rule_id") = 16),
 "callee_resolution_fact_id" bytea NOT NULL CHECK (octet_length("callee_resolution_fact_id") = 16),
 "expression_fact_id" bytea NOT NULL CHECK (octet_length("expression_fact_id") = 16),
 "reference_fact_id" bytea NOT NULL CHECK (octet_length("reference_fact_id") = 16),
 "resolution_fact_id" bytea NOT NULL CHECK (octet_length("resolution_fact_id") = 16),
 "binding_fact_id" bytea NOT NULL CHECK (octet_length("binding_fact_id") = 16),
 "parameter_fact_id" bytea NOT NULL CHECK (octet_length("parameter_fact_id") = 16),
 "scope_fact_id" bytea NOT NULL CHECK (octet_length("scope_fact_id") = 16),
 "module_node_id" bytea NOT NULL CHECK (octet_length("module_node_id") = 16),
 "start_byte" bigint NOT NULL,
 "end_byte" bigint NOT NULL,
 "model_proof_count" bigint NOT NULL,
 "model_proof_digest" bytea NOT NULL CHECK (octet_length("model_proof_digest") = 32),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_modeled_identities ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_modeled_identities FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_modeled_identities FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_modeled_identities FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_modeled_identities FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_modeled_identities TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_modeled_identities TO lctx_importer;
CREATE TABLE lctx_serving.source_parameter_identities (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "identity_id" bytea NOT NULL CHECK (octet_length("identity_id") = 16),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "parameter_node_id" bytea NOT NULL CHECK (octet_length("parameter_node_id") = 16),
 "source_flow_fact_id" bytea NOT NULL CHECK (octet_length("source_flow_fact_id") = 16),
 "source_origin_id" bytea NOT NULL CHECK (octet_length("source_origin_id") = 16),
 "condition_id" bytea NOT NULL CHECK (octet_length("condition_id") = 16),
 "return_site_fact_id" bytea NOT NULL CHECK (octet_length("return_site_fact_id") = 16),
 "expression_fact_id" bytea NOT NULL CHECK (octet_length("expression_fact_id") = 16),
 "reference_fact_id" bytea NOT NULL CHECK (octet_length("reference_fact_id") = 16),
 "resolution_fact_id" bytea NOT NULL CHECK (octet_length("resolution_fact_id") = 16),
 "binding_fact_id" bytea NOT NULL CHECK (octet_length("binding_fact_id") = 16),
 "parameter_fact_id" bytea NOT NULL CHECK (octet_length("parameter_fact_id") = 16),
 "module_node_id" bytea NOT NULL CHECK (octet_length("module_node_id") = 16),
 "start_byte" bigint NOT NULL,
 "end_byte" bigint NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_parameter_identities ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_parameter_identities FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_parameter_identities FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_parameter_identities FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_parameter_identities FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_parameter_identities TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_parameter_identities TO lctx_importer;
CREATE TABLE lctx_serving.return_completion_certificates (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "certificate_id" bytea NOT NULL CHECK (octet_length("certificate_id") = 16),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "return_site_fact_id" bytea NOT NULL CHECK (octet_length("return_site_fact_id") = 16),
 "entry_condition_id" bytea NOT NULL CHECK (octet_length("entry_condition_id") = 16),
 "exit_condition_id" bytea NOT NULL CHECK (octet_length("exit_condition_id") = 16),
 "entry_count" bigint NOT NULL,
 "exit_count" bigint NOT NULL,
 "entry_digest" bytea NOT NULL CHECK (octet_length("entry_digest") = 32),
 "exit_digest" bytea NOT NULL CHECK (octet_length("exit_digest") = 32),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.return_completion_certificates ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.return_completion_certificates FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.return_completion_certificates FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.return_completion_certificates FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.return_completion_certificates FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.return_completion_certificates TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.return_completion_certificates TO lctx_importer;
CREATE TABLE lctx_serving.model_context_protocols (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "model_id" bytea NOT NULL CHECK (octet_length("model_id") = 16),
 "revision" bigint NOT NULL,
 "class_node_id" bytea NOT NULL CHECK (octet_length("class_node_id") = 16),
 "class_fact_id" bytea NOT NULL CHECK (octet_length("class_fact_id") = 16),
 "class_module_fact_id" bytea NOT NULL CHECK (octet_length("class_module_fact_id") = 16),
 "allocation_node_id" bytea NOT NULL CHECK (octet_length("allocation_node_id") = 16),
 "allocation_fact_id" bytea NOT NULL CHECK (octet_length("allocation_fact_id") = 16),
 "allocation_module_fact_id" bytea NOT NULL CHECK (octet_length("allocation_module_fact_id") = 16),
 "initialization_node_id" bytea NOT NULL CHECK (octet_length("initialization_node_id") = 16),
 "initialization_fact_id" bytea NOT NULL CHECK (octet_length("initialization_fact_id") = 16),
 "initialization_module_fact_id" bytea NOT NULL CHECK (octet_length("initialization_module_fact_id") = 16),
 "entry" text NOT NULL,
 "entry_formal" text,
 "exit" text NOT NULL,
 "exception_formal" text,
 "origin" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.model_context_protocols ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.model_context_protocols FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.model_context_protocols FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.model_context_protocols FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.model_context_protocols FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.model_context_protocols TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.model_context_protocols TO lctx_importer;
CREATE TABLE lctx_serving.source_context_sites (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "site_id" bytea NOT NULL CHECK (octet_length("site_id") = 16),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "with_node_id" bytea NOT NULL CHECK (octet_length("with_node_id") = 16),
 "with_fact_id" bytea NOT NULL CHECK (octet_length("with_fact_id") = 16),
 "item_node_id" bytea NOT NULL CHECK (octet_length("item_node_id") = 16),
 "item_fact_id" bytea NOT NULL CHECK (octet_length("item_fact_id") = 16),
 "item_ordinal" bigint NOT NULL,
 "call_node_id" bytea NOT NULL CHECK (octet_length("call_node_id") = 16),
 "call_fact_id" bytea NOT NULL CHECK (octet_length("call_fact_id") = 16),
 "expression_fact_id" bytea NOT NULL CHECK (octet_length("expression_fact_id") = 16),
 "protocol_id" bytea NOT NULL CHECK (octet_length("protocol_id") = 16),
 "model_id" bytea NOT NULL CHECK (octet_length("model_id") = 16),
 "class_node_id" bytea NOT NULL CHECK (octet_length("class_node_id") = 16),
 "reference_fact_id" bytea NOT NULL CHECK (octet_length("reference_fact_id") = 16),
 "resolution_fact_id" bytea NOT NULL CHECK (octet_length("resolution_fact_id") = 16),
 "import_binding_fact_id" bytea NOT NULL CHECK (octet_length("import_binding_fact_id") = 16),
 "import_region_fact_id" bytea NOT NULL CHECK (octet_length("import_region_fact_id") = 16),
 "import_condition_id" bytea NOT NULL CHECK (octet_length("import_condition_id") = 16),
 "export_fact_id" bytea NOT NULL CHECK (octet_length("export_fact_id") = 16),
 "allocation_call_fact_id" bytea NOT NULL CHECK (octet_length("allocation_call_fact_id") = 16),
 "initialization_call_fact_id" bytea NOT NULL CHECK (octet_length("initialization_call_fact_id") = 16),
 "constructor_valid" boolean NOT NULL,
 "entry_argument_fact_id" bytea CHECK (octet_length("entry_argument_fact_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_context_sites ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_context_sites FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_context_sites FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_context_sites FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_context_sites FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_context_sites TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_context_sites TO lctx_importer;
CREATE TABLE lctx_serving.source_context_arguments (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "site_id" bytea NOT NULL CHECK (octet_length("site_id") = 16),
 "ordinal" bigint NOT NULL,
 "argument_fact_id" bytea NOT NULL CHECK (octet_length("argument_fact_id") = 16),
 "expression_fact_id" bytea NOT NULL CHECK (octet_length("expression_fact_id") = 16),
 "parameter_fact_id" bytea CHECK (octet_length("parameter_fact_id") = 16),
 "exception_class_node_id" bytea CHECK (octet_length("exception_class_node_id") = 16),
 "exception_class_fact_id" bytea CHECK (octet_length("exception_class_fact_id") = 16),
 "exception_module_fact_id" bytea CHECK (octet_length("exception_module_fact_id") = 16),
 "reference_fact_id" bytea CHECK (octet_length("reference_fact_id") = 16),
 "resolution_fact_id" bytea CHECK (octet_length("resolution_fact_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.source_context_arguments ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.source_context_arguments FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.source_context_arguments FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.source_context_arguments FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.source_context_arguments FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.source_context_arguments TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.source_context_arguments TO lctx_importer;
CREATE TABLE lctx_serving.summary_flow_steps (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "summary_id" bytea NOT NULL CHECK (octet_length("summary_id") = 16),
 "ordinal" bigint NOT NULL,
 "kind" text NOT NULL CHECK ("kind" IN ('raw_identity','callee_resolution','argument_evaluation','call_target','model_rule','return_exit','call_site','definition_reaching','return_source','callee_summary','finalizer_pass','preceding_call_normal','module_import_binding','module_import_region','callee_condition_link','caller_condition_link','expression_syntax','parameter_binding','completion_statement','local_assignment_binding','statement_condition','handler_class_evidence','definition_header_evidence','default_availability_evidence','default_value_evidence','default_stability_evidence','source_parameter_identity','context_construction','context_entry','context_exit','context_exception_evidence','context_entry_value_identity','model_invocation','source_modeled_identity','model_defaults_available','model_default_formal','model_frame_exit','source_call_normal','source_invocation')),
 "evidence_id" bytea NOT NULL CHECK (octet_length("evidence_id") = 16),
 "condition_id" bytea NOT NULL CHECK (octet_length("condition_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.summary_flow_steps ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.summary_flow_steps FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.summary_flow_steps FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.summary_flow_steps FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.summary_flow_steps FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.summary_flow_steps TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.summary_flow_steps TO lctx_importer;
CREATE TABLE lctx_serving.summary_boundaries (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "function_node_id" bytea NOT NULL CHECK (octet_length("function_node_id") = 16),
 "parameter_node_id" bytea NOT NULL CHECK (octet_length("parameter_node_id") = 16),
 "source_flow_fact_id" bytea NOT NULL CHECK (octet_length("source_flow_fact_id") = 16),
 "source_origin_id" bytea NOT NULL CHECK (octet_length("source_origin_id") = 16),
 "condition_id" bytea NOT NULL CHECK (octet_length("condition_id") = 16),
 "reason" text NOT NULL CHECK ("reason" IN ('native_unavailable','unresolved_target','unsupported_unpacking','ambiguous_binding','unsupported_control_flow','scope_boundary','budget_reached','missing_evidence','not_requested','provider_disagreement','outside_provider_model','syntax_error','undecodable_source','no_source_declaration','unreachable_in_context','variable_origin','dynamic_access','override_dispatch','runtime_unreachable','call_transfer','abstract_body','summary_depth_limit','condition_work_limit','condition_node_limit','condition_atom_limit','summary_pair_work_limit','expression_depth_limit','expression_work_limit','completion_depth_limit','completion_work_limit','summary_proof_limit','default_unavailable','default_stability_unknown','handler_name_cleanup','invocation_argument_limit','action_trigger_unavailable','resource_identity_unavailable','frame_exit_cleanup')),
 "local_through_call" boolean NOT NULL,
 "upstream_through_call" boolean NOT NULL,
 "raw_approximated" boolean NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.summary_boundaries ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.summary_boundaries FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.summary_boundaries FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.summary_boundaries FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.summary_boundaries FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.summary_boundaries TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.summary_boundaries TO lctx_importer;
CREATE TABLE lctx_serving.behavior_discharges (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "behavior_id" bytea NOT NULL CHECK (octet_length("behavior_id") = 16),
 "origin_id" bytea NOT NULL CHECK (octet_length("origin_id") = 16),
 "proof_kind" text NOT NULL CHECK ("proof_kind" IN ('caller_return_summary')),
 "decision" text NOT NULL CHECK ("decision" IN ('proved','open')),
 "summary_id" bytea CHECK (octet_length("summary_id") = 16),
 "reason" text CHECK ("reason" IN ('native_unavailable','unresolved_target','unsupported_unpacking','ambiguous_binding','unsupported_control_flow','scope_boundary','budget_reached','missing_evidence','not_requested','provider_disagreement','outside_provider_model','syntax_error','undecodable_source','no_source_declaration','unreachable_in_context','variable_origin','dynamic_access','override_dispatch','runtime_unreachable','call_transfer','abstract_body','summary_depth_limit','condition_work_limit','condition_node_limit','condition_atom_limit','summary_pair_work_limit','expression_depth_limit','expression_work_limit','completion_depth_limit','completion_work_limit','summary_proof_limit','default_unavailable','default_stability_unknown','handler_name_cleanup','invocation_argument_limit','action_trigger_unavailable','resource_identity_unavailable','frame_exit_cleanup')),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.behavior_discharges ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.behavior_discharges FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.behavior_discharges FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.behavior_discharges FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.behavior_discharges FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.behavior_discharges TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.behavior_discharges TO lctx_importer;
CREATE TABLE lctx_serving.flow_test_leaves (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "fact_id" bytea NOT NULL CHECK (octet_length("fact_id") = 16),
 "module_node_id" bytea NOT NULL CHECK (octet_length("module_node_id") = 16),
 "condition_id" bytea NOT NULL CHECK (octet_length("condition_id") = 16),
 "atom_id" bytea NOT NULL CHECK (octet_length("atom_id") = 16),
 "atom" text NOT NULL,
 "path" text,
 "leaf_start_byte" bigint NOT NULL,
 "leaf_end_byte" bigint NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.flow_test_leaves ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.flow_test_leaves FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.flow_test_leaves FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.flow_test_leaves FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.flow_test_leaves FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.flow_test_leaves TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.flow_test_leaves TO lctx_importer;
CREATE TABLE lctx_serving.flow_test_value_links (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "link_id" bytea NOT NULL CHECK (octet_length("link_id") = 16),
 "operation_node_id" bytea NOT NULL CHECK (octet_length("operation_node_id") = 16),
 "formal_node_id" bytea NOT NULL CHECK (octet_length("formal_node_id") = 16),
 "module_node_id" bytea NOT NULL CHECK (octet_length("module_node_id") = 16),
 "leaf_fact_id" bytea NOT NULL CHECK (octet_length("leaf_fact_id") = 16),
 "atom_id" bytea NOT NULL CHECK (octet_length("atom_id") = 16),
 "condition_id" bytea NOT NULL CHECK (octet_length("condition_id") = 16),
 "place" text NOT NULL,
 "origin" text NOT NULL CHECK ("origin" IN ('direct_parameter_reach_no_effect','resolved_builtin_type_operand','stable_after_exact_type_guard')),
 "effect_model_digest" bytea NOT NULL CHECK (octet_length("effect_model_digest") = 32),
 "use_id" bytea NOT NULL CHECK (octet_length("use_id") = 16),
 "use_fact_id" bytea NOT NULL CHECK (octet_length("use_fact_id") = 16),
 "reaching_fact_id" bytea NOT NULL CHECK (octet_length("reaching_fact_id") = 16),
 "definition_fact_id" bytea NOT NULL CHECK (octet_length("definition_fact_id") = 16),
 "stability_origin_id" bytea CHECK (octet_length("stability_origin_id") = 16),
 "stability_condition_id" bytea CHECK (octet_length("stability_condition_id") = 16),
 "path" text,
 "operand_start_byte" bigint NOT NULL,
 "operand_end_byte" bigint NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.flow_test_value_links ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.flow_test_value_links FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.flow_test_value_links FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.flow_test_value_links FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.flow_test_value_links FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.flow_test_value_links TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.flow_test_value_links TO lctx_importer;
CREATE TABLE lctx_serving.singletons (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "global" text NOT NULL,
 "class_node_id" bytea NOT NULL CHECK (octet_length("class_node_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.singletons ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.singletons FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.singletons FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.singletons FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.singletons FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.singletons TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.singletons TO lctx_importer;
CREATE TABLE lctx_serving.ambient_reads (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "global" text NOT NULL,
 "field" text NOT NULL,
 "reader_node_id" bytea CHECK (octet_length("reader_node_id") = 16),
 "reader" text,
 "phase" text NOT NULL CHECK ("phase" IN ('import','construction','snapshot','per_call')),
 "path" text,
 "line" bigint NOT NULL,
 "start_byte" bigint NOT NULL,
 "spelled" text NOT NULL,
 "condition" text,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.ambient_reads ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.ambient_reads FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.ambient_reads FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.ambient_reads FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.ambient_reads FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.ambient_reads TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.ambient_reads TO lctx_importer;
CREATE TABLE lctx_serving.place_claims (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "place_key" text NOT NULL,
 "kind" text NOT NULL,
 "subject_node_id" bytea CHECK (octet_length("subject_node_id") = 16),
 "holds" boolean NOT NULL,
 "boundary_reason" text,
 "reason" text,
 PRIMARY KEY (generation_digest,row_ordinal)
);
ALTER TABLE lctx_serving.place_claims ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.place_claims FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.place_claims FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.place_claims FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.place_claims FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.place_claims TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.place_claims TO lctx_importer;
CREATE TABLE lctx_serving.operation_text (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "node_id" bytea NOT NULL CHECK (octet_length("node_id") = 16),
 "text" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,node_id)
);
ALTER TABLE lctx_serving.operation_text ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.operation_text FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.operation_text FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.operation_text FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.operation_text FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.operation_text TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.operation_text TO lctx_importer;
CREATE TABLE lctx_serving.operation_vectors (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "node_id" bytea NOT NULL CHECK (octet_length("node_id") = 16),
 "embedding_view" text NOT NULL CHECK ("embedding_view" IN ('signature_doc','source_body')),
 "chunk" bigint NOT NULL,
 "input_hash" bytea NOT NULL CHECK (octet_length("input_hash") = 32),
 "vector" lctx_ext.vector(1024) NOT NULL CHECK (abs(lctx_ext.vector_norm("vector") - 1.0) <= 0.001),
 PRIMARY KEY (generation_digest,embedding_view,row_ordinal),
 UNIQUE (generation_digest,node_id,embedding_view,chunk)
) PARTITION BY LIST (generation_digest);
ALTER TABLE lctx_serving.operation_vectors ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.operation_vectors FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.operation_vectors FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.operation_vectors FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.operation_vectors FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.operation_vectors TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.operation_vectors TO lctx_importer;
ALTER TABLE lctx_serving.assertions ADD FOREIGN KEY (generation_digest,brief_id) REFERENCES lctx_serving.briefs(generation_digest,brief_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.brief_members ADD FOREIGN KEY (generation_digest,brief_id) REFERENCES lctx_serving.briefs(generation_digest,brief_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.symbol_map ADD FOREIGN KEY (generation_digest,brief_id) REFERENCES lctx_serving.briefs(generation_digest,brief_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.lexical_text ADD FOREIGN KEY (generation_digest,brief_id) REFERENCES lctx_serving.briefs(generation_digest,brief_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.vectors ADD FOREIGN KEY (generation_digest,brief_id) REFERENCES lctx_serving.briefs(generation_digest,brief_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.supports ADD FOREIGN KEY (generation_digest,finding_id) REFERENCES lctx_serving.support_findings(generation_digest,finding_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.supports ADD FOREIGN KEY (generation_digest,evidence_id) REFERENCES lctx_serving.evidence(generation_digest,evidence_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.support_witnesses ADD FOREIGN KEY (generation_digest,finding_id) REFERENCES lctx_serving.support_findings(generation_digest,finding_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.support_members ADD FOREIGN KEY (generation_digest,finding_id) REFERENCES lctx_serving.support_findings(generation_digest,finding_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.support_members ADD FOREIGN KEY (generation_digest,attribute_id) REFERENCES lctx_serving.support_attributes(generation_digest,attribute_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.support_attribute_incidences ADD FOREIGN KEY (generation_digest,finding_id) REFERENCES lctx_serving.support_findings(generation_digest,finding_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.support_attribute_incidences ADD FOREIGN KEY (generation_digest,attribute_id) REFERENCES lctx_serving.support_attributes(generation_digest,attribute_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.public_paths ADD FOREIGN KEY (generation_digest,node_id) REFERENCES lctx_serving.operations(generation_digest,node_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.operation_facets ADD FOREIGN KEY (generation_digest,node_id) REFERENCES lctx_serving.operations(generation_digest,node_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.operation_facet_status ADD FOREIGN KEY (generation_digest,node_id) REFERENCES lctx_serving.operations(generation_digest,node_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.operation_text ADD FOREIGN KEY (generation_digest,node_id) REFERENCES lctx_serving.operations(generation_digest,node_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.operation_vectors ADD FOREIGN KEY (generation_digest,node_id) REFERENCES lctx_serving.operations(generation_digest,node_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.behaviors ADD FOREIGN KEY (generation_digest,operation_node_id) REFERENCES lctx_serving.operations(generation_digest,node_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.operations ADD FOREIGN KEY (generation_digest,brief_id) REFERENCES lctx_serving.briefs(generation_digest,brief_id) DEFERRABLE INITIALLY DEFERRED;
