-- ADR-0072: mandatory API catalog; optional semantic artifact closure.
-- Existing migrations and retained generations remain immutable.
DO $$ DECLARE c record; BEGIN
 FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='lctx_serving.generations'::regclass
 AND contype='c' AND (pg_get_constraintdef(oid) LIKE '%bundle_format%' OR pg_get_constraintdef(oid) LIKE '%''format''%')
 LOOP EXECUTE format('ALTER TABLE lctx_serving.generations DROP CONSTRAINT %I',c.conname); END LOOP;
END $$;
ALTER TABLE lctx_serving.generations ADD CHECK
 (((manifest->>'format')::int,(manifest->>'bundle_format')::int) IN ((1,11),(2,12),(3,13)));
-- Generated by lctx-postgres/examples/projection_ddl.rs from cpg-schema.
CREATE TABLE lctx_serving.catalog_members (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "member_id" bytea NOT NULL CHECK (octet_length("member_id") = 16),
 "access_path" text NOT NULL,
 "owner_path" text NOT NULL,
 "operation_node_id" bytea CHECK (octet_length("operation_node_id") = 16),
 "kind" text NOT NULL,
 "resolution" text NOT NULL CHECK ("resolution" IN ('unresolved','source_known_effective_unresolved')),
 "brief_status" text NOT NULL CHECK ("brief_status" IN ('not_requested','not_selected','skipped','available')),
 "brief_reason" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,member_id)
);
ALTER TABLE lctx_serving.catalog_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_members FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_members FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_members FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_members FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_members TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_members TO lctx_importer;
CREATE TABLE lctx_serving.catalog_bindings (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "member_id" bytea NOT NULL CHECK (octet_length("member_id") = 16),
 "binding_id" bytea NOT NULL CHECK (octet_length("binding_id") = 16),
 "declaration_node_id" bytea CHECK (octet_length("declaration_node_id") = 16),
 "source_fact_id" bytea NOT NULL CHECK (octet_length("source_fact_id") = 16),
 "role" text NOT NULL CHECK ("role" IN ('selected_source','overload','shadowed_source','stub_source','source_alternative','provider_public_observation')),
 "own" boolean NOT NULL,
 "defining_path" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,member_id,binding_id)
);
ALTER TABLE lctx_serving.catalog_bindings ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_bindings FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_bindings FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_bindings FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_bindings FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_bindings TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_bindings TO lctx_importer;
CREATE TABLE lctx_serving.catalog_signatures (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "signature_id" bytea NOT NULL CHECK (octet_length("signature_id") = 16),
 "callable_node_id" bytea NOT NULL CHECK (octet_length("callable_node_id") = 16),
 "declaration_node_id" bytea CHECK (octet_length("declaration_node_id") = 16),
 "constructor_class_id" bytea CHECK (octet_length("constructor_class_id") = 16),
 "module_node_id" bytea NOT NULL CHECK (octet_length("module_node_id") = 16),
 "function_key" text,
 "signature_index" bigint,
 "role" text NOT NULL CHECK ("role" IN ('source','overload','provider_constructor')),
 "form" text NOT NULL CHECK ("form" IN ('source_list','list','ellipsis','param_spec')),
 "source_fact_id" bytea NOT NULL CHECK (octet_length("source_fact_id") = 16),
 "reason" text,
 "return_annotation" text,
 "docstring" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,signature_id)
);
ALTER TABLE lctx_serving.catalog_signatures ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_signatures FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_signatures FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_signatures FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_signatures FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_signatures TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_signatures TO lctx_importer;
CREATE TABLE lctx_serving.catalog_parameters (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "signature_id" bytea NOT NULL CHECK (octet_length("signature_id") = 16),
 "ordinal" bigint NOT NULL,
 "formal_node_id" bytea CHECK (octet_length("formal_node_id") = 16),
 "name" text,
 "kind" text CHECK ("kind" IN ('positional_only','positional_or_keyword','var_positional','keyword_only','var_keyword')),
 "required" boolean,
 "syntax_fact_id" bytea CHECK (octet_length("syntax_fact_id") = 16),
 "semantics_fact_id" bytea CHECK (octet_length("semantics_fact_id") = 16),
 "provider_name" text,
 "provider_kind" text CHECK ("provider_kind" IN ('positional_only','positional_or_keyword','var_positional','keyword_only','var_keyword')),
 "annotation_text" text,
 "provider_annotation" text,
 "default_state" text NOT NULL CHECK ("default_state" IN ('absent','literal_none','literal','source_expression','optional_expression_unavailable','unknown')),
 "default_text" text,
 "literal_json" text,
 "documentation" text,
 "reason" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,signature_id,ordinal)
);
ALTER TABLE lctx_serving.catalog_parameters ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_parameters FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_parameters FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_parameters FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_parameters FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_parameters TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_parameters TO lctx_importer;
CREATE TABLE lctx_serving.catalog_evidence (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "evidence_id" bytea NOT NULL CHECK (octet_length("evidence_id") = 16),
 "subject_node_id" bytea NOT NULL CHECK (octet_length("subject_node_id") = 16),
 "source_fact_id" bytea NOT NULL CHECK (octet_length("source_fact_id") = 16),
 "source_digest" bytea NOT NULL CHECK (octet_length("source_digest") = 32),
 "path" text NOT NULL,
 "start_byte" bigint NOT NULL,
 "end_byte" bigint NOT NULL,
 "role" text NOT NULL CHECK ("role" IN ('declares')),
 "text" text NOT NULL,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,evidence_id)
);
ALTER TABLE lctx_serving.catalog_evidence ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_evidence FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_evidence FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_evidence FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_evidence FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_evidence TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_evidence TO lctx_importer;
CREATE TABLE lctx_serving.catalog_types (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "term_id" bytea NOT NULL CHECK (octet_length("term_id") = 16),
 "source_fact_id" bytea NOT NULL CHECK (octet_length("source_fact_id") = 16),
 "kind" text NOT NULL CHECK ("kind" IN ('class_instance','class_object','type_of','typed_dict','union','intersection','callable','overload','bound_method','generic','tuple','literal','type_var','param_spec','type_var_tuple','module','any','never','none','type_alias','self_type','annotated','unpack','type_guard','param_list','special_form','other','truncated')),
 "display" text NOT NULL,
 "detail" text,
 "class_module" text,
 "class_key" text,
 "variable" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,term_id)
);
ALTER TABLE lctx_serving.catalog_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_types FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_types FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_types FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_types FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_types TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_types TO lctx_importer;
CREATE TABLE lctx_serving.catalog_type_args (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "parent_term_id" bytea NOT NULL CHECK (octet_length("parent_term_id") = 16),
 "role" text NOT NULL CHECK ("role" IN ('argument','member','parameter','return','element','variadic','signature','receiver','function','type_parameter','target','param_spec','bound','constraint','default')),
 "ordinal" bigint NOT NULL,
 "child_term_id" bytea NOT NULL CHECK (octet_length("child_term_id") = 16),
 "source_fact_id" bytea NOT NULL CHECK (octet_length("source_fact_id") = 16),
 "name" text,
 "parameter_kind" text CHECK ("parameter_kind" IN ('positional_only','positional_or_keyword','var_positional','keyword_only','var_keyword')),
 "required" boolean,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,parent_term_id,role,ordinal)
);
ALTER TABLE lctx_serving.catalog_type_args ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_type_args FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_type_args FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_type_args FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_type_args FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_type_args TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_type_args TO lctx_importer;
CREATE TABLE lctx_serving.catalog_type_observations (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "source_fact_id" bytea NOT NULL CHECK (octet_length("source_fact_id") = 16),
 "subject_node_id" bytea NOT NULL CHECK (octet_length("subject_node_id") = 16),
 "role" text NOT NULL CHECK ("role" IN ('parameter','return','call_result','argument','raised')),
 "declared" boolean NOT NULL,
 "term_id" bytea NOT NULL CHECK (octet_length("term_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,source_fact_id)
);
ALTER TABLE lctx_serving.catalog_type_observations ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_type_observations FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_type_observations FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_type_observations FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_type_observations FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_type_observations TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_type_observations TO lctx_importer;
CREATE TABLE lctx_serving.catalog_constructors (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "class_node_id" bytea NOT NULL CHECK (octet_length("class_node_id") = 16),
 "signature_id" bytea NOT NULL CHECK (octet_length("signature_id") = 16),
 "own" boolean NOT NULL,
 "ancestry_fact_id" bytea CHECK (octet_length("ancestry_fact_id") = 16),
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,class_node_id,signature_id)
);
ALTER TABLE lctx_serving.catalog_constructors ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_constructors FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_constructors FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_constructors FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_constructors FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_constructors TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_constructors TO lctx_importer;
ALTER TABLE lctx_serving.catalog_members ADD FOREIGN KEY (generation_digest,operation_node_id) REFERENCES lctx_serving.operations(generation_digest,node_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.catalog_bindings ADD FOREIGN KEY (generation_digest,member_id) REFERENCES lctx_serving.catalog_members(generation_digest,member_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.catalog_constructors ADD FOREIGN KEY (generation_digest,signature_id) REFERENCES lctx_serving.catalog_signatures(generation_digest,signature_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.catalog_parameters ADD FOREIGN KEY (generation_digest,signature_id) REFERENCES lctx_serving.catalog_signatures(generation_digest,signature_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.catalog_type_observations ADD FOREIGN KEY (generation_digest,term_id) REFERENCES lctx_serving.catalog_types(generation_digest,term_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.catalog_type_args ADD FOREIGN KEY (generation_digest,parent_term_id) REFERENCES lctx_serving.catalog_types(generation_digest,term_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.catalog_type_args ADD FOREIGN KEY (generation_digest,child_term_id) REFERENCES lctx_serving.catalog_types(generation_digest,term_id) DEFERRABLE INITIALLY DEFERRED;

CREATE OR REPLACE FUNCTION lctx_serving.prepare_generation(doc text, transport bytea) RETURNS bigint
 LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE id bytea:=sha256(convert_to(doc,'UTF8')); prior text; a bigint; n text; child text; v text;
BEGIN
 IF (doc::jsonb->>'format')::int IS DISTINCT FROM 3 OR (doc::jsonb->>'bundle_format')::int IS DISTINCT FROM 13
 OR doc::jsonb#>'{capabilities,catalog}' IS DISTINCT FROM 'true'::jsonb
 OR coalesce(doc::jsonb#>>'{context,library}','')='' THEN RAISE EXCEPTION 'unsupported projection context'; END IF;
 PERFORM pg_advisory_xact_lock(lctx_serving.lock_key(id));
 INSERT INTO lctx_serving.generations(generation_digest,canonical_manifest) VALUES(id,doc) ON CONFLICT DO NOTHING;
 SELECT canonical_manifest INTO prior FROM lctx_serving.generations WHERE generation_digest=id;
 IF prior<>doc THEN RAISE EXCEPTION 'projection identity conflict'; END IF;
 IF EXISTS(SELECT FROM lctx_serving.generations WHERE generation_digest=id AND state='failed') THEN RAISE EXCEPTION 'terminal projection failure'; END IF;
 INSERT INTO lctx_serving.import_recipes VALUES(id,1,transport) ON CONFLICT DO NOTHING;
 IF EXISTS(SELECT FROM lctx_serving.import_recipes WHERE generation_digest=id AND transport_digest<>transport)
 AND NOT lctx_serving.is_ready(id) THEN RAISE EXCEPTION 'frozen transport conflict'; END IF;
 UPDATE lctx_serving.import_attempts SET outcome='interrupted',finished_at=clock_timestamp(),failure_code='owner_disconnected'
 WHERE generation_digest=id AND outcome='running';
 INSERT INTO lctx_serving.import_attempts(generation_digest) VALUES(id) RETURNING attempt_id INTO a;
 IF NOT lctx_serving.is_ready(id) THEN
  FOREACH n IN ARRAY ARRAY['vectors','operation_vectors'] LOOP
   child:=CASE n WHEN 'vectors' THEN 'v_' ELSE 'o_' END || substr(encode(id,'hex'),1,48);
   IF to_regclass('lctx_serving.'||child) IS NULL THEN
    EXECUTE format('CREATE TABLE lctx_serving.%I PARTITION OF lctx_serving.%I FOR VALUES IN (%L)%s',child,n,id,
     CASE n WHEN 'operation_vectors' THEN ' PARTITION BY LIST (embedding_view)' ELSE '' END);
    IF n='operation_vectors' THEN
     FOREACH v IN ARRAY ARRAY['signature_doc','source_body'] LOOP
      EXECUTE format('CREATE TABLE lctx_serving.%I PARTITION OF lctx_serving.%I FOR VALUES IN (%L)',child||CASE v WHEN 'signature_doc' THEN '_d' ELSE '_s' END,child,v);
     END LOOP;
    END IF;
   ELSIF NOT EXISTS(SELECT FROM pg_class WHERE oid=to_regclass('lctx_serving.'||child)
      AND pg_get_expr(relpartbound,oid) LIKE '%'||encode(id,'hex')||'%') THEN
    RAISE EXCEPTION 'partition identity conflict';
   END IF;
  END LOOP;
 END IF;
 PERFORM lctx_serving.check_partitions(id);
 RETURN a;
END $$;
CREATE OR REPLACE FUNCTION lctx_serving.cleanup_generation(id bytea) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE n text; phase text; BEGIN
 IF NOT pg_try_advisory_xact_lock(lctx_serving.lock_key(id)) THEN RAISE EXCEPTION 'generation import is active'; END IF;
 SELECT state INTO phase FROM lctx_serving.generations WHERE generation_digest=id FOR UPDATE;
 IF phase IS NULL OR phase='ready' OR EXISTS(SELECT FROM lctx_serving.selections WHERE generation_digest=id) THEN RAISE EXCEPTION 'generation cannot be cleaned'; END IF;
 SET CONSTRAINTS ALL DEFERRED;
 FOREACH n IN ARRAY ARRAY['catalog_constructors','catalog_type_observations','catalog_type_args','catalog_types','catalog_parameters','catalog_signatures','catalog_evidence','catalog_bindings','catalog_members','briefs','assertions','supports','support_findings','support_witnesses','support_members','support_attributes','support_attribute_incidences','evidence','brief_members','symbol_map','public_paths','lexical_text','embedding_spec','vectors','operations','operation_facets','operation_facet_status','behaviors','conditions','condition_nodes','analysis_conditions','analysis_condition_nodes','callable_parameters','summary_flows','source_context_value_identities','source_body_completions','source_body_steps','source_body_release_inputs','source_call_bindings','source_call_normals','source_call_header_steps','model_frame_exits','model_frame_exit_arguments','model_frame_exit_steps','source_modeled_identities','source_parameter_identities','return_completion_certificates','model_context_protocols','source_context_sites','source_context_arguments','summary_flow_steps','summary_boundaries','behavior_discharges','flow_test_leaves','flow_test_value_links','singletons','ambient_reads','place_claims','operation_text','operation_vectors'] LOOP
  EXECUTE format('DELETE FROM lctx_serving.%I WHERE generation_digest=$1',n) USING id;
 END LOOP;
 DELETE FROM lctx_serving.artifact_locations WHERE generation_digest=id;
 DELETE FROM lctx_serving.artifacts WHERE generation_digest=id;
 IF phase<>'failed' THEN UPDATE lctx_serving.generations SET state='failed' WHERE generation_digest=id; END IF;
 UPDATE lctx_serving.import_attempts SET outcome='interrupted',finished_at=clock_timestamp(),failure_code='owned_cleanup' WHERE generation_digest=id AND outcome='running';
 -- Keep the manifest, transport, attempts and batch receipts as terminal diagnostic history.
 -- Content-addressed files remain retained, including files shared with other generations.
END $$;
CREATE OR REPLACE FUNCTION lctx_serving.analyze_generation(id bytea) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE n text; BEGIN
 IF NOT EXISTS(SELECT FROM lctx_serving.generations WHERE generation_digest=id AND state='validating') THEN RAISE EXCEPTION 'not validating'; END IF;
 FOREACH n IN ARRAY ARRAY['catalog_constructors','catalog_members','catalog_bindings','catalog_signatures','catalog_parameters','catalog_evidence','catalog_types','catalog_type_args','catalog_type_observations','vectors','operation_vectors','operations','operation_facets','operation_facet_status','behaviors','assertions','supports'] LOOP
  EXECUTE format('ANALYZE lctx_serving.%I',n);
 END LOOP;
END $$;
CREATE INDEX catalog_member_path ON lctx_serving.catalog_members(generation_digest,access_path COLLATE "C");
CREATE INDEX catalog_member_operation ON lctx_serving.catalog_members(generation_digest,operation_node_id);
CREATE INDEX catalog_binding_declaration ON lctx_serving.catalog_bindings(generation_digest,declaration_node_id);
CREATE INDEX catalog_signature_callable ON lctx_serving.catalog_signatures(generation_digest,callable_node_id);
CREATE INDEX catalog_signature_constructor ON lctx_serving.catalog_signatures(generation_digest,constructor_class_id);
CREATE INDEX catalog_evidence_subject ON lctx_serving.catalog_evidence(generation_digest,subject_node_id);
CREATE INDEX catalog_observation_subject ON lctx_serving.catalog_type_observations(generation_digest,subject_node_id);
