-- ADR-0074: source-backed surface and field associations. Retained generations are immutable.
DO $$ DECLARE c record; BEGIN
 FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='lctx_serving.generations'::regclass
 AND contype='c' AND (pg_get_constraintdef(oid) LIKE '%bundle_format%' OR pg_get_constraintdef(oid) LIKE '%''format''%')
 LOOP EXECUTE format('ALTER TABLE lctx_serving.generations DROP CONSTRAINT %I',c.conname); END LOOP;
END $$;
ALTER TABLE lctx_serving.generations ADD CHECK
 (((manifest->>'format')::int,(manifest->>'bundle_format')::int) IN ((1,11),(2,12),(3,13),(4,14)));
DO $$ DECLARE c record; BEGIN
 FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='lctx_serving.catalog_evidence'::regclass
 AND contype='c' AND pg_get_constraintdef(oid) LIKE '%role%'
 LOOP EXECUTE format('ALTER TABLE lctx_serving.catalog_evidence DROP CONSTRAINT %I',c.conname); END LOOP;
END $$;
ALTER TABLE lctx_serving.catalog_evidence ADD CHECK (role IN ('declares','surface','configuration','reader'));
-- Generated by lctx-postgres/examples/projection_ddl.rs from cpg-schema.
CREATE TABLE lctx_serving.catalog_surfaces (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "declaration_node_id" bytea NOT NULL CHECK (octet_length("declaration_node_id") = 16),
 "ordinal" bigint NOT NULL,
 "source_fact_id" bytea NOT NULL CHECK (octet_length("source_fact_id") = 16),
 "expression" text NOT NULL,
 "related_node_id" bytea CHECK (octet_length("related_node_id") = 16),
 "resolved_target" text,
 "binding_mode" text CHECK ("binding_mode" IN ('class','static','property')),
 "accessor_role" text CHECK ("accessor_role" IN ('getter','setter','deleter','cached_getter')),
 "protocol" text CHECK ("protocol" IN ('context_manager','async_context_manager')),
 "registration" text CHECK ("registration" IN ('tool','resource','prompt')),
 "admission" text NOT NULL CHECK ("admission" IN ('body_preserved','withheld')),
 "reason" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,declaration_node_id,ordinal)
);
ALTER TABLE lctx_serving.catalog_surfaces ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_surfaces FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_surfaces FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_surfaces FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_surfaces FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_surfaces TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_surfaces TO lctx_importer;
CREATE TABLE lctx_serving.catalog_configurations (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "field_id" bytea NOT NULL CHECK (octet_length("field_id") = 16),
 "class_node_id" bytea NOT NULL CHECK (octet_length("class_node_id") = 16),
 "source_fact_id" bytea NOT NULL CHECK (octet_length("source_fact_id") = 16),
 "syntax_fact_id" bytea CHECK (octet_length("syntax_fact_id") = 16),
 "record_kind" text NOT NULL CHECK ("record_kind" IN ('dataclass','attrs','pydantic','typed_dict','named_tuple')),
 "name" text NOT NULL,
 "ordinal" bigint NOT NULL,
 "term_id" bytea NOT NULL CHECK (octet_length("term_id") = 16),
 "alias" text,
 "init" boolean,
 "kw_only" boolean,
 "required" boolean,
 "read_only" boolean,
 "annotation_text" text,
 "default_state" text NOT NULL CHECK ("default_state" IN ('absent','literal_none','literal','source_expression','optional_expression_unavailable','unknown','factory_expression')),
 "default_text" text,
 "literal_json" text,
 "factory_text" text,
 "reason" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,field_id,source_fact_id)
);
ALTER TABLE lctx_serving.catalog_configurations ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_configurations FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_configurations FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_configurations FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_configurations FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_configurations TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_configurations TO lctx_importer;
CREATE TABLE lctx_serving.catalog_field_links (
 generation_digest bytea NOT NULL REFERENCES lctx_serving.generations(generation_digest),
 row_ordinal bigint NOT NULL CHECK (row_ordinal >= 0),
 "link_id" bytea NOT NULL CHECK (octet_length("link_id") = 16),
 "field_id" bytea NOT NULL CHECK (octet_length("field_id") = 16),
 "class_node_id" bytea NOT NULL CHECK (octet_length("class_node_id") = 16),
 "signature_id" bytea NOT NULL CHECK (octet_length("signature_id") = 16),
 "ordinal" bigint NOT NULL,
 "formal_node_id" bytea CHECK (octet_length("formal_node_id") = 16),
 "reader_node_id" bytea CHECK (octet_length("reader_node_id") = 16),
 "source_fact_id" bytea NOT NULL CHECK (octet_length("source_fact_id") = 16),
 "kind" text NOT NULL CHECK ("kind" IN ('declared_parameter','exact_storage','exact_reader')),
 "reason" text,
 PRIMARY KEY (generation_digest,row_ordinal),
 UNIQUE (generation_digest,link_id)
);
ALTER TABLE lctx_serving.catalog_field_links ENABLE ROW LEVEL SECURITY;
CREATE POLICY ready_read ON lctx_serving.catalog_field_links FOR SELECT TO lctx_serving USING (lctx_serving.is_ready(generation_digest));
CREATE POLICY import_read ON lctx_serving.catalog_field_links FOR SELECT TO lctx_importer USING (true);
CREATE POLICY import_insert ON lctx_serving.catalog_field_links FOR INSERT TO lctx_importer WITH CHECK (true);
CREATE TRIGGER frozen_projection BEFORE INSERT OR UPDATE OR DELETE ON lctx_serving.catalog_field_links FOR EACH ROW EXECUTE FUNCTION lctx_serving.require_loading();
GRANT SELECT ON lctx_serving.catalog_field_links TO lctx_serving,lctx_importer;
GRANT INSERT ON lctx_serving.catalog_field_links TO lctx_importer;
ALTER TABLE lctx_serving.catalog_configurations ADD FOREIGN KEY (generation_digest,term_id) REFERENCES lctx_serving.catalog_types(generation_digest,term_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lctx_serving.catalog_field_links ADD FOREIGN KEY (generation_digest,signature_id,ordinal) REFERENCES lctx_serving.catalog_parameters(generation_digest,signature_id,ordinal) DEFERRABLE INITIALLY DEFERRED;

CREATE OR REPLACE FUNCTION lctx_serving.prepare_generation(doc text, transport bytea) RETURNS bigint
 LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE id bytea:=sha256(convert_to(doc,'UTF8')); prior text; a bigint; n text; child text; v text;
BEGIN
 IF (doc::jsonb->>'format')::int IS DISTINCT FROM 4 OR (doc::jsonb->>'bundle_format')::int IS DISTINCT FROM 14
 OR doc::jsonb#>'{capabilities,catalog}' IS DISTINCT FROM 'true'::jsonb
 OR coalesce(doc::jsonb#>>'{context,library}','')='' THEN RAISE EXCEPTION 'unsupported projection context'; END IF;
 PERFORM pg_advisory_xact_lock(lctx_serving.lock_key(id));
 INSERT INTO lctx_serving.generations(generation_digest,canonical_manifest) VALUES(id,doc) ON CONFLICT DO NOTHING;
 SELECT canonical_manifest INTO prior FROM lctx_serving.generations WHERE generation_digest=id;
 IF prior<>doc THEN RAISE EXCEPTION 'projection identity conflict'; END IF;
 IF EXISTS(SELECT FROM lctx_serving.generations WHERE generation_digest=id AND state='failed') THEN RAISE EXCEPTION 'terminal projection failure'; END IF;
 INSERT INTO lctx_serving.import_recipes VALUES(id,1,transport) ON CONFLICT DO NOTHING;
 IF EXISTS(SELECT FROM lctx_serving.import_recipes WHERE generation_digest=id AND transport_digest<>transport)
 AND NOT lctx_serving.is_ready(id) THEN RAISE EXCEPTION 'frozen transport conflict'; END IF;
 UPDATE lctx_serving.import_attempts SET outcome='interrupted',finished_at=clock_timestamp(),failure_code='owner_disconnected'
 WHERE generation_digest=id AND outcome='running';
 INSERT INTO lctx_serving.import_attempts(generation_digest) VALUES(id) RETURNING attempt_id INTO a;
 IF NOT lctx_serving.is_ready(id) THEN
  FOREACH n IN ARRAY ARRAY['vectors','operation_vectors'] LOOP
   child:=CASE n WHEN 'vectors' THEN 'v_' ELSE 'o_' END || substr(encode(id,'hex'),1,48);
   IF to_regclass('lctx_serving.'||child) IS NULL THEN
    EXECUTE format('CREATE TABLE lctx_serving.%I PARTITION OF lctx_serving.%I FOR VALUES IN (%L)%s',child,n,id,
     CASE n WHEN 'operation_vectors' THEN ' PARTITION BY LIST (embedding_view)' ELSE '' END);
    IF n='operation_vectors' THEN
     FOREACH v IN ARRAY ARRAY['signature_doc','source_body'] LOOP
      EXECUTE format('CREATE TABLE lctx_serving.%I PARTITION OF lctx_serving.%I FOR VALUES IN (%L)',child||CASE v WHEN 'signature_doc' THEN '_d' ELSE '_s' END,child,v);
     END LOOP;
    END IF;
   ELSIF NOT EXISTS(SELECT FROM pg_class WHERE oid=to_regclass('lctx_serving.'||child)
      AND pg_get_expr(relpartbound,oid) LIKE '%'||encode(id,'hex')||'%') THEN
    RAISE EXCEPTION 'partition identity conflict';
   END IF;
  END LOOP;
 END IF;
 PERFORM lctx_serving.check_partitions(id);
 RETURN a;
END $$;
CREATE OR REPLACE FUNCTION lctx_serving.cleanup_generation(id bytea) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE n text; phase text; BEGIN
 IF NOT pg_try_advisory_xact_lock(lctx_serving.lock_key(id)) THEN RAISE EXCEPTION 'generation import is active'; END IF;
 SELECT state INTO phase FROM lctx_serving.generations WHERE generation_digest=id FOR UPDATE;
 IF phase IS NULL OR phase='ready' OR EXISTS(SELECT FROM lctx_serving.selections WHERE generation_digest=id) THEN RAISE EXCEPTION 'generation cannot be cleaned'; END IF;
 SET CONSTRAINTS ALL DEFERRED;
 FOREACH n IN ARRAY ARRAY['catalog_surfaces','catalog_field_links','catalog_configurations','catalog_constructors','catalog_type_observations','catalog_type_args','catalog_types','catalog_parameters','catalog_signatures','catalog_evidence','catalog_bindings','catalog_members','briefs','assertions','supports','support_findings','support_witnesses','support_members','support_attributes','support_attribute_incidences','evidence','brief_members','symbol_map','public_paths','lexical_text','embedding_spec','vectors','operations','operation_facets','operation_facet_status','behaviors','conditions','condition_nodes','analysis_conditions','analysis_condition_nodes','callable_parameters','summary_flows','source_context_value_identities','source_body_completions','source_body_steps','source_body_release_inputs','source_call_bindings','source_call_normals','source_call_header_steps','model_frame_exits','model_frame_exit_arguments','model_frame_exit_steps','source_modeled_identities','source_parameter_identities','return_completion_certificates','model_context_protocols','source_context_sites','source_context_arguments','summary_flow_steps','summary_boundaries','behavior_discharges','flow_test_leaves','flow_test_value_links','singletons','ambient_reads','place_claims','operation_text','operation_vectors'] LOOP
  EXECUTE format('DELETE FROM lctx_serving.%I WHERE generation_digest=$1',n) USING id;
 END LOOP;
 DELETE FROM lctx_serving.artifact_locations WHERE generation_digest=id;
 DELETE FROM lctx_serving.artifacts WHERE generation_digest=id;
 IF phase<>'failed' THEN UPDATE lctx_serving.generations SET state='failed' WHERE generation_digest=id; END IF;
 UPDATE lctx_serving.import_attempts SET outcome='interrupted',finished_at=clock_timestamp(),failure_code='owned_cleanup' WHERE generation_digest=id AND outcome='running';
 -- Keep the manifest, transport, attempts and batch receipts as terminal diagnostic history.
 -- Content-addressed files remain retained, including files shared with other generations.
END $$;
CREATE OR REPLACE FUNCTION lctx_serving.analyze_generation(id bytea) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE n text; BEGIN
 IF NOT EXISTS(SELECT FROM lctx_serving.generations WHERE generation_digest=id AND state='validating') THEN RAISE EXCEPTION 'not validating'; END IF;
 FOREACH n IN ARRAY ARRAY['catalog_surfaces','catalog_field_links','catalog_configurations','catalog_constructors','catalog_members','catalog_bindings','catalog_signatures','catalog_parameters','catalog_evidence','catalog_types','catalog_type_args','catalog_type_observations','vectors','operation_vectors','operations','operation_facets','operation_facet_status','behaviors','assertions','supports'] LOOP
  EXECUTE format('ANALYZE lctx_serving.%I',n);
 END LOOP;
END $$;
CREATE INDEX catalog_configuration_class ON lctx_serving.catalog_configurations(generation_digest,class_node_id);
CREATE INDEX catalog_field_link_class ON lctx_serving.catalog_field_links(generation_digest,class_node_id);
ALTER TABLE lctx_serving.catalog_surfaces ADD CHECK (ordinal >= 0);
ALTER TABLE lctx_serving.catalog_configurations ADD CHECK (ordinal >= 0);
ALTER TABLE lctx_serving.catalog_field_links ADD CHECK (ordinal >= 0 AND ((kind = 'exact_reader') = (reader_node_id IS NOT NULL)));
