//! Focused controls for the shared content, exact-view and durable ownership cutover.
use lctx_model::domain::{ContentHash,FiniteF64,Record,Relation,admission::Frontier,
    analytics::QualityStep,completed::{CompletedBinding,ContributionSpec},
    analysis::sources::SourceSnapshot,resources::ResourceBudget,stages::{Profile,ProviderOutcome}};
use lctx_surrealdb::{RuntimeConfig,compiler::NativeCompilerStore,control};
use std::collections::{BTreeMap,BTreeSet};
use surrealdb::types::{Object,RecordId,Value,Variables};
fn config()->RuntimeConfig {RuntimeConfig::read(std::path::Path::new(&std::env::var_os("LCTX_COMPILER_RUNTIME_CONFIG").expect("stable validation runtime"))).unwrap()}
fn row(run:[u8;16],value:f64)->QualityStep {QualityStep{run:serde_json::from_value(serde_json::json!(run)).unwrap(),ordinal:0,value:FiniteF64::new(value).unwrap()}}
fn specification(producer:String)->ContributionSpec {ContributionSpec{captured_binding:None,producer,profile:Profile::Catalog,model:lctx_model::domain::model().unwrap().digest(),implementation:ContentHash::of(b"native-control/v1"),configuration:None,inputs:vec![],outputs:BTreeSet::from([QualityStep::NAME.into()])}}
async fn contribute(store:&std::sync::Arc<NativeCompilerStore>,spec:ContributionSpec,row:&QualityStep,previous:&BTreeMap<String,lctx_model::domain::completed::CompletedView>)->(ContentHash,BTreeMap<String,lctx_model::domain::completed::CompletedView>){let relation=Relation::of::<QualityStep>();let id=store.begin_contribution(spec).await.unwrap();store.write_batch(&id,&relation,&QualityStep::encode(std::slice::from_ref(row)).unwrap()).await.unwrap();let views=store.complete_contribution(id,ProviderOutcome::Complete,&[relation],previous).await.unwrap();(id,views)}
#[tokio::test(flavor="multi_thread")]
async fn shared_revision_addresses_coexist_and_exact_views_select_their_payload(){
    let cfg=config();let a=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let b=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();
    assert_eq!(a.database(),b.database());assert_eq!(a.database(),&cfg.database);
    let nonce=control::fresh_identity("revision-control").unwrap();let run=nonce.0[..16].try_into().unwrap();
    let (_,av)=contribute(&a,specification(format!("a-{}",nonce.hex())),&row(run,1.0),&BTreeMap::new()).await;
    let (_,bv)=contribute(&b,specification(format!("b-{}",nonce.hex())),&row(run,2.0),&BTreeMap::new()).await;
    let budget=ResourceBudget::fixed(64<<20).unwrap();let relation=Relation::of::<QualityStep>();
    let mut ar=a.scan_rows(&av[QualityStep::NAME],&relation,None,None,&budget).await.unwrap();let ab=ar.next().await.unwrap().unwrap();assert_eq!(QualityStep::decode(&lctx_surrealdb::codec::decode_bodies(&relation,vec![ab],&budget).unwrap()).unwrap()[0].value,FiniteF64::new(1.0).unwrap());assert!(ar.next().await.unwrap().is_none());drop(ar);
    let mut br=b.scan_rows(&bv[QualityStep::NAME],&relation,None,None,&budget).await.unwrap();let bb=br.next().await.unwrap().unwrap();assert_eq!(QualityStep::decode(&lctx_surrealdb::codec::decode_bodies(&relation,vec![bb],&budget).unwrap()).unwrap()[0].value,FiniteF64::new(2.0).unwrap());assert!(br.next().await.unwrap().is_none());drop(br);
    a.abandon().await.unwrap();b.abandon().await.unwrap();
}
#[tokio::test(flavor="multi_thread")]
async fn only_admitted_retention_attaches_to_fresh_attempt_without_payload_replay(){
    let cfg=config();let source=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let target=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let nonce=control::fresh_identity("retention-control").unwrap();let spec=specification(nonce.hex());let run=nonce.0[..16].try_into().unwrap();let(id,views)=contribute(&source,spec.clone(),&row(run,3.0),&BTreeMap::new()).await;
    source.retain_product_identity(nonce,id).await.unwrap();assert!(target.attach_retained_product(nonce,&spec).await.unwrap().is_none());
    let view=views[QualityStep::NAME].clone();let relation=Relation::of::<QualityStep>();source.bind(CompletedBinding{boundary:None,source:SourceSnapshot::of_completed_view(&relation,spec.model,&view).unwrap(),view,configuration:None}).await.unwrap();source.mark_attempt_admitted().await.unwrap();
    let mut changed=spec.clone();changed.model=ContentHash::of(b"changed model");assert!(target.attach_retained_product(nonce,&changed).await.unwrap().is_none());changed=spec.clone();changed.implementation=ContentHash::of(b"changed implementation");assert!(target.attach_retained_product(nonce,&changed).await.unwrap().is_none());changed=spec.clone();changed.producer.push_str("changed source");assert!(target.attach_retained_product(nonce,&changed).await.unwrap().is_none());changed=spec.clone();changed.inputs.push(SourceSnapshot::of_completed_view(&relation,spec.model,&views[QualityStep::NAME]).unwrap());assert!(target.attach_retained_product(nonce,&changed).await.unwrap().is_none());
    let client=lctx_surrealdb::compiler::check_installation(&cfg).await.unwrap();let mut response=client.query("SELECT VALUE count() FROM compiler_record WHERE semantic_type=$relation AND semantic_key=$key GROUP ALL").bind(("relation",QualityStep::NAME)).bind(("key",row(run,3.0).id().hex())).await.unwrap().check().unwrap();let before:Vec<u64>=response.take(0).unwrap();
    let (attached,attached_views,descriptor)=target.attach_retained_product(nonce,&spec).await.unwrap().unwrap();
    let mut response=client.query("SELECT VALUE count() FROM compiler_record WHERE semantic_type=$relation AND semantic_key=$key GROUP ALL").bind(("relation",QualityStep::NAME)).bind(("key",row(run,3.0).id().hex())).await.unwrap().check().unwrap();let after:Vec<u64>=response.take(0).unwrap();assert_eq!(before,vec![1]);assert_eq!(after,before,"attachment does not replay or duplicate backing payloads");assert_ne!(id,attached);assert_eq!(attached_views[QualityStep::NAME],views[QualityStep::NAME]);assert_eq!(descriptor.spec,spec);
    let current=target.complete_contribution(attached,ProviderOutcome::Complete,&[relation],&BTreeMap::new()).await.unwrap();assert_eq!(current,attached_views);
    source.abandon().await.unwrap();target.abandon().await.unwrap();
}
#[tokio::test(flavor="multi_thread")]
async fn guarded_reachability_retains_shared_children(){
    let client=lctx_surrealdb::compiler::check_installation(&config()).await.unwrap();let nonce=control::fresh_identity("retirement-control").unwrap();let parent=RecordId::new("native_guard",format!("p{}",nonce.hex()));let other=RecordId::new("native_guard",format!("o{}",nonce.hex()));let child=RecordId::new("native_guard",format!("c{}",nonce.hex()));
    let rows=[&parent,&other,&child].into_iter().map(|id|{let mut row=Object::new();row.insert("id",id.clone());row.insert("revision",0i64);row.insert("retired",false);Value::Object(row)}).collect();control::ensure_rows(&client,None,rows).await.unwrap();control::hold(&client,None,parent.clone(),vec![child.clone()]).await.unwrap();control::hold(&client,None,other.clone(),vec![child.clone()]).await.unwrap();
    let pass=control::retire_reachable(&client,vec![parent],16).await.unwrap();assert_eq!(pass.retired,1);assert_eq!(pass.retained.len(),1);assert!(!control::retirement_eligibility(&client,child.clone()).await.unwrap().eligible);
    let pass=control::retire_reachable(&client,vec![other],16).await.unwrap();assert_eq!(pass.retired,2);control::ensure_rows(&client,None,vec![{let mut row=Object::new();row.insert("id",child.clone());row.insert("revision",0i64);row.insert("retired",false);Value::Object(row)}]).await.unwrap();control::retire(&client,child).await.unwrap();
}
#[tokio::test(flavor="multi_thread")]
async fn known_statement_abort_is_reconciled_and_attempt_fence_rejects_late_effect(){
    let cfg=config();let store=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let client=lctx_surrealdb::compiler::check_installation(&cfg).await.unwrap();assert!(control::effect(&client,Some(store.attempt()),"THROW 'expected native control abort'",Variables::new()).await.is_err());{let mut response=client.query("SELECT VALUE id FROM native_effect WHERE attempt=$attempt AND resolved=false").bind(("attempt",RecordId::new("native_attempt",store.attempt().hex()))).await.unwrap().check().unwrap();let pending:Vec<RecordId>=response.take(0).unwrap();assert!(pending.is_empty());}control::close_attempt(&client,store.attempt(),"frozen").await.unwrap();assert!(control::effect(&client,Some(store.attempt()),"RETURN NONE",Variables::new()).await.is_err());{let mut response=client.query("SELECT VALUE id FROM native_effect WHERE attempt=$attempt AND resolved=false").bind(("attempt",RecordId::new("native_attempt",store.attempt().hex()))).await.unwrap().check().unwrap();let pending:Vec<RecordId>=response.take(0).unwrap();assert!(pending.is_empty());}store.abandon().await.unwrap();
}

#[tokio::test(flavor="multi_thread")]
async fn retained_membership_deletion_refuses_attachment_and_same_view_revision_conflicts(){
    let cfg=config();let source=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let nonce=control::fresh_identity("deleted-membership-control").unwrap();let run=nonce.0[..16].try_into().unwrap();let spec=specification(nonce.hex());let (id,views)=contribute(&source,spec.clone(),&row(run,1.0),&BTreeMap::new()).await;
    let relation=Relation::of::<QualityStep>();let view=views[QualityStep::NAME].clone();source.bind(CompletedBinding{boundary:None,source:SourceSnapshot::of_completed_view(&relation,spec.model,&view).unwrap(),view,configuration:None}).await.unwrap();source.retain_product_identity(nonce,id).await.unwrap();source.mark_attempt_admitted().await.unwrap();
    let client=lctx_surrealdb::compiler::check_installation(&cfg).await.unwrap();client.query("DELETE compiler_membership WHERE contribution=$owner").bind(("owner",RecordId::new("compiler_contribution",id.hex()))).await.unwrap().check().unwrap();
    let target=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();assert!(target.attach_retained_product(nonce,&spec).await.is_err(),"retained descriptor alone cannot admit missing compact membership");source.abandon().await.unwrap();target.abandon().await.unwrap();
    let union=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let (_,prior)=contribute(&union,specification(format!("first{}",nonce.hex())),&row(run,1.0),&BTreeMap::new()).await;let id=union.begin_contribution(specification(format!("second{}",nonce.hex()))).await.unwrap();union.write_batch(&id,&relation,&QualityStep::encode(&[row(run,2.0)]).unwrap()).await.unwrap();assert!(union.complete_contribution(id,ProviderOutcome::Complete,&[relation],&prior).await.is_err(),"one exact view cannot select two revisions of a nominal row");let _=union.abandon().await;
}
#[tokio::test(flavor="multi_thread")]
async fn retained_empty_output_keeps_exact_zero_cardinality(){
    let cfg=config();let source=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let target=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let nonce=control::fresh_identity("empty-output-control").unwrap();let spec=specification(nonce.hex());let relation=Relation::of::<QualityStep>();let id=source.begin_contribution(spec.clone()).await.unwrap();let views=source.complete_contribution(id,ProviderOutcome::Complete,std::slice::from_ref(&relation),&BTreeMap::new()).await.unwrap();let view=views[QualityStep::NAME].clone();assert_eq!(view.rows,0);source.bind(CompletedBinding{boundary:None,source:SourceSnapshot::of_completed_view(&relation,spec.model,&view).unwrap(),view,configuration:None}).await.unwrap();source.retain_product_identity(nonce,id).await.unwrap();source.mark_attempt_admitted().await.unwrap();let (_,attached,descriptor)=target.attach_retained_product(nonce,&spec).await.unwrap().unwrap();assert_eq!(attached[QualityStep::NAME].rows,0);assert_eq!(descriptor.outputs[QualityStep::NAME].rows,0);source.abandon().await.unwrap();target.abandon().await.unwrap();
}
#[tokio::test(flavor="multi_thread")]
async fn reconciliation_fence_excludes_late_remote_commit_and_retirement_resumes_after_unpin(){
    let cfg=config();let client=lctx_surrealdb::compiler::check_installation(&cfg).await.unwrap();let operation=control::fresh_identity("unknown-effect-control").unwrap();let effect=RecordId::new("native_effect",operation.hex());let object=RecordId::new("native_guard",format!("unknown{}",operation.hex()));
    client.query("CREATE $effect SET attempt=NONE,request='control',committed=false,resolved=false,revision=0,epoch=1 RETURN NONE").bind(("effect",effect.clone())).await.unwrap().check().unwrap();
    let pending=client.as_ref().clone().begin().await.unwrap();pending.query("LET $fence=SELECT * FROM ONLY $effect FOR UPDATE; CREATE $object SET revision=0,retired=false RETURN NONE; UPDATE $effect SET committed=true,resolved=true,revision+=1 RETURN NONE").bind(("effect",effect)).bind(("object",object.clone())).await.unwrap().check().unwrap();
    assert!(!control::reconcile_effect(&client,operation).await.unwrap());assert!(pending.commit().await.is_err(),"fenced unknown transaction cannot commit after reconciliation");let mut response=client.query("SELECT VALUE id FROM $object").bind(("object",object.clone())).await.unwrap().check().unwrap();let absent:Vec<RecordId>=response.take(0).unwrap();assert!(absent.is_empty());
    let mut row=Object::new();row.insert("id",object.clone());row.insert("revision",0i64);row.insert("retired",false);control::ensure_rows(&client,None,vec![Value::Object(row)]).await.unwrap();let pin=control::ReaderPin::acquire(client.clone(),&[]).await.unwrap();pin.protect(object.clone()).await.unwrap();let first=control::retire_reachable(&client,vec![object],1).await.unwrap();assert_eq!(first.retired,0);assert_eq!(first.retained.len(),1);pin.release().await.unwrap();let next=control::resume_retirement(&client,first.identity,4).await.unwrap();assert_eq!(next.retired,1);assert!(next.remaining.is_empty());assert!(next.retained.is_empty());
}

#[tokio::test(flavor="multi_thread")]
async fn completed_state_is_exact_binding_closure_in_current_and_cold_owners(){
    let cfg=config();let store=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let nonce=control::fresh_identity("state-closure-control").unwrap();let mut run=nonce.0[..16].try_into().unwrap();
    let (_,first)=contribute(&store,specification(format!("first{}",nonce.hex())),&row(run,1.0),&BTreeMap::new()).await;
    run[0]^=1;let (_,second)=contribute(&store,specification(format!("second{}",nonce.hex())),&row(run,2.0),&first).await;
    let relation=Relation::of::<QualityStep>();let view=second[QualityStep::NAME].clone();store.bind(CompletedBinding{boundary:None,source:SourceSnapshot::of_completed_view(&relation,specification(String::new()).model,&view).unwrap(),view,configuration:None}).await.unwrap();
    assert_eq!(store.views().await.unwrap().len(),1,"unbound singleton view is not portable state authority");let identity=store.completed_state().await.unwrap();let bindings=store.bindings().await.unwrap();let client=lctx_surrealdb::compiler::check_installation(&cfg).await.unwrap();let cold=NativeCompilerStore::from_publication(client,cfg.namespace.clone(),cfg.database.clone(),bindings).await.unwrap();cold.verify_state().await.unwrap();assert_eq!(cold.completed_state().await.unwrap(),identity);store.abandon().await.unwrap();
}
#[tokio::test(flavor="multi_thread")]
async fn retirement_uses_exact_guards_without_blocking_on_unrelated_live_effects(){
    let client=lctx_surrealdb::compiler::check_installation(&config()).await.unwrap();let nonce=control::fresh_identity("parallel-retirement-control").unwrap();let unrelated=RecordId::new("native_effect",nonce.hex());let object=RecordId::new("native_guard",format!("late{}",nonce.hex()));let guard=RecordId::new("native_guard",ContentHash::of(&serde_json::to_vec(&Value::RecordId(object.clone())).unwrap()).hex());
    client.query("CREATE $effect SET attempt=NONE,request='unrelated-active-control',committed=false,resolved=false,revision=0,epoch=1 RETURN NONE").bind(("effect",unrelated)).await.unwrap().check().unwrap();
    let pending=client.as_ref().clone().begin().await.unwrap();pending.query("UPSERT $guard SET revision=(revision ?? 0)+1,retired=(retired ?? false) RETURN NONE; CREATE $object SET revision=0,retired=false RETURN NONE").bind(("guard",guard)).bind(("object",object.clone())).await.unwrap().check().unwrap();
    assert!(control::retirement_eligibility(&client,object.clone()).await.unwrap().eligible,"an unrelated active operation is not an object dependency");control::retire(&client,object.clone()).await.unwrap();assert!(pending.commit().await.is_err(),"late immutable insertion must conflict with retirement's exact guard");control::reconcile_effect(&client,nonce).await.unwrap();let mut response=client.query("SELECT VALUE id FROM $object").bind(("object",object)).await.unwrap().check().unwrap();let rows:Vec<RecordId>=response.take(0).unwrap();assert!(rows.is_empty());
}

#[tokio::test(flavor="multi_thread")]
async fn fresh_attempt_reactivates_content_but_original_attempt_effect_and_pin_epochs_stay_fenced(){
    let cfg=config();let old=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let client=lctx_surrealdb::compiler::check_installation(&cfg).await.unwrap();let nonce=control::fresh_identity("reactivation-control").unwrap();let object=RecordId::new("native_guard",format!("reactivate{}",nonce.hex()));let guard=RecordId::new("native_guard",ContentHash::of(&serde_json::to_vec(&Value::RecordId(object.clone())).unwrap()).hex());
    let mut row=Object::new();row.insert("id",object.clone());row.insert("revision",0i64);row.insert("retired",false);let value=Value::Object(row);control::ensure_rows(&client,Some(old.attempt()),vec![value.clone()]).await.unwrap();let old_pin=control::ReaderPin::acquire(client.clone(),&[]).await.unwrap();
    let mut response=client.query("SELECT VALUE epoch FROM $attempt").bind(("attempt",RecordId::new("native_attempt",old.attempt().hex()))).await.unwrap().check().unwrap();let epochs:Vec<i64>=response.take(0).unwrap();let epoch=epochs[0];
    let delayed=RecordId::new("native_effect",nonce.hex());client.query("CREATE $effect SET attempt=NONE,request='delayed-unowned-control',committed=false,resolved=false,revision=0,epoch=$epoch RETURN NONE").bind(("effect",delayed.clone())).bind(("epoch",epoch)).await.unwrap().check().unwrap();
    let first=control::retire_reachable(&client,vec![object.clone()],1).await.unwrap();assert_eq!(first.retired,1);let fresh=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();control::ensure_rows(&client,Some(fresh.attempt()),vec![value.clone()]).await.unwrap();
    assert!(control::ensure_rows(&client,Some(old.attempt()),vec![value]).await.is_err(),"an earlier attempt never borrows the reactivating attempt epoch");assert!(old_pin.protect(object.clone()).await.is_err(),"pin protection retains the original pin epoch");
    let delayed_result=client.query("BEGIN; LET $effect_state=SELECT * FROM ONLY $effect FOR UPDATE; LET $original_epoch=$effect_state.epoch; LET $guard_state=SELECT * FROM ONLY $guard FOR UPDATE; IF $original_epoch<=($guard_state.retired_through ?? 0) { THROW 'delayed original epoch fenced'; }; UPDATE $effect SET committed=true,resolved=true RETURN NONE; COMMIT;").bind(("effect",delayed)).bind(("guard",guard.clone())).await.unwrap().check();assert!(delayed_result.is_err(),"reactivation does not erase the retired-through watermark for a delayed unowned intent");control::reconcile_effect(&client,nonce).await.unwrap();
    let mut response=client.query("SELECT retired,retired_through FROM $guard").bind(("guard",guard)).await.unwrap().check().unwrap();let guards:Vec<Object>=response.take(0).unwrap();assert_eq!(guards[0].get("retired"),Some(&Value::Bool(false)));assert!(matches!(guards[0].get("retired_through"),Some(Value::Number(surrealdb::types::Number::Int(mark))) if *mark>=epoch));
    old_pin.release().await.unwrap();let second=control::retire_reachable(&client,vec![object],1).await.unwrap();assert_eq!(second.identity,first.identity);assert_eq!(second.retired,2,"explicit retirement revisits a legally reactivated root");old.abandon().await.unwrap();fresh.abandon().await.unwrap();
}
#[tokio::test(flavor="multi_thread")]
async fn retained_product_keeps_exact_prerequisite_closure_after_origin_publication_retirement(){
    let cfg=config();let origin=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let nonce=control::fresh_identity("retained-prerequisite-control").unwrap();let relation=Relation::of::<QualityStep>();let run=nonce.0[..16].try_into().unwrap();let (_,base)=contribute(&origin,specification(format!("base{}",nonce.hex())),&row(run,1.0),&BTreeMap::new()).await;let input=SourceSnapshot::of_completed_view(&relation,specification(String::new()).model,&base[QualityStep::NAME]).unwrap();
    let mut derived_spec=specification(format!("derived{}",nonce.hex()));derived_spec.inputs=vec![input];let mut derived_run=run;derived_run[0]^=1;let (derived,derived_views)=contribute(&origin,derived_spec.clone(),&row(derived_run,2.0),&BTreeMap::new()).await;let view=derived_views[QualityStep::NAME].clone();origin.bind(CompletedBinding{boundary:None,source:SourceSnapshot::of_completed_view(&relation,derived_spec.model,&view).unwrap(),view,configuration:None}).await.unwrap();origin.retain_product_identity(nonce,derived).await.unwrap();origin.mark_attempt_admitted().await.unwrap();
    let client=lctx_surrealdb::compiler::check_installation(&cfg).await.unwrap();let publication=RecordId::new("publication",nonce.hex());let mut publication_row=Object::new();publication_row.insert("id",publication.clone());publication_row.insert("handle","native-owner-control");publication_row.insert("manifest",surrealdb::types::Bytes::from(vec![]));publication_row.insert("views",surrealdb::types::Bytes::from(serde_json::to_vec(&origin.bindings().await.unwrap()).unwrap()));publication_row.insert("definition_epoch",nonce.hex());control::ensure_rows(&client,Some(origin.attempt()),vec![Value::Object(publication_row)]).await.unwrap();control::hold(&client,Some(origin.attempt()),publication.clone(),vec![RecordId::new("compiler_view",derived_views[QualityStep::NAME].identity.hex()),RecordId::new("compiler_view",base[QualityStep::NAME].identity.hex())]).await.unwrap();origin.abandon().await.unwrap();
    let retired=control::retire_reachable(&client,vec![publication],64).await.unwrap();assert!(retired.retired>=1);let target=NativeCompilerStore::begin(&cfg,Frontier::Facts).await.unwrap();let (attached,_,descriptor)=target.attach_retained_product(nonce,&derived_spec).await.unwrap().expect("admitted product retains its prerequisite closure independently of the origin publication");assert_eq!(descriptor.spec.inputs,derived_spec.inputs);let mut response=client.query("SELECT VALUE object FROM native_hold WHERE owner=$owner").bind(("owner",RecordId::new("compiler_contribution",attached.hex()))).await.unwrap().check().unwrap();let targets:Vec<RecordId>=response.take(0).unwrap();assert!(targets.contains(&RecordId::new("compiler_view",base[QualityStep::NAME].identity.hex())));
    let mut rows=target.scan_rows(&base[QualityStep::NAME],&relation,None,None,&ResourceBudget::fixed(64<<20).unwrap()).await.unwrap();assert!(rows.next().await.unwrap().is_some());assert!(rows.next().await.unwrap().is_none());drop(rows);target.abandon().await.unwrap();
}

#[tokio::test(flavor="multi_thread")]
#[ignore="database-wide backup exclusion requires explicit owned-service maintenance"]
async fn backup_hold_excludes_retirement_under_exclusive_maintenance(){
    let path=std::env::var_os("LCTX_SURREAL_INSTALLER_CONFIG").expect("explicit validation maintenance installer configuration");
    let cfg=RuntimeConfig::read(std::path::Path::new(&path)).unwrap();assert_eq!(cfg.authentication,lctx_surrealdb::AuthenticationScope::Root);
    let client=lctx_surrealdb::compiler::check_installation(&cfg).await.unwrap();let nonce=control::fresh_identity("backup-exclusion-control").unwrap();let object=RecordId::new("native_guard",nonce.hex());let mut row=Object::new();row.insert("id",object.clone());row.insert("revision",0i64);row.insert("retired",false);control::ensure_rows(&client,None,vec![Value::Object(row)]).await.unwrap();
    let backup=control::acquire_backup_hold(&client).await.unwrap();
    let result=async {let eligibility=control::retirement_eligibility(&client,object.clone()).await?;assert!(!eligibility.eligible);assert!(eligibility.reasons.contains(&"active native backup hold".to_string()));assert!(control::retire(&client,object.clone()).await.is_err());Ok::<(),lctx_model::domain::ModelError>(())}.await;
    control::release_backup_hold(&client,backup).await.unwrap();control::retire(&client,object).await.unwrap();result.unwrap();
}
