//! Authored prose conclusions. This owner proves exact documentary extraction, never behavior.
use crate::domain::{*,analysis::{self,native::{NativeAssertionPremise,NativeQualification},policy::EvidenceStatus,support::{DerivedEvidence,SourceFacts}},artifact::{ArtifactChunk,ArtifactChunkKey,ARTIFACT_CHUNK_BYTES},assertion::{AssertionQualification,Approximation},attribution::{Modality,Fidelity},catalog::*,normalized::{Rows,entities::*},source::*,syntax::*,value::Literal,resources::{ResourceBudget,Reservation}};
use crate::{Domain,DomainCode};
use unicode_segmentation::UnicodeSegmentation;
#[derive(Debug,Clone,Copy,PartialEq,Eq,Hash,DomainCode)]
#[repr(i16)]
pub enum DocumentaryBoundaryReason {NoSourceDeclaration=0,NoDocstring=1,NativeEvidenceUnavailable=2,UnsupportedLiteralMapping=3,EmptySummary=4}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="synthesis_documentary_boundaries")]
pub struct DocumentaryBoundary {#[model(key)]pub member:Id<CatalogMemberInvocation>,#[model(key)]pub candidate:Option<Id<CatalogCandidate>>,#[model(key)]pub reason:DocumentaryBoundaryReason}
/// A derived slice of an earlier occurrence, not a new native Evidence or source-body store.
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="synthesis_prose_slices",validate=validate_slice)]
pub struct ProseSlice {#[model(key)]pub literal:Id<Occurrence>,#[model(key)]pub start:i64,#[model(key)]pub end:i64}
fn validate_slice(r:&ProseSlice)->Result<(),ModelError>{if r.start<0||r.end<r.start{return Err(invalid("invalid documentary relative byte slice"));}Ok(())}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="synthesis_documentary_conclusions",rule="sourced_authored_prose",invariants=invariants,semantic_source=include_bytes!("documentary.rs"))]
pub struct DocumentaryConclusion {
 #[model(key)]pub member:Id<CatalogMemberInvocation>,
 #[model(key)]pub candidate:Id<CatalogCandidate>,
 #[model(key,premise)]pub declaration:Id<NativeAssertionPremise>,
 #[model(key,premise)]pub placement:Id<NativeAssertionPremise>,
 #[model(key,premise)]pub detail:Id<NativeAssertionPremise>,
 pub subject:Id<EntityRef>,
 pub docstring:Id<Occurrence>,
 /// Complete authored content, including all warnings/limits, remains independently anchored.
 pub prose:Id<ProseSlice>,
 pub excerpt:Id<ProseSlice>,
 pub literal:Id<Literal>,
 pub excerpt_digest:ContentHash,
 qualification:Id<AssertionQualification>,
}
impl DocumentaryConclusion {pub fn qualification(&self)->Id<AssertionQualification>{self.qualification}}
impl analysis::support::sealed::DerivedEvidence for DocumentaryConclusion {}
impl DerivedEvidence for DocumentaryConclusion {fn source_facts(&self)->SourceFacts{SourceFacts{qualification:self.qualification,status:EvidenceStatus::Documented,heuristic:false}}}
#[macro_export]
macro_rules! synthesis_documentary_inputs {($m:ident)=>{$m! {
 members:$crate::domain::catalog::CatalogMember,member_frames:$crate::domain::catalog::CatalogMemberInvocation,candidates:$crate::domain::catalog::CatalogCandidate,exposures:$crate::domain::catalog::CatalogExposure,paths:$crate::domain::catalog::CatalogPath,aliases:$crate::domain::catalog::CatalogAlias,
 public_exposures:$crate::domain::normalized::entities::PublicExposure,entity_candidates:$crate::domain::normalized::entities::SymbolEntityCandidate,refs:$crate::domain::normalized::entities::EntityRef,callables:$crate::domain::normalized::entities::CallableEntity,classes:$crate::domain::normalized::entities::ClassEntity,
 core_invocations:$crate::domain::analysis::catalog_core::Invocation,modules:$crate::domain::source::Module,artifacts:$crate::domain::source::SourceArtifact,occurrences:$crate::domain::source::Occurrence,chunks:$crate::domain::artifact::ArtifactChunk,
 declarations:$crate::domain::syntax::DeclarationObservation,placements:$crate::domain::syntax::SyntaxPlacement,details:$crate::domain::syntax::SyntaxDetailObservation,detail_values:$crate::domain::syntax::SyntaxDetail,literals:$crate::domain::value::Literal,
 native:$crate::domain::analysis::native::NativeAssertionPremise,native_qualifications:$crate::domain::analysis::native::NativeQualification,qualifications:$crate::domain::assertion::AssertionQualification,
}};}
macro_rules! outputs {($m:ident)=>{$m! {conclusions:DocumentaryConclusion,boundaries:DocumentaryBoundary,slices:ProseSlice,qualifications:AssertionQualification,}};}
macro_rules! data {($($f:ident:$ty:ty,)*)=>{
 pub struct Data{$(pub $f:Rows<$ty>,)*}
 impl Data {pub fn new(b:&ResourceBudget)->Self{Self{$($f:Rows::new(b),)*}} pub fn visit(&mut self,n:&str,b:&arrow_array::RecordBatch)->Result<bool,ModelError>{$(if n==<$ty>::NAME{self.$f.decode(b)?;return Ok(true);})*Ok(false)} pub fn validation_inputs()->Vec<ValidationInput>{vec![$(ValidationInput::of::<$ty>(&["id"]),)*]} pub fn stage_inputs()->Vec<stages::RelationUse>{{let mut rows=vec![$(stages::RelationUse::stored::<$ty>()),*];for r in &mut rows{if r.name()==AssertionQualification::NAME{*r=r.at_epoch(stages::PublicationBoundary::Facts);}}rows}}}
};} crate::synthesis_documentary_inputs!(data);
macro_rules! output {($($f:ident:$ty:ty,)*)=>{
 pub struct Output{$(pub $f:Rows<$ty>,)*}
 impl Output {pub fn new(b:&ResourceBudget)->Self{Self{$($f:Rows::new(b),)*}} pub fn visit(&mut self,n:&str,b:&arrow_array::RecordBatch)->Result<bool,ModelError>{$(if n==<$ty>::NAME{self.$f.decode(b)?;return Ok(true);})*Ok(false)} pub fn validation_inputs()->Vec<ValidationInput>{vec![$(ValidationInput::of::<$ty>(&["id"]),)*]} pub fn matches(&self,other:&Self)->Result<(),ModelError>{if !self.conclusions.same(&other.conclusions)||!self.boundaries.same(&other.boundaries){return Err(invalid("documentary conclusion/boundary closure differs"));}if !self.slices.same(&other.slices){return Err(invalid("documentary slice closure differs"));}for row in other.qualifications.iter(){if self.qualifications.get(row.id())!=Some(row){return Err(invalid("documentary qualification differs"));}}Ok(())}}
};} outputs!(output);
fn invalid(s:impl Into<String>)->ModelError{ModelError::Invalid(s.into())}
fn need<R:Record>(rows:&Rows<R>,id:Id<R>)->Result<&R,ModelError>{rows.get(id).ok_or_else(||invalid(format!("documentary input absent: {}",R::NAME)))}
pub fn relations()->Vec<Relation>{vec![Relation::of::<DocumentaryConclusion>(),Relation::of::<DocumentaryBoundary>(),Relation::of::<ProseSlice>()]}
fn entity(d:&Data,c:&CatalogCandidate)->Result<Option<Id<EntityRef>>,ModelError>{if let Some(p)=c.path{return Ok(Some(need(&d.paths,p)?.entity));}if let Some(a)=c.alias{return Ok(Some(need(&d.aliases,a)?.entity));}c.entity.map(|e|need(&d.entity_candidates,e).map(|r|r.entity)).transpose()}
fn source_declaration(d:&Data,id:Id<EntityRef>)->Result<Option<Id<Occurrence>>,ModelError>{Ok(match need(&d.refs,id)?{EntityRef::Callable{callable}=>match need(&d.callables,*callable)?{CallableEntity::Source{declaration,..}=>Some(*declaration),_=>None},EntityRef::Class{class}=>match need(&d.classes,*class)?{ClassEntity::Source{declaration}=>Some(*declaration),_=>None},_=>None})}
fn native<'a>(d:&'a Data,predicate:impl Fn(&NativeAssertionPremise)->bool,q:Id<AssertionQualification>)->Result<Option<&'a NativeAssertionPremise>,ModelError>{
 let mut found=None;for p in d.native.iter().filter(|p|predicate(p)){let Some(n)=d.native_qualifications.get(Id::of(&crate::domain::analysis::native::NativeQualificationKey{premise:p.id()})) else{continue};if n.qualification!=q||n.family!=p.family()||n.fidelity==Fidelity::DisplayOnly{continue;}if found.is_some(){return Err(invalid("documentary native support is ambiguous"));}found=Some(p);}Ok(found)
}
struct Bytes{value:String,_reservation:Box<dyn Reservation>}
fn read(d:&Data,occurrence:&Occurrence,b:&ResourceBudget)->Result<Bytes,ModelError>{let artifact=need(&d.artifacts,occurrence.source)?;if occurrence.start<0||occurrence.end<occurrence.start||occurrence.end>artifact.byte_len{return Err(invalid("documentary occurrence lies outside artifact"));}let len=(occurrence.end-occurrence.start) as usize;let reservation=b.reserve("synthesis-original-prose",len.checked_mul(2).and_then(|n|n.checked_add(size_of::<Bytes>())).ok_or_else(||invalid("documentary source allowance overflow"))?)?;let mut bytes=Vec::with_capacity(len);let mut offset=occurrence.start as usize;while offset<occurrence.end as usize{let chunk=need(&d.chunks,Id::of(&ArtifactChunkKey{artifact:artifact.id(),ordinal:(offset/ARTIFACT_CHUNK_BYTES) as i64}))?;let start=offset%ARTIFACT_CHUNK_BYTES;let count=(occurrence.end as usize-offset).min(ARTIFACT_CHUNK_BYTES-start);bytes.extend_from_slice(chunk.body.0.get(start..start+count).ok_or_else(||invalid("documentary source chunk missing"))?);offset+=count;}Ok(Bytes{value:String::from_utf8(bytes).map_err(|_|invalid("documentary source is not UTF-8"))?,_reservation:reservation})}
/// A single literal whose authored interior is the stored interpreted string has exact byte mapping.
/// Escapes, concatenation, interpolation, and bytes are withheld rather than parsed a second time.
pub fn literal_content<'a>(original:&'a str,interpreted:&str)->Option<(usize,&'a str)>{
 let prefix=original.bytes().take_while(|c|c.is_ascii_alphabetic()).count();let flags=&original[..prefix];if !matches!(flags,""|"r"|"R"|"u"|"U"){return None;}let rest=&original[prefix..];let quote=if rest.starts_with("\"\"\""){ "\"\"\"" }else if rest.starts_with("'''"){ "'''" }else if rest.starts_with('"'){"\""}else if rest.starts_with('\''){"'"}else{return None};let body=rest.strip_prefix(quote)?.strip_suffix(quote)?;if body.contains(quote)||body!=interpreted{return None;}Some((prefix+quote.len(),body))
}
/// Byte offsets into the original prose. A same-length line-break view avoids splitting soft wraps.
pub fn first_sentence(prose:&str,b:&ResourceBudget)->Result<Option<(usize,usize)>,ModelError>{
 let trimmed=prose.trim_start();let start=prose.len()-trimmed.len();if trimmed.is_empty(){return Ok(None);}let mut end=prose.len();let mut offset=start;for (index,line) in trimmed.split_inclusive('\n').enumerate(){let t=line.trim();if index>0&&(t.is_empty()||t.ends_with(':')||t.starts_with(':')||t.starts_with(">>>")||t.chars().all(|c|c=='-'||c=='=')){end=offset;break;}offset+=line.len();}
 let Some(segment)=prose.get(start..end) else{return Err(invalid("documentary paragraph offsets differ"))};let _reservation=b.reserve("synthesis-sentence-boundary",segment.len())?;let view=segment.replace(['\r','\n']," ");let Some((i,s))=view.split_sentence_bound_indices().next() else{return Ok(None)};let s=s.trim_end();if s.is_empty(){return Ok(None);}Ok(Some((start+i,start+i+s.len())))
}
fn boundary(o:&mut Output,m:Id<CatalogMemberInvocation>,c:Option<Id<CatalogCandidate>>,reason:DocumentaryBoundaryReason)->Result<(),ModelError>{o.boundaries.insert(DocumentaryBoundary{member:m,candidate:c,reason})?;Ok(())}
pub fn build(d:&Data,b:&ResourceBudget)->Result<Output,ModelError>{
 let _admission=b.reserve("synthesis-documentary-build",512)?;let mut out=Output::new(b);
 for frame in d.member_frames.iter(){let member=need(&d.members,frame.member)?;let invocation=need(&d.core_invocations,frame.invocation)?;if member.input!=invocation.input{return Err(invalid("documentary member crosses input"));}let mut candidates=0;
  for candidate in d.candidates.iter(){let link=need(&d.exposures,candidate.exposure)?;if link.member!=member.id(){continue;}let public=need(&d.public_exposures,link.exposure)?;if public.context!=invocation.context{continue;}candidates+=1;let Some(subject)=entity(d,candidate)? else{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::NoSourceDeclaration)?;continue};let Some(declaration)=source_declaration(d,subject)? else{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::NoSourceDeclaration)?;continue};
  let source=need(&d.occurrences,declaration)?.source;if need(&d.artifacts,source)?.input!=invocation.input{return Err(invalid("documentary source crosses input"));}let mut declarations=0;
  for row in d.declarations.iter().filter(|r|r.declaration==declaration){let q=need(&d.qualifications,row.qualification)?;if q.context!=invocation.context{continue;}declarations+=1;let Some(docstring)=row.docstring else{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::NoDocstring)?;continue};let Some(declaration_premise)=native(d,|p|matches!(p,NativeAssertionPremise::DeclarationObservation{assertion,..}if *assertion==row.id()),row.qualification)? else{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::NativeEvidenceUnavailable)?;continue};
  let statement=need(&d.occurrences,docstring)?;if statement.source!=source||statement.syntax_kind!=SyntaxKind::StmtExpr{return Err(invalid("documentary statement ownership differs"));}let mut children=0;
  for placement in d.placements.iter().filter(|p|p.parent==Some(docstring)&&p.field==crate::domain::lexical::SyntaxField::Value&&p.ordinal==0&&p.qualification==row.qualification){let occurrence=need(&d.occurrences,placement.occurrence)?;if occurrence.source!=source||occurrence.syntax_kind!=SyntaxKind::ExprStringLiteral{continue;}children+=1;if children>1{return Err(invalid("ambiguous documentary literal placement"));}let Some(placement_premise)=native(d,|p|matches!(p,NativeAssertionPremise::SyntaxPlacement{assertion,..}if *assertion==placement.id()),placement.qualification)? else{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::NativeEvidenceUnavailable)?;continue};let mut details=0;
  for detail in d.details.iter().filter(|r|r.occurrence==occurrence.id()&&r.qualification==row.qualification){let SyntaxDetail::Literal{literal}=need(&d.detail_values,detail.detail)? else{continue};let Literal::String{value}=need(&d.literals,*literal)? else{continue};details+=1;if details>1{return Err(invalid("ambiguous documentary string detail"));}let Some(detail_premise)=native(d,|p|matches!(p,NativeAssertionPremise::SyntaxDetailObservation{assertion,..}if *assertion==detail.id()),detail.qualification)? else{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::NativeEvidenceUnavailable)?;continue};let bytes=read(d,occurrence,b)?;let Some((body_offset,prose))=literal_content(&bytes.value,value.as_str()) else{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::UnsupportedLiteralMapping)?;continue};let Some((start,end))=first_sentence(prose,b)? else{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::EmptySummary)?;continue};
  let prose_id=out.slices.insert(ProseSlice{literal:occurrence.id(),start:body_offset as i64,end:(body_offset+prose.len()) as i64})?;let excerpt=out.slices.insert(ProseSlice{literal:occurrence.id(),start:(body_offset+start) as i64,end:(body_offset+end) as i64})?;
  let qualification=AssertionQualification{modality:q.modality.weakest(Modality::Candidate),approximation:q.approximation.join(Approximation::Over),..q.clone()};out.qualifications.insert(qualification.clone())?;out.conclusions.insert(DocumentaryConclusion{member:frame.id(),candidate:candidate.id(),declaration:declaration_premise.id(),placement:placement_premise.id(),detail:detail_premise.id(),subject,docstring,prose:prose_id,excerpt,literal:*literal,excerpt_digest:ContentHash::of(prose[start..end].as_bytes()),qualification:qualification.id()})?;
  }if details==0{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::NativeEvidenceUnavailable)?;}}
  if children==0{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::NativeEvidenceUnavailable)?;}}
  if declarations==0{boundary(&mut out,frame.id(),Some(candidate.id()),DocumentaryBoundaryReason::NoSourceDeclaration)?;}}
  if candidates==0{boundary(&mut out,frame.id(),None,DocumentaryBoundaryReason::NoSourceDeclaration)?;}
 }Ok(out)
}
pub fn invariants()->Vec<Invariant>{let mut inputs=Data::validation_inputs();for i in Output::validation_inputs(){if !inputs.iter().any(|v|v.name()==i.name()){inputs.push(i);}}vec![Invariant{name:"synthesis_documentary_replay",inputs,create:std::sync::Arc::new(|b|Box::new(Check{budget:b.clone(),data:Data::new(b),output:Output::new(b)}))}]}
struct Check{budget:ResourceBudget,data:Data,output:Output}
impl InvariantCheck for Check{fn visit(&mut self,n:&str,b:&arrow_array::RecordBatch)->Result<(),ModelError>{let input=self.data.visit(n,b)?;let output=self.output.visit(n,b)?;if !input&&!output{return Err(invalid("undeclared documentary invariant input"));}Ok(())}fn finish(self:Box<Self>)->Result<(),ModelError>{let expected=build(&self.data,&self.budget)?;self.output.matches(&expected)}}

#[cfg(test)]mod tests{
 use super::*;
 fn id<T>(n:u8)->Id<T>{serde::Deserialize::deserialize(serde::de::value::SeqDeserializer::<_,serde::de::value::Error>::new([n;16].into_iter())).unwrap()}
 fn pair(d:&mut Data,p:NativeAssertionPremise,q:&AssertionQualification){let n=NativeQualification{premise:p.id(),qualification:q.id(),family:p.family(),fidelity:Fidelity::NativeStructural,status:EvidenceStatus::StructurallyObserved};d.native.insert(p).unwrap();d.native_qualifications.insert(n).unwrap();}
 fn fixture(original:&str,interpreted:&str)->(ResourceBudget,Data,Id<CatalogMemberInvocation>){
  let b=ResourceBudget::fixed(32<<20).unwrap();let mut d=Data::new(&b);let source=SourceArtifact::from_bytes(id(1),"api.py".into(),original.as_bytes()).unwrap();for c in ArtifactChunk::split(&source,original.as_bytes()).unwrap(){d.chunks.insert(c).unwrap();}d.artifacts.insert(source.clone()).unwrap();let module=d.modules.insert(Module{source:source.id(),qualified_name:"pkg.api".into()}).unwrap();let q=AssertionQualification{context:id(2),scope:CoverageScope::Artifact{artifact:source.id()}.id(),condition:conditions::Diagram::always().id(),modality:Modality::Definite,approximation:Approximation::Exact};d.qualifications.insert(q.clone()).unwrap();
  let declaration=d.occurrences.insert(Occurrence{source:source.id(),start:0,end:original.len() as i64,syntax_kind:SyntaxKind::StmtFunctionDef,role:OccurrenceRole::Syntax,structural_path:vec![]}).unwrap();let docstring=d.occurrences.insert(Occurrence{source:source.id(),start:0,end:original.len() as i64,syntax_kind:SyntaxKind::StmtExpr,role:OccurrenceRole::Syntax,structural_path:vec![0]}).unwrap();let literal_occurrence=d.occurrences.insert(Occurrence{source:source.id(),start:0,end:original.len() as i64,syntax_kind:SyntaxKind::ExprStringLiteral,role:OccurrenceRole::Syntax,structural_path:vec![0,0]}).unwrap();
  let member=d.members.insert(CatalogMember{input:source.input,access:module,path:vec!["run".into()],name:"run".into()}).unwrap();let invocation=analysis::catalog_core::Invocation::new(source.input,q.context,id(3),None,[]).0;d.core_invocations.insert(invocation.clone()).unwrap();let frame=d.member_frames.insert(CatalogMemberInvocation{member,invocation:invocation.id()}).unwrap();
  let exposure=d.public_exposures.insert(PublicExposure{access:module,context:q.context,observation:id(4),origin:id(5),status:ResolutionStatus::Unresolved,reason:EntityReason::UntracedExposure}).unwrap();let link=d.exposures.insert(CatalogExposure{member,exposure}).unwrap();let callable=d.callables.insert(CallableEntity::Source{declaration,kind:CallableKind::Function}).unwrap();let entity=d.refs.insert(EntityRef::Callable{callable}).unwrap();let ec=d.entity_candidates.insert(SymbolEntityCandidate{resolution:id(6),entity}).unwrap();d.candidates.insert(CatalogCandidate{exposure:link,candidate:Some(id(7)),entity:Some(ec),path:None,alias:None}).unwrap();
  let row=DeclarationObservation{qualification:q.id(),declaration,name:id(8),kind:DeclarationKind::Function,parent:None,overload:false,docstring:Some(docstring)};d.declarations.insert(row.clone()).unwrap();pair(&mut d,NativeAssertionPremise::DeclarationObservation{assertion:row.id(),support:id(9)},&q);
  let placement=SyntaxPlacement{qualification:q.id(),occurrence:literal_occurrence,parent:Some(docstring),field:crate::domain::lexical::SyntaxField::Value,ordinal:0};d.placements.insert(placement.clone()).unwrap();pair(&mut d,NativeAssertionPremise::SyntaxPlacement{assertion:placement.id(),support:id(10)},&q);
  let literal=d.literals.insert(Literal::String{value:interpreted.into()}).unwrap();let value=d.detail_values.insert(SyntaxDetail::Literal{literal}).unwrap();let detail=SyntaxDetailObservation{qualification:q.id(),occurrence:literal_occurrence,ordinal:0,detail:value};d.details.insert(detail.clone()).unwrap();pair(&mut d,NativeAssertionPremise::SyntaxDetailObservation{assertion:detail.id(),support:id(11)},&q);(b,d,frame)
 }
 fn replay(d:&Data,o:&Output,b:&ResourceBudget)->Result<(),ModelError>{let mut c=(invariants().remove(0).create)(b);macro_rules! input{($($f:ident:$ty:ty,)*)=>{$(c.visit(<$ty>::NAME,&<$ty as Record>::encode(&d.$f.iter().cloned().collect::<Vec<_>>())?)?;)*};}crate::synthesis_documentary_inputs!(input);macro_rules! output{($($f:ident:$ty:ty,)*)=>{$(c.visit(<$ty>::NAME,&<$ty as Record>::encode(&o.$f.iter().cloned().collect::<Vec<_>>())?)?;)*};}outputs!(output);c.finish()}
 #[test]fn exact_unicode_soft_wrapped_outcome_retains_full_prose_and_candidate(){
  let text="\"\"\"Run it — fast\n    across contexts. Then stop.\n\nWarnings:\n    This is authored caution.\n\"\"\"";let (b,d,frame)=fixture(text,&text[3..text.len()-3]);let out=build(&d,&b).unwrap();assert_eq!(out.conclusions.len(),1);assert!(out.boundaries.is_empty());let c=out.conclusions.iter().next().unwrap();assert_eq!(c.member,frame);let ProseSlice{start,end,..}=out.slices.get(c.excerpt).unwrap();assert_eq!(&text[*start as usize..*end as usize],"Run it — fast\n    across contexts.");let ProseSlice{start,end,..}=out.slices.get(c.prose).unwrap();assert!(text[*start as usize..*end as usize].contains("authored caution"));let q=out.qualifications.get(c.qualification()).unwrap();assert_eq!((q.modality,q.approximation),(Modality::Candidate,Approximation::Over));assert_eq!(c.source_facts().status,EvidenceStatus::Documented);replay(&d,&out,&b).unwrap();
 }
 #[test]fn unsupported_literal_mapping_is_explicit_and_never_becomes_display_evidence(){for (raw,value)in[("\"Escaped\\ntext.\"","Escaped\ntext."),("f\"Interpolated {x}.\"","Interpolated {x}."),("\"First.\" \"Second.\"","First.Second."),("b\"Bytes.\"","Bytes.")]{let (b,d,_)=fixture(raw,value);let out=build(&d,&b).unwrap();assert!(out.conclusions.is_empty());assert!(out.boundaries.iter().any(|r|r.reason==DocumentaryBoundaryReason::UnsupportedLiteralMapping));replay(&d,&out,&b).unwrap();}assert_eq!(literal_content("r'''A\\b.'''","A\\b."),Some((4,"A\\b.")));}
 #[test]fn missing_native_support_or_wrong_typed_edge_never_guesses_a_docstring(){let(b,mut d,_)=fixture("\"Run.\"","Run.");d.native=Rows::new(&b);let out=build(&d,&b).unwrap();assert!(out.conclusions.is_empty());assert!(out.boundaries.iter().any(|r|r.reason==DocumentaryBoundaryReason::NativeEvidenceUnavailable));let(b,mut d,_)=fixture("\"Run.\"","Run.");let mut p=d.placements.iter().next().unwrap().clone();p.field=crate::domain::lexical::SyntaxField::Body;d.placements=Rows::new(&b);d.placements.insert(p).unwrap();assert!(build(&d,&b).unwrap().conclusions.is_empty());}
 #[test]fn context_and_literal_identity_are_not_spelling_or_equal_span_guesses(){let(b,mut d,_)=fixture("\"Run.\"","Run.");let mut p=d.public_exposures.iter().next().unwrap().clone();p.context=id(50);d.public_exposures=Rows::new(&b);d.public_exposures.insert(p).unwrap();let mut link=d.exposures.iter().next().unwrap().clone();link.exposure=d.public_exposures.iter().next().unwrap().id();d.exposures=Rows::new(&b);let linkid=d.exposures.insert(link).unwrap();let mut c=d.candidates.iter().next().unwrap().clone();c.exposure=linkid;d.candidates=Rows::new(&b);d.candidates.insert(c).unwrap();let out=build(&d,&b).unwrap();assert!(out.conclusions.is_empty());assert!(out.boundaries.iter().any(|r|r.candidate.is_none()));let(b,mut d,_)=fixture("\"Run.\"","Different.");assert!(build(&d,&b).unwrap().conclusions.is_empty());d.chunks=Rows::new(&b);assert!(build(&d,&b).is_err());}
 #[test]fn replay_refuses_forged_excerpt_qualification_support_or_coupled_deletion(){let(b,d,_)=fixture("\"Run it. Then stop.\"","Run it. Then stop.");for case in 0..4{let mut out=build(&d,&b).unwrap();let mut row=out.conclusions.iter().next().unwrap().clone();match case{0=>{row.excerpt_digest=ContentHash::of(b"forged");out.conclusions=Rows::new(&b);out.conclusions.insert(row).unwrap();},1=>{row.qualification=id(60);out.conclusions=Rows::new(&b);out.conclusions.insert(row).unwrap();},2=>{row.declaration=id(61);out.conclusions=Rows::new(&b);out.conclusions.insert(row).unwrap();},_=>{out.conclusions=Rows::new(&b);out.boundaries=Rows::new(&b);out.slices=Rows::new(&b);out.qualifications=Rows::new(&b);}}assert!(replay(&d,&out,&b).is_err());}}
 #[test]fn first_paragraph_section_boundaries_empty_and_budget_refusal(){let b=ResourceBudget::fixed(1<<20).unwrap();let text="Get a setting\n    Args:\n        key: Name.";let(s,e)=first_sentence(text,&b).unwrap().unwrap();assert_eq!(&text[s..e],"Get a setting");assert_eq!(first_sentence(" \n ",&b).unwrap(),None);let(b,d,_)=fixture("\"Run.\"","Run.");let tiny=ResourceBudget::fixed(1).unwrap();assert!(matches!(build(&d,&tiny),Err(ModelError::Resource{..})));assert_eq!(tiny.reserved(),0);assert_eq!(build(&d,&b).unwrap().conclusions.len(),1);}
}
