//! PARTIAL RESTART CHECKPOINT — not declared by synthesis/mod.rs or any producer.
//!
//! Proposed native MDX component operation, not compiled or qualified. Before activation:
//! add exact component/attribute/declared-option inputs to documentary::Data; add the
//! DocumentarySource::Component arm, component boundary output and authored constructor;
//! wire producer, shared replay, assertion policy/rendering and canonical source hash;
//! resolve the budget API in option(); retain source/effective ambiguity; add the actual
//! native Warning/ParamField and unknown/nested/inline/fenced/forged-span controls.
//! Existing Documentary13 remains the intended authored-prose authority, not behavior.
use crate::{Domain,DomainCode};use crate::domain::{*,analysis::native::NativeAssertionPremise,normalized::Rows,catalog::*,documents::*,resources::ResourceBudget};use super::documentary::{self,Data,Output,DocumentarySource,DocumentaryConclusion,ProseSource,ProseSlice};
#[derive(Debug,Clone,Copy,PartialEq,Eq,Hash,DomainCode)]#[repr(i16)]pub enum ComponentRole{Warning=0,Parameter=1}
#[derive(Debug,Clone,Copy,PartialEq,Eq,Hash,DomainCode)]#[repr(i16)]pub enum BoundaryReason{NativeEvidenceUnavailable=0,UnknownField=1,AmbiguousField=2,NestedField=3,MissingOriginalSpan=4,ForeignContext=5}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]#[model(name="synthesis_documentary_component_boundaries")]
pub struct ComponentBoundary{#[model(key)]pub member:Id<CatalogMemberInvocation>,#[model(key)]pub association:Id<evidence::DocumentAssociation>,#[model(key)]pub component:Id<DocumentComponentObservation>,#[model(key)]pub reason:BoundaryReason}
fn invalid(s:&str)->ModelError{ModelError::Invalid(s.into())}fn need<R:Record>(r:&Rows<R>,id:Id<R>)->Result<&R,ModelError>{r.get(id).ok_or_else(||invalid("documentary template premise absent"))}
fn native(d:&Data,q:Id<assertion::AssertionQualification>,predicate:impl Fn(&NativeAssertionPremise)->bool)->Option<Id<NativeAssertionPremise>>{d.native.iter().filter(|r|predicate(r)&&d.native_qualifications.iter().any(|n|n.premise==r.id()&&n.qualification==q&&n.family==attribution::FactFamily::Docs&&n.status==analysis::policy::EvidenceStatus::Documented&&n.fidelity!=attribution::Fidelity::DisplayOnly)).map(Record::id).min()}
fn literal_attribute<'a>(d:&'a Data,component:DocumentNodeComponentId,name:&str,q:Id<assertion::AssertionQualification>)->Result<Option<(&'a str,Id<NativeAssertionPremise>)>,ModelError>{let mut found=None;for a in d.component_attributes.iter().filter(|a|a.component==component&&a.qualification==q){let DocumentAttributeValue::Literal{name:n,value}=need(&d.component_values,a.value)?else{continue};if n!=name{continue;}let Some(premise)=native(d,q,|p|matches!(p,NativeAssertionPremise::DocumentAttributeObservation{assertion,..}if *assertion==a.id()))else{return Ok(None)};if found.is_some(){return Ok(None);}found=Some((value.as_str(),premise));}Ok(found)}
fn parent<'a>(d:&'a Data,row:&DocumentComponentObservation)->Result<Option<&'a DocumentComponentObservation>,ModelError>{let Some(parent)=row.parent else{return Ok(None)};let mut rows=d.components.iter().filter(|r|r.component==parent&&r.qualification==row.qualification&&r.passage==row.passage);let found=rows.next().ok_or_else(||invalid("native component parent unavailable"))?;if rows.next().is_some(){return Err(invalid("native component parent ambiguous"));}Ok(Some(found))}
fn nearest_field<'a>(d:&'a Data,row:&DocumentComponentObservation)->Result<Option<&'a DocumentComponentObservation>,ModelError>{let mut p=parent(d,row)?;for _ in 0..=d.components.len(){let Some(row)=p else{return Ok(None)};if native(d,row.qualification,|p|matches!(p,NativeAssertionPremise::DocumentComponentObservation{assertion,..}if *assertion==row.id())).is_none(){return Err(invalid("nearest component ancestry lacks native evidence"));}if row.name.as_deref()==Some("ParamField"){return Ok(Some(row));}p=parent(d,row)?;}Err(invalid("document component ancestry cycle"))}
/// This is lookup of an authored public parameter label, never source/effective correspondence.
fn option(d:&Data,member:Id<CatalogMember>,name:&str,context:Id<attribution::AnalysisContext>)->Result<Result<Id<CatalogOption>,BoundaryReason>,ModelError>{let mut effective=Rows::new(d.options.budget());let mut original=Rows::new(d.options.budget());for option in d.options.iter().filter(|r|r.member==member){match need(&d.option_subjects,option.subject)?{CatalogOptionSubject::Parameter{slot}=>{let slot=need(&d.option_slots,*slot)?;if need(&d.option_variants,slot.variant)?.context!=context{continue;}let shape=need(&d.parameter_shapes,need(&d.signature_parameters,slot.parameter)?.shape)?;if shape.name.as_ref().is_some_and(|n|n.as_str()==name){effective.insert(option.clone())?;}},CatalogOptionSubject::SourceParameter{parameter}=>{let mut matches=false;for link in d.parameter_links.iter().filter(|l|l.entity==*parameter){let p=need(&d.signature_parameters,link.parameter)?;let signature=need(&d.parameter_signatures,p.signature)?;if need(&d.qualifications,signature.qualification)?.context!=context{continue;}let shape=need(&d.parameter_shapes,p.shape)?;matches|=shape.name.as_ref().is_some_and(|n|n.as_str()==name);}if matches{original.insert(option.clone())?;}},_=>{}}}if effective.len()>1||original.len()>1{return Ok(Err(BoundaryReason::AmbiguousField));}Ok(effective.iter().next().or_else(||original.iter().next()).map(Record::id).ok_or(BoundaryReason::UnknownField))}
fn boundary(out:&mut Output,member:Id<CatalogMemberInvocation>,association:Id<evidence::DocumentAssociation>,component:Id<DocumentComponentObservation>,reason:BoundaryReason)->Result<(),ModelError>{out.component_boundaries.insert(ComponentBoundary{member,association,component,reason})?;Ok(())}
pub fn build(d:&Data,out:&mut Output,b:&ResourceBudget)->Result<(),ModelError>{for frame in d.member_frames.iter(){let inv=need(&d.core_invocations,frame.invocation)?;for association in d.document_associations.iter().filter(|a|a.member==frame.member){let candidate=need(&d.mention_candidates,association.candidate)?;let exposure=need(&d.public_exposures,candidate.exposure)?;if exposure.context!=inv.context||!d.exposures.iter().any(|e|e.member==frame.member&&e.exposure==exposure.id()){continue;}let assessment=need(&d.mention_assessments,candidate.assessment)?;let mention=need(&d.mentions,assessment.observation)?;let q=need(&d.qualifications,mention.qualification)?;if q.context!=inv.context{continue;}let Some(scope)=native(d,mention.qualification,|p|matches!(p,NativeAssertionPremise::DocumentMentionObservation{assertion,..}if *assertion==mention.id()))else{continue};
 for component in d.components.iter().filter(|c|c.passage==mention.passage){let Some(role)=(match component.name.as_deref(){Some("Warning")=>Some(ComponentRole::Warning),Some("ParamField")=>Some(ComponentRole::Parameter),_=>None})else{continue};let cq=need(&d.qualifications,component.qualification)?;if(cq.context,cq.scope,cq.condition)!=(q.context,q.scope,q.condition){boundary(out,frame.id(),association.id(),component.id(),BoundaryReason::ForeignContext)?;continue;}let Some(premise)=native(d,component.qualification,|p|matches!(p,NativeAssertionPremise::DocumentComponentObservation{assertion,..}if *assertion==component.id()))else{boundary(out,frame.id(),association.id(),component.id(),BoundaryReason::NativeEvidenceUnavailable)?;continue};let nearest=nearest_field(d,component)?;
 if role==ComponentRole::Parameter&&nearest.is_some(){boundary(out,frame.id(),association.id(),component.id(),BoundaryReason::NestedField)?;continue;}
 let field=if role==ComponentRole::Parameter{Some(component)}else{nearest};let(mut field_premise,mut option_id)=(None,None);if let Some(field)=field{let Some((label,attribute))=literal_attribute(d,field.component,"body",field.qualification)?else{boundary(out,frame.id(),association.id(),component.id(),BoundaryReason::UnknownField)?;continue};match option(d,frame.member,label,inv.context)?{Ok(option)=>{field_premise=Some(attribute);option_id=Some(option);},Err(reason)=>{boundary(out,frame.id(),association.id(),component.id(),reason)?;continue;}}}
 let Some(inner)=component.inner else{boundary(out,frame.id(),association.id(),component.id(),BoundaryReason::MissingOriginalSpan)?;continue};let excerpt=if role==ComponentRole::Parameter{let Some(lead)=component.lead else{boundary(out,frame.id(),association.id(),component.id(),BoundaryReason::MissingOriginalSpan)?;continue};lead}else{inner};let body=ProseSource::Span{span:inner};let clip=ProseSource::Span{span:excerpt};let(a,s,e)=documentary::original(d,&body)?;let(c,cs,ce)=documentary::original(d,&clip)?;let passage=ProseSource::Span{span:need(&d.nodes,mention.passage.id())?.span()};let(pa,ps,pe)=documentary::original(d,&passage)?;if a!=c||a!=pa||cs<s||ce>e||s<ps||e>pe||cq.scope!=(source::CoverageScope::Artifact{artifact:a}).id(){return Err(invalid("documentary component inner/lead is not its exact original passage"));}let title=literal_attribute(d,component.component,"title",component.qualification)?.map(|(_,p)|p);let source_input=need(&d.artifacts,a)?.input;let source=out.sources.insert(DocumentarySource::Component{member:frame.id(),association:association.id(),component:component.id(),premise,scope,field:field_premise,title,option:option_id,role,source_input,source_qualification:component.qualification})?;let prose_source=out.prose_sources.insert(body)?;let excerpt_source=out.prose_sources.insert(clip)?;let prose=out.slices.insert(ProseSlice{source:prose_source,start:0,end:e-s})?;let excerpt=out.slices.insert(ProseSlice{source:excerpt_source,start:0,end:ce-cs})?;let text=documentary::read_range(d,c,cs,ce,b)?;let qualification=assertion::AssertionQualification{context:inv.context,scope:(source::CoverageScope::Input{input:inv.input}).id(),condition:conditions::Diagram::always().id(),modality:attribution::Modality::Candidate,approximation:assertion::Approximation::Over};out.qualifications.insert(qualification.clone())?;out.conclusions.insert(DocumentaryConclusion::authored(source,prose,excerpt,ContentHash::of(text.value.as_bytes()),qualification.id(),analysis::policy::EvidenceStatus::Documented))?;
 }
 }}Ok(())}
pub fn text(d:&Data,out:&Output,c:&DocumentaryConclusion,b:&ResourceBudget)->Result<String,ModelError>{let DocumentarySource::Component{component,title,option,role,..}=need(&out.sources,c.source)?else{return Err(invalid("documentary component template has another source"))};let component=need(&d.components,*component)?;let part=documentary::read_slice(d,out,need(&out.slices,c.excerpt)?,b)?;let _allowance=b.reserve("documentary-component-template",part.value.len()+512)?;let base=ProseSource::Span{span:need(&d.nodes,component.passage.id())?.span()};let(a,_,_)=documentary::original(d,&base)?;let path=&need(&d.artifacts,a)?.path;let heading=d.passages.iter().find(|p|p.passage==component.passage&&p.qualification==component.qualification).and_then(|p|p.heading.as_deref()).unwrap_or("preamble");let mut label=String::new();if let Some(option)=option{let option=need(&d.options,*option)?;label=match need(&d.option_subjects,option.subject)?{CatalogOptionSubject::Parameter{slot}=>format!(", about declared effective signature slot {}",slot.hex()),CatalogOptionSubject::SourceParameter{parameter}=>format!(", about original source parameter {}; effective applicability remains unresolved",parameter.hex()),_=>return Err(invalid("documented component parameter is not a declared parameter"))};}let titled=if let Some(title)=title{let premise=need(&d.native,*title)?;let NativeAssertionPremise::DocumentAttributeObservation{assertion,..}=premise else{return Err(invalid("documentary title lacks native attribute"))};let attr=need(&d.component_attributes,*assertion)?;let DocumentAttributeValue::Literal{value,..}=need(&d.component_values,attr.value)?else{return Err(invalid("documentary title is not literal"))};format!(" (“{value}”)")}else{String::new()};Ok(format!("The documentation {}{titled}{label}, in `{path}` § {heading}: {}",if *role==ComponentRole::Warning{"warns"}else{"describes this parameter"},part.value))}
