//! Finite admitted capability contracts. Unbound method/capability pairs refuse activation.
//! Input scopes come from captured artifact roles; result observations never select the universe.
use super::{invalid,AnalysisMethod,AnalysisCapability};
use crate::domain::{*,attribution::{AnalysisContext,ProviderCoverage,FactFamily},input::{InputRevision,ArtifactUse},source::{SourceArtifact,CoverageScope},normalized::coverage::{Capability,NormalizationComputation,NormalizationCoverage},stages::{Profile,ReadPermit}};
#[derive(Clone,Copy)]
pub(crate) struct Contract {pub capability:AnalysisCapability,pub native:&'static [FactFamily],pub normalized:&'static [Capability],pub behavioral:bool}
pub(crate) fn contract(method:AnalysisMethod,capability:AnalysisCapability)->Result<Contract,ModelError> {match (method,capability) {(AnalysisMethod::LocalTransfers,AnalysisCapability::Transfers)=>Ok(Contract {capability,native:&[FactFamily::Flow],normalized:&[Capability::FlowLinks,Capability::FlowEvents,Capability::Bindings],behavioral:true}),(AnalysisMethod::Catalog,AnalysisCapability::Catalog)=>Ok(Contract {capability,native:&[],normalized:&[Capability::PublicExposure,Capability::Callables],behavioral:false}),_=>Err(invalid("analysis method/capability contract is not bound"))}}
pub(crate) fn method_contract(method:AnalysisMethod)->Result<Contract,ModelError> {match method {AnalysisMethod::LocalTransfers=>contract(method,AnalysisCapability::Transfers),AnalysisMethod::Catalog=>contract(method,AnalysisCapability::Catalog),_=>Err(invalid("analysis method has no admitted capability contract"))}}
pub(crate) fn inputs(native:bool)->Vec<ValidationInput> {let mut inputs=vec![ValidationInput::of::<InputRevision>(&["id"]),ValidationInput::of::<SourceArtifact>(&["id"]),ValidationInput::of::<ArtifactUse>(&["id"]),ValidationInput::of::<CoverageScope>(&["id"]),ValidationInput::of::<NormalizationComputation>(&["id"]),ValidationInput::of::<NormalizationCoverage>(&["id"])];if native {inputs.push(ValidationInput::of::<ProviderCoverage>(&["id"]));}inputs}
pub(crate) struct FrontierIndex {charge:charged::StateCharge,profile:Profile,inputs:charged::ChargedMap<Id<InputRevision>,InputRevision>,artifacts:charged::ChargedMap<Id<SourceArtifact>,SourceArtifact>,uses:charged::ChargedMap<Id<ArtifactUse>,ArtifactUse>,scopes:charged::ChargedMap<Id<CoverageScope>,CoverageScope>,computations:charged::ChargedMap<Id<NormalizationComputation>,NormalizationComputation>,normalized:charged::ChargedMap<Id<NormalizationCoverage>,NormalizationCoverage>,native:charged::ChargedMap<Id<ProviderCoverage>,ProviderCoverage>}
impl FrontierIndex {
    pub(crate) fn set_profile(&mut self,profile:Profile) {self.profile=profile;}
    pub(crate) fn new(profile:Profile,budget:&resources::ResourceBudget)->Self {Self {charge:charged::StateCharge::new(budget,"analysis_expected_frontier"),profile,inputs:Default::default(),artifacts:Default::default(),uses:Default::default(),scopes:Default::default(),computations:Default::default(),normalized:Default::default(),native:Default::default()}}
    pub(crate) fn visit(&mut self,relation:&str,batch:&arrow_array::RecordBatch)->Result<bool,ModelError> {macro_rules! insert {($r:ty,$field:ident)=>{if relation==<$r>::NAME {for row in <$r>::decode(batch)? {if self.$field.insert(&mut self.charge,row.id(),row)?.is_some() {return Err(ModelError::Conflict(<$r>::NAME));}}return Ok(true);}};}insert!(InputRevision,inputs);insert!(SourceArtifact,artifacts);insert!(ArtifactUse,uses);insert!(CoverageScope,scopes);insert!(NormalizationComputation,computations);insert!(NormalizationCoverage,normalized);insert!(ProviderCoverage,native);Ok(false)}
    pub(crate) fn domain(&self,input:Id<InputRevision>,context:Id<AnalysisContext>,contract:Contract)->Result<ExpectedDomain,ModelError> {
        if !self.inputs.contains_key(&input) {return Err(invalid("expected analysis input absent"));}
        let budget=self.charge.budget().ok_or_else(||invalid("expected frontier budget absent"))?;
        let bytes=self.artifacts.values().try_fold(0usize,|n,r|n.checked_add(size_of::<SourceArtifact>()+r.heap_bytes()+256)).and_then(|n|n.checked_add(self.uses.len().checked_mul(size_of::<ArtifactUse>()+256)?)).ok_or_else(||invalid("expected root allocation overflow"))?;
        let source_bytes=self.native.values().try_fold(0usize,|n,r|n.checked_add(size_of::<ProviderCoverage>()+r.heap_bytes()+32)).and_then(|n|n.checked_add(self.normalized.len().checked_mul(size_of::<NormalizationCoverage>()+32)?)).and_then(|n|n.checked_add(self.computations.len().checked_mul(size_of::<&NormalizationComputation>())?)).ok_or_else(||invalid("expected lower allocation overflow"))?;
        let reservation=budget.reserve("analysis_expected_roots",bytes.checked_add(source_bytes).and_then(|n|n.checked_add(self.artifacts.len().checked_mul(size_of::<ExpectedScope>()+128)?)).and_then(|n|n.checked_add(size_of::<ExpectedScope>())).ok_or_else(||invalid("expected domain allocation overflow"))?)?;
        let artifacts=self.artifacts.values().cloned().collect::<Vec<_>>();let uses=self.uses.values().cloned().collect::<Vec<_>>();
        let roots=admission::analysis_roots(&artifacts,&uses)?;
        let mut selected=charged::ChargedMap::default();let mut charge=charged::StateCharge::new(budget,"analysis_expected_scopes");
        for artifact in self.artifacts.values().filter(|r|r.input==input && roots.contains(&r.id()) && admission::ArtifactClass::of(&r.path)==Some(admission::ArtifactClass::PythonSource)) {let scope=CoverageScope::Artifact {artifact:artifact.id()};if self.scopes.get(&scope.id())!=Some(&scope) {return Err(invalid("expected captured artifact scope absent"));}selected.insert(&mut charge,scope.id(),scope)?;}
        let requested=!contract.behavioral || self.profile==Profile::Behavioral;
        if selected.is_empty() {let scope=CoverageScope::Input {input};if self.scopes.get(&scope.id())!=Some(&scope) {return Err(invalid("empty input analysis scope absent"));}return Ok(ExpectedDomain {scopes:vec![ExpectedScope {scope:scope.id(),context,requested,no_scope:requested,native:vec![],normalized:vec![]}],_reservation:reservation});}
        let _outputs=budget.reserve("analysis_expected_domain",selected.len().checked_mul(size_of::<ExpectedScope>()+256).ok_or_else(||invalid("expected scope output allocation overflow"))?)?;
        let mut out=Vec::with_capacity(selected.len());
        for (scope,_) in selected.iter() {
            let mut native=Vec::new();let mut normalized=Vec::new();
            for family in contract.native {let rows=self.native.values().filter(|r|r.scope==*scope && r.context==context && r.family==*family).collect::<Vec<_>>();if rows.is_empty() {return Err(invalid("expected native family scope absent"));}for row in rows {row.validate()?;native.push(row.clone());}}
            for capability in contract.normalized {let computations=self.computations.values().filter(|r|r.capability==*capability).collect::<Vec<_>>();if computations.len()!=1 {return Err(invalid("expected normalized capability declaration absent or ambiguous"));}let computation=computations[0];if computation.profile!=self.profile.name() {return Err(invalid("normalized capability has another profile"));}let rows=self.normalized.values().filter(|r|r.scope==*scope && r.context==context && r.computation==computation.id()).collect::<Vec<_>>();if rows.len()!=1 {return Err(invalid("expected normalized capability scope absent or ambiguous"));}normalized.push(rows[0].clone());}
            out.push(ExpectedScope {scope:*scope,context,requested,no_scope:false,native,normalized});
        }
        Ok(ExpectedDomain {scopes:out,_reservation:reservation})
    }
}
pub(crate) struct ExpectedDomain {pub scopes:Vec<ExpectedScope>,_reservation:Box<dyn resources::Reservation>}
pub(crate) struct ExpectedScope {pub scope:Id<CoverageScope>,pub context:Id<AnalysisContext>,pub requested:bool,pub no_scope:bool,pub native:Vec<ProviderCoverage>,pub normalized:Vec<NormalizationCoverage>}
/// Capture binds the expected-domain operation to actual R0 inputs. Batch membership is independently
/// rechecked from effect-owner physical inputs before publication; this is not a new read authority.
pub struct CoverageAdmission<'a> {sources:&'a super::sources::CapturedSources,index:FrontierIndex}
impl<'a> CoverageAdmission<'a> {
    pub fn new(sources:&'a super::sources::CapturedSources,budget:&resources::ResourceBudget)->Result<Self,ModelError> {let profile=sources.profile().ok_or_else(||invalid("coverage admission requires a captured stage profile"))?;Ok(Self {sources,index:FrontierIndex::new(profile,budget)})}
    pub fn visit<R:Record>(&mut self,permit:&ReadPermit<'_,R>,batch:&arrow_array::RecordBatch)->Result<(),ModelError> {self.sources.accepts(permit)?;if !self.index.visit(R::NAME,batch)? {return Err(invalid("relation is not an expected-domain input"));}Ok(())}
    pub(crate) fn domain(&self,input:Id<InputRevision>,context:Id<AnalysisContext>,method:AnalysisMethod,capability:AnalysisCapability,source_digest:ContentHash)->Result<ExpectedDomain,ModelError> {if source_digest!=self.sources.digest() {return Err(invalid("expected domain belongs to another source capture"));}let contract=contract(method,capability)?;for input in inputs(!contract.native.is_empty()) {if !self.sources.has_relation(input.name()) {return Err(invalid("expected-domain relation was not declared and completed"));}}self.index.domain(input,context,contract)}
}
