"""The native member uses the workspace condition-kernel crate."""

from pathlib import Path

import pyarrow as pa
import pyarrow.ipc as ipc
import pytest
from lctx_semantics import (
    ConditionGraph,
    SemanticExecutor,
    catalog_limits,
    kernel_format,
    probe_compatible,
    probe_implies,
)

from lctx_mcp.generation import NATIVE_IPC_FILES, load


def test_native_condition_boundary_uses_the_rust_kernel() -> None:
    assert kernel_format() == 1
    assert catalog_limits() == (100_000, 100_000, 1_000_000)
    assert probe_compatible("truthy(a)", "!truthy(a)") is False
    assert probe_compatible("truthy(a)", "!truthy(b)") is True
    assert probe_implies("truthy(a) & truthy(b)", "truthy(a)") is True
    assert probe_implies("truthy(a)", "truthy(b)") is False
    assert probe_compatible("over_budget", "true") is None
    assert probe_compatible("truthy(a)" * 10_000, "true") is None
    with pytest.raises(ValueError):
        probe_compatible("not a condition", "true")


def test_native_catalog_distinguishes_stored_from_retained_shared_tail() -> None:
    # Generated by docs/design_review/evidence/2026-09-26_native-shared-tail/catalog_probe.rs.
    false_id = "b9902e4735719efc29674ec10253ffeb"
    tail = "582196dd0392bc0d10d69c216e22ce8e"
    true_id = "119f0180894a5ece441560e03b8236a6"
    left = "59a52ede131541f26cc2574d40b8a05d"
    right = "6bfb7e47c31c43b4f1600656c728e949"
    graph = ConditionGraph(
        kernel_format(),
        [
            ("4f0d287539d62371456550b9152b4c11", left, None),
            ("ca905e1a56c869bf28aba2053f2f71d6", right, None),
        ],
        [
            (tail, "truthy(z)", false_id, true_id),
            (left, "truthy(a)", false_id, tail),
            (right, "truthy(b)", false_id, tail),
        ],
    )
    assert graph.condition_count == 2
    assert graph.node_count == 3
    assert graph.retained_node_count == 4


def test_native_catalog_refuses_aggregate_retained_limit_before_hydration() -> None:
    # The same production catalog loader is exercised with repeated references to an
    # eleven-node root. The Rust control uses distinct, valid roots at the configured cap;
    # repetition here verifies that native admission happens before expensive copying.
    false_id = "b9902e4735719efc29674ec10253ffeb"
    true_id = "119f0180894a5ece441560e03b8236a6"
    ids = (
        "17a8c3d15be3c074398bb4b484123cc8",
        "2576b7e779e8aa40e032efe52e061641",
        "eb0d589677720f1489c6d517b4aa0066",
        "d0aff079b711428859eb0614f6867a3d",
        "62c50676ad4ea5d1fde7a36e9d09579a",
        "c0b7c125452ecd3a69ffcc24a9467696",
        "9c7ce3f7340f4bfd2d22ac4b5eb3f1e8",
        "cbe127cab1b7fac81855bec6efc7cda5",
        "796f8e76684305f20b34adc2c7291610",
        "214c3a74021a666c82559bcabd7a1fad",
        "d3473c5b395252a1f574d6698644ff7a",
    )
    nodes = [
        (node, f"truthy(z{index:02})", false_id, ids[index + 1] if index < 10 else true_id)
        for index, node in enumerate(ids)
    ]
    assert len(nodes) < catalog_limits()[1]
    conditions = [("38c7573afdd004939e33697b0dd1120e", ids[0], None)] * 90_910
    assert len(conditions) < catalog_limits()[0]
    with pytest.raises(ValueError, match="11 stored, over 1000000 expanded"):
        ConditionGraph(kernel_format(), conditions, nodes)


def test_generation_condition_graph_is_hydrated_and_rejects_bad_nodes(generation: Path) -> None:
    loaded = load(generation, None)
    graph = loaded.condition_graph
    assert graph is not None and graph.condition_count > 0 and graph.node_count > 0
    assert graph.retained_node_count > 0
    rows = loaded.tables["conditions"].to_pylist()
    condition = next(r["condition_id"].hex() for r in rows if r["root_id"] is not None)
    assert graph.compatible(condition, condition) == (True, None)
    assert graph.implies(condition, condition) == (True, None)

    conditions = [
        (
            r["condition_id"].hex(),
            None if r["root_id"] is None else r["root_id"].hex(),
            r["boundary_reason"],
        )
        for r in rows
    ]
    nodes = [
        (r["node_id"].hex(), r["atom"], r["low_id"].hex(), r["high_id"].hex())
        for r in loaded.tables["condition_nodes"].to_pylist()
    ]
    first = nodes[0]
    nodes[0] = (first[0], first[1] + "x", first[2], first[3])
    with pytest.raises(ValueError):
        ConditionGraph(kernel_format(), conditions, nodes)
    with pytest.raises(ValueError, match="format"):
        ConditionGraph(kernel_format() + 1, conditions, nodes)


def test_native_index_resolves_one_public_formal_and_its_proof(generation: Path) -> None:
    index = load(generation, None).condition_graph
    assert index is not None
    paths, boundaries, total, truncated, work = index.inspect_value_paths(
        "pkg.controls.passthrough", "options", "none", "", True, 0, 10
    )
    assert len(paths) == total == work == 1 and paths[0][1] == "established"
    assert len(paths[0][3]) > 0 and boundaries == [] and not truncated
    with pytest.raises(ValueError, match="unknown operation formal"):
        index.inspect_value_paths("pkg.controls.passthrough", "absent", "none", "", True, 0, 10)
    with pytest.raises(ValueError, match="unknown public operation"):
        index.inspect_value_paths("pkg.absent", "options", "none", "", True, 0, 10)
    with pytest.raises(ValueError, match="limit"):
        index.inspect_value_paths("pkg.controls.passthrough", "options", "none", "", True, 0, 0)


def test_native_open_boundaries_keep_sibling_origin_ids(generation: Path) -> None:
    loaded = load(generation, None)
    conditions = [
        (r["condition_id"].hex(), None if r["root_id"] is None else r["root_id"].hex(),
         r["boundary_reason"])
        for r in loaded.tables["conditions"].to_pylist()
    ]
    nodes = [
        (r["node_id"].hex(), r["atom"], r["low_id"].hex(), r["high_id"].hex())
        for r in loaded.tables["condition_nodes"].to_pylist()
    ]
    condition = next(r[0] for r in conditions if r[1] is not None)
    operation, formal, fact = ("01" * 16, "02" * 16, "03" * 16)
    index = SemanticExecutor(
        kernel_format(), loaded.snapshot_id, loaded.manifest["entry_value_effect_digest"],
        conditions, nodes, [operation], [("pkg.siblings", operation)],
        [(operation, formal, "value")], [], [],
        [(operation, formal, fact, "04" * 16, condition, "call_transfer"),
         (operation, formal, fact, "05" * 16, condition, "unsupported_control_flow")],
        [], [],
    )
    paths, open_rows, total, truncated, work = index.inspect_value_paths(
        "pkg.siblings", "value", "none", "", True, 0, 2
    )
    assert paths == [] and total == work == 2 and not truncated
    assert {(row[1], row[3]) for row in open_rows} == {
        ("04" * 16, "call_transfer"),
        ("05" * 16, "unsupported_control_flow"),
    }


def test_native_index_refuses_missing_proof_steps(generation: Path) -> None:
    loaded = load(generation, None)
    conditions = [
        (
            r["condition_id"].hex(),
            None if r["root_id"] is None else r["root_id"].hex(),
            r["boundary_reason"],
        )
        for r in loaded.tables["conditions"].to_pylist()
    ]
    nodes = [
        (r["node_id"].hex(), r["atom"], r["low_id"].hex(), r["high_id"].hex())
        for r in loaded.tables["condition_nodes"].to_pylist()
    ]
    condition = next(r[0] for r in conditions if r[1] is not None)
    operation, formal, summary = ("01" * 16, "02" * 16, "03" * 16)
    args = (
        kernel_format(),
        loaded.snapshot_id,
        loaded.manifest["entry_value_effect_digest"],
        conditions,
        nodes,
        [operation],
        [("pkg.one", operation)],
        [(operation, formal, "value")],
        [(summary, operation, formal, condition, "established", None, 0)],
    )
    with pytest.raises(ValueError, match="no proof steps"):
        SemanticExecutor(*args, [], [], [], [])
    with pytest.raises(ValueError, match="missing cited callee summary"):
        SemanticExecutor(*args, [(summary, 0, "callee_summary", "04" * 16, condition)], [], [], [])


def test_native_index_admits_schema_finalizer_kind_and_rejects_unknown_kind(
    generation: Path,
) -> None:
    loaded = load(generation, None)
    conditions = [
        (r["condition_id"].hex(), _hex(r["root_id"]), r["boundary_reason"])
        for r in loaded.tables["conditions"].to_pylist()
    ]
    nodes = [
        (r["node_id"].hex(), r["atom"], r["low_id"].hex(), r["high_id"].hex())
        for r in loaded.tables["condition_nodes"].to_pylist()
    ]
    condition = next(r[0] for r in conditions if r[1] is not None)
    operation, formal, summary = ("01" * 16, "02" * 16, "03" * 16)
    prefix = (
        kernel_format(), loaded.snapshot_id, loaded.manifest["entry_value_effect_digest"],
        conditions, nodes, [operation], [("pkg.finalizer", operation)],
        [(operation, formal, "value")],
        [(summary, operation, formal, condition, "established", None, 0)],
    )
    finalizer = (summary, 0, "finalizer_pass", "04" * 16, condition)
    index = SemanticExecutor(*prefix, [finalizer], [], [], [])
    paths, _, _, _, _ = index.inspect_value_paths(
        "pkg.finalizer", "value", "none", "", True, 0, 1
    )
    assert paths[0][3][0][0] == "finalizer_pass"
    with pytest.raises(ValueError, match="invalid summary proof step"):
        SemanticExecutor(*prefix, [(summary, 0, "invented_step", "04" * 16, condition)], [], [], [])


def test_native_ipc_projection_rejects_schema_drift(generation: Path) -> None:
    loaded = load(generation, None)
    files = [(name, (generation / f"{name}.arrow").read_bytes()) for name in NATIVE_IPC_FILES]
    index = SemanticExecutor.from_ipc(
        kernel_format(), loaded.snapshot_id,
        loaded.manifest["entry_value_effect_digest"], files,
    )
    assert index.condition_count == loaded.condition_graph.condition_count

    steps = ipc.open_file(generation / "summary_flow_steps.arrow").read_all()
    changed = steps.append_column("unexpected", pa.array([False] * steps.num_rows))
    sink = pa.BufferOutputStream()
    with ipc.new_file(sink, changed.schema) as writer:
        writer.write_table(changed)
    drifted = [
        (name, sink.getvalue().to_pybytes() if name == "summary_flow_steps" else data)
        for name, data in files
    ]
    with pytest.raises(ValueError, match="native serving schema drift"):
        SemanticExecutor.from_ipc(
            kernel_format(), loaded.snapshot_id,
            loaded.manifest["entry_value_effect_digest"], drifted,
        )


def _hex(value: bytes | None) -> str | None:
    return None if value is None else value.hex()


def test_exact_input_refutes_only_a_cited_summary_path(generation: Path) -> None:
    index = load(generation, None).condition_graph
    assert index is not None
    paths, _, _, _, _ = index.inspect_value_paths(
        "pkg.controls.strict", "value", "none", "", True, 0, 10
    )
    assert len(paths) == 1
    summary = paths[0][0]

    verdict, proof, boundary, theory_work = index.assess_value_path(
        "pkg.controls.strict", "value", summary, "none", "", True
    )
    assert verdict == "refuted_under_model" and boundary is None
    assert len(proof) == 1 and proof[0][1] == "pkg/controls.py"
    assert proof[0][2] < proof[0][3]
    assert theory_work[0] >= 1 and theory_work[1] == 1 and theory_work[2] > 0

    # A satisfiable remainder after a checked link is may-model compatibility only.
    compatible, linked, boundary, theory_work = index.assess_value_path(
        "pkg.controls.strict", "value", summary, "int", "1", True
    )
    assert compatible == "compatible_under_model" and len(linked) == 1
    assert boundary is None
    assert theory_work[1] == 1
    # `is None` does not depend on a builtin name in the runtime namespace.
    assert (
        index.assess_value_path("pkg.controls.strict", "value", summary, "none", "", False)[0]
        == "refuted_under_model"
    )

    paths, boundaries, total, truncated, work = index.inspect_value_paths(
        "pkg.controls.strict", "value", "none", "", True, 0, 1
    )
    assert len(paths) == total == work == 1
    assert paths[0][0] == summary and paths[0][4] == "refuted_under_model"
    assert paths[0][7][1] == 1
    assert boundaries == [] and not truncated
    assert index.inspect_value_paths("pkg.controls.strict", "value", "none", "", True, 1, 1) == (
        [],
        [],
        1,
        False,
        0,
    )
    with pytest.raises(ValueError, match="cursor offset"):
        index.inspect_value_paths("pkg.controls.strict", "value", "none", "", True, 2, 1)

    paths, boundaries, total, truncated, work = index.inspect_value_paths(
        "pkg.controls.build", "label", "str", "x", True, 0, 1
    )
    assert paths == [] and len(boundaries) == total == work == 1
    assert len(boundaries[0][1]) == 32
    assert boundaries[0][3] == "call_transfer" and not truncated


def test_native_string_membership_and_integer_equality_stay_path_local() -> None:
    # Rows come from the production Diagram/IdHasher probe in the W11 evidence folder.
    false_id = "b9902e4735719efc29674ec10253ffeb"
    true_id = "119f0180894a5ece441560e03b8236a6"
    entries = (
        ("1e620f8e6baa4f80335aa61d523df131", "35f0fe9b56ec63e62d552dcec6baea49",
         "11c2c3afeac4740229637d741053f688",
         'member_of(transport,{"http","sse"})#02020202020202020202020202020202:s10-20'),
        ("5eb046a3c7c73c13eda3af197414aabd", "75dbd3aa23cbd30889b03a140ad17cc1",
         "91e83ddc13998c845e62e903de83f584",
         "equals(transport,2)#02020202020202020202020202020202:s10-20"),
    )
    snapshot, effect = "aa" * 16, "bb" * 32
    operation, formal, module = "01" * 16, "03" * 16, "02" * 16
    conditions = [(condition, root, None) for condition, root, _, _ in entries]
    nodes = [(root, atom, false_id, true_id) for _, root, _, atom in entries]
    flows = [(f"{index:02x}" * 16, operation, formal, condition, "conditional", None, 0)
             for index, (condition, _, _, _) in enumerate(entries, start=4)]
    steps = [(summary, 0, "finalizer_pass", "09" * 16, condition)
             for summary, _, _, condition, _, _, _ in flows]
    leaves = [(f"{index:02x}" * 16, module, condition, atom_id, atom, "pkg/transport.py", 10, 20)
              for index, (condition, _, atom_id, atom) in enumerate(entries, start=6)]
    links = [(f"{index:02x}" * 16, operation, formal, module, leaf[0], atom_id, condition,
              "transport", "direct_parameter_reach_no_effect", effect,
              ("pkg/transport.py", 10, 20))
             for index, ((condition, _, atom_id, _), leaf) in enumerate(zip(entries, leaves), start=8)]
    index = SemanticExecutor(
        kernel_format(), snapshot, effect, conditions, nodes,
        [operation], [("pkg.transport", operation)], [(operation, formal, "transport")],
        flows, steps, [], leaves, links,
    )

    def results(kind: str, value: str) -> dict[str, str]:
        paths, boundaries, total, truncated, work = index.inspect_value_paths(
            "pkg.transport", "transport", kind, value, True, 0, 10
        )
        assert total == work == 2 and not truncated and boundaries == []
        return {path[0]: path[4] for path in paths}

    member, equals = (flow[0] for flow in flows)
    assert results("str", "stdio") == {
        member: "refuted_under_model", equals: "unknown",
    }
    assert results("str", "http") == {
        member: "compatible_under_model", equals: "unknown",
    }
    assert results("int", "3") == {
        member: "unknown", equals: "refuted_under_model",
    }
    assert results("bool", "true") == {member: "unknown", equals: "unknown"}


def test_native_value_path_page_has_stable_bounded_boundary_order(generation: Path) -> None:
    loaded = load(generation, None)
    conditions = [
        (
            r["condition_id"].hex(),
            None if r["root_id"] is None else r["root_id"].hex(),
            r["boundary_reason"],
        )
        for r in loaded.tables["conditions"].to_pylist()
    ]
    nodes = [
        (r["node_id"].hex(), r["atom"], r["low_id"].hex(), r["high_id"].hex())
        for r in loaded.tables["condition_nodes"].to_pylist()
    ]
    condition = next(r[0] for r in conditions if r[1] is not None)
    operation, formal = "01" * 16, "02" * 16
    index = SemanticExecutor(
        kernel_format(),
        loaded.snapshot_id,
        loaded.manifest["entry_value_effect_digest"],
        conditions,
        nodes,
        [operation],
        [("pkg.one", operation)],
        [(operation, formal, "value")],
        [],
        [],
        [
            (operation, formal, "04" * 16, "14" * 16, condition, "call_transfer"),
            (operation, formal, "03" * 16, "13" * 16, condition, "unsupported_control_flow"),
        ],
        [],
        [],
    )
    first = index.inspect_value_paths("pkg.one", "value", "none", "", True, 0, 1)
    second = index.inspect_value_paths("pkg.one", "value", "none", "", True, 1, 1)
    assert first[2:] == (2, True, 1)
    assert second[2:] == (2, False, 1)
    assert first[1][0][0] == "03" * 16 and second[1][0][0] == "04" * 16
    assert first[1][0][1] == "13" * 16 and second[1][0][1] == "14" * 16
