//! Explicit receipt ingestion. This module never launches analyzed code.
use crate::{ExtractError, ExtractInput, ExtractOutput};
use cpg_schema::{Table, evidence::*, id::content_digest, query::QueryRow};
use sha2::{Digest as _, Sha256};
use std::path::Path;
fn error(message: impl ToString) -> ExtractError {
    ExtractError::Library(message.to_string())
}
pub fn identity(input: &ExtractInput) -> Result<DeploymentEnvironment, ExtractError> {
    let library = input
        .release
        .environment_library()
        .ok_or_else(|| error("task observations require an acquired library"))?;
    let cfg = crate::config::pyrefly_config(input)?;
    let context = crate::config::context(&cfg, input)?;
    // Runtime observations additionally cover native/data/.pth inputs. Installation RECORDs
    // and generated bytecode are excluded because they encode environment-local script paths.
    let mut runtime = cpg_schema::IdHasher::new("deployment-runtime-files-v1");
    for root in &input.site_packages {
        for entry in walkdir::WalkDir::new(root)
            .follow_links(false)
            .sort_by_file_name()
            .into_iter()
            .filter_entry(|e| e.file_name() != "__pycache__")
        {
            let entry = entry.map_err(error)?;
            if !entry.file_type().is_file() && !entry.file_type().is_symlink() {
                continue;
            }
            let path = entry.path();
            if entry.file_name() == "RECORD" || path.extension().is_some_and(|e| e == "pyc") {
                continue;
            }
            runtime
                .str(&path.strip_prefix(root).map_err(error)?.to_string_lossy())
                .digest_field(content_digest(&std::fs::read(path)?));
        }
    }
    let interpreter_digest = content_digest(&std::fs::read(input.venv_root.join("bin/python"))?);
    Ok(DeploymentEnvironment {
        runtime_digest: runtime.finish_digest(),
        interpreter_digest,
        release_id: input.release.release_id,
        lock_digest: library.lock_digest,
        environment_digest: context.environment_digest,
        python_version: context.python_version,
        platform: context.python_platform,
        requirement: library.requirement.clone(),
        metadata: library
            .distributions
            .iter()
            .flat_map(|d| {
                d.metadata
                    .iter()
                    .map(|(path, bytes)| (path.clone(), content_digest(bytes)))
            })
            .collect(),
    })
}
pub fn attach(
    input: &ExtractInput,
    output: &mut ExtractOutput,
    paths: &[std::path::PathBuf],
) -> Result<(), ExtractError> {
    if paths.is_empty() {
        return Ok(());
    }
    let expected = identity(input)?;
    let corpus = input
        .corpus
        .as_ref()
        .ok_or_else(|| error("task observations require selected corpus source"))?;
    let batch = output
        .table(CapturedArtifacts::NAME)
        .ok_or_else(|| error("missing captured artifacts"))?;
    let mut captured = CapturedArtifactsRow::read_batch(batch)?;
    for path in paths {
        let size = std::fs::metadata(path)?.len();
        if size > 65536 {
            return Err(error("task receipt exceeds 64 KiB"));
        }
        let bytes = std::fs::read(path)?;
        let receipt: TaskReceipt = serde_json::from_slice(&bytes).map_err(error)?;
        validate(&receipt, &expected)?;
        let relative = Path::new(&receipt.source_path);
        if relative
            .components()
            .any(|c| !matches!(c, std::path::Component::Normal(_)))
        {
            return Err(error("task receipt source must be corpus relative"));
        }
        let source = corpus.release.root.join(relative);
        if !corpus.release.files.contains(&source)
            && !corpus.documents.contains(&source)
            && !corpus.assets.contains(&source)
        {
            return Err(error("task receipt refers to an unselected source"));
        }
        let original = std::fs::read(&source)?;
        if format!("{:x}", Sha256::digest(&original)) != receipt.source_sha256 {
            return Err(error("stale task receipt source"));
        }
        let artifact = artifact_id(
            corpus.release.release_id,
            &receipt.source_path,
            content_digest(&original),
        );
        let detail = DeploymentDetail {
            distribution: None,
            version: None,
            field: "task_observation".into(),
            original: receipt.task.clone(),
            name: None,
            extras: vec![],
            marker: None,
            constraint: None,
            interpretation: CheckStatus::Passed,
            diagnostic: Some(
                "Observed under the entire pinned environment; minimal installation is unproved."
                    .into(),
            ),
            environment_digest: Some(expected.environment_digest),
            lock_digest: Some(expected.lock_digest),
            task: Some(TaskObservation {
                target_artifact: artifact,
                receipt,
            }),
            referenced_path: None,
        };
        let logical = format!("task-observations/{}.json", content_digest(&bytes).hex());
        captured.push(crate::capture(
            input.snapshot_id,
            corpus.release.release_id,
            output.context_id,
            &logical,
            "task_observation",
            &bytes,
            "mapped_with_evidence",
            "explicit operator task receipt; independently checked against acquired inputs",
            &[detail],
        )?);
    }
    captured.sort_by_key(|r| r.artifact_id);
    captured.dedup_by_key(|r| r.artifact_id);
    let replacement = CapturedArtifacts::to_sorted_batch(&captured)?;
    output
        .tables
        .iter_mut()
        .find(|(name, _)| *name == CapturedArtifacts::NAME)
        .unwrap()
        .1 = replacement;
    Ok(())
}
fn validate(receipt: &TaskReceipt, expected: &DeploymentEnvironment) -> Result<(), ExtractError> {
    if receipt.format != 1
        || receipt.policy != "fastmcp-stdio-v1"
        || !matches!(receipt.task.as_str(), "programmatic" | "cli")
        || receipt.environment != *expected
    {
        return Err(error(
            "stale or unsupported task receipt environment/policy",
        ));
    }
    let command: Vec<&str> = if receipt.task == "programmatic" {
        vec!["<environment>/bin/python", "<source>/server.py"]
    } else {
        vec![
            "<environment>/bin/python",
            "-c",
            "from fastmcp.cli import app; app()",
            "run",
            "<source>/server.py:mcp",
            "--transport",
            "stdio",
        ]
    };
    if receipt.source_path != "examples/fastmcp_config/server.py"
        || receipt.command != command
        || receipt.tool != "add"
        || receipt.arguments != std::collections::BTreeMap::from([("a".into(), 2), ("b".into(), 3)])
    {
        return Err(error(
            "task receipt does not match its fixed interaction policy",
        ));
    }
    let runner = format!(
        "{:x}",
        Sha256::digest(include_bytes!("../../../scripts/deployment_check.py"))
    );
    if receipt.runner_sha256 != runner {
        return Err(error("stale task receipt runner"));
    }
    if receipt.timeout_seconds != 45
        || receipt.elapsed_ms > 60000
        || receipt.command.len() > 20
        || receipt.tools.len() > 100
        || receipt.result.as_ref().is_some_and(|r| r.len() > 4096)
        || receipt.diagnostic.as_ref().is_some_and(|r| r.len() > 8192)
    {
        return Err(error("task receipt limits disagree"));
    }
    if receipt.execution == CheckStatus::Passed
        && (!receipt.tools.iter().any(|s| s == "add")
            || receipt.result.as_deref() != Some("5")
            || receipt.diagnostic.is_some())
    {
        return Err(error(
            "successful task receipt lacks the required MCP observation",
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn task_receipts_require_exact_inputs_and_actual_observation() {
        let environment = DeploymentEnvironment {
            runtime_digest: cpg_schema::Digest([4; 32]),
            interpreter_digest: cpg_schema::Digest([5; 32]),
            release_id: cpg_schema::Id::ZERO,
            lock_digest: cpg_schema::Digest([1; 32]),
            environment_digest: cpg_schema::Digest([2; 32]),
            python_version: "3.14.7".into(),
            platform: "linux".into(),
            requirement: "fastmcp==4.0.5".into(),
            metadata: Default::default(),
        };
        let mut r = TaskReceipt {
            format: 1,
            policy: "fastmcp-stdio-v1".into(),
            task: "programmatic".into(),
            runner_sha256: format!(
                "{:x}",
                Sha256::digest(include_bytes!("../../../scripts/deployment_check.py"))
            ),
            source_path: "examples/fastmcp_config/server.py".into(),
            source_sha256: "0".repeat(64),
            environment: environment.clone(),
            command: vec![
                "<environment>/bin/python".into(),
                "<source>/server.py".into(),
            ],
            tool: "add".into(),
            arguments: std::collections::BTreeMap::from([("a".into(), 2), ("b".into(), 3)]),
            elapsed_ms: 1,
            timeout_seconds: 45,
            execution: CheckStatus::Passed,
            tools: vec!["add".into()],
            result: Some("5".into()),
            diagnostic: None,
        };
        assert!(validate(&r, &environment).is_ok());
        r.environment.lock_digest = cpg_schema::Digest([3; 32]);
        assert!(validate(&r, &environment).is_err());
        r.environment = environment.clone();
        r.result = None;
        assert!(validate(&r, &environment).is_err());
        r.execution = CheckStatus::Failed;
        assert!(validate(&r, &environment).is_ok());
        r.runner_sha256 = "bad".into();
        assert!(validate(&r, &environment).is_err());
    }
}
