//! C1 contextual evidence consumes completed C0 and typed original facts, independently of brief seeds.
use crate::{generation_read::{AttemptSession,ProviderOptions},model_runtime::{AttemptRuntime,StageSession}};
use futures::TryStreamExt;
use lctx_model::domain::{*,catalog::evidence::{self,build::{self,EvidenceData}},analysis::{self,catalog_evidence::*},normalized::Rows,stages::*};
use lctx_postgres::{generations::GenerationAttempt,roles::RoleConfig};
use std::sync::Arc;
async fn load<R:Record>(session:&StageSession,rows:&mut Rows<R>,permit:&ReadPermit<'_,R>,admission:Option<&mut analysis::expected::CoverageAdmission<'_>>)->Result<(),ModelError> {let query=session.query(&format!("SELECT * FROM \"{}\"",R::NAME)).await.map_err(ModelError::codec)?;let mut stream=query.execute_stream().await.map_err(ModelError::codec)?;let mut admission=admission;while let Some(batch)=stream.try_next().await.map_err(ModelError::codec)? {if let Some(admission)=admission.as_deref_mut() {admission.visit(permit,&batch)?;}rows.decode(&batch)?;}Ok(())}
pub async fn produce(access:StageAccess<'_, '_>,attempt:&GenerationAttempt,config:&RoleConfig,runtime:&AttemptRuntime,model:&Arc<ValidatedModel>)->Result<(),ModelError> {
 let sources=analysis::sources::CapturedSources::capture(&access,runtime.budget())?;let mut admission=analysis::expected::CoverageAdmission::new(&sources,runtime.budget())?;
 let reader=AttemptSession::open(config,attempt,&access,model.clone(),ProviderOptions::default()).await.map_err(ModelError::codec)?;let session=runtime.session(&access);let mut data=EvidenceData::new(runtime.budget());
 macro_rules! core {($($f:ident:$ty:ty,)*)=>{$(let permit=access.read::<$ty>()?;session.register(&permit,reader.table(&permit).map_err(ModelError::codec)?)?;load(&session,&mut data.core.$f,&permit,if <$ty>::NAME==source::SourceArtifact::NAME || <$ty>::NAME==attribution::ProviderCoverage::NAME {Some(&mut admission)}else{None}).await?;)*};}lctx_model::catalog_inputs!(core);
 macro_rules! catalog {($($f:ident:$ty:ty,)*)=>{$(let permit=access.read::<$ty>()?;session.register(&permit,reader.table(&permit).map_err(ModelError::codec)?)?;load(&session,&mut data.catalog.$f,&permit,None).await?;)*};}lctx_model::catalog_outputs!(catalog);
 macro_rules! facts {($($f:ident:$ty:ty,)*)=>{$(let permit=access.read::<$ty>()?;session.register(&permit,reader.table(&permit).map_err(ModelError::codec)?)?;load(&session,&mut data.facts.$f,&permit,if <$ty>::NAME==input::ArtifactUse::NAME {Some(&mut admission)}else{None}).await?;)*};}lctx_model::catalog_evidence_inputs!(facts);
 let mut definitions=Rows::<analysis::AnalysisDefinition>::new(runtime.budget());let mut parameters=Rows::<analysis::MethodParameters>::new(runtime.budget());
 macro_rules! meta {($ty:ty,$rows:ident,$admit:expr)=>{{let permit=access.read::<$ty>()?;session.register(&permit,reader.table(&permit).map_err(ModelError::codec)?)?;load(&session,&mut $rows,&permit,$admit).await?;}};}
 meta!(analysis::AnalysisDefinition,definitions,None);meta!(analysis::MethodParameters,parameters,None);
 macro_rules! expected {($($ty:ty),*)=>{$({let mut rows=Rows::<$ty>::new(runtime.budget());meta!($ty,rows,Some(&mut admission));})*};}expected!(input::InputRevision,source::CoverageScope,normalized::coverage::NormalizationComputation,normalized::coverage::NormalizationCoverage);
 drop(session);reader.close().await.map_err(ModelError::codec)?;let budget=runtime.budget().clone();let (data,rows)=tokio::task::spawn_blocking(move || {let rows=build::build(&data,&budget)?;Ok::<_,ModelError>((data,rows))}).await.map_err(ModelError::codec)??;
 let (expected_parameters,definition)=build::definition();if definitions.get(definition.id())!=Some(&definition) || parameters.get(expected_parameters.id())!=Some(&expected_parameters) {return Err(ModelError::Invalid("C1 requires its completed authored definition".into()));}
 let mut output=StageOutput::new(access,attempt,model,runtime.budget().clone(),Default::default())?;
 macro_rules! write {($($f:ident:$ty:ty,)*)=>{$(output.declare::<$ty>()?;for row in rows.$f.iter() {output.push(row.clone()).await?;})*};}lctx_model::catalog_evidence_outputs!(write);
 macro_rules! declare {($($ty:ty),*)=>{$(output.declare::<$ty>()?;)*};}declare!(Invocation,InvocationSource,AnalysisInput,ProjectionInput,SourceReceipt,AnalysisOutcome,AnalysisCoverage,CoverageSource,AnalysisCoveragePremise,CoverageRequirement,CoverageRequiredSource,evidence::EvidenceInvocation);
 let mut invocations=Rows::new(runtime.budget());let expected_parents=evidence::frames::parents(&data.facts.runs,&data.facts.core_invocations,runtime.budget())?;for parent in expected_parents.iter() {
  let source=InvocationSource::CatalogCore {invocation:parent.id()};let (invocation,parents,receipts,projections)=Invocation::admitted(parent.input,parent.context,definition.id(),None,[source.id()],&sources,[],runtime.budget())?;if !projections.is_empty(){return Err(ModelError::Invalid("C1 has no projection requirement".into()));}
  output.push(source).await?;for row in parents {output.push(row).await?;}for receipt in receipts {output.push(receipt).await?;}
  let admitted=coverage::admit(&invocation,&definition,analysis::AnalysisCapability::CatalogEvidence,&admission,runtime.budget())?;
  for scope in admitted.scopes() {let (requirement,members)=scope.expectation().records()?;output.push(requirement).await?;for member in members {output.push(member).await?;}for observed in scope.observations() {output.push(observed.source().clone()).await?;}let (coverage,members)=coverage::assess(scope.expectation(),scope.observations(),analysis::AnalysisStatus::Completed,None,runtime.budget())?;output.push(coverage).await?;for member in members {output.push(member).await?;}}
  output.push(AnalysisOutcome {invocation:invocation.id(),status:analysis::AnalysisStatus::Completed,reason:None}).await?;output.push(invocation.clone()).await?;invocations.insert(invocation)?;
 }
 let links=build::invocation_links(&rows,&invocations,runtime.budget())?;for row in links.iter() {output.push(row.clone()).await?;}drop(links);drop(invocations);drop(expected_parents);drop(rows);drop(data);drop(admission);drop(sources);output.finish(ProviderOutcome::Complete).await
}
