//! Fresh binding publication is independent of body outcomes and caller continuation.
use crate::domain::{*,analysis::{self,source_call as publication,policy::EvidenceStatus,native::NativeAssertionPremise},normalized::{Rows,binding_normalization::{BindingData,BindingOutput}},conditions::entry::EntryData,source::Occurrence,resources::ResourceBudget};
use crate::{Domain,DomainSum};
use super::{source_call::{CheckedSourceBinding,SourceCallRequest},evaluation::EvaluationData,records::ordered_digest};
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="source_call_headers",rule="fresh_source_binding",invariants=header_invariants)]
pub struct SourceCallHeader{#[model(key,premise)]pub invocation:Id<publication::AnalysisInvocation>,#[model(key)]pub event:Id<normalized::events::NormalizedCallEvent>,#[model(premise)]pub attempt:Id<normalized::bindings::CallBindingAttempt>,pub owner:Id<normalized::entities::EntityRef>,pub callee:Id<normalized::entities::EntityRef>,pub declaration:Id<Occurrence>,pub qualification:Id<assertion::AssertionQualification>,pub status:EvidenceStatus,pub premises:ContentHash}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="source_call_header_members",rule="source_call_header_premise",conclusion=header)]
pub struct HeaderMember{#[model(key)]pub header:Id<SourceCallHeader>,#[model(key)]pub ordinal:i64,#[model(premise)]pub premise:Id<NativeAssertionPremise>}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="source_call_boundaries")]
pub struct SourceCallBoundary{#[model(key)]pub invocation:Id<publication::AnalysisInvocation>,#[model(key)]pub event:Id<normalized::events::NormalizedCallEvent>,pub reason:obligation::ObligationKind}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="source_call_runs",invariants=run_invariants,publication_checks=profile_checks)]
pub struct SourceCallRun{#[model(key)]pub invocation:Id<publication::AnalysisInvocation>,pub requested:bool,pub bound:i64,pub refused:i64}
impl analysis::support::sealed::DerivedEvidence for SourceCallHeader{}
impl analysis::support::DerivedEvidence for SourceCallHeader{fn source_facts(&self)->analysis::support::SourceFacts{analysis::support::SourceFacts{qualification:self.qualification,status:self.status,heuristic:false}}}
#[derive(Debug,Clone,PartialEq,Eq,Hash,DomainSum)]
#[model(name="source_call_outcomes")]
pub enum SourceCallOutcome{#[model(code=0)]Normal,#[model(code=1)]Raised{site:Id<Occurrence>,exception:super::ExactRuntimeException}}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="source_call_frame_releases",rule="source_call_frame_release")]
pub struct SourceFrameRelease{#[model(key,premise)]pub header:Id<SourceCallHeader>,#[model(key,premise)]pub body:Id<super::body_records::SourceBodyCompletion>}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="source_call_invocations",rule="source_call_invocation",invariants=invocation_invariants)]
pub struct SourceInvocation{#[model(key,premise)]pub invocation:Id<publication::AnalysisInvocation>,#[model(key,premise)]pub release:Id<SourceFrameRelease>,pub qualification:Id<assertion::AssertionQualification>,pub outcome:Id<SourceCallOutcome>,pub status:EvidenceStatus}
#[derive(Debug,Clone,PartialEq,Eq,Domain)]
#[model(name="source_call_invocation_boundaries")]
pub struct InvocationBoundary{#[model(key)]pub header:Id<SourceCallHeader>,pub reason:obligation::ObligationKind}
impl analysis::support::sealed::DerivedEvidence for SourceInvocation{}
impl analysis::support::DerivedEvidence for SourceInvocation{fn source_facts(&self)->analysis::support::SourceFacts{analysis::support::SourceFacts{qualification:self.qualification,status:self.status,heuristic:false}}}
pub struct SourceCallData{pub evaluation:EvaluationData,pub flow:EntryData,pub bindings:BindingData,pub output:BindingOutput,pub completed:super::completion_production::CompletedEvaluations,pub base:Rows<analysis::base_completion::AnalysisInvocation>,pub definitions:Rows<analysis::AnalysisDefinition>,pub bodies:Rows<super::body_records::SourceBodyCompletion>}

impl SourceCallData{
 pub fn new(budget:&ResourceBudget)->Self{Self{evaluation:EvaluationData::new(budget),flow:EntryData::new(budget),bindings:BindingData::new(budget),output:BindingOutput::new(budget),completed:super::completion_production::CompletedEvaluations::new(budget),base:Rows::new(budget),definitions:Rows::new(budget),bodies:Rows::new(budget)}}
 pub fn visit(&mut self,name:&str,batch:&arrow_array::RecordBatch)->Result<(),ModelError>{self.completed.visit(name,batch)?;if name==analysis::base_completion::AnalysisInvocation::NAME{self.base.decode(batch)?;}else if name==analysis::AnalysisDefinition::NAME{self.definitions.decode(batch)?;}else if name==super::body_records::SourceBodyCompletion::NAME{self.bodies.decode(batch)?;}self.evaluation.visit(name,batch)?;self.flow.visit(name,batch)?;self.bindings.visit(name,batch)?;macro_rules! output{($($field:ident:$ty:ty,)*)=>{$(if name==<$ty>::NAME{self.output.$field.decode(batch)?;})*};}crate::normalized_binding_outputs!(output);Ok(())}
 pub fn inputs()->Vec<ValidationInput>{let mut inputs=EvaluationData::validation_inputs();inputs.extend(EntryData::validation_inputs().into_iter().map(|input|if stages::is_vocabulary(input.name()){input.at_epoch(stages::PublicationBoundary::Facts)}else{input}));inputs.extend(BindingData::validation_inputs());inputs.extend(BindingOutput::validation_inputs());inputs.extend(super::records::base_invariants().remove(0).inputs.into_iter().map(|input|if stages::is_vocabulary(input.name()){input.at_epoch(stages::PublicationBoundary::Facts)}else{input}));inputs.extend([ValidationInput::of::<analysis::base_completion::AnalysisInvocation>(&["id"]),ValidationInput::of::<super::body_records::SourceBodyCompletion>(&["id"])]);inputs.sort_by_key(|i|(i.name(),i.prefix()));inputs.dedup_by_key(|i|(i.name(),i.prefix()));inputs}
}
pub struct SourceCallRecords{pub run:SourceCallRun,pub headers:Rows<SourceCallHeader>,pub members:Rows<HeaderMember>,pub boundaries:Rows<SourceCallBoundary>,pub outcome:publication::AnalysisOutcome,pub invocations:Rows<SourceInvocation>,pub releases:Rows<SourceFrameRelease>,pub call_outcomes:Rows<SourceCallOutcome>,pub invocation_boundaries:Rows<InvocationBoundary>}
pub fn prepare_all(data:&SourceCallData,invocation:&publication::AnalysisInvocation,definition:&analysis::AnalysisDefinition,profile:stages::Profile,budget:&ResourceBudget)->Result<SourceCallRecords,ModelError>{
 let invalid=|s:&str|ModelError::Invalid(s.into());if *definition!=super::configuration::source_calls().1||invocation.definition!=definition.id()||invocation.subject.is_some(){return Err(invalid("source call definition/frame is unbound"));}
 let mut records=SourceCallRecords{run:SourceCallRun{invocation:invocation.id(),requested:profile==stages::Profile::Behavioral,bound:0,refused:0},headers:Rows::new(budget),members:Rows::new(budget),boundaries:Rows::new(budget),outcome:publication::AnalysisOutcome{invocation:invocation.id(),status:analysis::AnalysisStatus::Completed,reason:None},invocations:Rows::new(budget),releases:Rows::new(budget),call_outcomes:Rows::new(budget),invocation_boundaries:Rows::new(budget)};if profile==stages::Profile::Catalog{records.outcome.status=analysis::AnalysisStatus::NotRequested;records.outcome.reason=Some(obligation::ObligationKind::NotRequested);return Ok(records)}
 let mut headers=Vec::new();let mut header_charge=charged::StateCharge::new(budget,"source_call_private_headers");let verified=normalized::binding_normalization::verify(&data.bindings,&data.output,budget)?;
 let mut charge=charged::StateCharge::new(budget,"source_call_root_inventory");let bytes=data.evaluation.artifacts.iter().try_fold(0usize,|n,r|n.checked_add(size_of::<source::SourceArtifact>()+r.heap_bytes()+256)).and_then(|n|n.checked_add(data.evaluation.uses.len().checked_mul(size_of::<input::ArtifactUse>()+256)?)).ok_or_else(||invalid("source call root allowance overflow"))?;charge.grow(bytes)?;
 let roots=admission::analysis_roots(&data.evaluation.artifacts.iter().cloned().collect::<Vec<_>>(),&data.evaluation.uses.iter().cloned().collect::<Vec<_>>())?;
 for event in data.bindings.event_events.iter().filter(|e|e.context==invocation.context){let site=data.bindings.occurrences.get(event.site).ok_or_else(||invalid("source call event site missing"))?;let artifact=data.evaluation.artifacts.get(site.source).ok_or_else(||invalid("source call artifact missing"))?;if artifact.input!=invocation.input||!roots.contains(&artifact.id())||admission::ArtifactClass::of(&artifact.path)!=Some(admission::ArtifactClass::PythonSource){continue;}
 let mut candidates=data.output.attempts.iter().filter(|a|a.event==event.id()).filter_map(|a|verified.composition(a.id()).map(|c|(a,c)));let first=candidates.next();let result=if candidates.next().is_some(){Err(obligation::ObligationKind::AmbiguousBinding)}else if let Some((attempt,admission))=first{CheckedSourceBinding::derive(&data.evaluation,&data.flow,&data.bindings,&data.output,verified.bound(attempt.id()).ok_or_else(||invalid("composition lacks private bound call"))?,admission,SourceCallRequest{input:invocation.input,context:invocation.context,event:event.id()},budget)?}else{Err(obligation::ObligationKind::UnresolvedTarget)};
 match result{Ok(proof)=>{let header=SourceCallHeader{invocation:invocation.id(),event:event.id(),attempt:proof.attempt(),owner:proof.caller(),callee:proof.callee(),declaration:proof.declaration(),qualification:proof.qualification(),status:proof.status(),premises:ordered_digest("source-call-header-premises",proof.premises().iter().map(Record::id))};for(ordinal,premise)in proof.premises().iter().enumerate(){records.members.insert(HeaderMember{header:header.id(),ordinal:ordinal.try_into().map_err(|_|invalid("source call ordinal overflow"))?,premise:premise.id()})?;}header_charge.grow(size_of::<(CheckedSourceBinding,SourceCallHeader)>()*2)?;records.headers.insert(header.clone())?;headers.push((proof,header));},Err(reason)=>{records.boundaries.insert(SourceCallBoundary{invocation:invocation.id(),event:event.id(),reason})?;}}
 }
 let mut resolved=charged::ChargedSet::default();let mut resolved_charge=charged::StateCharge::new(budget,"source_invocation_body_membership");
 for base in data.base.iter().filter(|b|(b.input,b.context)==(invocation.input,invocation.context)){
 let definition=data.definitions.get(base.definition).ok_or_else(||invalid("source call completion definition absent"))?;
 let expected=super::completion_production::complete_all_with_bodies(&data.completed,base,definition,profile,budget,&mut |body,row|{
 if data.bodies.get(row.id())!=Some(row){return Err(invalid("source invocation body differs from earlier immutable completion"));}
 for(header,record)in &headers{if header.callee()!=body.request().callee{continue;}if !resolved.insert(&mut resolved_charge,record.id())?{return Err(invalid("source invocation body mapping is ambiguous"));}
 match super::source_invocation::CheckedSourceInvocation::derive(&data.evaluation,header,body,budget)?{Err(reason)=>{records.invocation_boundaries.insert(InvocationBoundary{header:record.id(),reason})?;},Ok(proof)=>{let release=SourceFrameRelease{header:record.id(),body:row.id()};let outcome=match proof.outcome(){super::source_invocation::InvocationOutcome::Normal=>SourceCallOutcome::Normal,super::source_invocation::InvocationOutcome::Raised{site,exception}=>SourceCallOutcome::Raised{site,exception}};records.invocations.insert(SourceInvocation{invocation:invocation.id(),release:release.id(),qualification:proof.qualification(),outcome:outcome.id(),status:proof.status()})?;records.releases.insert(release)?;records.call_outcomes.insert(outcome)?;}}
 }Ok(())})?;for body in expected.bodies.iter(){if data.bodies.get(body.id())!=Some(body){return Err(invalid("source invocation omitted earlier body membership"));}}
 }
 for(_,header)in &headers{if !resolved.contains(&header.id()){records.invocation_boundaries.insert(InvocationBoundary{header:header.id(),reason:obligation::ObligationKind::MissingEvidence})?;}}
 records.run.bound=records.headers.len().try_into().map_err(|_|invalid("source call header count overflow"))?;records.run.refused=records.boundaries.len().try_into().map_err(|_|invalid("source call boundary count overflow"))?;if !records.boundaries.is_empty()||!records.invocation_boundaries.is_empty(){records.outcome.status=analysis::AnalysisStatus::Partial;records.outcome.reason=Some(obligation::ObligationKind::UnresolvedTarget);}Ok(records)
}
fn invariant_inputs()->Vec<ValidationInput>{let mut inputs=SourceCallData::inputs();inputs.extend([ValidationInput::of::<publication::AnalysisInvocation>(&["id"]),ValidationInput::of::<analysis::base_completion::AnalysisInvocation>(&["id"]),ValidationInput::of::<analysis::AnalysisDefinition>(&["id"]),ValidationInput::of::<SourceCallRun>(&["id"]),ValidationInput::of::<SourceCallHeader>(&["id"]),ValidationInput::of::<HeaderMember>(&["id"]),ValidationInput::of::<SourceCallBoundary>(&["id"]),ValidationInput::of::<publication::AnalysisOutcome>(&["id"]),ValidationInput::of::<SourceInvocation>(&["id"]),ValidationInput::of::<SourceFrameRelease>(&["id"]),ValidationInput::of::<SourceCallOutcome>(&["id"]),ValidationInput::of::<InvocationBoundary>(&["id"])]);inputs.sort_by_key(|i|(i.name(),i.prefix()));inputs.dedup_by_key(|i|(i.name(),i.prefix()));inputs}
fn run_invariants()->Vec<Invariant>{vec![Invariant{name:"source_call_inventory",inputs:invariant_inputs(),create:std::sync::Arc::new(|budget|Box::new(SourceCheck::new(budget)))}]}
fn invocation_invariants()->Vec<Invariant>{vec![Invariant{name:"source_call_invocation_replay",inputs:invariant_inputs(),create:std::sync::Arc::new(|budget|Box::new(SourceCheck::new(budget)))}]}
fn header_invariants()->Vec<Invariant>{vec![Invariant{name:"source_call_header_replay",inputs:invariant_inputs(),create:std::sync::Arc::new(|budget|Box::new(SourceCheck::new(budget)))}]}
struct SourceCheck{data:SourceCallData,invocations:Rows<publication::AnalysisInvocation>,base:Rows<analysis::base_completion::AnalysisInvocation>,definitions:Rows<analysis::AnalysisDefinition>,runs:Rows<SourceCallRun>,headers:Rows<SourceCallHeader>,members:Rows<HeaderMember>,boundaries:Rows<SourceCallBoundary>,outcomes:Rows<publication::AnalysisOutcome>,calls:Rows<SourceInvocation>,releases:Rows<SourceFrameRelease>,call_outcomes:Rows<SourceCallOutcome>,invocation_boundaries:Rows<InvocationBoundary>,budget:ResourceBudget}
impl SourceCheck{fn new(budget:&ResourceBudget)->Self{Self{data:SourceCallData::new(budget),invocations:Rows::new(budget),base:Rows::new(budget),definitions:Rows::new(budget),runs:Rows::new(budget),headers:Rows::new(budget),members:Rows::new(budget),boundaries:Rows::new(budget),outcomes:Rows::new(budget),calls:Rows::new(budget),releases:Rows::new(budget),call_outcomes:Rows::new(budget),invocation_boundaries:Rows::new(budget),budget:budget.clone()}}}
impl InvariantCheck for SourceCheck{
 fn visit(&mut self,name:&str,batch:&arrow_array::RecordBatch)->Result<(),ModelError>{self.data.visit(name,batch)?;macro_rules! rows{($($field:ident:$ty:ty,)*)=>{$(if name==<$ty>::NAME{self.$field.decode(batch)?;})*};}rows!{invocations:publication::AnalysisInvocation,base:analysis::base_completion::AnalysisInvocation,definitions:analysis::AnalysisDefinition,runs:SourceCallRun,headers:SourceCallHeader,members:HeaderMember,boundaries:SourceCallBoundary,outcomes:publication::AnalysisOutcome,calls:SourceInvocation,releases:SourceFrameRelease,call_outcomes:SourceCallOutcome,invocation_boundaries:InvocationBoundary,}Ok(())}
 fn visit_input(&mut self,input:&ValidationInput,batch:&arrow_array::RecordBatch)->Result<(),ModelError>{self.visit(input.name(),batch)}
 fn finish(self:Box<Self>)->Result<(),ModelError>{let invalid=|s:&str|ModelError::Invalid(s.into());let mut frames=charged::ChargedSet::default();let mut charge=charged::StateCharge::new(&self.budget,"source_call_frames");for base in self.base.iter(){frames.insert(&mut charge,(base.input,base.context))?;}if self.invocations.len()!=frames.len()||frames.iter().any(|frame|self.invocations.iter().filter(|i|(i.input,i.context)==*frame).count()!=1){return Err(invalid("source call omitted/duplicated completion frame"));}
 let mut runs=Rows::new(&self.budget);let mut headers=Rows::new(&self.budget);let mut members=Rows::new(&self.budget);let mut boundaries=Rows::new(&self.budget);let mut outcomes=Rows::new(&self.budget);let mut calls=Rows::new(&self.budget);let mut releases=Rows::new(&self.budget);let mut call_outcomes=Rows::new(&self.budget);let mut invocation_boundaries=Rows::new(&self.budget);
 for invocation in self.invocations.iter(){let mut parents=Rows::new(&self.budget);for base in self.base.iter().filter(|b|(b.input,b.context)==(invocation.input,invocation.context)){parents.insert(publication::InvocationSource::BaseCompletion{invocation:base.id()})?;}let mut key=KeySink::new("analysis-invocation-inputs");for row in parents.iter(){row.id().encode(&mut key);}if key.finish()!=invocation.inputs{return Err(invalid("source call completion parent inventory differs"));}let run=self.runs.iter().find(|r|r.invocation==invocation.id()).ok_or_else(||invalid("source call run absent"))?;let definition=self.definitions.get(invocation.definition).ok_or_else(||invalid("source call definition absent"))?;let expected=prepare_all(&self.data,invocation,definition,if run.requested{stages::Profile::Behavioral}else{stages::Profile::Catalog},&self.budget)?;runs.insert(expected.run)?;outcomes.insert(expected.outcome)?;for r in expected.headers.iter(){headers.insert(r.clone())?;}for r in expected.members.iter(){members.insert(r.clone())?;}for r in expected.boundaries.iter(){boundaries.insert(r.clone())?;}for r in expected.invocations.iter(){calls.insert(r.clone())?;}for r in expected.releases.iter(){releases.insert(r.clone())?;}for r in expected.call_outcomes.iter(){call_outcomes.insert(r.clone())?;}for r in expected.invocation_boundaries.iter(){invocation_boundaries.insert(r.clone())?;}}
 if !self.runs.same(&runs)||!self.headers.same(&headers)||!self.members.same(&members)||!self.boundaries.same(&boundaries)||!self.outcomes.same(&outcomes)||!self.calls.same(&calls)||!self.releases.same(&releases)||!self.call_outcomes.same(&call_outcomes)||!self.invocation_boundaries.same(&invocation_boundaries){return Err(invalid("source call inventory differs from independently replayed binding universe"));}Ok(())}
}
fn profile_checks()->Vec<PublicationInvariant>{vec![PublicationInvariant{name:"source_call_profile",inputs:vec![ValidationInput::of::<SourceCallRun>(&["id"]),ValidationInput::of::<publication::AnalysisInvocation>(&["id"])],create:std::sync::Arc::new(|b|Box::new(ProfileCheck{runs:Rows::new(b),invocations:Rows::new(b)}))}]}
struct ProfileCheck{runs:Rows<SourceCallRun>,invocations:Rows<publication::AnalysisInvocation>}
impl PublicationCheck for ProfileCheck{fn visit(&mut self,name:&str,batch:&arrow_array::RecordBatch)->Result<(),ModelError>{if name==SourceCallRun::NAME{self.runs.decode(batch)?;}else if name==publication::AnalysisInvocation::NAME{self.invocations.decode(batch)?;}Ok(())}fn finish(self:Box<Self>,_sources:&[stages::CompletedRelation],profile:stages::Profile)->Result<(),ModelError>{if self.runs.len()!=self.invocations.len()||self.runs.iter().any(|r|self.invocations.get(r.invocation).is_none()||r.requested!=(profile==stages::Profile::Behavioral)){return Err(ModelError::Invalid("source call changes actual requested profile".into()));}Ok(())}}
pub fn relations()->Vec<Relation>{vec![Relation::of::<SourceCallHeader>(),Relation::of::<HeaderMember>(),Relation::of::<SourceCallBoundary>(),Relation::of::<SourceCallRun>(),Relation::of::<SourceInvocation>(),Relation::of::<SourceFrameRelease>(),Relation::of::<SourceCallOutcome>(),Relation::of::<InvocationBoundary>()]}

pub fn stage(profile:stages::Profile,definition:&analysis::AnalysisDefinition,model:&ValidatedModel)->Result<stages::Stage,ModelError>{
 use stages::*;if *definition!=super::configuration::source_calls().1{return Err(ModelError::Invalid("source call stage definition is unbound".into()));}
 let mut outputs=vec![Relation::of::<publication::AnalysisInvocation>(),Relation::of::<publication::AnalysisInput>(),Relation::of::<publication::SourceReceipt>(),Relation::of::<publication::ProjectionInput>(),Relation::of::<publication::InvocationSource>(),Relation::of::<publication::AnalysisOutcome>()];outputs.extend(publication::coverage::relations());outputs.extend(relations());outputs.sort_by_key(Relation::name);outputs.dedup_by_key(|r|r.name());
 let own=outputs.iter().map(Relation::name).collect::<std::collections::BTreeSet<_>>();let facts=crate::domain::facts_relations().iter().map(Relation::name).collect::<std::collections::BTreeSet<_>>();let mut inputs=std::collections::BTreeMap::new();
 let mut initial=if profile==Profile::Behavioral{invariant_inputs()}else{vec![ValidationInput::of::<analysis::base_completion::AnalysisInvocation>(&["id"]),ValidationInput::of::<analysis::AnalysisDefinition>(&["id"])]};
 for relation in &outputs{for check in relation.publication_checks(){initial.extend(check.inputs.iter().cloned());}}
 let mut pending=Vec::new();for input in initial{if own.contains(input.name())||inputs.contains_key(input.name()){continue;}let relation=model.relations().iter().find(|r|r.name()==input.name()).ok_or_else(||ModelError::Invalid(format!("source call input missing {}",input.name())))?;inputs.insert(input.name(),RelationUse::of_relation(relation).completed_store());pending.push(input.name());}
 while let Some(name)=pending.pop(){let relation=model.relations().iter().find(|r|r.name()==name).ok_or_else(||ModelError::Invalid(format!("source call closure missing {name}")))?;let references=relation.fields().iter().filter_map(|f|f.target().map(|(_,n)|n));let checks=relation.invariants().iter().flat_map(|i|i.inputs.iter()).map(ValidationInput::name);
 for required in references.chain(checks){if own.contains(required){return Err(ModelError::Invalid(format!("source call predecessor {name} depends on unfinished output {required}")));}if !facts.contains(required)&&!inputs.contains_key(required){let relation=model.relations().iter().find(|r|r.name()==required).ok_or_else(||ModelError::Invalid(format!("source call predecessor missing {required}")))?;inputs.insert(required,RelationUse::of_relation(relation).completed_store());pending.push(required);}}
 }
 let inputs=normalized::facts_stage_inputs(inputs.into_values().collect());let mut key=KeySink::new("source-call-definition");definition.id().encode(&mut key);
 Ok(Stage{name:"prepare_source_calls",inputs,outputs:outputs.iter().map(RelationUse::of_relation).collect(),contributes:vec![],coverage:vec![],provider:None,profiles:vec![profile],effect:Effect::Pure,code:ContentHash::of(include_bytes!("source_call_records.rs")),configuration:key.finish()})
}
