//! Canonical model-owned validation definitions. Membership is explicit, not inferred from relations.
use super::*;
pub fn definitions() -> ValidationDefinitions {
    let mut definitions = ValidationDefinitions::default();
    definitions.invariants.extend(super::protocols::invariants());
    definitions.invariants.extend(super::attribution::invocation_invariants());
    definitions.invariants.extend(super::attribution::coverage_ownership_invariants());
    definitions.invariants.extend(super::input::input_invariants());
    definitions.invariants.extend(super::input::class_invariants());
    definitions.invariants.extend(super::input::ownership_invariants());
    definitions.invariants.extend(super::input::acquisition_invariants());
    definitions.invariants.extend(super::local_fields::field_invariants());
    definitions.invariants.extend(super::local_theory::theory_invariants());
    definitions.invariants.extend(super::local_semantics::local_invariants());
    definitions.invariants.extend(super::composition::composition_invariants());
    definitions.invariants.extend(super::deployment::collection_invariants());
    definitions.invariants.extend(super::deployment::report_shape_invariants());
    definitions.invariants.extend(super::calls::provider_module_invariants());
    definitions.invariants.extend(super::calls::signature_invariants());
    definitions.invariants.extend(super::calls::origin_invariants());
    definitions.invariants.extend(super::calls::provider_site_invariants());
    definitions.invariants.extend(super::calls::call_syntax_invariants());
    definitions.invariants.extend(super::calls::resolution_invariants());
    definitions.invariants.extend(super::calls::target_invariants());
    definitions.invariants.extend(super::calls::native_support_invariants());
    definitions.invariants.extend(super::assumptions::invariants());
    definitions.invariants.extend(super::class_metadata::transform_invariants());
    definitions.invariants.extend(super::assertion::qualification_invariants());
    definitions.invariants.extend(super::assertion::evidence_invariants());
    definitions.invariants.extend(super::source::occurrence_invariants());
    definitions.invariants.extend(super::artifact::content_invariants());
    definitions.invariants.extend(super::lexical::lexical_invariants());
    definitions.invariants.extend(super::value::literal_set_invariants());
    definitions.invariants.extend(super::symbols::export_enumeration_invariants());
    definitions.invariants.extend(super::symbols::sequence_invariants());
    definitions.invariants.extend(super::symbols::symbol_invariants());
    definitions.invariants.extend(super::assumptions_universe::invariants());
    definitions.invariants.extend(super::syntax::syntax_invariants());
    definitions.invariants.extend(super::syntax::boundary_invariants());
    definitions.invariants.extend(super::declarations::declaration_invariants());
    definitions.invariants.extend(super::flow_capture::inventory_invariants());
    definitions.invariants.extend(super::atom_decision::invariants());
    definitions.invariants.extend(super::types::parameter_list_invariants());
    definitions.invariants.extend(super::types::dict_field_invariants());
    definitions.invariants.extend(super::types::sequence_invariants());
    definitions.invariants.extend(super::types::type_invariants());
    definitions.invariants.extend(super::types::body_invariants());
    definitions.invariants.extend(super::types::record_invariants());
    definitions.invariants.extend(super::flow_inventory::inventory_invariants());
    definitions.invariants.extend(super::flow::view_invariants());
    definitions.invariants.extend(super::flow::flow_invariants());
    definitions.invariants.extend(super::flow::flow_path_invariants());
    definitions.invariants.extend(super::documents::document_invariants());
    definitions.invariants.extend(super::embedding::text::text_invariants());
    definitions.invariants.extend(super::embedding::analytic::invariants());
    definitions.invariants.extend(super::catalog::build::invariants());
    definitions.invariants.extend(super::catalog::build::invocation_invariants());
    definitions.invariants.extend(super::synthesis::seeds::invariants());
    definitions.invariants.extend(super::synthesis::frames::invariants());
    definitions.invariants.extend(super::synthesis::briefs::invariants());
    definitions.invariants.extend(super::synthesis::patterns::invariants());
    definitions.invariants.extend(super::synthesis::documentary::invariants());
    definitions.invariants.extend(super::synthesis::assertions::invariants());
    definitions.invariants.extend(super::synthesis::summary::invariants());
    definitions.invariants.extend(super::synthesis::observations::invariants());
    definitions.invariants.extend(super::selection::build::invariants());
    definitions.invariants.extend(super::selection::frames::invariants());
    definitions.invariants.extend(super::conditions::condition_invariants());
    definitions.invariants.extend(super::conditions::entry::entry_invariants());
    definitions.invariants.extend(super::conditions::rebase::guard_invariants());
    definitions.invariants.extend(super::conditions::stability::stability_invariants());
    definitions.invariants.extend(super::conditions::stability::guard_substitution_invariants());
    definitions.invariants.extend(super::projection::normalization::invariants());
    definitions.invariants.extend(super::calls::signature_enumeration::enumeration_invariants());
    definitions.invariants.extend(super::structural::frames::invariants());
    definitions.publication_checks.extend(super::structural::frames::profile_checks());
    definitions.invariants.extend(super::models::records::invariants());
    definitions.invariants.extend(super::execution::enriched_production::run_invariants());
    definitions.invariants.extend(super::execution::enriched_production::binding_invariants());
    definitions.invariants.extend(super::execution::enriched_production::context_invariants());
    definitions.invariants.extend(super::execution::enriched_production::definition_invariants());
    definitions.invariants.extend(super::execution::enriched_production::modeled_invariants());
    definitions.invariants.extend(super::execution::enriched_production::statement_invariants());
    definitions.publication_checks.extend(super::execution::enriched_production::profile_checks());
    definitions.invariants.extend(super::execution::records::base_invariants());
    definitions.invariants.extend(super::execution::completion_records::completion_invariants());
    definitions.invariants.extend(super::execution::model_production::run_invariants());
    definitions.publication_checks.extend(super::execution::model_production::profile_checks());
    definitions.invariants.extend(super::execution::body_records::body_invariants());
    definitions.invariants.extend(super::execution::completion_production::run_invariants());
    definitions.publication_checks.extend(super::execution::completion_production::run_publication_checks());
    definitions.invariants.extend(super::execution::summary_consequences::refutation_invariants());
    definitions.invariants.extend(super::execution::summary_replay::invariants());
    definitions.publication_checks.extend(super::execution::summary_replay::profile_checks());
    definitions.invariants.extend(super::execution::summary_proof::invariants());
    definitions.invariants.extend(super::execution::production::run_invariants());
    definitions.publication_checks.extend(super::execution::production::run_publication_checks());
    definitions.invariants.extend(super::execution::source_call_records::source_call_invariants());
    definitions.publication_checks.extend(super::execution::source_call_records::profile_checks());
    definitions.invariants.extend(super::retrieval::build::invariants());
    definitions.invariants.extend(super::retrieval::consumption::invariants());
    definitions.invariants.extend(super::analysis::findings::finding_invariants());
    definitions.publication_checks.extend(super::analysis::frontier::analysis_checks());
    definitions.publication_checks.extend(super::analysis::frontier::catalog_checks());
    definitions.invariants.extend(super::analysis::native::inventory_invariants());
    definitions.invariants.extend(super::analytics::frames::invariants());
    definitions.invariants.extend(super::normalized::binding_normalization::invariants());
    definitions.invariants.extend(super::normalized::callable_normalization::invariants());
    definitions.invariants.extend(super::normalized::entity_normalization::invariants());
    definitions.invariants.extend(super::normalized::callable_aspects::invariants());
    definitions.invariants.extend(super::normalized::event_normalization::invariants());
    definitions.invariants.extend(super::normalized::receiver::invariants());
    definitions.invariants.extend(super::normalized::relation_normalization::invariants());
    definitions.invariants.extend(super::types::queries::invariants());
    definitions.invariants.extend(super::types::locations::invariants());
    definitions.invariants.extend(super::types::signatures::signature_port_invariants());
    definitions.invariants.extend(super::types::overload_origins::trace_invariants());
    definitions.invariants.extend(super::types::generics::generic_invariants());
    definitions.invariants.extend(super::catalog::evidence::build::invariants());
    definitions.invariants.extend(super::catalog::evidence::build::invocation_invariants());
    definitions.invariants.extend(super::catalog::evidence::frames::invariants());
    definitions.invariants.extend(super::analysis::local::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::local::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::local::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::local::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::local::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::local::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::base_evaluation::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::base_evaluation::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::base_evaluation::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::base_evaluation::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::base_evaluation::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::base_evaluation::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::base_completion::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::base_completion::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::base_completion::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::base_completion::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::base_completion::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::base_completion::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::source_call::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::source_call::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::source_call::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::source_call::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::source_call::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::source_call::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::enriched_execution::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::enriched_execution::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::enriched_execution::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::enriched_execution::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::enriched_execution::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::enriched_execution::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::model::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::model::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::model::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::model::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::model::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::model::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::summary::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::summary::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::summary::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::summary::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::summary::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::summary::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::structural::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::structural::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::structural::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::structural::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::structural::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::structural::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::analytic_embedding::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::analytic_embedding::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::analytic_embedding::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::analytic_embedding::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::analytic_embedding::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::analytic_embedding::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::analytic::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::analytic::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::analytic::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::analytic::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::analytic::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::analytic::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::catalog_core::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::catalog_core::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::catalog_core::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::catalog_core::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::catalog_core::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::catalog_core::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::catalog_evidence::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::catalog_evidence::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::catalog_evidence::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::catalog_evidence::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::catalog_evidence::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::catalog_evidence::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::selection::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::selection::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::selection::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::selection::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::selection::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::selection::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::synthesis::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::synthesis::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::synthesis::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::synthesis::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::synthesis::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::synthesis::obligations::discharge_invariants());
    definitions.invariants.extend(super::analysis::retrieval::coverage::coverage_invariants());
    definitions.publication_checks.extend(super::analysis::retrieval::coverage::publication_checks());
    definitions.invariants.extend(super::analysis::retrieval::support::support_invariants());
    definitions.publication_checks.extend(super::analysis::retrieval::invocation::source_publication_checks());
    definitions.invariants.extend(super::analysis::retrieval::invocation::invocation_invariants());
    definitions.invariants.extend(super::analysis::retrieval::obligations::discharge_invariants());
    definitions.invariants.extend(super::transfer::local::family_invariants());
    definitions.invariants.extend(super::transfer::local::control_invariants());
    definitions.invariants.extend(super::transfer::model::family_invariants());
    definitions.invariants.extend(super::transfer::summary::family_invariants());
    definitions.invariants.extend(super::transfer::summary::control_invariants());
    definitions.invariants.extend(super::assertion::support_invariants::<super::transfer::local::TransferAlternative, super::transfer::local::TransferSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::transfer::model::TransferAlternative, super::transfer::model::TransferSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::transfer::summary::TransferAlternative, super::transfer::summary::TransferSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::transfer::local::ControlInfluence, super::transfer::local::ControlSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::transfer::summary::ControlInfluence, super::transfer::summary::ControlSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::protocols::NativeExitObservation, super::protocols::NativeExitSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::protocols::NativeTerminalObservation, super::protocols::NativeTerminalSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::protocols::NativeExitDiagnostic, super::protocols::NativeExitDiagnosticSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::ruff::RuffContextObservation, super::ruff::RuffContextSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::ruff::RuffBindingObservation, super::ruff::RuffBindingSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::ruff::RuffDefinitionObservation, super::ruff::RuffDefinitionSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::deployment::TaskReportObservation, super::deployment::TaskReportSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::deployment::DeploymentObservation, super::deployment::DeploymentSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::calls::Signature, super::calls::SignatureSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::calls::CallTarget, super::calls::CallTargetSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::calls::ProviderCallSite, super::calls::ProviderCallSiteSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::calls::CallSyntax, super::calls::CallSyntaxSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::calls::CallResolution, super::calls::CallResolutionSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::class_metadata::ClassMetadataObservation, super::class_metadata::ClassMetadataSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::class_metadata::ClassMemberObservation, super::class_metadata::ClassMemberSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::source::SyntaxObservation, super::source::SyntaxSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::lexical::LexicalScopeObservation, super::lexical::LexicalScopeSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::lexical::BindingObservation, super::lexical::BindingSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::lexical::ReferenceObservation, super::lexical::ReferenceSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::lexical::LexicalResolution, super::lexical::LexicalResolutionSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::diagnostics::RuffDiagnosticObservation, super::diagnostics::RuffDiagnosticSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::diagnostics::PyreflyDiagnosticObservation, super::diagnostics::PyreflyDiagnosticSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::diagnostics::NativeParameterDefinitionObservation, super::diagnostics::NativeParameterDefinitionSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::symbols::SymbolObservation, super::symbols::SymbolSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::symbols::FunctionTraitObservation, super::symbols::FunctionTraitSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::symbols::ClassTraitObservation, super::symbols::ClassTraitSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::symbols::ClassAncestryObservation, super::symbols::ClassAncestrySupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::symbols::ParameterAnnotationObservation, super::symbols::ParameterAnnotationSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::symbols::PublicNameObservation, super::symbols::PublicNameSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::symbols::ExportEnumerationObservation, super::symbols::ExportEnumerationSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::symbols::ParameterDocObservation, super::symbols::ParameterDocSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::symbols::ModuleResolutionObservation, super::symbols::ModuleResolutionSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::syntax::SyntaxPlacement, super::syntax::SyntaxPlacementSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::syntax::SyntaxDetailObservation, super::syntax::SyntaxDetailSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::syntax::DeclarationObservation, super::syntax::DeclarationSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::syntax::DeclarationDecorator, super::syntax::DeclarationDecoratorSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::syntax::ImportAliasObservation, super::syntax::ImportAliasSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::syntax::DunderAllObservation, super::syntax::DunderAllSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::syntax::ParameterSyntaxObservation, super::syntax::ParameterSyntaxSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::syntax::ClassFieldSyntaxObservation, super::syntax::ClassFieldSyntaxSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::declarations::SymbolDeclaration, super::declarations::SymbolDeclarationSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::declarations::ParameterDeclaration, super::declarations::ParameterDeclarationSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow_capture::FlowCaptureTimingObservation, super::flow_capture::FlowCaptureTimingSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::TypeObservation, super::types::TypeSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::TypePresentation, super::types::TypePresentationSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::TypeVariableRestriction, super::types::TypeRestrictionSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::FunctionBodyObservation, super::types::FunctionBodySupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::RecordFieldObservation, super::types::RecordFieldSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow_inventory::FlowUseInventoryObservation, super::flow_inventory::FlowUseInventorySupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowUseObservation, super::flow::FlowUseSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowDefinitionObservation, super::flow::FlowDefinitionSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowReachingObservation, super::flow::FlowReachingSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowNarrowingObservation, super::flow::FlowNarrowingSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowSourceViewObservation, super::flow::FlowSourceViewSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowValueObservation, super::flow::FlowValueSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowRegionObservation, super::flow::FlowRegionSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowTestObservation, super::flow::FlowTestSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowTestLeafObservation, super::flow::FlowTestLeafSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowAttributeLoadObservation, super::flow::FlowAttributeLoadSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::flow::FlowValuePathObservation, super::flow::FlowValuePathSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::documents::DocumentObservation, super::documents::DocumentSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::documents::PassageObservation, super::documents::PassageSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::documents::CodeBlockObservation, super::documents::CodeBlockSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::documents::DocumentLinkObservation, super::documents::DocumentLinkSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::documents::DocumentMentionObservation, super::documents::DocumentMentionSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::documents::DocumentComponentObservation, super::documents::DocumentComponentSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::documents::DocumentAttributeObservation, super::documents::DocumentAttributeSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::captures::CaptureObservation, super::captures::CaptureSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::calls::signature_enumeration::SignatureEnumerationObservation, super::calls::signature_enumeration::SignatureEnumerationSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::queries::TypeQueryObservation, super::types::queries::TypeQuerySupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::signatures::NativeSignatureObservation, super::types::signatures::NativeSignatureSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::signatures::SignatureTypeObservation, super::types::signatures::SignatureTypeSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::overload_origins::NativeOverloadObservation, super::types::overload_origins::NativeOverloadSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::overload_origins::NativeOverloadCandidate, super::types::overload_origins::NativeOverloadCandidateSupport>());
    definitions.invariants.extend(super::assertion::support_invariants::<super::types::generics::GenericSpecializationObservation, super::types::generics::GenericSpecializationSupport>());
    definitions
}

/// Resolve a record's declared canonical checks for finite semantic controls.
pub fn invariants_for<R: Record>() -> Vec<Invariant> {
    definitions().required_for(&[Relation::of::<R>()]).expect("declared canonical invariant references").invariants
}
pub fn publication_checks_for<R: Record>() -> Vec<PublicationInvariant> {
    definitions().required_for(&[Relation::of::<R>()]).expect("declared canonical publication references").publication_checks
}
